CREATE TABLE [EDAA_REF].[BYR_EMP_PKY_MPRS_CURRPREV_INF_HST]
(
	[MJR_P_SUB_CT_ID] [varchar](256) NULL,
	[BYR_ID] [int] NULL,
	[INDV_LST_NM] [varchar](256) NULL,
	[MGR_EMP_ID] [int] NULL,
	[MGR_ID] [int] NULL,
	[PKY_ID] [int] NULL,
	[MPRS_CT_ID] [int] NULL,
	[INS_DT] [datetime2](7) NULL,
	[CURR_PKY_ID] [int] NULL,
	[PKY_DSC] [varchar](256) NULL,
	[CURR_MPRS_CT_ID] [int] NULL,
	[MPRS_CT_DSC] [varchar](256) NULL,
	[EMP_ID] [int] NULL,
	[AUD_INS_SKY] [bigint] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
