CREATE TABLE [EDAA_REF].[DAY_TM_INTVL_INF] (
    [DAY_TM_INTVL_ID] SMALLINT NOT NULL,
    [HR]              TIME (0) NOT NULL,
    UNIQUE NONCLUSTERED ([DAY_TM_INTVL_ID] ASC) NOT ENFORCED
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
