CREATE TABLE [EDAA_REF].[DIM_ITM_LB_MARK]
(
	[PROD_SK] [int] NULL,
	[UDT_DT] [datetime2](7) NULL,
	[UDT_BY] [nvarchar](4000) NULL,
	[LB_MARK_ID] [int] NULL,
	[ITM_SKU] [nvarchar](4000) NULL,
	[UPC_TYP_NM] [nvarchar](4000) NULL,
	[P_LB_VRS_ID] [int] NULL,
	[LB_MARK_NT] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
