CREATE TABLE [EDAA_REF].[DIM_LB_MARK_GRP]
(
	[LB_SK] [int] NULL,
	[UDT_DT] [datetime2](7) NULL,
	[UDT_BY] [nvarchar](4000) NULL,
	[LB_MARK_GRP_ID] [int] NULL,
	[LB_MARK_ID] [int] NULL,
	[LB_MARK_GRP_NM] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
