CREATE TABLE [EDAA_REF].[GS_STA_FUEL_TYP_SETUP_HST]
(
	[STR_ID] [smallint] NOT NULL,
	[FUEL_TYP_ID] [smallint] NOT NULL,
	[RW_UDT_TS] [datetime2](7) NOT NULL,
	[PRD_STRT_DT] [date] NOT NULL,
	[PRD_END_DT] [date] NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
