CREATE TABLE [EDAA_REF].[ITM_GRP_HST]
(
	[ITM_GRP_ID] [int] NOT NULL,
	[ITM_GRP_NM] [varchar](128) NOT NULL,
	[ITM_GRP_DESC] [varchar](512) NULL,
	[ITM_STAT_ATV_IND] [char](1) NOT NULL,
	[PRD_STRT_DT] [date] NOT NULL,
	[PRD_END_DT] [date] NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
