CREATE TABLE [EDAA_REF].[ITM_GRP_ITM_HST]
(
	[ITM_GRP_ID] [int] NOT NULL,
	[ITM_SKU_ID] [decimal](18, 0) NOT NULL,
	[PRD_STRT_DT] [date] NOT NULL,
	[PRD_END_DT] [date] NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
