CREATE TABLE [EDAA_REF].[REF_FTWR_PROD_STYLE]
(
	[FTWR_PROD_STYLE_ID] [int] NOT NULL,
	[FTWR_PROD_STYLE_NM] [varchar](128) NULL,
	[FTWR_PROD_STYLE_DESC] [varchar](512) NULL,
	[MJR_ATTR_TYP_ID] [int] NULL,
	[MJR_ATTR_SUB_TYP_ID] [int] NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_FTWR_PROD_STYLE] PRIMARY KEY NONCLUSTERED
	(
		[FTWR_PROD_STYLE_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
