CREATE TABLE [EDAA_REF].[REF_FTWR_PROD_TGT_GENDR]
(
	[FTWR_PROD_TGT_GENDR_ID] [int] NOT NULL,
	[FTWR_PROD_TGT_GENDR_NM] [varchar](128) NULL,
	[FTWR_PROD_TGT_GENDR_DESC] [varchar](512) NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_FTWR_PROD_TGT_GENDR] PRIMARY KEY NONCLUSTERED
	(
		[FTWR_PROD_TGT_GENDR_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
