/****** Object:  Table [EDAA_REF].[REF_TXN_LN]    Script Date: 3/21/2023 12:48:40 AM ******/

CREATE TABLE [EDAA_REF].[REF_TXN_LN]
(
	[TXN_LN_ID] [int] NOT NULL,
	[TXN_LN_DESC] [nvarchar](100) NOT NULL,
	[TXN_LN_GRP_CTGRY_ID] [int] NOT NULL,
	[TXN_LN_GRP_CTGRY_NM] [nvarchar](35) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
