CREATE TABLE [EDAA_REF].[REF_FTWR_PROD_FEAT]
(
	[FTWR_PROD_FEAT_ID] [int] NOT NULL,
	[FTWR_PROD_FEAT_NM] [varchar](128) NULL,
	[FTWR_PROD_FEAT_DESC] [varchar](512) NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_FTWR_PROD_FEAT] PRIMARY KEY NONCLUSTERED
	(
		[FTWR_PROD_FEAT_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
