CREATE TABLE [EDAA_REF].[REF_SUST_CERT]
(
	[SUST_CERT_ID] [int] NOT NULL,
	[SUST_CERT_NM] [varchar](128) NULL,
	[SUST_CERT_DESC] [varchar](512) NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_SUST_CERT] PRIMARY KEY NONCLUSTERED
	(
		[SUST_CERT_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
