CREATE TABLE [EDAA_REF].[REF_PROD_SIZ_RNG_CD]
(
	[PROD_SIZ_RNG_CD_ID] [int] NOT NULL,
	[PROD_SIZ_RNG_CD_NM] [varchar](128) NULL,
	[PROD_SIZ_RNG_CD_DESC] [varchar](512) NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_PROD_SIZ_RNG_CD] PRIMARY KEY NONCLUSTERED
	(
		[PROD_SIZ_RNG_CD_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
