CREATE TABLE [EDAA_REF].[REF_FBRC]
(
	[FBRC_ID] [int] NOT NULL,
	[FBRC_NM] [varchar](128) NULL,
	[FBRC_DESC] [varchar](512) NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_FBRC] PRIMARY KEY NONCLUSTERED
	(
		[FBRC_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
