CREATE PROC [EDAA_ETL].[PROC_ADV_ANALYT_OSA_PREDICT_INCR_LOAD]
AS
BEGIN

  BEGIN TRY
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON;

    /*DATAMART AUDITING VARIABLES*/
    DECLARE @NEW_AUD_SKY BIGINT;
    DECLARE @NBR_OF_RW_ISRT INT;
    DECLARE @NBR_OF_RW_UDT INT;
    DECLARE @EXEC_LYR VARCHAR(255);
    DECLARE @EXEC_JOB VARCHAR(500);
    DECLARE @SRC_ENTY VARCHAR(500);
    DECLARE @TGT_ENTY VARCHAR(500);
    DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL.PROC_ADV_ANALYT_OSA_PREDICT_INCR_LOAD';
    DECLARE @ERROR_LINE AS INT;
    DECLARE @ERROR_MSG AS NVARCHAR(MAX);
    DECLARE @DELETE_LAST_HOUR DATETIME;



    /*AUDIT LOG START*/
    EXEC ETL.AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_PRES',
                                   @EXEC_JOB = 'EDAA_ETL.PROC_ADV_ANALYT_OSA_PREDICT_INCR_LOAD',
                                   @SRC_ENTY = 'EDAA_STG.ADV_ANALYT_OSA_PREDICT',
                                   @TGT_ENTY = 'EDAA_PRES.ADVANCED_ANALYTICS_OSA_PREDICTIONS',
                                   @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

    --INSERT into ADVANCED_ANALYTICS_OSA_PREDICTIONS_HIST
    INSERT INTO [EDAA_PRES].[ADVANCED_ANALYTICS_OSA_PREDICTIONS_HIST]
	(
	[DAY_DT],
    [UT_ID],
    [P_ID],
    [P_NM],
    [UPC_ID],
    [BOH],
    [ALERT_TYPE],
    [FCST],
    [IT_LOC_ASL_ID],
    [IT_LOC_SCTN_ID],
    [IT_LOC_PSTN_ID],
    [PROMO_FLG],
    [OOS_HITS],
    [DSD_FLAG],
    [ALERT_TABLE_CREATION_TS]
	)
      SELECT
        [DAY_DT],
        [UT_ID],
        CAST([P_ID] AS decimal(7, 0)) AS [P_ID],
        [P_NM],
        [UPC_ID],
        [BOH],
        [ALERT_TYPE],
        [FCST],
        [IT_LOC_ASL_ID],
        [IT_LOC_SCTN_ID],
        [IT_LOC_PSTN_ID],
        [PROMO_FLG],
        [OOS_HITS],
        [DSD_FLAG],
        [ALERT_TABLE_CREATION_TS]
      FROM [EDAA_STG].[ADV_ANALYT_OSA_PREDICT]

    --INSERT into ADVANCED_ANALYTICS_OSA_PREDICTIONS

    INSERT INTO [EDAA_PRES].[ADVANCED_ANALYTICS_OSA_PREDICTIONS]
	(
	[DAY_DT],
    [UT_ID],
    [P_ID],
    [P_NM],
    [UPC_ID],
    [BOH],
    [ALERT_TYPE],
    [FCST],
    [IT_LOC_ASL_ID],
    [IT_LOC_SCTN_ID],
    [IT_LOC_PSTN_ID],
    [PROMO_FLG],
    [DSD_FLAG],
    [OOS_HITS],
    [ALERT_TABLE_CREATION_TS]
	)
      SELECT
        [DAY_DT],
        [UT_ID],
        CAST([P_ID] AS decimal(7, 0)) AS [P_ID],
        [P_NM],
        [UPC_ID],
        [BOH],
        [ALERT_TYPE],
        [FCST],
        [IT_LOC_ASL_ID],
        [IT_LOC_SCTN_ID],
        [IT_LOC_PSTN_ID],
        [PROMO_FLG],
        [DSD_FLAG],
        [OOS_HITS],
        [ALERT_TABLE_CREATION_TS]
      FROM [EDAA_STG].[ADV_ANALYT_OSA_PREDICT]

    --PRINT 'DELETED MORE THAN 60 DAYS DATA IN HIST TABLE'
    DELETE FROM [EDAA_PRES].[ADVANCED_ANALYTICS_OSA_PREDICTIONS_HIST]
    WHERE DAY_DT <= (SELECT CAST(CONVERT(varchar, DATEADD(DAY, -60, GETDATE()), 23) AS date))

    SET @DELETE_LAST_HOUR = (SELECT MAX([ALERT_TABLE_CREATION_TS]) FROM [EDAA_PRES].[ADVANCED_ANALYTICS_OSA_PREDICTIONS])
    DELETE FROM [EDAA_PRES].[ADVANCED_ANALYTICS_OSA_PREDICTIONS]
    WHERE [ALERT_TABLE_CREATION_TS]  < @DELETE_LAST_HOUR

    --Update STATISTICS
    UPDATE STATISTICS EDAA_PRES.ADVANCED_ANALYTICS_OSA_PREDICTIONS_HIST

    PRINT 'Data Load completed.......'


  END TRY

  BEGIN CATCH

    SELECT
      @ERROR_LINE = ERROR_NUMBER(),
      @ERROR_MSG = ERROR_MESSAGE();


    --------- Log execution error ----------
    EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                  @ERROR_LINE = @ERROR_LINE,
                                  @ERROR_MSG = @ERROR_MSG;

    -- Detect the change
    THROW;
  END CATCH

END
