CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_ONETIME_DATAFIX1]  AS


BEGIN
----step1
CREATE TABLE [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_NEW]
WITH (  CLUSTERED COLUMNSTORE INDEX
     ,  DISTRIBUTION =  HASH(ITM_SKU))
AS
SELECT  *
FROM    [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV]
OPTION  (LABEL  = 'CTAS : FCT_DLY_STR_ITMSKU_INV')
;
----step2
--Rename the tables
DROP TABLE [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV];
RENAME OBJECT [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_NEW] TO [FCT_DLY_STR_ITMSKU_INV];

END
GO
