CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_ADJ_TABLELOAD] AS
BEGIN TRY

  /*DATAMART AUDITING VARIABLES*/
  DECLARE @NEW_AUD_SKY bigint
  DECLARE @NBR_OF_RW_ISRT int
  DECLARE @NBR_OF_RW_UDT int
  DECLARE @EXEC_LYR varchar(255)
  DECLARE @EXEC_JOB varchar(500)
  DECLARE @SRC_ENTY varchar(500)
  DECLARE @TGT_ENTY varchar(500)
  DECLARE @GETDATETIME datetime = GETDATE()
  /*AUDIT LOG START*/
  EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
                                          @EXEC_JOB = 'PROC_FCT_DLY_STR_ITMSKU_SLS_ADJ_TABLELOAD',
                                          @SRC_ENTY = 'UT_UPC_DLY_SL_ADJ_HST',
                                          @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_ADJ',
                                          @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

  DECLARE @NUMBEROFPARTITIONS int,
          @NEXTPROCESSINGSTARTDATE date,
          @MAXPROCESSINGDATE date,
          @PROCESSINGENDDATE date
  DECLARE @NBR_OF_RW_ISRT_TOTAL int = 0,
          @NBR_OF_RW_UDT_TOTAL int = 0


  PRINT ('----starting DW load----');

  WITH incr_data
  AS (SELECT
    ISNULL(PROD_HIST_SK, -1) AS PROD_HIST_SK,
    ISNULL(GEO_HIST_SK, -1) AS GEO_HIST_SK,
    CAST(REPLACE(A.DA_BUS_DT, '-', '') AS int) AS DT_SK,
    A.DA_CRT_DT AS CR_DT,
    A.DA_UT_ID AS STR_ID,
    A.DA_UPC_ID AS ITM_SKU,
    DA_RTL_T_AM AS SLS_ADJ_AMT,
    DA_UPC_T_QT AS SLS_ADJ_QTY,
    DA_UPC_T_WGT_QT AS SLS_ADJ_WGT,
    DA_UPC_PTS_AM AS PRM_TO_SLS_ADJ_AMT,
    DA_UPC_PTS_QT AS PRM_TO_SLS_ADJ_QTY,
    DA_UPC_PTS_WGT_QT AS PRM_TO_SLS_ADJ_WGT,
    DA_UPC_PTS_MKDN_AM AS PRM_TO_SLS_MKDN_ADJ_AMT,
    DA_UPC_PTC_AM AS CLRNC_SLS_ADJ_AMT,
    DA_UPC_PTC_QT AS CLRNC_ADJ_QTY,
    DA_UPC_PTC_WGT_QT AS CLRNC_ADJ_WGT,
    DA_UPC_PTC_MKDN_AM AS CLRNC_MKDN_ADJ_AMT,
    DA_CGS_P_CST_ADJ_AM AS COGS_ADJ_AMT,
    DA_CGS_FNC_CHRG_AM AS COGS_FNC_CHRG_ADJ_AMT,
    DA_CGS_FNC_CR_AM AS COGS_FNC_CR_ADJ_AMT,
    DA_CGS_STG_CHRG_AM AS COGS_STRGE_CHRG_ADJ_AMT,
    DA_CGS_FRT_AM AS COGS_FRT_ADJ_AMT,
    DA_CGS_DC_HDL_AM AS COGS_DIST_CNTR_HNDL_ADJ_AMT,
    DA_UPC_T_DMGN_AM AS DRCT_MGN_ADJ_AMT,
    DA_UPC_PTS_DMGN_AM AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
    DA_UPC_PTC_DMGN_AM AS CLRNC_DRCT_MGN_ADJ_AMT

  FROM EDAA_STG.UT_UPC_DLY_SL_ADJ_HST AS A

  LEFT OUTER JOIN (SELECT
    GEO_HIST_SK,
    STR_ID,
    VLD_FRM,
    VLD_TO
  FROM EDAA_DW.DIM_GEO
  --WHERE   IS_CURR<>0

  ) AS GEO
    ON GEO.STR_ID = A.DA_UT_ID
    AND CAST(A.DA_BUS_DT AS date) BETWEEN GEO.VLD_FRM AND ISNULL(GEO.VLD_TO, CAST('2099-01-01' AS date))

  LEFT OUTER JOIN (SELECT
    PROD_HIST_SK,
    ITM_SKU,
    PROD_SK,
    VLD_FRM,
    VLD_TO
  FROM EDAA_DW.DIM_PROD
  --WHERE   IS_CURR<>0

  ) AS P
    ON P.ITM_SKU = A.DA_UPC_ID
    AND CAST(A.DA_BUS_DT AS date) BETWEEN P.VLD_FRM AND ISNULL(P.VLD_TO, CAST('2099-01-01' AS date)))

  INSERT INTO EDAA_DW.FCT_DLY_STR_ITMSKU_SLS_ADJ
    SELECT
      PROD_HIST_SK,
      GEO_HIST_SK,
      DT_SK,
      CR_DT,
      STR_ID,
      ITM_SKU,
      SLS_ADJ_AMT,
      SLS_ADJ_QTY,
      SLS_ADJ_WGT,
      PRM_TO_SLS_ADJ_AMT,
      PRM_TO_SLS_ADJ_QTY,
      PRM_TO_SLS_ADJ_WGT,
      PRM_TO_SLS_MKDN_ADJ_AMT,
      CLRNC_SLS_ADJ_AMT,
      CLRNC_ADJ_QTY,
      CLRNC_ADJ_WGT,
      CLRNC_MKDN_ADJ_AMT,
      COGS_ADJ_AMT,
      COGS_FNC_CHRG_ADJ_AMT,
      COGS_FNC_CR_ADJ_AMT,
      COGS_STRGE_CHRG_ADJ_AMT,
      COGS_FRT_ADJ_AMT,
      COGS_DIST_CNTR_HNDL_ADJ_AMT,
      DRCT_MGN_ADJ_AMT,
      PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
      CLRNC_DRCT_MGN_ADJ_AMT,
      @NEW_AUD_SKY,
      NULL
    FROM incr_data
    WHERE SLS_ADJ_AMT <> 0
    OR SLS_ADJ_QTY <> 0
    OR SLS_ADJ_WGT <> 0
    OR PRM_TO_SLS_ADJ_AMT <> 0
    OR PRM_TO_SLS_ADJ_QTY <> 0
    OR PRM_TO_SLS_ADJ_WGT <> 0
    OR PRM_TO_SLS_MKDN_ADJ_AMT <> 0
    OR CLRNC_SLS_ADJ_AMT <> 0
    OR CLRNC_ADJ_QTY <> 0
    OR CLRNC_ADJ_WGT <> 0
    OR CLRNC_MKDN_ADJ_AMT <> 0
    OR COGS_ADJ_AMT <> 0
    OR COGS_FNC_CHRG_ADJ_AMT <> 0
    OR COGS_FNC_CR_ADJ_AMT <> 0
    OR COGS_STRGE_CHRG_ADJ_AMT <> 0
    OR COGS_FRT_ADJ_AMT <> 0
    OR COGS_DIST_CNTR_HNDL_ADJ_AMT <> 0
    OR DRCT_MGN_ADJ_AMT <> 0
    OR PRM_TO_SLS_DRCT_MGN_ADJ_AMT <> 0
    OR CLRNC_DRCT_MGN_ADJ_AMT <> 0;



  PRINT ('---DW load complete---');

  BEGIN

    SELECT
      @NBR_OF_RW_ISRT = COUNT(1)
    FROM EDAA_DW.FCT_DLY_STR_ITMSKU_SLS_ADJ
    WHERE AUD_INS_SK = @NEW_AUD_SKY
    SELECT
      @NBR_OF_RW_UDT = COUNT(1)
    FROM EDAA_DW.FCT_DLY_STR_ITMSKU_SLS_ADJ
    WHERE AUD_UPD_SK = @NEW_AUD_SKY

    SET @NBR_OF_RW_UDT_TOTAL = @NBR_OF_RW_UDT_TOTAL + @NBR_OF_RW_UDT
    SET @NBR_OF_RW_ISRT_TOTAL = @NBR_OF_RW_ISRT_TOTAL + @NBR_OF_RW_ISRT



  END

  /*AUDIT LOG END*/
  EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
                                        @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT_TOTAL,
                                        @NBR_OF_RW_UDT = @NBR_OF_RW_UDT_TOTAL


  --PRINT 'TRUNCATE TABLE EDAA_STG.STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC'

  EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
                                          @EXEC_JOB = 'PRES_INCR_PROC_FCT_DLY_STR_ITMSKU_SLS_ADJ_TABLELOAD',
                                          @SRC_ENTY = 'UT_UPC_DLY_SL_ADJ_HST',
                                          @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_ADJ',
                                          @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

  /*-------------------TY DATA POPULATION----------------------------------*/
  TRUNCATE TABLE [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC];
  WITH incr_data
  AS (SELECT
    CAST(REPLACE(A.DA_BUS_DT, '-', '') AS int) AS DT_SK,
    CAST(REPLACE(d.lst_yr_fsc_dt, '-', '') AS int) AS LY_DT_SK,
    CAST(REPLACE(d.Lst_Yr_Hldy_Dt, '-', '') AS int) AS LY_DT_SK_HLDY,
    CAST(REPLACE(d.Lst_Yr_Cal_Dt, '-', '') AS int) AS LY_DT_SK_CAL,
    A.DA_UT_ID AS STR_ID,
    A.DA_UPC_ID AS ITM_SKU,
    SUM(DA_RTL_T_AM) AS SLS_AMT,
    SUM(DA_UPC_T_QT) AS SLS_QTY,
    SUM(DA_UPC_T_WGT_QT) AS SLS_WGT,
    SUM(DA_UPC_PTS_AM) AS PRM_TO_SLS_AMT,
    SUM(DA_UPC_PTS_QT) AS PRM_TO_SLS_QTY,
    SUM(DA_UPC_PTS_WGT_QT) AS PRM_TO_SLS_WGT,
    SUM(DA_UPC_PTS_MKDN_AM) AS PRM_TO_SLS_MKDN_AMT,
    SUM(DA_UPC_PTC_AM) AS CLRNC_SLS_AMT,
    SUM(DA_UPC_PTC_QT) AS CLRNC_QTY,
    SUM(DA_UPC_PTC_WGT_QT) AS CLRNC_WGT,
    SUM(DA_UPC_PTC_MKDN_AM) AS CLRNC_MKDN_AMT,
    SUM(DA_CGS_P_CST_ADJ_AM) AS COGS_AMT,
    SUM(DA_CGS_FNC_CHRG_AM) AS COGS_FNC_CHRG_AMT,
    SUM(DA_CGS_FNC_CR_AM) AS COGS_FNC_CR_AMT,
    SUM(DA_CGS_STG_CHRG_AM) AS COGS_STRGE_CHRG_AMT,
    SUM(DA_CGS_FRT_AM) AS COGS_FRT_AMT,
    SUM(DA_CGS_DC_HDL_AM) AS COGS_DIST_CNTR_HNDL_AMT,
    SUM(DA_UPC_T_DMGN_AM) AS DRCT_MGN_AMT,
    SUM(DA_UPC_PTS_DMGN_AM) AS PRM_TO_SLS_DRCT_MGN_AMT,
    SUM(DA_UPC_PTC_DMGN_AM) AS CLRNC_DRCT_MGN_AMT

  FROM EDAA_STG.UT_UPC_DLY_SL_ADJ_HST AS A
  INNER JOIN edaa_dw.dim_dly_cal d
    ON CAST(REPLACE(A.DA_BUS_DT, '-', '') AS int) = d.DT_SK
    AND d.Fsc_Yr = (SELECT
      Fsc_Yr
    FROM edaa_dw.dim_dly_cal
    WHERE dt_sk = format(GETDATE(), 'yyyyMMdd'))

  LEFT OUTER JOIN (SELECT
    GEO_HIST_SK,
    GEO_SK,
    STR_ID,
    VLD_FRM,
    VLD_TO
  FROM EDAA_DW.DIM_GEO
  --WHERE   IS_CURR<>0

  ) AS GEO
    ON GEO.STR_ID = A.DA_UT_ID
    AND CAST(A.DA_BUS_DT AS date) BETWEEN GEO.VLD_FRM AND ISNULL(GEO.VLD_TO, CAST('2099-01-01' AS date))

  LEFT OUTER JOIN (SELECT
    PROD_HIST_SK,
    ITM_SKU,
    PROD_SK,
    VLD_FRM,
    VLD_TO
  FROM EDAA_DW.DIM_PROD
  --WHERE 	IS_CURR<>0

  ) AS P
    ON P.ITM_SKU = A.DA_UPC_ID
    AND CAST(A.DA_BUS_DT AS date) BETWEEN P.VLD_FRM AND ISNULL(P.VLD_TO, CAST('2099-01-01' AS date))

  GROUP BY CAST(REPLACE(A.DA_BUS_DT, '-', '') AS int),
           CAST(REPLACE(d.lst_yr_fsc_dt, '-', '') AS int),
           CAST(REPLACE(d.Lst_Yr_Hldy_Dt, '-', '') AS int),
           CAST(REPLACE(d.Lst_Yr_Cal_Dt, '-', '') AS int),
           A.DA_UT_ID,
           A.DA_UPC_ID)



  INSERT INTO [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
    SELECT
      DT_SK,
      LY_DT_SK,
      LY_DT_SK_HLDY,
      LY_DT_SK_CAL,
      ITM_SKU,
      STR_ID,
      SLS_AMT,
      0,
      SLS_QTY,
      0,
      SLS_WGT,
      0,
      PRM_TO_SLS_AMT,
      0,
      PRM_TO_SLS_QTY,
      0,
      PRM_TO_SLS_WGT,
      0,
      PRM_TO_SLS_MKDN_AMT,
      0,
      CLRNC_SLS_AMT,
      0,
      CLRNC_QTY,
      0,
      CLRNC_WGT,
      0,
      CLRNC_MKDN_AMT,
      0,
      COGS_AMT,
      0,
      COGS_FNC_CHRG_AMT,
      0,
      COGS_FNC_CR_AMT,
      0,
      COGS_STRGE_CHRG_AMT,
      0,
      DRCT_MGN_AMT,
      0,
      PRM_TO_SLS_DRCT_MGN_AMT,
      0,
      CLRNC_DRCT_MGN_AMT,
      0,
      COGS_FRT_AMT,
      0,
      COGS_DIST_CNTR_HNDL_AMT,
      0,
      @GETDATETIME
    FROM incr_data
    WHERE SLS_AMT <> 0
    OR SLS_QTY <> 0
    OR SLS_WGT <> 0
    OR PRM_TO_SLS_AMT <> 0
    OR PRM_TO_SLS_QTY <> 0
    OR PRM_TO_SLS_WGT <> 0
    OR PRM_TO_SLS_MKDN_AMT <> 0
    OR CLRNC_SLS_AMT <> 0
    OR CLRNC_QTY <> 0
    OR CLRNC_WGT <> 0
    OR CLRNC_MKDN_AMT <> 0
    OR COGS_AMT <> 0
    OR COGS_FNC_CHRG_AMT <> 0
    OR COGS_FNC_CR_AMT <> 0
    OR COGS_STRGE_CHRG_AMT <> 0
    OR DRCT_MGN_AMT <> 0
    OR PRM_TO_SLS_DRCT_MGN_AMT <> 0
    OR CLRNC_DRCT_MGN_AMT <> 0
    OR COGS_FRT_AMT <> 0
    OR COGS_DIST_CNTR_HNDL_AMT <> 0;


  /*--------------------LY DATA POPULATION STARTS-----------------------------*/
  PRINT ('TY DATA POPULATION END')
  PRINT ('LY DATA POPULATION STARTS')

  ;
  WITH incr_data
  AS (
  SELECT
    TY_DT_SK AS DT_SK,
    LY_DT_SK AS LY_DT_SK,
    LY_DT_SK_HLDY AS LY_DT_SK_HLDY,
    LY_DT_SK_CAL AS LY_DT_SK_CAL,
    A.[ITM_SKU],
    A.[STR_ID],
    [SLS_ADJ_AMT] AS SLS_AMT,
    [SLS_ADJ_QTY] AS SLS_QTY,
    [SLS_ADJ_WGT] AS SLS_WGT,
    [PRM_TO_SLS_ADJ_AMT] AS PRM_TO_SLS_AMT,
    [PRM_TO_SLS_ADJ_QTY] AS PRM_TO_SLS_QTY,
    [PRM_TO_SLS_ADJ_WGT] AS PRM_TO_SLS_WGT,
    [PRM_TO_SLS_MKDN_ADJ_AMT] AS PRM_TO_SLS_MKDN_AMT,
    [CLRNC_SLS_ADJ_AMT] AS CLRNC_SLS_AMT,
    [CLRNC_ADJ_QTY] AS CLRNC_QTY,
    [CLRNC_ADJ_WGT] AS CLRNC_WGT,
    [CLRNC_MKDN_ADJ_AMT] AS CLRNC_MKDN_AMT,
    [COGS_ADJ_AMT] AS COGS_AMT,
    [COGS_FNC_CHRG_ADJ_AMT] AS COGS_FNC_CHRG_AMT,
    [COGS_FNC_CR_ADJ_AMT] AS COGS_FNC_CR_AMT,
    [COGS_STRGE_CHRG_ADJ_AMT] AS COGS_STRGE_CHRG_AMT,
    [DRCT_MGN_ADJ_AMT] AS DRCT_MGN_AMT,
    [PRM_TO_SLS_DRCT_MGN_ADJ_AMT] AS PRM_TO_SLS_DRCT_MGN_AMT,
    [CLRNC_DRCT_MGN_ADJ_AMT] AS CLRNC_DRCT_MGN_AMT,
    [COGS_FRT_ADJ_AMT] AS COGS_FRT_AMT,
    [COGS_DIST_CNTR_HNDL_ADJ_AMT] AS COGS_DIST_CNTR_HNDL_AMT

  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_ADJ] AS A
  INNER JOIN (SELECT
    CAST(REPLACE(z.DA_BUS_DT, '-', '') AS int) AS TY_DT_SK,
    CAST(REPLACE(d.lst_yr_fsc_dt, '-', '') AS int) AS LY_DT_SK,
    CAST(REPLACE(d.Lst_Yr_Hldy_Dt, '-', '') AS int) AS LY_DT_SK_HLDY,
    CAST(REPLACE(d.Lst_Yr_Cal_Dt, '-', '') AS int) AS LY_DT_SK_CAL,
    MAX('k') AS misc_col
  FROM edaa_dw.dim_dly_cal d
  INNER JOIN EDAA_STG.UT_UPC_DLY_SL_ADJ_HST z
    ON d.Dt_Sk = CAST(REPLACE(z.DA_BUS_DT, '-', '') AS int)
    AND d.Fsc_Yr = (SELECT
      Fsc_Yr
    FROM edaa_dw.dim_dly_cal
    WHERE dt_sk = format(GETDATE(), 'yyyyMMdd'))
  GROUP BY CAST(REPLACE(z.DA_BUS_DT, '-', '') AS int),
           CAST(REPLACE(d.lst_yr_fsc_dt, '-', '') AS int),
           CAST(REPLACE(d.Lst_Yr_Hldy_Dt, '-', '') AS int),
           CAST(REPLACE(d.Lst_Yr_Cal_Dt, '-', '') AS int)) b
    ON b.ly_dt_sk = A.DT_SK
    AND NOT EXISTS (SELECT
      'k'
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] lyty
    WHERE lyty.LY_DT_SK = b.LY_DT_SK)
	)



  INSERT INTO [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
    SELECT
      DT_SK,
      LY_DT_SK,
      LY_DT_SK_HLDY,
      LY_DT_SK_CAL,
      ITM_SKU,
      STR_ID,
      0,
      SLS_AMT,
      0,
      SLS_QTY,
      0,
      SLS_WGT,
      0,
      PRM_TO_SLS_AMT,
      0,
      PRM_TO_SLS_QTY,
      0,
      PRM_TO_SLS_WGT,
      0,
      PRM_TO_SLS_MKDN_AMT,
      0,
      CLRNC_SLS_AMT,
      0,
      CLRNC_QTY,
      0,
      CLRNC_WGT,
      0,
      CLRNC_MKDN_AMT,
      0,
      COGS_AMT,
      0,
      COGS_FNC_CHRG_AMT,
      0,
      COGS_FNC_CR_AMT,
      0,
      COGS_STRGE_CHRG_AMT,
      0,
      DRCT_MGN_AMT,
      0,
      PRM_TO_SLS_DRCT_MGN_AMT,
      0,
      CLRNC_DRCT_MGN_AMT,
      0,
      COGS_FRT_AMT,
      0,
      COGS_DIST_CNTR_HNDL_AMT,
      @GETDATETIME
    FROM incr_data
    WHERE SLS_AMT <> 0
    OR SLS_QTY <> 0
    OR SLS_WGT <> 0
    OR PRM_TO_SLS_AMT <> 0
    OR PRM_TO_SLS_QTY <> 0
    OR PRM_TO_SLS_WGT <> 0
    OR PRM_TO_SLS_MKDN_AMT <> 0
    OR CLRNC_SLS_AMT <> 0
    OR CLRNC_QTY <> 0
    OR CLRNC_WGT <> 0
    OR CLRNC_MKDN_AMT <> 0
    OR COGS_AMT <> 0
    OR COGS_FNC_CHRG_AMT <> 0
    OR COGS_FNC_CR_AMT <> 0
    OR COGS_STRGE_CHRG_AMT <> 0
    OR DRCT_MGN_AMT <> 0
    OR PRM_TO_SLS_DRCT_MGN_AMT <> 0
    OR CLRNC_DRCT_MGN_AMT <> 0
    OR COGS_FRT_AMT <> 0
    OR COGS_DIST_CNTR_HNDL_AMT <> 0;

  /*--------------------LY_FSC DATA POPULATION END-----------------------------*/
  IF EXISTS (SELECT
      DT_SK,
      ITM_SKU,
      STR_ID,
      MAX('k') AS misc_col
    FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
    GROUP BY DT_SK,
             ITM_SKU,
             STR_ID
    EXCEPT
    SELECT
      DT_SK,
      ITM_SKU,
      STR_ID,
      MAX('k') AS misc_col
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
    GROUP BY DT_SK,
             ITM_SKU,
             STR_ID)
  BEGIN

    /*--------------------SUM TY & LY IN SINGLE ROW-----------------------------*/
    INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] ([DT_SK]
    , [LY_DT_SK]
    , [LY_DT_SK_HLDY]
    , [LY_DT_SK_CAL]
    , [ITM_SKU]
    , [STR_ID]
    , [SLS_ADJ_AMT_TY_FSC]
    , [SLS_ADJ_AMT_LY_FSC]
    , [SLS_ADJ_QTY_TY_FSC]
    , [SLS_ADJ_QTY_LY_FSC]
    , [SLS_ADJ_WGT_TY_FSC]
    , [SLS_ADJ_WGT_LY_FSC]
    , [PRM_TO_SLS_ADJ_AMT_TY_FSC]
    , [PRM_TO_SLS_ADJ_AMT_LY_FSC]
    , [PRM_TO_SLS_ADJ_QTY_TY_FSC]
    , [PRM_TO_SLS_ADJ_QTY_LY_FSC]
    , [PRM_TO_SLS_ADJ_WGT_TY_FSC]
    , [PRM_TO_SLS_ADJ_WGT_LY_FSC]
    , [PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC]
    , [PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC]
    , [CLRNC_SLS_ADJ_AMT_TY_FSC]
    , [CLRNC_SLS_ADJ_AMT_LY_FSC]
    , [CLRNC_ADJ_QTY_TY_FSC]
    , [CLRNC_ADJ_QTY_LY_FSC]
    , [CLRNC_ADJ_WGT_TY_FSC]
    , [CLRNC_ADJ_WGT_LY_FSC]
    , [CLRNC_MKDN_ADJ_AMT_TY_FSC]
    , [CLRNC_MKDN_ADJ_AMT_LY_FSC]
    , [COGS_ADJ_AMT_TY_FSC]
    , [COGS_ADJ_AMT_LY_FSC]
    , [COGS_FNC_CHRG_ADJ_AMT_TY_FSC]
    , [COGS_FNC_CHRG_ADJ_AMT_LY_FSC]
    , [COGS_FNC_CR_ADJ_AMT_TY_FSC]
    , [COGS_FNC_CR_ADJ_AMT_LY_FSC]
    , [COGS_STRGE_CHRG_ADJ_AMT_TY_FSC]
    , [COGS_STRGE_CHRG_ADJ_AMT_LY_FSC]
    , [DRCT_MGN_ADJ_AMT_TY_FSC]
    , [DRCT_MGN_ADJ_AMT_LY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC]
    , [CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC]
    , [CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC]
    , [COGS_FRT_ADJ_AMT_TY_FSC]
    , [COGS_FRT_ADJ_AMT_LY_FSC]
    , [COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC]
    , [COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC]
    , [LOADKEY]
    , [UPDATEDTIMESTAMP])
      SELECT
        CAST(x.DT_SK AS int) AS DT_SK,
        CAST(x.LY_DT_SK AS int) AS LY_DT_SK,
        CAST(x.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
        CAST(x.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
        x.ITM_SKU,
        x.STR_ID,
        SUM(x.[SLS_ADJ_AMT_TY_FSC]) AS SLS_AMT_TY_FSC,
        SUM(x.[SLS_ADJ_AMT_LY_FSC]) AS SLS_AMT_LY_FSC,
        SUM(x.[SLS_ADJ_QTY_TY_FSC]) AS SLS_ADJ_QTY_TY_FSC,
        SUM(x.[SLS_ADJ_QTY_LY_FSC]) AS SLS_ADJ_QTY_LY_FSC,
        SUM(x.[SLS_ADJ_WGT_TY_FSC]) AS SLS_ADJ_WGT_TY_FSC,
        SUM(x.[SLS_ADJ_WGT_LY_FSC]) AS SLS_ADJ_WGT_LY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_AMT_TY_FSC]) AS PRM_TO_SLS_ADJ_AMT_TY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_AMT_LY_FSC]) AS PRM_TO_SLS_ADJ_AMT_LY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_QTY_TY_FSC]) AS PRM_TO_SLS_ADJ_QTY_TY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_QTY_LY_FSC]) AS PRM_TO_SLS_ADJ_QTY_LY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_WGT_TY_FSC]) AS PRM_TO_SLS_ADJ_WGT_TY_FSC,
        SUM(x.[PRM_TO_SLS_ADJ_WGT_LY_FSC]) AS PRM_TO_SLS_ADJ_WGT_LY_FSC,
        SUM(x.[PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC]) AS PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC,
        SUM(x.[PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC]) AS PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
        SUM(x.[CLRNC_SLS_ADJ_AMT_TY_FSC]) AS CLRNC_SLS_ADJ_AMT_TY_FSC,
        SUM(x.[CLRNC_SLS_ADJ_AMT_LY_FSC]) AS CLRNC_SLS_ADJ_AMT_LY_FSC,
        SUM(x.[CLRNC_ADJ_QTY_TY_FSC]) AS CLRNC_ADJ_QTY_TY_FSC,
        SUM(x.[CLRNC_ADJ_QTY_LY_FSC]) AS CLRNC_ADJ_QTY_LY_FSC,
        SUM(x.[CLRNC_ADJ_WGT_TY_FSC]) AS CLRNC_ADJ_WGT_TY_FSC,
        SUM(x.[CLRNC_ADJ_WGT_LY_FSC]) AS CLRNC_ADJ_WGT_LY_FSC,
        SUM(x.[CLRNC_MKDN_ADJ_AMT_TY_FSC]) AS CLRNC_MKDN_ADJ_AMT_TY_FSC,
        SUM(x.[CLRNC_MKDN_ADJ_AMT_LY_FSC]) AS CLRNC_MKDN_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_ADJ_AMT_TY_FSC]) AS COGS_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_ADJ_AMT_LY_FSC]) AS COGS_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_FNC_CHRG_ADJ_AMT_TY_FSC]) AS COGS_FNC_CHRG_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_FNC_CHRG_ADJ_AMT_LY_FSC]) AS COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_FNC_CR_ADJ_AMT_TY_FSC]) AS COGS_FNC_CR_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_FNC_CR_ADJ_AMT_LY_FSC]) AS COGS_FNC_CR_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_STRGE_CHRG_ADJ_AMT_TY_FSC]) AS COGS_STRGE_CHRG_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_STRGE_CHRG_ADJ_AMT_LY_FSC]) AS COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
        SUM(x.[DRCT_MGN_ADJ_AMT_TY_FSC]) AS DRCT_MGN_ADJ_AMT_TY_FSC,
        SUM(x.[DRCT_MGN_ADJ_AMT_LY_FSC]) AS DRCT_MGN_ADJ_AMT_LY_FSC,
        SUM(x.[PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC]) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC,
        SUM(x.[PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC]) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
        SUM(x.[CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC]) AS CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC,
        SUM(x.[CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC]) AS CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_FRT_ADJ_AMT_TY_FSC]) AS COGS_FRT_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_FRT_ADJ_AMT_LY_FSC]) AS COGS_FRT_ADJ_AMT_LY_FSC,
        SUM(x.[COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC]) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC,
        SUM(x.[COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC]) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC,
        @NEW_AUD_SKY AS LOADKEY,
        @GETDATETIME AS [UPDATEDTIMESTAMP]
      FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] x
      GROUP BY CAST(x.DT_SK AS int),
               CAST(x.LY_DT_SK AS int),
               CAST(x.LY_DT_SK_HLDY AS int),
               CAST(x.LY_DT_SK_CAL AS int),
               x.ITM_SKU,
               x.STR_ID
  END
  ELSE
  BEGIN
    /*Update the TY data where its 0 for all rows*/
    UPDATE a
    SET a.SLS_ADJ_AMT_TY_FSC = (a.SLS_ADJ_AMT_TY_FSC + b.SLS_ADJ_AMT_TY_FSC),
        a.SLS_ADJ_QTY_TY_FSC = (a.SLS_ADJ_QTY_TY_FSC + b.SLS_ADJ_QTY_TY_FSC),
        a.SLS_ADJ_WGT_TY_FSC = (a.SLS_ADJ_WGT_TY_FSC + b.SLS_ADJ_WGT_TY_FSC),
        a.PRM_TO_SLS_ADJ_AMT_TY_FSC = (a.PRM_TO_SLS_ADJ_AMT_TY_FSC + b.PRM_TO_SLS_ADJ_AMT_TY_FSC),
        a.PRM_TO_SLS_ADJ_QTY_TY_FSC = (a.PRM_TO_SLS_ADJ_QTY_TY_FSC + b.PRM_TO_SLS_ADJ_QTY_TY_FSC),
        a.PRM_TO_SLS_ADJ_WGT_TY_FSC = (a.PRM_TO_SLS_ADJ_WGT_TY_FSC + b.PRM_TO_SLS_ADJ_WGT_TY_FSC),
        a.PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC = (a.PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC + b.PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC),
        a.CLRNC_SLS_ADJ_AMT_TY_FSC = (a.CLRNC_SLS_ADJ_AMT_TY_FSC + b.CLRNC_SLS_ADJ_AMT_TY_FSC),
        a.CLRNC_ADJ_QTY_TY_FSC = (a.CLRNC_ADJ_QTY_TY_FSC + b.CLRNC_ADJ_QTY_TY_FSC),
        a.CLRNC_ADJ_WGT_TY_FSC = (a.CLRNC_ADJ_WGT_TY_FSC + b.CLRNC_ADJ_WGT_TY_FSC),
        a.CLRNC_MKDN_ADJ_AMT_TY_FSC = (a.CLRNC_MKDN_ADJ_AMT_TY_FSC + b.CLRNC_MKDN_ADJ_AMT_TY_FSC),
        a.COGS_ADJ_AMT_TY_FSC = (a.COGS_ADJ_AMT_TY_FSC + b.COGS_ADJ_AMT_TY_FSC),
        a.COGS_FNC_CHRG_ADJ_AMT_TY_FSC = (a.COGS_FNC_CHRG_ADJ_AMT_TY_FSC + b.COGS_FNC_CHRG_ADJ_AMT_TY_FSC),
        a.COGS_FNC_CR_ADJ_AMT_TY_FSC = (a.COGS_FNC_CR_ADJ_AMT_TY_FSC + b.COGS_FNC_CR_ADJ_AMT_TY_FSC),
        a.COGS_STRGE_CHRG_ADJ_AMT_TY_FSC = (a.COGS_STRGE_CHRG_ADJ_AMT_TY_FSC + b.COGS_STRGE_CHRG_ADJ_AMT_TY_FSC),
        a.DRCT_MGN_ADJ_AMT_TY_FSC = (a.DRCT_MGN_ADJ_AMT_TY_FSC + b.DRCT_MGN_ADJ_AMT_TY_FSC),
        a.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC = (a.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC + b.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC),
        a.CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC = (a.CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC + b.CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC),
        a.COGS_FRT_ADJ_AMT_TY_FSC = (a.COGS_FRT_ADJ_AMT_TY_FSC + b.COGS_FRT_ADJ_AMT_TY_FSC),
        a.COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC = (a.COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC + b.COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC),
        a.UPDATEDTIMESTAMP = GETDATE()
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] a, (
	SELECT
      CAST(x.DT_SK AS int) AS DT_SK,
      x.ITM_SKU,
      x.STR_ID,
      SUM(x.SLS_ADJ_AMT_TY_FSC) AS SLS_ADJ_AMT_TY_FSC,
      SUM(x.SLS_ADJ_QTY_TY_FSC) AS SLS_ADJ_QTY_TY_FSC,
      SUM(x.SLS_ADJ_WGT_TY_FSC) AS SLS_ADJ_WGT_TY_FSC,
      SUM(x.PRM_TO_SLS_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_ADJ_AMT_TY_FSC,
      SUM(x.PRM_TO_SLS_ADJ_QTY_TY_FSC) AS PRM_TO_SLS_ADJ_QTY_TY_FSC,
      SUM(x.PRM_TO_SLS_ADJ_WGT_TY_FSC) AS PRM_TO_SLS_ADJ_WGT_TY_FSC,
      SUM(x.PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC,
      SUM(x.CLRNC_SLS_ADJ_AMT_TY_FSC) AS CLRNC_SLS_ADJ_AMT_TY_FSC,
      SUM(x.CLRNC_ADJ_QTY_TY_FSC) AS CLRNC_ADJ_QTY_TY_FSC,
      SUM(x.CLRNC_ADJ_WGT_TY_FSC) AS CLRNC_ADJ_WGT_TY_FSC,
      SUM(x.CLRNC_MKDN_ADJ_AMT_TY_FSC) AS CLRNC_MKDN_ADJ_AMT_TY_FSC,
      SUM(x.COGS_ADJ_AMT_TY_FSC) AS COGS_ADJ_AMT_TY_FSC,
      SUM(x.COGS_FNC_CHRG_ADJ_AMT_TY_FSC) AS COGS_FNC_CHRG_ADJ_AMT_TY_FSC,
      SUM(x.COGS_FNC_CR_ADJ_AMT_TY_FSC) AS COGS_FNC_CR_ADJ_AMT_TY_FSC,
      SUM(x.COGS_STRGE_CHRG_ADJ_AMT_TY_FSC) AS COGS_STRGE_CHRG_ADJ_AMT_TY_FSC,
      SUM(x.DRCT_MGN_ADJ_AMT_TY_FSC) AS DRCT_MGN_ADJ_AMT_TY_FSC,
      SUM(x.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC,
      SUM(x.CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC) AS CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC,
      SUM(x.COGS_FRT_ADJ_AMT_TY_FSC) AS COGS_FRT_ADJ_AMT_TY_FSC,
      SUM(x.COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC
    FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] x
    GROUP BY CAST(x.DT_SK AS int),
             CAST(x.LY_DT_SK AS int),
             CAST(x.LY_DT_SK_HLDY AS int),
             CAST(x.LY_DT_SK_CAL AS int),
             x.ITM_SKU,
             x.STR_ID) b
    WHERE a.ITM_SKU = b.ITM_SKU
    AND a.DT_SK = b.DT_SK
    AND a.STR_ID = b.STR_ID
  END


  --UPDATE HOLIDAY & CALENDAR DATA
  UPDATE T
  SET T.SLS_ADJ_AMT_LY_HLDY= T.SLS_ADJ_AMT_LY_FSC,
  T.SLS_ADJ_QTY_LY_HLDY= T.SLS_ADJ_QTY_LY_FSC,
  T.SLS_ADJ_WGT_LY_HLDY= T.SLS_ADJ_WGT_LY_FSC,
  T.PRM_TO_SLS_ADJ_AMT_LY_HLDY= T.PRM_TO_SLS_ADJ_AMT_LY_FSC,
  T.PRM_TO_SLS_ADJ_QTY_LY_HLDY= T.PRM_TO_SLS_ADJ_QTY_LY_FSC,
  T.PRM_TO_SLS_ADJ_WGT_LY_HLDY= T.PRM_TO_SLS_ADJ_WGT_LY_FSC,
  T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY= T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
  T.CLRNC_SLS_ADJ_AMT_LY_HLDY= T.CLRNC_SLS_ADJ_AMT_LY_FSC,
  T.CLRNC_ADJ_QTY_LY_HLDY= T.CLRNC_ADJ_QTY_LY_FSC,
  T.CLRNC_ADJ_WGT_LY_HLDY= T.CLRNC_ADJ_WGT_LY_FSC,
  T.CLRNC_MKDN_ADJ_AMT_LY_HLDY= T.CLRNC_MKDN_ADJ_AMT_LY_FSC,
  T.COGS_ADJ_AMT_LY_HLDY= T.COGS_ADJ_AMT_LY_FSC,
  T.COGS_FNC_CHRG_ADJ_AMT_LY_HLDY= T.COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
  T.COGS_FNC_CR_ADJ_AMT_LY_HLDY= T.COGS_FNC_CR_ADJ_AMT_LY_FSC,
  T.COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY= T.COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
  T.DRCT_MGN_ADJ_AMT_LY_HLDY= T.DRCT_MGN_ADJ_AMT_LY_FSC,
  T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY= T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
  T.CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY= T.CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
  T.COGS_FRT_ADJ_AMT_LY_HLDY= T.COGS_FRT_ADJ_AMT_LY_FSC,
  T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY= T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC
  FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T ,[EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]  S
  WHERE T.LY_DT_SK = S.LY_DT_SK_HLDY AND T.STR_ID=S.STR_ID AND T.ITM_SKU=S.ITM_SKU


  UPDATE T
  SET T.SLS_ADJ_AMT_LY_CAL = T.SLS_ADJ_AMT_LY_FSC,
  T.SLS_ADJ_QTY_LY_CAL = T.SLS_ADJ_QTY_LY_FSC,
  T.SLS_ADJ_WGT_LY_CAL = T.SLS_ADJ_WGT_LY_FSC,
  T.PRM_TO_SLS_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_ADJ_AMT_LY_FSC,
  T.PRM_TO_SLS_ADJ_QTY_LY_CAL = T.PRM_TO_SLS_ADJ_QTY_LY_FSC,
  T.PRM_TO_SLS_ADJ_WGT_LY_CAL = T.PRM_TO_SLS_ADJ_WGT_LY_FSC,
  T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
  T.CLRNC_SLS_ADJ_AMT_LY_CAL = T.CLRNC_SLS_ADJ_AMT_LY_FSC,
  T.CLRNC_ADJ_QTY_LY_CAL = T.CLRNC_ADJ_QTY_LY_FSC,
  T.CLRNC_ADJ_WGT_LY_CAL = T.CLRNC_ADJ_WGT_LY_FSC,
  T.CLRNC_MKDN_ADJ_AMT_LY_CAL = T.CLRNC_MKDN_ADJ_AMT_LY_FSC,
  T.COGS_ADJ_AMT_LY_CAL = T.COGS_ADJ_AMT_LY_FSC,
  T.COGS_FNC_CHRG_ADJ_AMT_LY_CAL = T.COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
  T.COGS_FNC_CR_ADJ_AMT_LY_CAL = T.COGS_FNC_CR_ADJ_AMT_LY_FSC,
  T.COGS_STRGE_CHRG_ADJ_AMT_LY_CAL = T.COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
  T.DRCT_MGN_ADJ_AMT_LY_CAL = T.DRCT_MGN_ADJ_AMT_LY_FSC,
  T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
  T.CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL = T.CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
  T.COGS_FRT_ADJ_AMT_LY_CAL = T.COGS_FRT_ADJ_AMT_LY_FSC,
  T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL = T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC
  FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T ,[EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]  S
  WHERE T.LY_DT_SK = S.LY_DT_SK_CAL AND T.STR_ID=S.STR_ID AND T.ITM_SKU=S.ITM_SKU



   /*--UPDATE HOLIDAY
  UPDATE T
  SET T.SLS_AMT_LY_HLDY = ISNULL(S.SLS_AMT,0),
      T.SLS_QTY_LY_HLDY = ISNULL(S.SLS_QTY,0),
      T.SLS_WGT_LY_HLDY = ISNULL(S.SLS_WGT,0),
      T.PRM_TO_SLS_AMT_LY_HLDY = ISNULL(S.PRM_TO_SLS_AMT,0),
      T.PRM_TO_SLS_QTY_LY_HLDY = ISNULL(S.PRM_TO_SLS_QTY,0),
      T.PRM_TO_SLS_WGT_LY_HLDY = ISNULL(S.PRM_TO_SLS_WGT,0),
      T.PRM_TO_SLS_MKDN_AMT_LY_HLDY = ISNULL(S.PRM_TO_SLS_MKDN_AMT,0),
      T.CLRNC_SLS_AMT_LY_HLDY = ISNULL(S.CLRNC_SLS_AMT,0),
      T.CLRNC_QTY_LY_HLDY = ISNULL(S.CLRNC_QTY,0),
      T.CLRNC_WGT_LY_HLDY = ISNULL(S.CLRNC_WGT,0),
      T.CLRNC_MKDN_AMT_LY_HLDY = ISNULL(S.CLRNC_MKDN_AMT,0),
      T.COGS_AMT_LY_HLDY = ISNULL(S.COGS_AMT,0),
      T.COGS_FNC_CHRG_AMT_LY_HLDY = ISNULL(S.COGS_FNC_CHRG_AMT,0),
      T.COGS_STRGE_CHRG_AMT_LY_HLDY = ISNULL(S.COGS_STRGE_CHRG_AMT,0),
      T.DRCT_MGN_AMT_LY_HLDY = ISNULL(S.DRCT_MGN_AMT,0),
      T.PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY = ISNULL(S.PRM_TO_SLS_DRCT_MGN_AMT,0),
      T.CLRNC_DRCT_MGN_AMT_LY_HLDY = ISNULL(S.CLRNC_DRCT_MGN_AMT,0),
      T.COGS_FRT_AMT_LY_HLDY = ISNULL(S.COGS_FRT_AMT,0),
      T.COGS_DIST_CNTR_HNDL_AMT_LY_HLDY = ISNULL(S.COGS_DIST_CNTR_HNDL_AMT,0),
      T.[COGS_FNC_CR_AMT_LY_HLDY] = ISNULL(S.[COGS_FNC_CR_AMT],0)
  FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
  INNER JOIN (
  SELECT
    CAST(b.DT_SK AS int) AS DT_SK,
    CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
    CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
    CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
    A.[ITM_SKU] AS ITM_SKU,
    A.[STR_ID] AS STR_ID,
    SUM([SLS_AMT]) AS SLS_AMT,
    SUM([SLS_QTY]) AS SLS_QTY,
    SUM([SLS_WGT]) AS SLS_WGT,
    SUM([PRM_TO_SLS_AMT]) AS PRM_TO_SLS_AMT,
    SUM([PRM_TO_SLS_QTY]) AS PRM_TO_SLS_QTY,
    SUM([PRM_TO_SLS_WGT]) AS PRM_TO_SLS_WGT,
    SUM([PRM_TO_SLS_MKDN_AMT]) AS PRM_TO_SLS_MKDN_AMT,
    SUM([CLRNC_SLS_AMT]) AS CLRNC_SLS_AMT,
    SUM([CLRNC_QTY]) AS CLRNC_QTY,
    SUM([CLRNC_WGT]) AS CLRNC_WGT,
    SUM([CLRNC_MKDN_AMT]) AS CLRNC_MKDN_AMT,
    SUM([COGS_AMT]) AS COGS_AMT,
    SUM([COGS_FNC_CHRG_AMT]) AS COGS_FNC_CHRG_AMT,
    SUM([COGS_FNC_CR_AMT]) AS COGS_FNC_CR_AMT,
    SUM([COGS_STRGE_CHRG_AMT]) AS COGS_STRGE_CHRG_AMT,
    SUM([DRCT_MGN_AMT]) AS DRCT_MGN_AMT,
    SUM([PRM_TO_SLS_DRCT_MGN_AMT]) AS PRM_TO_SLS_DRCT_MGN_AMT,
    SUM([CLRNC_DRCT_MGN_AMT]) AS CLRNC_DRCT_MGN_AMT,
    SUM([COGS_FRT_AMT]) AS COGS_FRT_AMT,
    SUM([COGS_DIST_CNTR_HNDL_AMT]) AS COGS_DIST_CNTR_HNDL_AMT

  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
  INNER JOIN (
  SELECT DISTINCT
    DT_SK,
    LY_DT_SK,
    LY_DT_SK_HLDY,
    LY_DT_SK_CAL
  FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
  ) b
    ON a.DT_SK = b.LY_DT_SK_HLDY
  GROUP BY CAST(b.DT_SK AS int),
           CAST(b.LY_DT_SK AS int),
           CAST(b.LY_DT_SK_HLDY AS int),
           CAST(b.LY_DT_SK_CAL AS int),
           A.[ITM_SKU],
           A.[STR_ID]
	) S
    ON T.ITM_SKU = S.ITM_SKU AND T.STR_ID = S.STR_ID AND T.LY_DT_SK_HLDY = S.LY_DT_SK_HLDY


  --UPDATE CALENDAR
  UPDATE T
  SET T.SLS_AMT_LY_CAL = ISNULL(S.SLS_AMT,0),
      T.SLS_QTY_LY_CAL = ISNULL(S.SLS_QTY,0),
      T.SLS_WGT_LY_CAL = ISNULL(S.SLS_WGT,0),
      T.PRM_TO_SLS_AMT_LY_CAL = ISNULL(S.PRM_TO_SLS_AMT,0),
      T.PRM_TO_SLS_QTY_LY_CAL = ISNULL(S.PRM_TO_SLS_QTY,0),
      T.PRM_TO_SLS_WGT_LY_CAL = ISNULL(S.PRM_TO_SLS_WGT,0),
      T.PRM_TO_SLS_MKDN_AMT_LY_CAL = ISNULL(S.PRM_TO_SLS_MKDN_AMT,0),
      T.CLRNC_SLS_AMT_LY_CAL = ISNULL(S.CLRNC_SLS_AMT,0),
      T.CLRNC_QTY_LY_CAL = ISNULL(S.CLRNC_QTY,0),
      T.CLRNC_WGT_LY_CAL = ISNULL(S.CLRNC_WGT,0),
      T.CLRNC_MKDN_AMT_LY_CAL = ISNULL(S.CLRNC_MKDN_AMT,0),
      T.COGS_AMT_LY_CAL = ISNULL(S.COGS_AMT,0),
      T.COGS_FNC_CHRG_AMT_LY_CAL = ISNULL(S.COGS_FNC_CHRG_AMT,0),
      T.COGS_STRGE_CHRG_AMT_LY_CAL = ISNULL(S.COGS_STRGE_CHRG_AMT,0),
      T.DRCT_MGN_AMT_LY_CAL = ISNULL(S.DRCT_MGN_AMT,0),
      T.PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL = ISNULL(S.PRM_TO_SLS_DRCT_MGN_AMT,0),
      T.CLRNC_DRCT_MGN_AMT_LY_CAL = ISNULL(S.CLRNC_DRCT_MGN_AMT,0),
      T.COGS_FRT_AMT_LY_CAL = ISNULL(S.COGS_FRT_AMT,0),
      T.COGS_DIST_CNTR_HNDL_AMT_LY_CAL = ISNULL(S.COGS_DIST_CNTR_HNDL_AMT,0),
      T.[COGS_FNC_CR_AMT_LY_CAL] = ISNULL(S.[COGS_FNC_CR_AMT],0)
  FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
  INNER JOIN (
  SELECT
    CAST(b.DT_SK AS int) AS DT_SK,
    CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
    CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
    CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
    A.[ITM_SKU] AS ITM_SKU,
    A.[STR_ID] AS STR_ID,
    SUM([SLS_AMT]) AS SLS_AMT,
    SUM([SLS_QTY]) AS SLS_QTY,
    SUM([SLS_WGT]) AS SLS_WGT,
    SUM([PRM_TO_SLS_AMT]) AS PRM_TO_SLS_AMT,
    SUM([PRM_TO_SLS_QTY]) AS PRM_TO_SLS_QTY,
    SUM([PRM_TO_SLS_WGT]) AS PRM_TO_SLS_WGT,
    SUM([PRM_TO_SLS_MKDN_AMT]) AS PRM_TO_SLS_MKDN_AMT,
    SUM([CLRNC_SLS_AMT]) AS CLRNC_SLS_AMT,
    SUM([CLRNC_QTY]) AS CLRNC_QTY,
    SUM([CLRNC_WGT]) AS CLRNC_WGT,
    SUM([CLRNC_MKDN_AMT]) AS CLRNC_MKDN_AMT,
    SUM([COGS_AMT]) AS COGS_AMT,
    SUM([COGS_FNC_CHRG_AMT]) AS COGS_FNC_CHRG_AMT,
    SUM([COGS_FNC_CR_AMT]) AS COGS_FNC_CR_AMT,
    SUM([COGS_STRGE_CHRG_AMT]) AS COGS_STRGE_CHRG_AMT,
    SUM([DRCT_MGN_AMT]) AS DRCT_MGN_AMT,
    SUM([PRM_TO_SLS_DRCT_MGN_AMT]) AS PRM_TO_SLS_DRCT_MGN_AMT,
    SUM([CLRNC_DRCT_MGN_AMT]) AS CLRNC_DRCT_MGN_AMT,
    SUM([COGS_FRT_AMT]) AS COGS_FRT_AMT,
    SUM([COGS_DIST_CNTR_HNDL_AMT]) AS COGS_DIST_CNTR_HNDL_AMT

  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
  INNER JOIN (
  SELECT DISTINCT
    DT_SK,
    LY_DT_SK,
    LY_DT_SK_HLDY,
    LY_DT_SK_CAL
  FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
  ) b
    ON a.DT_SK = b.LY_DT_SK_CAL
  GROUP BY CAST(b.DT_SK AS int),
           CAST(b.LY_DT_SK AS int),
           CAST(b.LY_DT_SK_HLDY AS int),
           CAST(b.LY_DT_SK_CAL AS int),
           A.[ITM_SKU],
           A.[STR_ID]) S
    ON T.ITM_SKU = S.ITM_SKU
    AND T.STR_ID = S.STR_ID
    AND T.LY_DT_SK_CAL = S.LY_DT_SK_CAL */


  --UPDATE TABLE STATISTICS
  UPDATE STATISTICS [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC];
  UPDATE STATISTICS [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_ADJ];
  --TRUNCATE TABLE
  TRUNCATE TABLE [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC];

  /*[CM]:19-FEB-2022 MERGE TO SLS DATA ENDS - THERE SHOULD BE SOME WAY TO LOG EXEC TIME*/
  EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,@NBR_OF_RW_ISRT = 0,@NBR_OF_RW_UDT = 0

END TRY

BEGIN CATCH
  DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_ADJ_TABLELOAD]'
  DECLARE @ERROR_LINE AS int;
  DECLARE @ERROR_MSG AS nvarchar(max);

  SELECT
    @ERROR_LINE = ERROR_NUMBER(),
    @ERROR_MSG = ERROR_MESSAGE();

  --------- Log execution error ----------
  EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                @ERROR_LINE = @ERROR_LINE,
                                @ERROR_MSG = @ERROR_MSG;
  -- Detect the change
  THROW;

END CATCH
