CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_LOST_SLS_TABLELOAD] AS

BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'PROC_FCT_DLY_STR_ITMSKU_LOST_SLS_TABLELOAD'
,@SRC_ENTY  = 'DLY_UT_P_UPC_HST_LOSTSALES'
,@TGT_ENTY = 'FCT_DLY_STR_ITMSKU_LOST_SLS'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

DECLARE @NBR_OF_RW_ISRT_TOTAL INT = 0,  @NBR_OF_RW_UDT_TOTAL INT =0

INSERT INTO EDAA_DW.FCT_DLY_STR_ITMSKU_LOST_SLS

SELECT	ISNULL(PROD_HIST_SK,-1)					AS PROD_HIST_SK,
		ISNULL(GEO_HIST_SK, -1) 				AS GEO_HIST_SK,
		A.DAY_DT								AS DT_SK,
		A.P_UPC_ID								AS ITM_SKU,
		A.UT_ID									AS STR_ID,
		max(TG_RGL_LOST_SL_QT)					AS REG_LOST_SLS_QTY,
		max(TG_PROMO_LOST_SL_QT)				AS PROMO_LOST_SLS_QTY,
		@NEW_AUD_SKY							AS AUD_INS_SK,
		NULL									AS AUD_UPD_SK
FROM EDAA_STG.DLY_UT_P_UPC_HST_LOSTSALES AS A

LEFT OUTER JOIN (SELECT GEO_HIST_SK,
						STR_ID,
						VLD_FRM,
						VLD_TO
			FROM 		EDAA_DW.DIM_GEO
			--WHERE 	IS_CURR<>0
					) AS GEO
	ON GEO.STR_ID = A.UT_ID
	AND  cast(A.DAY_DT as date) BETWEEN GEO.VLD_FRM AND ISNULL(GEO.VLD_TO, CAST('2099-01-01' AS DATE))

LEFT OUTER JOIN (SELECT PROD_HIST_SK,
						ITM_SKU,
						PROD_SK,
						VLD_FRM,
						VLD_TO
			FROM 		EDAA_DW.DIM_PROD
			--WHERE 	IS_CURR<>0
					) AS P
	ON  P.ITM_SKU = A.P_UPC_ID
	AND  cast(A.DAY_DT as date) BETWEEN P.VLD_FRM AND ISNULL(P.VLD_TO, CAST('2099-01-01' AS DATE))

GROUP BY
		ISNULL(PROD_HIST_SK,-1)	,
		ISNULL(GEO_HIST_SK, -1) ,
		A.DAY_DT,
		A.P_UPC_ID,
		A.UT_ID
		;

PRINT('DATA LOAD DONE IN DW TABLE');

BEGIN

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM EDAA_DW.FCT_DLY_STR_ITMSKU_LOST_SLS WHERE AUD_INS_SK = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT(1)  FROM EDAA_DW.FCT_DLY_STR_ITMSKU_LOST_SLS WHERE AUD_UPD_SK = @NEW_AUD_SKY


/*AUDIT LOG END*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT;

END



END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_LOST_SLS_TABLELOAD]'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


   THROW;




END CATCH
