CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_ONETIME_DATAFIX2]  AS


BEGIN

;with cte
as
(
select str_id,itm_sku,INV_ROW_START_DT,INV_ROW_END_DT,row_number() over(partition by str_id,itm_sku
order by INV_ROW_START_DT desc) as R from [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV]
)
select * INTO [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_TEMP] FROM cte
where R IN (1,2);

UPDATE A
SET A.INV_ROW_END_DT= DATEADD(DAY,-1,B.INV_ROW_START_DT)
FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_TEMP] A INNER JOIN (SELECT MAX(INV_ROW_START_DT) as INV_ROW_START_DT,ITM_SKU,STR_ID FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV]                           GROUP BY  ITM_SKU,STR_ID) B
ON A.STR_ID=B.STR_ID AND A.ITM_SKU=B.ITM_SKU
WHERE R=2;

update A set A.inv_row_end_dt=B.inv_row_end_dt from [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV] A
join [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_TEMP] B on A.STR_ID=B.STR_ID AND A.ITM_SKU=B.ITM_SKU and A.inv_row_start_dt=B.inv_row_start_dt;

DROP TABLE [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_TEMP];

END
GO
