CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_DLY_LOAD] @SRC_NAME [VARCHAR](100)
AS
  IF @SRC_NAME = 'UT_UPC_DLY_SL_ADJ_HST'
    OR @SRC_NAME = 'UT_UPC_DLY_SL_HST'
  BEGIN
  --exec [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_DLY_LOAD] 'UT_UPC_DLY_SL_ADJ_HST'
  BEGIN TRY

    /*Datamart Auditing variables*/
    DECLARE @NEW_AUD_SKY bigint
    DECLARE @NBR_OF_RW_ISRT int
    DECLARE @NBR_OF_RW_UDT int
    DECLARE @EXEC_LYR varchar(255)
    DECLARE @EXEC_JOB varchar(500)
    DECLARE @SRC_ENTY varchar(500)
    DECLARE @TGT_ENTY varchar(500)
    DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_SLS_DLY_LOAD'
    DECLARE @ERROR_LINE AS int
    DECLARE @ERROR_MSG AS nvarchar(max)
    DECLARE @SLS_DATETIME datetime
    DECLARE @GETDATE datetime = GETDATE()


    /*Audit Log Start*/
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_PRES',
                                            @EXEC_JOB = 'PROC_FCT_DLY_ITM_SKU_STR_SLS_DLY_LOAD',
                                            @SRC_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC',
                                            @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_DLY',
                                            @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;

    --TRUNCATE STAGE TABLE
    TRUNCATE TABLE [EDAA_STG].[FCT_DLY_STR_ITMSKU_SLS_DLY];

    --GET TE WATER MARK VALUE
    DECLARE @INCL_WTRMRK datetime
    SET @INCL_WTRMRK = (SELECT MAX(UPDATEDTIMESTAMP) FROM [EDAA_STG].[DLY_SLS_STR_ITMSKU_WATRMARK])

    --TRUNCATE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY] FOR IPOP LOAD
    IF @INCL_WTRMRK = '1900-01-01 00:00:00.000'
    BEGIN
      TRUNCATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]
    END

    ;
    WITH CTE
    AS (
	SELECT DISTINCT
      DT_SK,
      ITM_SKU,
      STR_ID
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] a
    WHERE a.UPDATEDTIMESTAMP > (SELECT MAX(UPDATEDTIMESTAMP) FROM [EDAA_STG].[DLY_SLS_STR_ITMSKU_WATRMARK])
    UNION
    SELECT DISTINCT
      DT_SK,
      ITM_SKU,
      STR_ID
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] a
    WHERE a.UPDATEDTIMESTAMP > (SELECT MAX(UPDATEDTIMESTAMP) FROM [EDAA_STG].[DLY_SLS_STR_ITMSKU_WATRMARK])),
    COMBINED_TABLES
    AS (
	SELECT
      dtsel.ROW_ID_VAL,
      dtsel.PRE_DEF_ID,
      CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)) AS DT_VAL,
      a.[ITM_SKU],
      a.[STR_ID],
      [SLS_AMT_TY_FSC],
      [SLS_AMT_LY_FSC],
      [SLS_AMT_LY_HLDY],
      [SLS_AMT_LY_CAL],
      [SLS_QTY_TY_FSC],
      [SLS_QTY_LY_FSC],
      [SLS_QTY_LY_HLDY],
      [SLS_QTY_LY_CAL],
      [SLS_WGT_TY_FSC],
      [SLS_WGT_LY_FSC],
      [SLS_WGT_LY_HLDY],
      [SLS_WGT_LY_CAL],
      [PRM_TO_SLS_AMT_TY_FSC],
      [PRM_TO_SLS_AMT_LY_FSC],
      [PRM_TO_SLS_AMT_LY_HLDY],
      [PRM_TO_SLS_AMT_LY_CAL],
      [PRM_TO_SLS_QTY_TY_FSC],
      [PRM_TO_SLS_QTY_LY_FSC],
      [PRM_TO_SLS_QTY_LY_HLDY],
      [PRM_TO_SLS_QTY_LY_CAL],
      [PRM_TO_SLS_WGT_TY_FSC],
      [PRM_TO_SLS_WGT_LY_FSC],
      [PRM_TO_SLS_WGT_LY_HLDY],
      [PRM_TO_SLS_WGT_LY_CAL],
      [PRM_TO_SLS_MKDN_AMT_TY_FSC],
      [PRM_TO_SLS_MKDN_AMT_LY_FSC],
      [PRM_TO_SLS_MKDN_AMT_LY_HLDY],
      [PRM_TO_SLS_MKDN_AMT_LY_CAL],
      [CLRNC_SLS_AMT_TY_FSC],
      [CLRNC_SLS_AMT_LY_FSC],
      [CLRNC_SLS_AMT_LY_HLDY],
      [CLRNC_SLS_AMT_LY_CAL],
      [CLRNC_QTY_TY_FSC],
      [CLRNC_QTY_LY_FSC],
      [CLRNC_QTY_LY_HLDY],
      [CLRNC_QTY_LY_CAL],
      [CLRNC_WGT_TY_FSC],
      [CLRNC_WGT_LY_FSC],
      [CLRNC_WGT_LY_HLDY],
      [CLRNC_WGT_LY_CAL],
      [CLRNC_MKDN_AMT_TY_FSC],
      [CLRNC_MKDN_AMT_LY_FSC],
      [CLRNC_MKDN_AMT_LY_HLDY],
      [CLRNC_MKDN_AMT_LY_CAL],
      [COGS_AMT_TY_FSC],
      [COGS_AMT_LY_FSC],
      [COGS_AMT_LY_HLDY],
      [COGS_AMT_LY_CAL],
      [COGS_FNC_CHRG_AMT_TY_FSC],
      [COGS_FNC_CHRG_AMT_LY_FSC],
      [COGS_FNC_CHRG_AMT_LY_HLDY],
      [COGS_FNC_CHRG_AMT_LY_CAL],
      [COGS_FNC_CR_AMT_TY_FSC],
      [COGS_FNC_CR_AMT_LY_FSC],
      [COGS_FNC_CR_AMT_LY_HLDY],
      [COGS_FNC_CR_AMT_LY_CAL],
      [COGS_STRGE_CHRG_AMT_TY_FSC],
      [COGS_STRGE_CHRG_AMT_LY_FSC],
      [COGS_STRGE_CHRG_AMT_LY_HLDY],
      [COGS_STRGE_CHRG_AMT_LY_CAL],
      [DRCT_MGN_AMT_TY_FSC],
      [DRCT_MGN_AMT_LY_FSC],
      [DRCT_MGN_AMT_LY_HLDY],
      [DRCT_MGN_AMT_LY_CAL],
      [PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC],
      [PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC],
      [PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY],
      [PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL],
      [CLRNC_DRCT_MGN_AMT_TY_FSC],
      [CLRNC_DRCT_MGN_AMT_LY_FSC],
      [CLRNC_DRCT_MGN_AMT_LY_HLDY],
      [CLRNC_DRCT_MGN_AMT_LY_CAL],
      [COGS_FRT_AMT_TY_FSC],
      [COGS_FRT_AMT_LY_FSC],
      [COGS_FRT_AMT_LY_HLDY],
      [COGS_FRT_AMT_LY_CAL],
      [COGS_DIST_CNTR_HNDL_AMT_TY_FSC],
      [COGS_DIST_CNTR_HNDL_AMT_LY_FSC],
      [COGS_DIST_CNTR_HNDL_AMT_LY_HLDY],
      [COGS_DIST_CNTR_HNDL_AMT_LY_CAL]
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] a
    INNER JOIN CTE b
      ON a.STR_ID = b.STR_ID AND a.ITM_SKU = b.ITM_SKU AND a.DT_SK = b.DT_SK
    INNER JOIN (SELECT
      *,
      ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
    FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
    WHERE AGG_TYP = 'DLY') dtsel
      ON a.DT_SK = dtsel.PRE_DEF_ID


    UNION

    SELECT
      dtsel.ROW_ID_VAL,
      dtsel.PRE_DEF_ID,
      CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)) AS DT_VAL,
      a.[ITM_SKU],
      a.[STR_ID],
      [SLS_ADJ_AMT_TY_FSC],
      [SLS_ADJ_AMT_LY_FSC],
      [SLS_ADJ_AMT_LY_HLDY],
      [SLS_ADJ_AMT_LY_CAL],
      [SLS_ADJ_QTY_TY_FSC],
      [SLS_ADJ_QTY_LY_FSC],
      [SLS_ADJ_QTY_LY_HLDY],
      [SLS_ADJ_QTY_LY_CAL],
      [SLS_ADJ_WGT_TY_FSC],
      [SLS_ADJ_WGT_LY_FSC],
      [SLS_ADJ_WGT_LY_HLDY],
      [SLS_ADJ_WGT_LY_CAL],
      [PRM_TO_SLS_ADJ_AMT_TY_FSC],
      [PRM_TO_SLS_ADJ_AMT_LY_FSC],
      [PRM_TO_SLS_ADJ_AMT_LY_HLDY],
      [PRM_TO_SLS_ADJ_AMT_LY_CAL],
      [PRM_TO_SLS_ADJ_QTY_TY_FSC],
      [PRM_TO_SLS_ADJ_QTY_LY_FSC],
      [PRM_TO_SLS_ADJ_QTY_LY_HLDY],
      [PRM_TO_SLS_ADJ_QTY_LY_CAL],
      [PRM_TO_SLS_ADJ_WGT_TY_FSC],
      [PRM_TO_SLS_ADJ_WGT_LY_FSC],
      [PRM_TO_SLS_ADJ_WGT_LY_HLDY],
      [PRM_TO_SLS_ADJ_WGT_LY_CAL],
      [PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC],
      [PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC],
      [PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY],
      [PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL],
      [CLRNC_SLS_ADJ_AMT_TY_FSC],
      [CLRNC_SLS_ADJ_AMT_LY_FSC],
      [CLRNC_SLS_ADJ_AMT_LY_HLDY],
      [CLRNC_SLS_ADJ_AMT_LY_CAL],
      [CLRNC_ADJ_QTY_TY_FSC],
      [CLRNC_ADJ_QTY_LY_FSC],
      [CLRNC_ADJ_QTY_LY_HLDY],
      [CLRNC_ADJ_QTY_LY_CAL],
      [CLRNC_ADJ_WGT_TY_FSC],
      [CLRNC_ADJ_WGT_LY_FSC],
      [CLRNC_ADJ_WGT_LY_HLDY],
      [CLRNC_ADJ_WGT_LY_CAL],
      [CLRNC_MKDN_ADJ_AMT_TY_FSC],
      [CLRNC_MKDN_ADJ_AMT_LY_FSC],
      [CLRNC_MKDN_ADJ_AMT_LY_HLDY],
      [CLRNC_MKDN_ADJ_AMT_LY_CAL],
      [COGS_ADJ_AMT_TY_FSC],
      [COGS_ADJ_AMT_LY_FSC],
      [COGS_ADJ_AMT_LY_HLDY],
      [COGS_ADJ_AMT_LY_CAL],
      [COGS_FNC_CHRG_ADJ_AMT_TY_FSC],
      [COGS_FNC_CHRG_ADJ_AMT_LY_FSC],
      [COGS_FNC_CHRG_ADJ_AMT_LY_HLDY],
      [COGS_FNC_CHRG_ADJ_AMT_LY_CAL],
      [COGS_FNC_CR_ADJ_AMT_TY_FSC],
      [COGS_FNC_CR_ADJ_AMT_LY_FSC],
      [COGS_FNC_CR_ADJ_AMT_LY_HLDY],
      [COGS_FNC_CR_ADJ_AMT_LY_CAL],
      [COGS_STRGE_CHRG_ADJ_AMT_TY_FSC],
      [COGS_STRGE_CHRG_ADJ_AMT_LY_FSC],
      [COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY],
      [COGS_STRGE_CHRG_ADJ_AMT_LY_CAL],
      [DRCT_MGN_ADJ_AMT_TY_FSC],
      [DRCT_MGN_ADJ_AMT_LY_FSC],
      [DRCT_MGN_ADJ_AMT_LY_HLDY],
      [DRCT_MGN_ADJ_AMT_LY_CAL],
      [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC],
      [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC],
      [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY],
      [PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL],
      [CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC],
      [CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC],
      [CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY],
      [CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL],
      [COGS_FRT_ADJ_AMT_TY_FSC],
      [COGS_FRT_ADJ_AMT_LY_FSC],
      [COGS_FRT_ADJ_AMT_LY_HLDY],
      [COGS_FRT_ADJ_AMT_LY_CAL],
      [COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC],
      [COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC],
      [COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY],
      [COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL]
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] a
    INNER JOIN CTE b
      ON a.STR_ID = b.STR_ID AND a.ITM_SKU = b.ITM_SKU AND a.DT_SK = b.DT_SK
    INNER JOIN (SELECT
      *,
      ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
    FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
    WHERE AGG_TYP = 'DLY') dtsel
      ON a.DT_SK = dtsel.PRE_DEF_ID),

    INCREMENTAL_LOAD
    AS (
	SELECT
      ROW_ID_VAL,
      PRE_DEF_ID,
      DT_VAL,
      ITM_SKU,
      STR_ID,
      SUM(SLS_AMT_TY_FSC) AS SLS_AMT_TY_FSC,
      SUM(SLS_AMT_LY_FSC) AS SLS_AMT_LY_FSC,
      SUM(SLS_AMT_LY_HLDY) AS SLS_AMT_LY_HLDY,
      SUM(SLS_AMT_LY_CAL) AS SLS_AMT_LY_CAL,
      SUM(SLS_QTY_TY_FSC) AS SLS_QTY_TY_FSC,
      SUM(SLS_QTY_LY_FSC) AS SLS_QTY_LY_FSC,
      SUM(SLS_QTY_LY_HLDY) AS SLS_QTY_LY_HLDY,
      SUM(SLS_QTY_LY_CAL) AS SLS_QTY_LY_CAL,
      SUM(SLS_WGT_TY_FSC) AS SLS_WGT_TY_FSC,
      SUM(SLS_WGT_LY_FSC) AS SLS_WGT_LY_FSC,
      SUM(SLS_WGT_LY_HLDY) AS SLS_WGT_LY_HLDY,
      SUM(SLS_WGT_LY_CAL) AS SLS_WGT_LY_CAL,
      SUM(PRM_TO_SLS_AMT_TY_FSC) AS PRM_TO_SLS_AMT_TY_FSC,
      SUM(PRM_TO_SLS_AMT_LY_FSC) AS PRM_TO_SLS_AMT_LY_FSC,
      SUM(PRM_TO_SLS_AMT_LY_HLDY) AS PRM_TO_SLS_AMT_LY_HLDY,
      SUM(PRM_TO_SLS_AMT_LY_CAL) AS PRM_TO_SLS_AMT_LY_CAL,
      SUM(PRM_TO_SLS_QTY_TY_FSC) AS PRM_TO_SLS_QTY_TY_FSC,
      SUM(PRM_TO_SLS_QTY_LY_FSC) AS PRM_TO_SLS_QTY_LY_FSC,
      SUM(PRM_TO_SLS_QTY_LY_HLDY) AS PRM_TO_SLS_QTY_LY_HLDY,
      SUM(PRM_TO_SLS_QTY_LY_CAL) AS PRM_TO_SLS_QTY_LY_CAL,
      SUM(PRM_TO_SLS_WGT_TY_FSC) AS PRM_TO_SLS_WGT_TY_FSC,
      SUM(PRM_TO_SLS_WGT_LY_FSC) AS PRM_TO_SLS_WGT_LY_FSC,
      SUM(PRM_TO_SLS_WGT_LY_HLDY) AS PRM_TO_SLS_WGT_LY_HLDY,
      SUM(PRM_TO_SLS_WGT_LY_CAL) AS PRM_TO_SLS_WGT_LY_CAL,
      SUM(PRM_TO_SLS_MKDN_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_AMT_TY_FSC,
      SUM(PRM_TO_SLS_MKDN_AMT_LY_FSC) AS PRM_TO_SLS_MKDN_AMT_LY_FSC,
      SUM(PRM_TO_SLS_MKDN_AMT_LY_HLDY) AS PRM_TO_SLS_MKDN_AMT_LY_HLDY,
      SUM(PRM_TO_SLS_MKDN_AMT_LY_CAL) AS PRM_TO_SLS_MKDN_AMT_LY_CAL,
      SUM(CLRNC_SLS_AMT_TY_FSC) AS CLRNC_SLS_AMT_TY_FSC,
      SUM(CLRNC_SLS_AMT_LY_FSC) AS CLRNC_SLS_AMT_LY_FSC,
      SUM(CLRNC_SLS_AMT_LY_HLDY) AS CLRNC_SLS_AMT_LY_HLDY,
      SUM(CLRNC_SLS_AMT_LY_CAL) AS CLRNC_SLS_AMT_LY_CAL,
      SUM(CLRNC_QTY_TY_FSC) AS CLRNC_QTY_TY_FSC,
      SUM(CLRNC_QTY_LY_FSC) AS CLRNC_QTY_LY_FSC,
      SUM(CLRNC_QTY_LY_HLDY) AS CLRNC_QTY_LY_HLDY,
      SUM(CLRNC_QTY_LY_CAL) AS CLRNC_QTY_LY_CAL,
      SUM(CLRNC_WGT_TY_FSC) AS CLRNC_WGT_TY_FSC,
      SUM(CLRNC_WGT_LY_FSC) AS CLRNC_WGT_LY_FSC,
      SUM(CLRNC_WGT_LY_HLDY) AS CLRNC_WGT_LY_HLDY,
      SUM(CLRNC_WGT_LY_CAL) AS CLRNC_WGT_LY_CAL,
      SUM(CLRNC_MKDN_AMT_TY_FSC) AS CLRNC_MKDN_AMT_TY_FSC,
      SUM(CLRNC_MKDN_AMT_LY_FSC) AS CLRNC_MKDN_AMT_LY_FSC,
      SUM(CLRNC_MKDN_AMT_LY_HLDY) AS CLRNC_MKDN_AMT_LY_HLDY,
      SUM(CLRNC_MKDN_AMT_LY_CAL) AS CLRNC_MKDN_AMT_LY_CAL,
      SUM(COGS_AMT_TY_FSC) AS COGS_AMT_TY_FSC,
      SUM(COGS_AMT_LY_FSC) AS COGS_AMT_LY_FSC,
      SUM(COGS_AMT_LY_HLDY) AS COGS_AMT_LY_HLDY,
      SUM(COGS_AMT_LY_CAL) AS COGS_AMT_LY_CAL,
      SUM(COGS_FNC_CHRG_AMT_TY_FSC) AS COGS_FNC_CHRG_AMT_TY_FSC,
      SUM(COGS_FNC_CHRG_AMT_LY_FSC) AS COGS_FNC_CHRG_AMT_LY_FSC,
      SUM(COGS_FNC_CHRG_AMT_LY_HLDY) AS COGS_FNC_CHRG_AMT_LY_HLDY,
      SUM(COGS_FNC_CHRG_AMT_LY_CAL) AS COGS_FNC_CHRG_AMT_LY_CAL,
      SUM(COGS_FNC_CR_AMT_TY_FSC) AS COGS_FNC_CR_AMT_TY_FSC,
      SUM(COGS_FNC_CR_AMT_LY_FSC) AS COGS_FNC_CR_AMT_LY_FSC,
      SUM(COGS_FNC_CR_AMT_LY_HLDY) AS COGS_FNC_CR_AMT_LY_HLDY,
      SUM(COGS_FNC_CR_AMT_LY_CAL) AS COGS_FNC_CR_AMT_LY_CAL,
      SUM(COGS_STRGE_CHRG_AMT_TY_FSC) AS COGS_STRGE_CHRG_AMT_TY_FSC,
      SUM(COGS_STRGE_CHRG_AMT_LY_FSC) AS COGS_STRGE_CHRG_AMT_LY_FSC,
      SUM(COGS_STRGE_CHRG_AMT_LY_HLDY) AS COGS_STRGE_CHRG_AMT_LY_HLDY,
      SUM(COGS_STRGE_CHRG_AMT_LY_CAL) AS COGS_STRGE_CHRG_AMT_LY_CAL,
      SUM(DRCT_MGN_AMT_TY_FSC) AS DRCT_MGN_AMT_TY_FSC,
      SUM(DRCT_MGN_AMT_LY_FSC) AS DRCT_MGN_AMT_LY_FSC,
      SUM(DRCT_MGN_AMT_LY_HLDY) AS DRCT_MGN_AMT_LY_HLDY,
      SUM(DRCT_MGN_AMT_LY_CAL) AS DRCT_MGN_AMT_LY_CAL,
      SUM(PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC,
      SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
      SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY,
      SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL,
      SUM(CLRNC_DRCT_MGN_AMT_TY_FSC) AS CLRNC_DRCT_MGN_AMT_TY_FSC,
      SUM(CLRNC_DRCT_MGN_AMT_LY_FSC) AS CLRNC_DRCT_MGN_AMT_LY_FSC,
      SUM(CLRNC_DRCT_MGN_AMT_LY_HLDY) AS CLRNC_DRCT_MGN_AMT_LY_HLDY,
      SUM(CLRNC_DRCT_MGN_AMT_LY_CAL) AS CLRNC_DRCT_MGN_AMT_LY_CAL,
      SUM(COGS_FRT_AMT_TY_FSC) AS COGS_FRT_AMT_TY_FSC,
      SUM(COGS_FRT_AMT_LY_FSC) AS COGS_FRT_AMT_LY_FSC,
      SUM(COGS_FRT_AMT_LY_HLDY) AS COGS_FRT_AMT_LY_HLDY,
      SUM(COGS_FRT_AMT_LY_CAL) AS COGS_FRT_AMT_LY_CAL,
      SUM(COGS_DIST_CNTR_HNDL_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_TY_FSC,
      SUM(COGS_DIST_CNTR_HNDL_AMT_LY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
      SUM(COGS_DIST_CNTR_HNDL_AMT_LY_HLDY) AS COGS_DIST_CNTR_HNDL_AMT_LY_HLDY,
      SUM(COGS_DIST_CNTR_HNDL_AMT_LY_CAL) AS COGS_DIST_CNTR_HNDL_AMT_LY_CAL
    FROM COMBINED_TABLES
    GROUP BY ROW_ID_VAL,
             PRE_DEF_ID,
             DT_VAL,
             ITM_SKU,
             STR_ID
	)

    --SAVE AS STAGE TABLE
	INSERT INTO [EDAA_STG].[FCT_DLY_STR_ITMSKU_SLS_DLY]
    SELECT * FROM INCREMENTAL_LOAD

    --DELETE MORE THAN 42 DAYS DATA IN DLY TABLE
    DELETE a
      FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY] a
      JOIN [EDAA_STG].[FCT_DLY_STR_ITMSKU_SLS_DLY]  b
        ON a.STR_ID = b.STR_ID
        AND a.ITM_SKU = b.ITM_SKU
        AND a.PRE_DEF_ID = b.PRE_DEF_ID

    INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]
      SELECT
        *,
        GETDATE()
      FROM [EDAA_STG].[FCT_DLY_STR_ITMSKU_SLS_DLY]

    --DELETE MORE THAN 42 DAYS DATA
    DELETE FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]
    WHERE PRE_DEF_ID < format(GETDATE() - 43, 'yyyyMMdd')

    --UPDATE STATISTICS
    UPDATE STATISTICS [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]

    --UPDATE UPDATEDTIMESTAMP
    UPDATE [EDAA_STG].[DLY_SLS_STR_ITMSKU_WATRMARK]
    SET UPDATEDTIMESTAMP = GETDATE()



  END TRY

  BEGIN CATCH
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
                                          @NBR_OF_RW_ISRT = 0,
                                          @NBR_OF_RW_UDT = 0
    SET @ERROR_PROCEDURE_NAME = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_SLS_DLY_LOAD'

    SELECT
      @ERROR_LINE = ERROR_NUMBER(),
      @ERROR_MSG = ERROR_MESSAGE();

    --------- Log execution error ----------
    EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                  @ERROR_LINE = @ERROR_LINE,
                                  @ERROR_MSG = @ERROR_MSG;

    THROW;

  END CATCH

  END
