CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_COST_MPRS_AGG_LOAD] AS
BEGIN TRY

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL.PROC_FCT_DLY_COST_MPRS_AGG_LOAD'
DECLARE @ERROR_LINE AS int
DECLARE @ERROR_MSG AS NVARCHAR(MAX)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_PRES'
,@EXEC_JOB  = 'PROC_FCT_DLY_COST_MPRS_AGG_LOAD'
,@SRC_ENTY  = 'FCT_PRODUCT_COST_RCV_TY_LY_FSC'
,@TGT_ENTY = 'FCT_COST_MPRS_ITMSKU_AGG'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;


TRUNCATE TABLE [EDAA_PRES].[FCT_COST_MPRS_ITMSKU_AGG]

--Combine Cost RCV agg values
;BEGIN
WITH dim_product AS
(
SELECT
DISTINCT Lvl1_Prod_Id,
		 PROD_HIST_SK,
		 ITM_SKU
FROM EDAA_DW.DIM_PROD
WHERE IS_Curr_Ind=1
AND Lvl1_Prod_Id IS NOT NULL AND Lvl1_Prod_Id !='n/a'
),
combined_tables AS (
SELECT
dtsel_t.CLN_TYP_ID,
dtsel_t.PRE_DEF_ID,
CONVERT(DATE,CONVERT(VARCHAR(10),dtsel_t.MAX_DT,120)) AS DT_VAL,
T.GEO_HIST_SK,
T.PROD_HIST_SK,
P.Lvl1_Prod_Id,
T.Itm_Sku,
 MJR_PKG_UT_QTY_TY_FSC,
 MJR_PKG_UT_QTY_LY_FSC,
 ITM_GRSS_CST_AMT_TY_FSC,
 ITM_GRSS_CST_AMT_LY_FSC,
 ITM_NET_CST_AMT_TY_FSC,
 ITM_NET_CST_AMT_LY_FSC,
 ITM_CHRG_EA_AMT_TY_FSC,
 ITM_CHRG_EA_AMT_LY_FSC,
 ITM_ALW_EA_AMT_TY_FSC,
 ITM_ALW_EA_AMT_LY_FSC,
 PO_CHRG_EA_AMT_TY_FSC,
 PO_CHRG_EA_AMT_LY_FSC,
 PO_ALW_EA_AMT_TY_FSC,
 PO_ALW_EA_AMT_LY_FSC,
 CSH_DCT_EA_AMT_TY_FSC,
 CSH_DCT_EA_AMT_LY_FSC,
 FRT_CHRG_EA_AMT_TY_FSC,
 FRT_CHRG_EA_AMT_LY_FSC,
 FRT_ALW_EA_AMT_TY_FSC,
 FRT_ALW_EA_AMT_LY_FSC,
 FRT_UNLD_CHRG_AMT_TY_FSC,
 FRT_UNLD_CHRG_AMT_LY_FSC,
 IPT_LD_CHRG_AMT_TY_FSC,
 IPT_LD_CHRG_AMT_LY_FSC,
 BKH_FRT_CHRG_AMT_TY_FSC,
 BKH_FRT_CHRG_AMT_LY_FSC,
 EXTD_BKH_FRT_CHRG_AMT_TY_FSC,
 EXTD_BKH_FRT_CHRG_AMT_LY_FSC,
 CostOfGoodsReductionAmount_TY_FSC,
 CostOfGoodsReductionAmount_LY_FSC,
 SwellAndDefectiveAlw_TY_FSC,
 SwellAndDefectiveAlw_LY_FSC
FROM [EDAA_PRES].[FCT_PRODUCT_COST_RCV_TY_LY_FSC] AS T
JOIN EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP AS dtsel_t
ON dtsel_t.AGG_TYP='AGG'
AND T.DT_SK>=dtsel_t.MIN_DT
AND T.DT_SK<=dtsel_t.MAX_DT
JOIN dim_product P ON T.Itm_Sku=P.Itm_Sku
)

INSERT INTO [EDAA_PRES].[FCT_COST_MPRS_ITMSKU_AGG]
(ROW_ID_VAL,CLN_TYP_ID,PRE_DEF_ID,DT_VAL,GEO_HIST_SK,PROD_HIST_SK,ITM_SKU,MJR_PKG_UT_QTY_TY_FSC,MJR_PKG_UT_QTY_LY_FSC,ITM_GRSS_CST_AMT_TY_FSC,ITM_GRSS_CST_AMT_LY_FSC,ITM_NET_CST_AMT_TY_FSC,ITM_NET_CST_AMT_LY_FSC,ITM_CHRG_EA_AMT_TY_FSC,ITM_CHRG_EA_AMT_LY_FSC,ITM_ALW_EA_AMT_TY_FSC,ITM_ALW_EA_AMT_LY_FSC,PO_CHRG_EA_AMT_TY_FSC,PO_CHRG_EA_AMT_LY_FSC,PO_ALW_EA_AMT_TY_FSC,PO_ALW_EA_AMT_LY_FSC,CSH_DCT_EA_AMT_TY_FSC,CSH_DCT_EA_AMT_LY_FSC,FRT_CHRG_EA_AMT_TY_FSC,FRT_CHRG_EA_AMT_LY_FSC,FRT_ALW_EA_AMT_TY_FSC,FRT_ALW_EA_AMT_LY_FSC,FRT_UNLD_CHRG_AMT_TY_FSC,FRT_UNLD_CHRG_AMT_LY_FSC,IPT_LD_CHRG_AMT_TY_FSC,IPT_LD_CHRG_AMT_LY_FSC,BKH_FRT_CHRG_AMT_TY_FSC,BKH_FRT_CHRG_AMT_LY_FSC,EXTD_BKH_FRT_CHRG_AMT_TY_FSC,EXTD_BKH_FRT_CHRG_AMT_LY_FSC,CostOfGoodsReductionAmount_TY_FSC,CostOfGoodsReductionAmount_LY_FSC,SwellAndDefectiveAlw_TY_FSC,SwellAndDefectiveAlw_LY_FSC)
SELECT
combined_tables.PRE_DEF_ID,
combined_tables.CLN_TYP_ID,
combined_tables.PRE_DEF_ID,
combined_tables.DT_VAL,
combined_tables.GEO_HIST_SK,
combined_tables.PROD_HIST_SK,
combined_tables.ITM_SKU,
SUM(combined_tables.MJR_PKG_UT_QTY_TY_FSC) AS MJR_PKG_UT_QTY_TY_FSC,
SUM(combined_tables.MJR_PKG_UT_QTY_LY_FSC) AS MJR_PKG_UT_QTY_LY_FSC,
SUM(combined_tables.ITM_GRSS_CST_AMT_TY_FSC) AS ITM_GRSS_CST_AMT_TY_FSC,
SUM(combined_tables.ITM_GRSS_CST_AMT_LY_FSC) AS ITM_GRSS_CST_AMT_LY_FSC,
SUM(combined_tables.ITM_NET_CST_AMT_TY_FSC) AS ITM_NET_CST_AMT_TY_FSC,
SUM(combined_tables.ITM_NET_CST_AMT_LY_FSC) AS ITM_NET_CST_AMT_LY_FSC,
SUM(combined_tables.ITM_CHRG_EA_AMT_TY_FSC) AS ITM_CHRG_EA_AMT_TY_FSC,
SUM(combined_tables.ITM_CHRG_EA_AMT_LY_FSC) AS ITM_CHRG_EA_AMT_LY_FSC,
SUM(combined_tables.ITM_ALW_EA_AMT_TY_FSC) AS  ITM_ALW_EA_AMT_TY_FSC,
SUM(combined_tables.ITM_ALW_EA_AMT_LY_FSC) AS ITM_ALW_EA_AMT_LY_FSC,
SUM(combined_tables.PO_CHRG_EA_AMT_TY_FSC) AS PO_CHRG_EA_AMT_TY_FSC,
SUM(combined_tables.PO_CHRG_EA_AMT_LY_FSC) AS PO_CHRG_EA_AMT_LY_FSC,
SUM(combined_tables.PO_ALW_EA_AMT_TY_FSC) AS PO_ALW_EA_AMT_TY_FSC,
SUM(combined_tables.PO_ALW_EA_AMT_LY_FSC) AS PO_ALW_EA_AMT_LY_FSC,
SUM(combined_tables.CSH_DCT_EA_AMT_TY_FSC) AS CSH_DCT_EA_AMT_TY_FSC,
SUM(combined_tables.CSH_DCT_EA_AMT_LY_FSC) AS CSH_DCT_EA_AMT_LY_FSC,
SUM(combined_tables.FRT_CHRG_EA_AMT_TY_FSC) AS FRT_CHRG_EA_AMT_TY_FSC,
SUM(combined_tables.FRT_CHRG_EA_AMT_LY_FSC) AS FRT_CHRG_EA_AMT_LY_FSC,
SUM(combined_tables.FRT_ALW_EA_AMT_TY_FSC) AS FRT_ALW_EA_AMT_TY_FSC,
SUM(combined_tables.FRT_ALW_EA_AMT_LY_FSC) AS FRT_ALW_EA_AMT_LY_FSC,
SUM(combined_tables.FRT_UNLD_CHRG_AMT_TY_FSC) AS FRT_UNLD_CHRG_AMT_TY_FSC,
SUM(combined_tables.FRT_UNLD_CHRG_AMT_LY_FSC) AS FRT_UNLD_CHRG_AMT_LY_FSC,
SUM(combined_tables.IPT_LD_CHRG_AMT_TY_FSC) AS IPT_LD_CHRG_AMT_TY_FSC,
SUM(combined_tables.IPT_LD_CHRG_AMT_LY_FSC) AS IPT_LD_CHRG_AMT_TY_FSC,
SUM(combined_tables.BKH_FRT_CHRG_AMT_TY_FSC) AS BKH_FRT_CHRG_AMT_TY_FSC,
SUM(combined_tables.BKH_FRT_CHRG_AMT_LY_FSC) AS BKH_FRT_CHRG_AMT_LY_FSC,
SUM(combined_tables.EXTD_BKH_FRT_CHRG_AMT_TY_FSC) AS EXTD_BKH_FRT_CHRG_AMT_TY_FSC,
SUM(combined_tables.EXTD_BKH_FRT_CHRG_AMT_LY_FSC) AS EXTD_BKH_FRT_CHRG_AMT_LY_FSC,
SUM(combined_tables.CostOfGoodsReductionAmount_TY_FSC) AS CostOfGoodsReductionAmount_TY_FSC,
SUM(combined_tables.CostOfGoodsReductionAmount_LY_FSC) AS CostOfGoodsReductionAmount_LY_FSC,
SUM(combined_tables.SwellAndDefectiveAlw_TY_FSC) AS SwellAndDefectiveAlw_TY_FSC,
SUM(combined_tables.SwellAndDefectiveAlw_LY_FSC) AS SwellAndDefectiveAlw_LY_FSC
FROM
combined_tables
GROUP BY
combined_tables.PRE_DEF_ID,
combined_tables.CLN_TYP_ID,
combined_tables.PRE_DEF_ID,
combined_tables.DT_VAL,
combined_tables.GEO_HIST_SK,
combined_tables.PROD_HIST_SK,
combined_tables.ITM_SKU
END

BEGIN
WITH dim_product_avg AS
(
SELECT
DISTINCT Lvl1_Prod_Id,
		 PROD_HIST_SK,
		 ITM_SKU
FROM EDAA_DW.DIM_PROD
WHERE IS_Curr_Ind=1
AND Lvl1_Prod_Id IS NOT NULL AND Lvl1_Prod_Id !='n/a'
),
combined_tables_avg AS (
SELECT
dtsel_t.CLN_TYP_ID,
dtsel_t.PRE_DEF_ID,
CONVERT(DATE,CONVERT(VARCHAR(10),dtsel_t.MAX_DT,120)) AS DT_VAL,
T.GEO_HIST_SK,
T.PROD_HIST_SK,
P.Lvl1_Prod_Id,
T.Itm_Sku,
 MJR_PKG_UT_QTY_TY_FSC,
 MJR_PKG_UT_QTY_LY_FSC,
 ITM_GRSS_CST_AMT_TY_FSC,
 ITM_GRSS_CST_AMT_LY_FSC,
 ITM_NET_CST_AMT_TY_FSC,
 ITM_NET_CST_AMT_LY_FSC,
 ITM_CHRG_EA_AMT_TY_FSC,
 ITM_CHRG_EA_AMT_LY_FSC,
 ITM_ALW_EA_AMT_TY_FSC,
 ITM_ALW_EA_AMT_LY_FSC,
 PO_CHRG_EA_AMT_TY_FSC,
 PO_CHRG_EA_AMT_LY_FSC,
 PO_ALW_EA_AMT_TY_FSC,
 PO_ALW_EA_AMT_LY_FSC,
 CSH_DCT_EA_AMT_TY_FSC,
 CSH_DCT_EA_AMT_LY_FSC,
 FRT_CHRG_EA_AMT_TY_FSC,
 FRT_CHRG_EA_AMT_LY_FSC,
 FRT_ALW_EA_AMT_TY_FSC,
 FRT_ALW_EA_AMT_LY_FSC,
 FRT_UNLD_CHRG_AMT_TY_FSC,
 FRT_UNLD_CHRG_AMT_LY_FSC,
 IPT_LD_CHRG_AMT_TY_FSC,
 IPT_LD_CHRG_AMT_LY_FSC,
 BKH_FRT_CHRG_AMT_TY_FSC,
 BKH_FRT_CHRG_AMT_LY_FSC,
 EXTD_BKH_FRT_CHRG_AMT_TY_FSC,
 EXTD_BKH_FRT_CHRG_AMT_LY_FSC,
 CostOfGoodsReductionAmount_TY_FSC,
 CostOfGoodsReductionAmount_LY_FSC,
 SwellAndDefectiveAlw_TY_FSC,
 SwellAndDefectiveAlw_LY_FSC
FROM [EDAA_PRES].[FCT_PRODUCT_COST_RCV_TY_LY_FSC] AS T
JOIN EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP AS dtsel_t
ON dtsel_t.AGG_TYP='AGG'
AND T.DT_SK>=dtsel_t.MIN_DT
AND T.DT_SK<=dtsel_t.MAX_DT
JOIN dim_product_avg P ON T.Itm_Sku=P.Itm_Sku
)
INSERT INTO [EDAA_PRES].[FCT_COST_MPRS_ITMSKU_AGG]
(ROW_ID_VAL,CLN_TYP_ID,PRE_DEF_ID,DT_VAL,GEO_HIST_SK,PROD_HIST_SK,ITM_SKU,MJR_PKG_UT_QTY_TY_FSC,MJR_PKG_UT_QTY_LY_FSC,ITM_GRSS_CST_AMT_TY_FSC,ITM_GRSS_CST_AMT_LY_FSC,ITM_NET_CST_AMT_TY_FSC,ITM_NET_CST_AMT_LY_FSC,ITM_CHRG_EA_AMT_TY_FSC,ITM_CHRG_EA_AMT_LY_FSC,ITM_ALW_EA_AMT_TY_FSC,ITM_ALW_EA_AMT_LY_FSC,PO_CHRG_EA_AMT_TY_FSC,PO_CHRG_EA_AMT_LY_FSC,PO_ALW_EA_AMT_TY_FSC,PO_ALW_EA_AMT_LY_FSC,CSH_DCT_EA_AMT_TY_FSC,CSH_DCT_EA_AMT_LY_FSC,FRT_CHRG_EA_AMT_TY_FSC,FRT_CHRG_EA_AMT_LY_FSC,FRT_ALW_EA_AMT_TY_FSC,FRT_ALW_EA_AMT_LY_FSC,FRT_UNLD_CHRG_AMT_TY_FSC,FRT_UNLD_CHRG_AMT_LY_FSC,IPT_LD_CHRG_AMT_TY_FSC,IPT_LD_CHRG_AMT_LY_FSC,BKH_FRT_CHRG_AMT_TY_FSC,BKH_FRT_CHRG_AMT_LY_FSC,EXTD_BKH_FRT_CHRG_AMT_TY_FSC,EXTD_BKH_FRT_CHRG_AMT_LY_FSC,CostOfGoodsReductionAmount_TY_FSC,CostOfGoodsReductionAmount_LY_FSC,SwellAndDefectiveAlw_TY_FSC,SwellAndDefectiveAlw_LY_FSC)
SELECT
combined_tables_avg.PRE_DEF_ID,
combined_tables_avg.CLN_TYP_ID,
combined_tables_avg.PRE_DEF_ID,
combined_tables_avg.DT_VAL,
combined_tables_avg.GEO_HIST_SK,
PROD.PROD_HIST_SK,
PROD.ITM_SKU,
AVG(combined_tables_avg.MJR_PKG_UT_QTY_TY_FSC) AS MJR_PKG_UT_QTY_TY_FSC,
AVG(combined_tables_avg.MJR_PKG_UT_QTY_LY_FSC) AS MJR_PKG_UT_QTY_LY_FSC,
AVG(combined_tables_avg.ITM_GRSS_CST_AMT_TY_FSC) AS ITM_GRSS_CST_AMT_TY_FSC,
AVG(combined_tables_avg.ITM_GRSS_CST_AMT_LY_FSC) AS ITM_GRSS_CST_AMT_LY_FSC,
AVG(combined_tables_avg.ITM_NET_CST_AMT_TY_FSC) AS ITM_NET_CST_AMT_TY_FSC,
AVG(combined_tables_avg.ITM_NET_CST_AMT_LY_FSC) AS ITM_NET_CST_AMT_LY_FSC,
AVG(combined_tables_avg.ITM_CHRG_EA_AMT_TY_FSC) AS ITM_CHRG_EA_AMT_TY_FSC,
AVG(combined_tables_avg.ITM_CHRG_EA_AMT_LY_FSC) AS ITM_CHRG_EA_AMT_LY_FSC,
AVG(combined_tables_avg.ITM_ALW_EA_AMT_TY_FSC) AS  ITM_ALW_EA_AMT_TY_FSC,
AVG(combined_tables_avg.ITM_ALW_EA_AMT_LY_FSC) AS ITM_ALW_EA_AMT_LY_FSC,
AVG(combined_tables_avg.PO_CHRG_EA_AMT_TY_FSC) AS PO_CHRG_EA_AMT_TY_FSC,
AVG(combined_tables_avg.PO_CHRG_EA_AMT_LY_FSC) AS PO_CHRG_EA_AMT_LY_FSC,
AVG(combined_tables_avg.PO_ALW_EA_AMT_TY_FSC) AS PO_ALW_EA_AMT_TY_FSC,
AVG(combined_tables_avg.PO_ALW_EA_AMT_LY_FSC) AS PO_ALW_EA_AMT_LY_FSC,
AVG(combined_tables_avg.CSH_DCT_EA_AMT_TY_FSC) AS CSH_DCT_EA_AMT_TY_FSC,
AVG(combined_tables_avg.CSH_DCT_EA_AMT_LY_FSC) AS CSH_DCT_EA_AMT_LY_FSC,
AVG(combined_tables_avg.FRT_CHRG_EA_AMT_TY_FSC) AS FRT_CHRG_EA_AMT_TY_FSC,
AVG(combined_tables_avg.FRT_CHRG_EA_AMT_LY_FSC) AS FRT_CHRG_EA_AMT_LY_FSC,
AVG(combined_tables_avg.FRT_ALW_EA_AMT_TY_FSC) AS FRT_ALW_EA_AMT_TY_FSC,
AVG(combined_tables_avg.FRT_ALW_EA_AMT_LY_FSC) AS FRT_ALW_EA_AMT_LY_FSC,
AVG(combined_tables_avg.FRT_UNLD_CHRG_AMT_TY_FSC) AS FRT_UNLD_CHRG_AMT_TY_FSC,
AVG(combined_tables_avg.FRT_UNLD_CHRG_AMT_LY_FSC) AS FRT_UNLD_CHRG_AMT_LY_FSC,
AVG(combined_tables_avg.IPT_LD_CHRG_AMT_TY_FSC) AS IPT_LD_CHRG_AMT_TY_FSC,
AVG(combined_tables_avg.IPT_LD_CHRG_AMT_LY_FSC) AS IPT_LD_CHRG_AMT_TY_FSC,
AVG(combined_tables_avg.BKH_FRT_CHRG_AMT_TY_FSC) AS BKH_FRT_CHRG_AMT_TY_FSC,
AVG(combined_tables_avg.BKH_FRT_CHRG_AMT_LY_FSC) AS BKH_FRT_CHRG_AMT_LY_FSC,
AVG(combined_tables_avg.EXTD_BKH_FRT_CHRG_AMT_TY_FSC) AS EXTD_BKH_FRT_CHRG_AMT_TY_FSC,
AVG(combined_tables_avg.EXTD_BKH_FRT_CHRG_AMT_LY_FSC) AS EXTD_BKH_FRT_CHRG_AMT_LY_FSC,
AVG(combined_tables_avg.CostOfGoodsReductionAmount_TY_FSC) AS CostOfGoodsReductionAmount_TY_FSC,
AVG(combined_tables_avg.CostOfGoodsReductionAmount_LY_FSC) AS CostOfGoodsReductionAmount_LY_FSC,
AVG(combined_tables_avg.SwellAndDefectiveAlw_TY_FSC) AS SwellAndDefectiveAlw_TY_FSC,
AVG(combined_tables_avg.SwellAndDefectiveAlw_LY_FSC) AS SwellAndDefectiveAlw_LY_FSC
FROM
combined_tables_avg
	INNER JOIN dim_product_avg PROD
		ON combined_tables_avg.Lvl1_Prod_Id=PROD.Lvl1_Prod_Id
			AND combined_tables_avg.ITM_SKU!=PROD.ITM_SKU
GROUP BY
combined_tables_avg.PRE_DEF_ID,
combined_tables_avg.CLN_TYP_ID,
combined_tables_avg.PRE_DEF_ID,
combined_tables_avg.DT_VAL,
combined_tables_avg.GEO_HIST_SK,
PROD.PROD_HIST_SK,
PROD.ITM_SKU
END


 --UPDATE STATISTICS
BEGIN
 UPDATE STATISTICS [EDAA_PRES].[FCT_COST_MPRS_ITMSKU_AGG];
END

END TRY

BEGIN CATCH
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = 0, @NBR_OF_RW_UDT  = 0
SET @ERROR_PROCEDURE_NAME = 'EDAA_ETL.PROC_FCT_DLY_COST_MPRS_AGG_LOAD'
--SET @ERROR_LINE
--SET @ERROR_MSG

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();

--------- Log execution error ----------
EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

   THROW;

END CATCH
