CREATE PROC [EDAA_ETL].[PROC_UPC_INITIAL_STGTABLE_DELETE] @SRC_ENTY [VARCHAR](500) AS
BEGIN
IF @SRC_ENTY ='UT_UPC_DLY_SL_ADJ_HST'
	BEGIN
		truncate table [EDAA_STG].[UT_UPC_DLY_SL_ADJ_HST_INITIAL];
	END
IF @SRC_ENTY ='UT_UPC_DLY_SL_HST'
	BEGIN
		truncate table [EDAA_STG].[UT_UPC_DLY_SL_HST_INITIAL];
	END
IF @SRC_ENTY ='UT_UPC_DLY_INV_TN_DTL_HST'
	BEGIN
		truncate table [EDAA_STG].[UT_UPC_DLY_INV_TN_DTL_HST_INITIAL];
	END
IF @SRC_ENTY ='UT_UPC_DLY_INV_HST'
	BEGIN
		truncate table [EDAA_STG].[UT_UPC_DLY_INV_HST_INITIAL];
		truncate table [EDAA_STG].[UT_UPC_DLY_INV_HST_DER_INITIAL];
	END
IF @SRC_ENTY ='DLY_UT_P_UPC_HST_LOSTSALES'
	BEGIN
		truncate table [EDAA_STG].[DLY_UT_P_UPC_HST_LOSTSALES];
	END
ELSE
	BEGIN
		PRINT('TABLES LOADED SUCCESSFULLY!!!!');
	END

END
