CREATE PROC [EDAA_ETL].[PROC_DM_FACTS_UPC_INITIAL_TABLELOAD] @SRC_ENTY [VARCHAR](500) AS
BEGIN
IF @SRC_ENTY ='UT_UPC_DLY_SL_ADJ_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_ADJ_INITIAL_TABLELOAD];
	END
IF @SRC_ENTY ='UT_UPC_DLY_SL_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_INITIAL_TABLELOAD];
	END
IF @SRC_ENTY ='UT_UPC_DLY_INV_TN_DTL_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_ADJ_INITIAL_TABLELOAD];
	END
IF @SRC_ENTY ='UT_UPC_DLY_INV_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_HST_INITIAL_TABLELOAD];
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_TABLELOAD];
	END
IF @SRC_ENTY ='DLY_UT_P_UPC_HST_LOSTSALES'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_LOST_SLS_INITIAL_TABLELOAD] ;
	END
ELSE
	BEGIN
		PRINT('TABLES LOADED SUCCESSFULLY!!!!');
	END

END
