CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_TABLELOAD] AS


BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_TABLELOAD'
,@SRC_ENTY  = 'UT_UPC_DLY_INV_HST_INITIAL'
,@TGT_ENTY  = 'FCT_DLY_STR_ITMSKU_INV'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


INSERT INTO [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV]
SELECT	ISNULL(PROD_HIST_SK,-1)						AS PROD_HIST_SK,
		ISNULL(GEO_HIST_SK, -1) 					AS GEO_HIST_SK,
		A.STR_ID									AS STR_ID,
		A.UPC_ID									AS ITM_SKU,
		A.INV_ROW_START_DT							AS INV_ROW_START_DT,
		A.INV_ROW_END_DT							AS INV_ROW_END_DT,
		A.INV_EACH_AMT								AS INV_EACH_AMT,
		A.INV_FNC_CHRG_AMT							AS INV_FNC_CHRG_AMT,
		A.INV_FNC_CR_AMT							AS INV_FNC_CR_AMT,
		A.INV_STRGE_CHRG_AMT						AS INV_STRGE_CHRG_AMT,
		A.INV_FRT_AMT								AS INV_FRT_AMT,
		A.INV_DIST_CNTR_HNDL_AMT					AS INV_DIST_CNTR_HNDL_AMT,
		A.INV_AMT									AS INV_AMT,
		A.INV_QTY									AS INV_QTY,
		CASE WHEN A.INV_CLRNC_IND = 'Y'
				THEN	0
			 WHEN A.INV_CLRNC_IND = 'N'
				THEN	1
			 ELSE  NULL
		END										AS INV_CLRNC_IND,
		@NEW_AUD_SKY							AS AUD_INS_SK,
		NULL									AS AUD_UPD_SK

FROM EDAA_STG.UT_UPC_DLY_INV_HST_DER_INITIAL AS A

LEFT OUTER JOIN (SELECT GEO_HIST_SK,
						STR_ID,
						VLD_FRM,
						VLD_TO
			FROM 		EDAA_DW.DIM_GEO
			--WHERE 	IS_CURR<>0

					) AS GEO
	ON GEO.STR_ID = A.STR_ID
	AND  cast(A.INV_ROW_START_DT as date) BETWEEN GEO.VLD_FRM AND ISNULL(GEO.VLD_TO, CAST('2099-01-01' AS DATE))

LEFT OUTER JOIN (SELECT PROD_HIST_SK,
						ITM_SKU,
						PROD_SK,
						VLD_FRM,
						VLD_TO
		FROM 		EDAA_DW.DIM_PROD
			--WHERE 	IS_CURR<>0

					) AS P
	ON  P.ITM_SKU = A.UPC_ID
	AND  cast(A.INV_ROW_START_DT as date) BETWEEN P.VLD_FRM AND ISNULL(P.VLD_TO, CAST('2099-01-01' AS DATE))

;

print('---DW load complete---');


BEGIN

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV] WHERE AUD_INS_SK = @NEW_AUD_SKY
print(@NBR_OF_RW_ISRT)

END


/*AUDIT LOG END*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_TABLELOAD]'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------

EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


 THROW;




END CATCH
