CREATE PROC [EDAA_ETL].[PROC_PRES_FACTS_AGG_TABLELOAD] @SRC_NAME [VARCHAR](500) AS
BEGIN
IF @SRC_NAME = 'UT_UPC_DLY_SL_ADJ_HST'
    OR @SRC_NAME = 'UT_UPC_DLY_SL_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD] @SRC_NAME;
	END
IF @SRC_NAME ='UT_UPC_DLY_INV_TN_DTL_HST'
	BEGIN
		EXEC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_AGG_LOAD];
	END
ELSE
	BEGIN
		PRINT('TABLES LOADED SUCCESSFULLY!!!!');
	END
END
