CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_PRES_SLS_TY_LY_DATA_FIX]
AS
BEGIN
  BEGIN TRY

    /*DATAMART AUDITING VARIABLES*/
    DECLARE @NEW_AUD_SKY bigint
    DECLARE @NBR_OF_RW_ISRT int
    DECLARE @NBR_OF_RW_UDT int
    DECLARE @EXEC_LYR varchar(255)
    DECLARE @EXEC_JOB varchar(500)
    DECLARE @SRC_ENTY varchar(500)
    DECLARE @TGT_ENTY varchar(500)
    DECLARE @GETDATETIME datetime = GETDATE()

    /* -------- insert into TY subset table --------  */
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
                                            @EXEC_JOB = 'PROC_FCT_DLY_STR_ITMSKU_PRES_SLS_TY_LY_DATA_FIX',
                                            @SRC_ENTY = 'FCT_DLY_STR_ITMSKU_SLS',
                                            @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC',
                                            @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


    ;
    WITH DTSEL
    AS (
	SELECT
      DT_SK AS DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal
    WHERE FSC_YR=YEAR(GETDATE()) AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')
	),

    LY_HLDY_DATA_LOAD
    AS (SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      SUM(SLS_ADJ_AMT) AS SLS_ADJ_AMT,
      SUM(SLS_ADJ_QTY) AS SLS_ADJ_QTY,
      SUM(SLS_ADJ_WGT) AS SLS_ADJ_WGT,
      SUM(PRM_TO_SLS_ADJ_AMT) AS PRM_TO_SLS_ADJ_AMT,
      SUM(PRM_TO_SLS_ADJ_QTY) AS PRM_TO_SLS_ADJ_QTY,
      SUM(PRM_TO_SLS_ADJ_WGT) AS PRM_TO_SLS_ADJ_WGT,
      SUM(PRM_TO_SLS_MKDN_ADJ_AMT) AS PRM_TO_SLS_MKDN_ADJ_AMT,
      SUM(CLRNC_SLS_ADJ_AMT) AS CLRNC_SLS_ADJ_AMT,
      SUM(CLRNC_ADJ_QTY) AS CLRNC_ADJ_QTY,
      SUM(CLRNC_ADJ_WGT) AS CLRNC_ADJ_WGT,
      SUM(CLRNC_MKDN_ADJ_AMT) AS CLRNC_MKDN_ADJ_AMT,
      SUM(COGS_ADJ_AMT) AS COGS_ADJ_AMT,
      SUM(COGS_FNC_CHRG_ADJ_AMT) AS COGS_FNC_CHRG_ADJ_AMT,
      SUM(COGS_FNC_CR_ADJ_AMT) AS COGS_FNC_CR_ADJ_AMT,
      SUM(COGS_STRGE_CHRG_ADJ_AMT) AS COGS_STRGE_CHRG_ADJ_AMT,
      SUM(COGS_FRT_ADJ_AMT) AS COGS_FRT_ADJ_AMT,
      SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT) AS COGS_DIST_CNTR_HNDL_ADJ_AMT,
      SUM(DRCT_MGN_ADJ_AMT) AS DRCT_MGN_ADJ_AMT,
      SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
      SUM(CLRNC_DRCT_MGN_ADJ_AMT) AS CLRNC_DRCT_MGN_ADJ_AMT
    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_ADJ] AS a
    INNER JOIN DTSEL b
      ON a.DT_SK = b.LY_DT_SK_HLDY
    GROUP BY CAST(b.DT_SK AS int),
             CAST(b.LY_DT_SK AS int),
             CAST(b.LY_DT_SK_HLDY AS int),
             CAST(b.LY_DT_SK_CAL AS int),
             A.[ITM_SKU],
             A.[STR_ID])


    UPDATE T
    SET T.SLS_ADJ_AMT_LY_HLDY = S.SLS_ADJ_AMT,
        T.SLS_ADJ_QTY_LY_HLDY = S.SLS_ADJ_QTY,
        T.SLS_ADJ_WGT_LY_HLDY = S.SLS_ADJ_WGT,
        T.PRM_TO_SLS_ADJ_AMT_LY_HLDY = S.PRM_TO_SLS_ADJ_AMT,
        T.PRM_TO_SLS_ADJ_QTY_LY_HLDY = S.PRM_TO_SLS_ADJ_QTY,
        T.PRM_TO_SLS_ADJ_WGT_LY_HLDY = S.PRM_TO_SLS_ADJ_WGT,
        T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY = S.PRM_TO_SLS_MKDN_ADJ_AMT,
        T.CLRNC_SLS_ADJ_AMT_LY_HLDY = S.CLRNC_SLS_ADJ_AMT,
        T.CLRNC_ADJ_QTY_LY_HLDY = S.CLRNC_ADJ_QTY,
        T.CLRNC_ADJ_WGT_LY_HLDY = S.CLRNC_ADJ_WGT,
        T.CLRNC_MKDN_ADJ_AMT_LY_HLDY = S.CLRNC_MKDN_ADJ_AMT,
        T.COGS_ADJ_AMT_LY_HLDY = S.COGS_ADJ_AMT,
        T.COGS_FNC_CHRG_ADJ_AMT_LY_HLDY = S.COGS_FNC_CHRG_ADJ_AMT,
        T.COGS_FNC_CR_ADJ_AMT_LY_HLDY = S.COGS_FNC_CR_ADJ_AMT,
        T.COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY = S.COGS_STRGE_CHRG_ADJ_AMT,
        T.DRCT_MGN_ADJ_AMT_LY_HLDY = S.DRCT_MGN_ADJ_AMT,
        T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY = S.PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
        T.CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY = S.CLRNC_DRCT_MGN_ADJ_AMT,
        T.COGS_FRT_ADJ_AMT_LY_HLDY = S.COGS_FRT_ADJ_AMT,
        T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY = S.COGS_DIST_CNTR_HNDL_ADJ_AMT,
        T.[UPDATEDTIMESTAMP] = GETDATE()
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T
    INNER JOIN LY_HLDY_DATA_LOAD S
      ON T.LY_DT_SK_HLDY = S.LY_DT_SK_HLDY
      AND T.STR_ID = S.STR_ID
      AND T.ITM_SKU = S.ITM_SKU




    ;
    WITH DTSEL
    AS (
	SELECT
      DT_SK AS DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal
    WHERE FSC_YR=YEAR(GETDATE()) AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')
	)
	,
    LY_CAL_DATA_LOAD
    AS (SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      SUM(SLS_ADJ_AMT) AS SLS_ADJ_AMT,
      SUM(SLS_ADJ_QTY) AS SLS_ADJ_QTY,
      SUM(SLS_ADJ_WGT) AS SLS_ADJ_WGT,
      SUM(PRM_TO_SLS_ADJ_AMT) AS PRM_TO_SLS_ADJ_AMT,
      SUM(PRM_TO_SLS_ADJ_QTY) AS PRM_TO_SLS_ADJ_QTY,
      SUM(PRM_TO_SLS_ADJ_WGT) AS PRM_TO_SLS_ADJ_WGT,
      SUM(PRM_TO_SLS_MKDN_ADJ_AMT) AS PRM_TO_SLS_MKDN_ADJ_AMT,
      SUM(CLRNC_SLS_ADJ_AMT) AS CLRNC_SLS_ADJ_AMT,
      SUM(CLRNC_ADJ_QTY) AS CLRNC_ADJ_QTY,
      SUM(CLRNC_ADJ_WGT) AS CLRNC_ADJ_WGT,
      SUM(CLRNC_MKDN_ADJ_AMT) AS CLRNC_MKDN_ADJ_AMT,
      SUM(COGS_ADJ_AMT) AS COGS_ADJ_AMT,
      SUM(COGS_FNC_CHRG_ADJ_AMT) AS COGS_FNC_CHRG_ADJ_AMT,
      SUM(COGS_FNC_CR_ADJ_AMT) AS COGS_FNC_CR_ADJ_AMT,
      SUM(COGS_STRGE_CHRG_ADJ_AMT) AS COGS_STRGE_CHRG_ADJ_AMT,
      SUM(COGS_FRT_ADJ_AMT) AS COGS_FRT_ADJ_AMT,
      SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT) AS COGS_DIST_CNTR_HNDL_ADJ_AMT,
      SUM(DRCT_MGN_ADJ_AMT) AS DRCT_MGN_ADJ_AMT,
      SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
      SUM(CLRNC_DRCT_MGN_ADJ_AMT) AS CLRNC_DRCT_MGN_ADJ_AMT
    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_ADJ] AS a
    INNER JOIN DTSEL b
      ON a.DT_SK = b.LY_DT_SK_CAL
    GROUP BY CAST(b.DT_SK AS int),
             CAST(b.LY_DT_SK AS int),
             CAST(b.LY_DT_SK_HLDY AS int),
             CAST(b.LY_DT_SK_CAL AS int),
             A.[ITM_SKU],
             A.[STR_ID])


    UPDATE T
    SET T.SLS_ADJ_AMT_LY_CAL = S.SLS_ADJ_AMT,
        T.SLS_ADJ_QTY_LY_CAL = S.SLS_ADJ_QTY,
        T.SLS_ADJ_WGT_LY_CAL = S.SLS_ADJ_WGT,
        T.PRM_TO_SLS_ADJ_AMT_LY_CAL = S.PRM_TO_SLS_ADJ_AMT,
        T.PRM_TO_SLS_ADJ_QTY_LY_CAL = S.PRM_TO_SLS_ADJ_QTY,
        T.PRM_TO_SLS_ADJ_WGT_LY_CAL = S.PRM_TO_SLS_ADJ_WGT,
        T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL = S.PRM_TO_SLS_MKDN_ADJ_AMT,
        T.CLRNC_SLS_ADJ_AMT_LY_CAL = S.CLRNC_SLS_ADJ_AMT,
        T.CLRNC_ADJ_QTY_LY_CAL = S.CLRNC_ADJ_QTY,
        T.CLRNC_ADJ_WGT_LY_CAL = S.CLRNC_ADJ_WGT,
        T.CLRNC_MKDN_ADJ_AMT_LY_CAL = S.CLRNC_MKDN_ADJ_AMT,
        T.COGS_ADJ_AMT_LY_CAL = S.COGS_ADJ_AMT,
        T.COGS_FNC_CHRG_ADJ_AMT_LY_CAL = S.COGS_FNC_CHRG_ADJ_AMT,
        T.COGS_FNC_CR_ADJ_AMT_LY_CAL = S.COGS_FNC_CR_ADJ_AMT,
        T.COGS_STRGE_CHRG_ADJ_AMT_LY_CAL = S.COGS_STRGE_CHRG_ADJ_AMT,
        T.DRCT_MGN_ADJ_AMT_LY_CAL = S.DRCT_MGN_ADJ_AMT,
        T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL = S.PRM_TO_SLS_DRCT_MGN_ADJ_AMT,
        T.CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL = S.CLRNC_DRCT_MGN_ADJ_AMT,
        T.COGS_FRT_ADJ_AMT_LY_CAL = S.COGS_FRT_ADJ_AMT,
        T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL = S.COGS_DIST_CNTR_HNDL_ADJ_AMT,
        T.[UPDATEDTIMESTAMP] = GETDATE()
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T
    INNER JOIN LY_CAL_DATA_LOAD S
      ON T.LY_DT_SK_CAL = S.LY_DT_SK_CAL
      AND T.STR_ID = S.STR_ID
      AND T.ITM_SKU = S.ITM_SKU

    PRINT ('UPDATE FCT_DLY_STR_ITMSKU_SLS_TY_LY')
     ;
    WITH DTSEL
    AS (
	SELECT
      DT_SK AS DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal
    WHERE FSC_YR=YEAR(GETDATE()) AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')
	),
    LY_HLDY_DATA_LOAD
    AS (SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      SUM([SLS_AMT]) AS SLS_AMT,
      SUM([SLS_QTY]) AS SLS_QTY,
      SUM([SLS_WGT]) AS SLS_WGT,
      SUM([PRM_TO_SLS_AMT]) AS PRM_TO_SLS_AMT,
      SUM([PRM_TO_SLS_QTY]) AS PRM_TO_SLS_QTY,
      SUM([PRM_TO_SLS_WGT]) AS PRM_TO_SLS_WGT,
      SUM([PRM_TO_SLS_MKDN_AMT]) AS PRM_TO_SLS_MKDN_AMT,
      SUM([CLRNC_SLS_AMT]) AS CLRNC_SLS_AMT,
      SUM([CLRNC_QTY]) AS CLRNC_QTY,
      SUM([CLRNC_WGT]) AS CLRNC_WGT,
      SUM([CLRNC_MKDN_AMT]) AS CLRNC_MKDN_AMT,
      SUM([COGS_AMT]) AS COGS_AMT,
      SUM([COGS_FNC_CHRG_AMT]) AS COGS_FNC_CHRG_AMT,
      SUM([COGS_FNC_CR_AMT]) AS COGS_FNC_CR_AMT,
      SUM([COGS_STRGE_CHRG_AMT]) AS COGS_STRGE_CHRG_AMT,
      SUM([DRCT_MGN_AMT]) AS DRCT_MGN_AMT,
      SUM([PRM_TO_SLS_DRCT_MGN_AMT]) AS PRM_TO_SLS_DRCT_MGN_AMT,
      SUM([CLRNC_DRCT_MGN_AMT]) AS CLRNC_DRCT_MGN_AMT,
      SUM([COGS_FRT_AMT]) AS COGS_FRT_AMT,
      SUM([COGS_DIST_CNTR_HNDL_AMT]) AS COGS_DIST_CNTR_HNDL_AMT

    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
    INNER JOIN DTSEL b
      ON a.DT_SK = b.LY_DT_SK_HLDY
    GROUP BY CAST(b.DT_SK AS int),
             CAST(b.LY_DT_SK AS int),
             CAST(b.LY_DT_SK_HLDY AS int),
             CAST(b.LY_DT_SK_CAL AS int),
             A.[ITM_SKU],
             A.[STR_ID])


    UPDATE T
    SET T.SLS_AMT_LY_HLDY = S.SLS_AMT,
        T.SLS_QTY_LY_HLDY = S.SLS_QTY,
        T.SLS_WGT_LY_HLDY = S.SLS_WGT,
        T.PRM_TO_SLS_AMT_LY_HLDY = S.PRM_TO_SLS_AMT,
        T.PRM_TO_SLS_QTY_LY_HLDY = S.PRM_TO_SLS_QTY,
        T.PRM_TO_SLS_WGT_LY_HLDY = S.PRM_TO_SLS_WGT,
        T.PRM_TO_SLS_MKDN_AMT_LY_HLDY = S.PRM_TO_SLS_MKDN_AMT,
        T.CLRNC_SLS_AMT_LY_HLDY = S.CLRNC_SLS_AMT,
        T.CLRNC_QTY_LY_HLDY = S.CLRNC_QTY,
        T.CLRNC_WGT_LY_HLDY = S.CLRNC_WGT,
        T.CLRNC_MKDN_AMT_LY_HLDY = S.CLRNC_MKDN_AMT,
        T.COGS_AMT_LY_HLDY = S.COGS_AMT,
        T.COGS_FNC_CHRG_AMT_LY_HLDY = S.COGS_FNC_CHRG_AMT,
        T.COGS_STRGE_CHRG_AMT_LY_HLDY = S.COGS_STRGE_CHRG_AMT,
        T.DRCT_MGN_AMT_LY_HLDY = S.DRCT_MGN_AMT,
        T.PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY = S.PRM_TO_SLS_DRCT_MGN_AMT,
        T.CLRNC_DRCT_MGN_AMT_LY_HLDY = S.CLRNC_DRCT_MGN_AMT,
        T.COGS_FRT_AMT_LY_HLDY = S.COGS_FRT_AMT,
        T.COGS_DIST_CNTR_HNDL_AMT_LY_HLDY = S.COGS_DIST_CNTR_HNDL_AMT,
        T.[COGS_FNC_CR_AMT_LY_HLDY] = S.[COGS_FNC_CR_AMT],
        T.[UPDATEDTIMESTAMP] = GETDATE()
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
    INNER JOIN LY_HLDY_DATA_LOAD S
      ON T.ITM_SKU = S.ITM_SKU
      AND T.STR_ID = S.STR_ID
      AND T.LY_DT_SK_HLDY = S.LY_DT_SK_HLDY



    ;
    WITH DTSEL
    AS (
	SELECT
      DT_SK AS DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal
    WHERE FSC_YR=YEAR(GETDATE()) AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')
	),
    LY_CAL_DATA_LOAD
    AS (SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      SUM([SLS_AMT]) AS SLS_AMT,
      SUM([SLS_QTY]) AS SLS_QTY,
      SUM([SLS_WGT]) AS SLS_WGT,
      SUM([PRM_TO_SLS_AMT]) AS PRM_TO_SLS_AMT,
      SUM([PRM_TO_SLS_QTY]) AS PRM_TO_SLS_QTY,
      SUM([PRM_TO_SLS_WGT]) AS PRM_TO_SLS_WGT,
      SUM([PRM_TO_SLS_MKDN_AMT]) AS PRM_TO_SLS_MKDN_AMT,
      SUM([CLRNC_SLS_AMT]) AS CLRNC_SLS_AMT,
      SUM([CLRNC_QTY]) AS CLRNC_QTY,
      SUM([CLRNC_WGT]) AS CLRNC_WGT,
      SUM([CLRNC_MKDN_AMT]) AS CLRNC_MKDN_AMT,
      SUM([COGS_AMT]) AS COGS_AMT,
      SUM([COGS_FNC_CHRG_AMT]) AS COGS_FNC_CHRG_AMT,
      SUM([COGS_FNC_CR_AMT]) AS COGS_FNC_CR_AMT,
      SUM([COGS_STRGE_CHRG_AMT]) AS COGS_STRGE_CHRG_AMT,
      SUM([DRCT_MGN_AMT]) AS DRCT_MGN_AMT,
      SUM([PRM_TO_SLS_DRCT_MGN_AMT]) AS PRM_TO_SLS_DRCT_MGN_AMT,
      SUM([CLRNC_DRCT_MGN_AMT]) AS CLRNC_DRCT_MGN_AMT,
      SUM([COGS_FRT_AMT]) AS COGS_FRT_AMT,
      SUM([COGS_DIST_CNTR_HNDL_AMT]) AS COGS_DIST_CNTR_HNDL_AMT
    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
    INNER JOIN DTSEL b
      ON a.DT_SK = b.LY_DT_SK_CAL
    GROUP BY CAST(b.DT_SK AS int),
             CAST(b.LY_DT_SK AS int),
             CAST(b.LY_DT_SK_HLDY AS int),
             CAST(b.LY_DT_SK_CAL AS int),
             A.[ITM_SKU],
             A.[STR_ID])


    UPDATE T
    SET T.SLS_AMT_LY_CAL = S.SLS_AMT,
        T.SLS_QTY_LY_CAL = S.SLS_QTY,
        T.SLS_WGT_LY_CAL = S.SLS_WGT,
        T.PRM_TO_SLS_AMT_LY_CAL = S.PRM_TO_SLS_AMT,
        T.PRM_TO_SLS_QTY_LY_CAL = S.PRM_TO_SLS_QTY,
        T.PRM_TO_SLS_WGT_LY_CAL = S.PRM_TO_SLS_WGT,
        T.PRM_TO_SLS_MKDN_AMT_LY_CAL = S.PRM_TO_SLS_MKDN_AMT,
        T.CLRNC_SLS_AMT_LY_CAL = S.CLRNC_SLS_AMT,
        T.CLRNC_QTY_LY_CAL = S.CLRNC_QTY,
        T.CLRNC_WGT_LY_CAL = S.CLRNC_WGT,
        T.CLRNC_MKDN_AMT_LY_CAL = S.CLRNC_MKDN_AMT,
        T.COGS_AMT_LY_CAL = S.COGS_AMT,
        T.COGS_FNC_CHRG_AMT_LY_CAL = S.COGS_FNC_CHRG_AMT,
        T.COGS_STRGE_CHRG_AMT_LY_CAL = S.COGS_STRGE_CHRG_AMT,
        T.DRCT_MGN_AMT_LY_CAL = S.DRCT_MGN_AMT,
        T.PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL = S.PRM_TO_SLS_DRCT_MGN_AMT,
        T.CLRNC_DRCT_MGN_AMT_LY_CAL = S.CLRNC_DRCT_MGN_AMT,
        T.COGS_FRT_AMT_LY_CAL = S.COGS_FRT_AMT,
        T.COGS_DIST_CNTR_HNDL_AMT_LY_CAL = S.COGS_DIST_CNTR_HNDL_AMT,
        T.[COGS_FNC_CR_AMT_LY_CAL] = S.[COGS_FNC_CR_AMT],
        T.[UPDATEDTIMESTAMP] = GETDATE()
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
    INNER JOIN LY_CAL_DATA_LOAD S
      ON T.ITM_SKU = S.ITM_SKU
      AND T.STR_ID = S.STR_ID
      AND T.LY_DT_SK_CAL = S.LY_DT_SK_CAL




    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
                                          @NBR_OF_RW_ISRT = 0,
                                          @NBR_OF_RW_UDT = 0


  END TRY

  BEGIN CATCH
    DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_PRES_SLS_TY_LY_DATA_FIX]'
    DECLARE @ERROR_LINE AS int;
    DECLARE @ERROR_MSG AS nvarchar(max);

    SELECT
      @ERROR_LINE = ERROR_NUMBER(),
      @ERROR_MSG = ERROR_MESSAGE();

    --------- Log execution error ----------
    EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                  @ERROR_LINE = @ERROR_LINE,
                                  @ERROR_MSG = @ERROR_MSG;

    -- Detect the change


    THROW;

  END CATCH
END
