CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_PRE_PROD_DATA_FIX]
AS
BEGIN

		--Get all the DT_SK and LY_DY for current YEAR
		IF OBJECT_ID('tempdb..#SLS_ITM_SKU_DATES') IS NOT NULL
		BEGIN
		  DROP TABLE #SLS_ITM_SKU_DATES
		END

		--Get all the DT_SK and LY_DT_SK
		SELECT
		  DT_SK,
		  FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
		  FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
		  FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
		  INTO #SLS_ITM_SKU_DATES
		FROM edaa_dw.dim_dly_cal d
		--WHERE FSC_YR=YEAR(GETDATE())


		UPDATE a
		SET a.LY_DT_SK_HLDY = b.LY_DT_SK_HLDY,
			a.LY_DT_SK_CAL = b.LY_DT_SK_CAL
		FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] a
		JOIN #SLS_ITM_SKU_DATES b
		  ON a.Dt_SK = b.DT_SK


		UPDATE a
		SET a.LY_DT_SK_HLDY = b.LY_DT_SK_HLDY,
			a.LY_DT_SK_CAL = b.LY_DT_SK_CAL
		FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] a
		JOIN #SLS_ITM_SKU_DATES b
		  ON a.Dt_SK = b.DT_SK

		UPDATE T
				SET T.SLS_AMT_LY_HLDY = T.SLS_AMT_LY_FSC,
					T.SLS_QTY_LY_HLDY = T.SLS_QTY_LY_FSC,
					T.SLS_WGT_LY_HLDY = T.SLS_WGT_LY_FSC,
					T.PRM_TO_SLS_AMT_LY_HLDY = T.PRM_TO_SLS_AMT_LY_FSC,
					T.PRM_TO_SLS_QTY_LY_HLDY = T.PRM_TO_SLS_QTY_LY_FSC,
					T.PRM_TO_SLS_WGT_LY_HLDY = T.PRM_TO_SLS_WGT_LY_FSC,
					T.PRM_TO_SLS_MKDN_AMT_LY_HLDY = T.PRM_TO_SLS_MKDN_AMT_LY_FSC,
					T.CLRNC_SLS_AMT_LY_HLDY = T.CLRNC_SLS_AMT_LY_FSC,
					T.CLRNC_QTY_LY_HLDY = T.CLRNC_QTY_LY_FSC,
					T.CLRNC_WGT_LY_HLDY = T.CLRNC_WGT_LY_FSC,
					T.CLRNC_MKDN_AMT_LY_HLDY = T.CLRNC_MKDN_AMT_LY_FSC,
					T.COGS_AMT_LY_HLDY = T.COGS_AMT_LY_FSC,
					T.COGS_FNC_CHRG_AMT_LY_HLDY = T.COGS_FNC_CHRG_AMT_LY_FSC,
					T.COGS_STRGE_CHRG_AMT_LY_HLDY = T.COGS_STRGE_CHRG_AMT_LY_FSC,
					T.DRCT_MGN_AMT_LY_HLDY = T.DRCT_MGN_AMT_LY_FSC,
					T.PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY = T.PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
					T.CLRNC_DRCT_MGN_AMT_LY_HLDY = T.CLRNC_DRCT_MGN_AMT_LY_FSC,
					T.COGS_FRT_AMT_LY_HLDY = T.COGS_FRT_AMT_LY_FSC,
					T.COGS_DIST_CNTR_HNDL_AMT_LY_HLDY = T.COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
					T.[COGS_FNC_CR_AMT_LY_HLDY] = T.[COGS_FNC_CR_AMT_LY_FSC]
				FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
				WHERE T.ITM_SKU=T.ITM_SKU and T.STR_ID=T.STR_ID AND T.LY_DT_SK_HLDY=T.LY_DT_SK


				UPDATE T
				SET T.SLS_AMT_LY_CAL = T.SLS_AMT_LY_FSC,
					T.SLS_QTY_LY_CAL = T.SLS_QTY_LY_FSC,
					T.SLS_WGT_LY_CAL = T.SLS_WGT_LY_FSC,
					T.PRM_TO_SLS_AMT_LY_CAL = T.PRM_TO_SLS_AMT_LY_FSC,
					T.PRM_TO_SLS_QTY_LY_CAL = T.PRM_TO_SLS_QTY_LY_FSC,
					T.PRM_TO_SLS_WGT_LY_CAL = T.PRM_TO_SLS_WGT_LY_FSC,
					T.PRM_TO_SLS_MKDN_AMT_LY_CAL = T.PRM_TO_SLS_MKDN_AMT_LY_FSC,
					T.CLRNC_SLS_AMT_LY_CAL = T.CLRNC_SLS_AMT_LY_FSC,
					T.CLRNC_QTY_LY_CAL = T.CLRNC_QTY_LY_FSC,
					T.CLRNC_WGT_LY_CAL = T.CLRNC_WGT_LY_FSC,
					T.CLRNC_MKDN_AMT_LY_CAL = T.CLRNC_MKDN_AMT_LY_FSC,
					T.COGS_AMT_LY_CAL = T.COGS_AMT_LY_FSC,
					T.COGS_FNC_CHRG_AMT_LY_CAL = T.COGS_FNC_CHRG_AMT_LY_FSC,
					T.COGS_STRGE_CHRG_AMT_LY_CAL = T.COGS_STRGE_CHRG_AMT_LY_FSC,
					T.DRCT_MGN_AMT_LY_CAL = T.DRCT_MGN_AMT_LY_FSC,
					T.PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL = T.PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
					T.CLRNC_DRCT_MGN_AMT_LY_CAL = T.CLRNC_DRCT_MGN_AMT_LY_FSC,
					T.COGS_FRT_AMT_LY_CAL = T.COGS_FRT_AMT_LY_FSC,
					T.COGS_DIST_CNTR_HNDL_AMT_LY_CAL = T.COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
					T.[COGS_FNC_CR_AMT_LY_CAL] = T.[COGS_FNC_CR_AMT_LY_FSC]
				FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
				WHERE T.ITM_SKU=T.ITM_SKU and T.STR_ID=T.STR_ID AND T.LY_DT_SK_CAL=T.LY_DT_SK


			UPDATE T
			SET T.SLS_ADJ_AMT_LY_HLDY = T.SLS_ADJ_AMT_LY_FSC,
				T.SLS_ADJ_QTY_LY_HLDY = T.SLS_ADJ_QTY_LY_FSC,
				T.SLS_ADJ_WGT_LY_HLDY = T.SLS_ADJ_WGT_LY_FSC,
				T.PRM_TO_SLS_ADJ_AMT_LY_HLDY = T.PRM_TO_SLS_ADJ_AMT_LY_FSC,
				T.PRM_TO_SLS_ADJ_QTY_LY_HLDY = T.PRM_TO_SLS_ADJ_QTY_LY_FSC,
				T.PRM_TO_SLS_ADJ_WGT_LY_HLDY = T.PRM_TO_SLS_ADJ_WGT_LY_FSC,
				T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY = T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
				T.CLRNC_SLS_ADJ_AMT_LY_HLDY = T.CLRNC_SLS_ADJ_AMT_LY_FSC,
				T.CLRNC_ADJ_QTY_LY_HLDY = T.CLRNC_ADJ_QTY_LY_FSC,
				T.CLRNC_ADJ_WGT_LY_HLDY = T.CLRNC_ADJ_WGT_LY_FSC,
				T.CLRNC_MKDN_ADJ_AMT_LY_HLDY = T.CLRNC_MKDN_ADJ_AMT_LY_FSC,
				T.COGS_ADJ_AMT_LY_HLDY = T.COGS_ADJ_AMT_LY_FSC,
				T.COGS_FNC_CHRG_ADJ_AMT_LY_HLDY = T.COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
				T.COGS_FNC_CR_ADJ_AMT_LY_HLDY = T.COGS_FNC_CR_ADJ_AMT_LY_FSC,
				T.COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY = T.COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
				T.DRCT_MGN_ADJ_AMT_LY_HLDY = T.DRCT_MGN_ADJ_AMT_LY_FSC,
				T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY = T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
				T.CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY = T.CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
				T.COGS_FRT_ADJ_AMT_LY_HLDY = T.COGS_FRT_ADJ_AMT_LY_FSC,
				T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY = T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC
			FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T
			WHERE T.LY_DT_SK = T.LY_DT_SK_HLDY AND T.STR_ID=T.STR_ID AND T.ITM_SKU=T.ITM_SKU

			UPDATE T
			SET T.SLS_ADJ_AMT_LY_CAL = T.SLS_ADJ_AMT_LY_FSC,
				T.SLS_ADJ_QTY_LY_CAL = T.SLS_ADJ_QTY_LY_FSC,
				T.SLS_ADJ_WGT_LY_CAL = T.SLS_ADJ_WGT_LY_FSC,
				T.PRM_TO_SLS_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_ADJ_AMT_LY_FSC,
				T.PRM_TO_SLS_ADJ_QTY_LY_CAL = T.PRM_TO_SLS_ADJ_QTY_LY_FSC,
				T.PRM_TO_SLS_ADJ_WGT_LY_CAL = T.PRM_TO_SLS_ADJ_WGT_LY_FSC,
				T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
				T.CLRNC_SLS_ADJ_AMT_LY_CAL = T.CLRNC_SLS_ADJ_AMT_LY_FSC,
				T.CLRNC_ADJ_QTY_LY_CAL = T.CLRNC_ADJ_QTY_LY_FSC,
				T.CLRNC_ADJ_WGT_LY_CAL = T.CLRNC_ADJ_WGT_LY_FSC,
				T.CLRNC_MKDN_ADJ_AMT_LY_CAL = T.CLRNC_MKDN_ADJ_AMT_LY_FSC,
				T.COGS_ADJ_AMT_LY_CAL = T.COGS_ADJ_AMT_LY_FSC,
				T.COGS_FNC_CHRG_ADJ_AMT_LY_CAL = T.COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
				T.COGS_FNC_CR_ADJ_AMT_LY_CAL = T.COGS_FNC_CR_ADJ_AMT_LY_FSC,
				T.COGS_STRGE_CHRG_ADJ_AMT_LY_CAL = T.COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
				T.DRCT_MGN_ADJ_AMT_LY_CAL = T.DRCT_MGN_ADJ_AMT_LY_FSC,
				T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL = T.PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
				T.CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL = T.CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
				T.COGS_FRT_ADJ_AMT_LY_CAL = T.COGS_FRT_ADJ_AMT_LY_FSC,
				T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL = T.COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC
			FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] T
			WHERE T.LY_DT_SK = T.LY_DT_SK_CAL AND T.STR_ID=T.STR_ID AND T.ITM_SKU=T.ITM_SKU

END
