CREATE PROC [EDAA_ETL].[PROC_FCT_PROMO_TB_LOAD] @ENTITY_NAME [NVARCHAR](100), @FULL_OR_INCL [NVARCHAR](2)
AS
BEGIN

  -- SET NOCOUNT ON added to prevent extra result sets from
  -- interfering with SELECT statements.
  SET NOCOUNT ON


  DECLARE @TRUNCATE_TABLE varchar(100)
  DECLARE @SQL varchar(255)

  IF UPPER(@FULL_OR_INCL) = 'F'
  BEGIN

    IF @ENTITY_NAME = 'PromotionAdvertisementBlock'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_PROMO_ADV_BLK]'
    END

    IF @ENTITY_NAME = 'PromotionAdvertisementSampleDocumentFact'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_PROMO_ADV_SMPL_DOC]'
    END

    IF @ENTITY_NAME = 'PromotionStoreProductHistory'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_PROMO_UT_P_HST]'
    END

    IF @ENTITY_NAME = 'PROMO_BLK_P_SGRP_HST'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_PROMO_BLK_P_SGRP_HST]'
    END

    IF @ENTITY_NAME = 'PromotionProductHistory'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_PROMO_PROD_HIST]'
    END

    IF @ENTITY_NAME = 'RWB_UT_P_FCST_HST'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[FCT_RWB_UT_P_FCST_HST]'
    END

    IF @ENTITY_NAME = 'PromotionVehicle'
    BEGIN
      SET @TRUNCATE_TABLE = '[EDAA_DW].[DIM_PROMO_VHL]'
    END

    --TRUNCATE TABLE
    SET @SQL = 'TRUNCATE TABLE ' + @TRUNCATE_TABLE
    EXECUTE (@SQL)


  END


  IF @ENTITY_NAME = 'PromotionAdvertisementBlock'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_PROMO_ADV_BLK_DATA_LOAD]
  END

  IF @ENTITY_NAME = 'PromotionProductHistory'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_PROMO_PROD_HIST_DATA_LOAD]
  END

  IF @ENTITY_NAME = 'PromotionAdvertisementSampleDocumentFact'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_PROMO_ADV_SMPL_DOC_LOAD]
  END

  IF @ENTITY_NAME = 'PromotionStoreProductHistory'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_PROMO_UT_P_HST_DATA_LOAD]
  END

  IF @ENTITY_NAME = 'PromotionVehicle'
  BEGIN
    EXEC [EDAA_ETL].[PROC_DIM_PROMO_VHL_DATA_LOAD]
  END

  IF @ENTITY_NAME = 'PROMO_BLK_P_SGRP_HST'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_PROMO_BLK_P_SGRP_HST_DATA_LOAD]
  END

  IF @ENTITY_NAME = 'RWB_UT_P_FCST_HST'
  BEGIN
    EXEC [EDAA_ETL].[PROC_FCT_RWB_UT_P_FCST_HST_DATA_LOAD]
  END

END
