CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_DT_SK_DELETE] @DT_SK [INT] AS
BEGIN
	--exec  [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_DT_SK_DELETE] 20221201

	BEGIN TRY

	  /*DATAMART AUDITING VARIABLES*/
	  DECLARE @NEW_AUD_SKY bigint
	  DECLARE @EXEC_LYR varchar(255)
	  DECLARE @EXEC_JOB varchar(500)
	  DECLARE @SRC_ENTY varchar(500)
	  DECLARE @TGT_ENTY varchar(500)

	  /* -------- insert into TY subset table --------  */
	  EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
											  @EXEC_JOB = 'PROC_FCT_DLY_STR_ITMSKU_SLS_DT_SK_DELETE',
											  @SRC_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_DLY',
											  @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_DLY',
											  @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

	  --DELETE UPC PRES TABLE
	  DELETE FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC]
	  WHERE DT_SK=@DT_SK
	  DELETE FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC]
	  WHERE DT_SK=@DT_SK
	  DELETE FROM  [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]
	  WHERE PRE_DEF_ID=@DT_SK



	END TRY

	BEGIN CATCH
	  DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_DT_SK_DELETE]'
	  DECLARE @ERROR_LINE AS int;
	  DECLARE @ERROR_MSG AS nvarchar(max);

	  SELECT
		@ERROR_LINE = ERROR_NUMBER(),
		@ERROR_MSG = ERROR_MESSAGE();

	  --------- Log execution error ----------
	  EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
									@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
									@ERROR_LINE = @ERROR_LINE,
									@ERROR_MSG = @ERROR_MSG;

	  -- Detect the change
	  THROW;

	END CATCH
END
