CREATE PROC [EDAA_ETL].[PROC_ANLT_SVC_EMP_UT_ROLE_INF_TABLELOAD] AS

BEGIN
--EXEC [EDAA_ETL].[PROC_ANLT_SVC_EMP_UT_ROLE_INF_TABLELOAD]
	BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'PROC_ANLT_SVC_EMP_UT_ROLE_INF_TABLELOAD'
,@SRC_ENTY  = 'ANLT_SVC_EMP_UT_ROLE_INF'
,@TGT_ENTY = 'ANLT_SVC_EMP_UT_ROLE_INF'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

--TRUNCATE STAGE TABLE
TRUNCATE TABLE EDAA_DW.ANLT_SVC_EMP_UT_ROLE_INF;

--INSERT DATA INTO DW LAYER FROM STAGE
INSERT INTO EDAA_DW.ANLT_SVC_EMP_UT_ROLE_INF
select
MJR_EMP_ID,
UT_ID,
ROLE_TYP_NM
FROM EDAA_STG.ANLT_SVC_EMP_UT_ROLE_INF;

print('---DW load complete---');


END TRY

	BEGIN CATCH
	DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[PROC_ANLT_SVC_EMP_UT_ROLE_INF_TABLELOAD]'
	DECLARE @ERROR_LINE AS INT;
	DECLARE @ERROR_MSG AS NVARCHAR(max);

	 SELECT
		  @ERROR_LINE =  ERROR_NUMBER()
		   ,@ERROR_MSG = ERROR_MESSAGE();
	--------- Log execution error ----------

	EXEC EDAA_CNTL.SP_LOG_AUD_ERR
	@AUD_SKY = @NEW_AUD_SKY,
	@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
	@ERROR_LINE = @ERROR_LINE,
	@ERROR_MSG = @ERROR_MSG;

	THROW;

	END CATCH
END
