CREATE PROC [EDAA_ETL].[PROC_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY] AS
BEGIN
  -- exec [EDAA_ETL].[PROC_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY]

  BEGIN TRY
    /*DATAMART AUDITING VARIABLES*/
    DECLARE @NEW_AUD_SKY bigint
    DECLARE @NBR_OF_RW_ISRT bigint
    DECLARE @NBR_OF_RW_UDT bigint
    DECLARE @EXEC_LYR varchar(255)
    DECLARE @EXEC_JOB varchar(500)
    DECLARE @SRC_ENTY varchar(500)
    DECLARE @TGT_ENTY varchar(500)


    /*AUDIT LOG START*/
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
                                            @EXEC_JOB = 'EDAA_ETL.PROC_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY',
                                            @SRC_ENTY = 'FCT_DSTB_CTR_INV_QTY_TY_LY_FSC',
                                            @TGT_ENTY = 'FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY',
                                            @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


    DECLARE @DATETIME DATETIME
    SET @DATETIME = (SELECT
      MAX(UPDATEDTIMESTAMP)
    FROM [EDAA_STG].[FCT_SL_WTRMARK] WHERE TABLE_NME ='FCT_DSTB_CTR_INV_QTY_TY_LY_FSC' );

	--TRUNCATE TABLE IF EXISTS
	IF CAST(@DATETIME AS DATE) = '1900-01-01'
	BEGIN
		TRUNCATE TABLE [EDAA_PRES].[FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY]
	END

	TRUNCATE TABLE EDAA_STG.TEMP_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY

    --LOAD ALL DATA  TO TEMP TABLE
    INSERT INTO EDAA_STG.TEMP_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY
	(
	  [ROW_ID_VAL]
	  ,[PRE_DEF_ID]
	  ,[DT_VAL]
      ,[STR_ID]
      ,[P_ID]
      ,[DSTB_CTR_DRC_STO_DLVY_CT]
      ,[DSTB_CTR_PLT_CT]
      ,[DSTB_CTR_FNC_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_LY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_LY_FSC]
      ,[EST_DLVY_CST_AM_TY_FSC]
      ,[EST_DLVY_CST_AM_LY_FSC]
      ,[TRNSF_QT_TY_FSC]
      ,[TRNSF_QT_LY_FSC]
      ,[WK_OUT_OF_STK_QT_TY_FSC]
      ,[WK_OUT_OF_STK_QT_LY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_TY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_LY_FSC]
      ,[WK_OVRD_SBS_QT_TY_FSC]
      ,[WK_OVRD_SBS_QT_LY_FSC]
      ,[WK_ADJ_QT_TY_FSC]
      ,[WK_ADJ_QT_LY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_TY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_LY_FSC]
      ,[WK_MVMT_CST_AM_TY_FSC]
      ,[WK_MVMT_CST_AM_LY_FSC]
      ,[WK_MVMT_RTL_AM_TY_FSC]
      ,[WK_MVMT_RTL_AM_LY_FSC]
      ,[WK_RCV_QT_TY_FSC]
      ,[WK_RCV_QT_LY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[DSTB_CTR_CST_AM_TY_FSC]
      ,[DSTB_CTR_CST_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CR_AM_LY_HLDY]
      ,[DSTB_CTR_STG_CHRG_AM_LY_HLDY]
      ,[EST_DLVY_CST_AM_LY_HLDY]
      ,[TRNSF_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_SBS_QT_LY_HLDY]
      ,[WK_OVRD_SBS_QT_LY_HLDY]
      ,[WK_ADJ_QT_LY_HLDY]
      ,[WK_DSTB_CTR_MVMT_QT_LY_HLDY]
      ,[WK_MVMT_CST_AM_LY_HLDY]
      ,[WK_MVMT_RTL_AM_LY_HLDY]
      ,[WK_RCV_QT_LY_HLDY]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[DSTB_CTR_CST_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_CAL]
      ,[DSTB_CTR_FNC_CR_AM_LY_CAL]
      ,[DSTB_CTR_STG_CHRG_AM_LY_CAL]
      ,[EST_DLVY_CST_AM_LY_CAL]
      ,[TRNSF_QT_LY_CAL]
      ,[WK_OUT_OF_STK_QT_LY_CAL]
      ,[WK_OUT_OF_STK_SBS_QT_LY_CAL]
      ,[WK_OVRD_SBS_QT_LY_CAL]
      ,[WK_ADJ_QT_LY_CAL]
      ,[WK_DSTB_CTR_MVMT_QT_LY_CAL]
      ,[WK_MVMT_CST_AM_LY_CAL]
      ,[WK_MVMT_RTL_AM_LY_CAL]
      ,[WK_RCV_QT_LY_CAL]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[DSTB_CTR_CST_AM_LY_CAL]
      ,[UPDATEDTIMESTAMP]
	  )
	  SELECT
      dtsel.ROW_ID_VAL,
      dtsel.PRE_DEF_ID,
      dtsel.DT_VAL
	  ,A.[STR_ID]
      ,A.[P_ID]
      ,A.[DSTB_CTR_DRC_STO_DLVY_CT]
      ,A.[DSTB_CTR_PLT_CT]
      ,A.[DSTB_CTR_FNC_CHRG_AM_TY_FSC]
      ,A.[DSTB_CTR_FNC_CHRG_AM_LY_FSC]
      ,A.[DSTB_CTR_FNC_CR_AM_TY_FSC]
      ,A.[DSTB_CTR_FNC_CR_AM_LY_FSC]
      ,A.[DSTB_CTR_STG_CHRG_AM_TY_FSC]
      ,A.[DSTB_CTR_STG_CHRG_AM_LY_FSC]
      ,A.[EST_DLVY_CST_AM_TY_FSC]
      ,A.[EST_DLVY_CST_AM_LY_FSC]
      ,A.[TRNSF_QT_TY_FSC]
      ,A.[TRNSF_QT_LY_FSC]
      ,A.[WK_OUT_OF_STK_QT_TY_FSC]
      ,A.[WK_OUT_OF_STK_QT_LY_FSC]
      ,A.[WK_OUT_OF_STK_SBS_QT_TY_FSC]
      ,A.[WK_OUT_OF_STK_SBS_QT_LY_FSC]
      ,A.[WK_OVRD_SBS_QT_TY_FSC]
      ,A.[WK_OVRD_SBS_QT_LY_FSC]
      ,A.[WK_ADJ_QT_TY_FSC]
      ,A.[WK_ADJ_QT_LY_FSC]
      ,A.[WK_DSTB_CTR_MVMT_QT_TY_FSC]
      ,A.[WK_DSTB_CTR_MVMT_QT_LY_FSC]
      ,A.[WK_MVMT_CST_AM_TY_FSC]
      ,A.[WK_MVMT_CST_AM_LY_FSC]
      ,A.[WK_MVMT_RTL_AM_TY_FSC]
      ,A.[WK_MVMT_RTL_AM_LY_FSC]
      ,A.[WK_RCV_QT_TY_FSC]
      ,A.[WK_RCV_QT_LY_FSC]
      ,A.[DSTB_CTR_BAL_ON_HND_QT_TY_FSC]
      ,A.[DSTB_CTR_BAL_ON_HND_QT_LY_FSC]
      ,A.[RTL_SVC_CTR_BAL_ON_HND_QT_TY_FSC]
      ,A.[RTL_SVC_CTR_BAL_ON_HND_QT_LY_FSC]
      ,A.[DSTB_CTR_CST_AM_TY_FSC]
      ,A.[DSTB_CTR_CST_AM_LY_FSC]
      ,A.[DSTB_CTR_FNC_CHRG_AM_LY_HLDY]
      ,A.[DSTB_CTR_FNC_CR_AM_LY_HLDY]
      ,A.[DSTB_CTR_STG_CHRG_AM_LY_HLDY]
      ,A.[EST_DLVY_CST_AM_LY_HLDY]
      ,A.[TRNSF_QT_LY_HLDY]
      ,A.[WK_OUT_OF_STK_QT_LY_HLDY]
      ,A.[WK_OUT_OF_STK_SBS_QT_LY_HLDY]
      ,A.[WK_OVRD_SBS_QT_LY_HLDY]
      ,A.[WK_ADJ_QT_LY_HLDY]
      ,A.[WK_DSTB_CTR_MVMT_QT_LY_HLDY]
      ,A.[WK_MVMT_CST_AM_LY_HLDY]
      ,A.[WK_MVMT_RTL_AM_LY_HLDY]
      ,A.[WK_RCV_QT_LY_HLDY]
      ,A.[DSTB_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,A.[RTL_SVC_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,A.[DSTB_CTR_CST_AM_LY_HLDY]
      ,A.[DSTB_CTR_FNC_CHRG_AM_LY_CAL]
      ,A.[DSTB_CTR_FNC_CR_AM_LY_CAL]
      ,A.[DSTB_CTR_STG_CHRG_AM_LY_CAL]
      ,A.[EST_DLVY_CST_AM_LY_CAL]
      ,A.[TRNSF_QT_LY_CAL]
      ,A.[WK_OUT_OF_STK_QT_LY_CAL]
      ,A.[WK_OUT_OF_STK_SBS_QT_LY_CAL]
      ,A.[WK_OVRD_SBS_QT_LY_CAL]
      ,A.[WK_ADJ_QT_LY_CAL]
      ,A.[WK_DSTB_CTR_MVMT_QT_LY_CAL]
      ,A.[WK_MVMT_CST_AM_LY_CAL]
      ,A.[WK_MVMT_RTL_AM_LY_CAL]
      ,A.[WK_RCV_QT_LY_CAL]
      ,A.[DSTB_CTR_BAL_ON_HND_QT_LY_CAL]
      ,A.[RTL_SVC_CTR_BAL_ON_HND_QT_LY_CAL]
      ,A.[DSTB_CTR_CST_AM_LY_CAL]
      ,A.[UPDATEDTIMESTAMP]
    FROM EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC A
	INNER JOIN
         (SELECT
           *,
		   CONVERT(date, CONVERT(varchar(10), MAX_DT, 120)) AS DT_VAL
           ,ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
         FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
         WHERE AGG_TYP = 'DLY') dtsel

    ON A.DT_SK >= dtsel.MIN_DT
    AND A.DT_SK <= dtsel.MAX_DT
    AND A.[UPDATEDTIMESTAMP] >= @DATETIME


	  --DELETE IF EXISTS IN DLY TABLE
    DELETE FROM T
      FROM EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY T
      JOIN EDAA_STG.TEMP_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY S
        ON T.PRE_DEF_ID = S.PRE_DEF_ID
        AND T.[STR_ID] = S.[STR_ID]
        AND T.[P_ID] = S.[P_ID]
		AND T.[DSTB_CTR_DRC_STO_DLVY_CT] = S.[DSTB_CTR_DRC_STO_DLVY_CT]
		--AND T.[DSTB_CTR_PLT_CT] = S.[DSTB_CTR_PLT_CT]


    --INSERT DATA IF NOT EXISTS IN PRES TABLE
    INSERT INTO EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY
	(
	  [ROW_ID_VAL]
      ,[PRE_DEF_ID]
      ,[DT_VAL]
      ,[STR_ID]
      ,[P_ID]
      ,[DSTB_CTR_DRC_STO_DLVY_CT]
      ,[DSTB_CTR_PLT_CT]
      ,[DSTB_CTR_FNC_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_LY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_LY_FSC]
      ,[EST_DLVY_CST_AM_TY_FSC]
      ,[EST_DLVY_CST_AM_LY_FSC]
      ,[TRNSF_QT_TY_FSC]
      ,[TRNSF_QT_LY_FSC]
      ,[WK_OUT_OF_STK_QT_TY_FSC]
      ,[WK_OUT_OF_STK_QT_LY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_TY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_LY_FSC]
      ,[WK_OVRD_SBS_QT_TY_FSC]
      ,[WK_OVRD_SBS_QT_LY_FSC]
      ,[WK_ADJ_QT_TY_FSC]
      ,[WK_ADJ_QT_LY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_TY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_LY_FSC]
      ,[WK_MVMT_CST_AM_TY_FSC]
      ,[WK_MVMT_CST_AM_LY_FSC]
      ,[WK_MVMT_RTL_AM_TY_FSC]
      ,[WK_MVMT_RTL_AM_LY_FSC]
      ,[WK_RCV_QT_TY_FSC]
      ,[WK_RCV_QT_LY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[DSTB_CTR_CST_AM_TY_FSC]
      ,[DSTB_CTR_CST_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CR_AM_LY_HLDY]
      ,[DSTB_CTR_STG_CHRG_AM_LY_HLDY]
      ,[EST_DLVY_CST_AM_LY_HLDY]
      ,[TRNSF_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_SBS_QT_LY_HLDY]
      ,[WK_OVRD_SBS_QT_LY_HLDY]
      ,[WK_ADJ_QT_LY_HLDY]
      ,[WK_DSTB_CTR_MVMT_QT_LY_HLDY]
      ,[WK_MVMT_CST_AM_LY_HLDY]
      ,[WK_MVMT_RTL_AM_LY_HLDY]
      ,[WK_RCV_QT_LY_HLDY]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[DSTB_CTR_CST_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_CAL]
      ,[DSTB_CTR_FNC_CR_AM_LY_CAL]
      ,[DSTB_CTR_STG_CHRG_AM_LY_CAL]
      ,[EST_DLVY_CST_AM_LY_CAL]
      ,[TRNSF_QT_LY_CAL]
      ,[WK_OUT_OF_STK_QT_LY_CAL]
      ,[WK_OUT_OF_STK_SBS_QT_LY_CAL]
      ,[WK_OVRD_SBS_QT_LY_CAL]
      ,[WK_ADJ_QT_LY_CAL]
      ,[WK_DSTB_CTR_MVMT_QT_LY_CAL]
      ,[WK_MVMT_CST_AM_LY_CAL]
      ,[WK_MVMT_RTL_AM_LY_CAL]
      ,[WK_RCV_QT_LY_CAL]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[DSTB_CTR_CST_AM_LY_CAL]
      ,[UPDATEDTIMESTAMP]
	)
    SELECT [ROW_ID_VAL]
      ,[PRE_DEF_ID]
      ,[DT_VAL]
      ,[STR_ID]
      ,[P_ID]
      ,[DSTB_CTR_DRC_STO_DLVY_CT]
      ,[DSTB_CTR_PLT_CT]
      ,[DSTB_CTR_FNC_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_TY_FSC]
      ,[DSTB_CTR_FNC_CR_AM_LY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_TY_FSC]
      ,[DSTB_CTR_STG_CHRG_AM_LY_FSC]
      ,[EST_DLVY_CST_AM_TY_FSC]
      ,[EST_DLVY_CST_AM_LY_FSC]
      ,[TRNSF_QT_TY_FSC]
      ,[TRNSF_QT_LY_FSC]
      ,[WK_OUT_OF_STK_QT_TY_FSC]
      ,[WK_OUT_OF_STK_QT_LY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_TY_FSC]
      ,[WK_OUT_OF_STK_SBS_QT_LY_FSC]
      ,[WK_OVRD_SBS_QT_TY_FSC]
      ,[WK_OVRD_SBS_QT_LY_FSC]
      ,[WK_ADJ_QT_TY_FSC]
      ,[WK_ADJ_QT_LY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_TY_FSC]
      ,[WK_DSTB_CTR_MVMT_QT_LY_FSC]
      ,[WK_MVMT_CST_AM_TY_FSC]
      ,[WK_MVMT_CST_AM_LY_FSC]
      ,[WK_MVMT_RTL_AM_TY_FSC]
      ,[WK_MVMT_RTL_AM_LY_FSC]
      ,[WK_RCV_QT_TY_FSC]
      ,[WK_RCV_QT_LY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_TY_FSC]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_FSC]
      ,[DSTB_CTR_CST_AM_TY_FSC]
      ,[DSTB_CTR_CST_AM_LY_FSC]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CR_AM_LY_HLDY]
      ,[DSTB_CTR_STG_CHRG_AM_LY_HLDY]
      ,[EST_DLVY_CST_AM_LY_HLDY]
      ,[TRNSF_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_QT_LY_HLDY]
      ,[WK_OUT_OF_STK_SBS_QT_LY_HLDY]
      ,[WK_OVRD_SBS_QT_LY_HLDY]
      ,[WK_ADJ_QT_LY_HLDY]
      ,[WK_DSTB_CTR_MVMT_QT_LY_HLDY]
      ,[WK_MVMT_CST_AM_LY_HLDY]
      ,[WK_MVMT_RTL_AM_LY_HLDY]
      ,[WK_RCV_QT_LY_HLDY]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_HLDY]
      ,[DSTB_CTR_CST_AM_LY_HLDY]
      ,[DSTB_CTR_FNC_CHRG_AM_LY_CAL]
      ,[DSTB_CTR_FNC_CR_AM_LY_CAL]
      ,[DSTB_CTR_STG_CHRG_AM_LY_CAL]
      ,[EST_DLVY_CST_AM_LY_CAL]
      ,[TRNSF_QT_LY_CAL]
      ,[WK_OUT_OF_STK_QT_LY_CAL]
      ,[WK_OUT_OF_STK_SBS_QT_LY_CAL]
      ,[WK_OVRD_SBS_QT_LY_CAL]
      ,[WK_ADJ_QT_LY_CAL]
      ,[WK_DSTB_CTR_MVMT_QT_LY_CAL]
      ,[WK_MVMT_CST_AM_LY_CAL]
      ,[WK_MVMT_RTL_AM_LY_CAL]
      ,[WK_RCV_QT_LY_CAL]
      ,[DSTB_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[RTL_SVC_CTR_BAL_ON_HND_QT_LY_CAL]
      ,[DSTB_CTR_CST_AM_LY_CAL]
      ,[UPDATEDTIMESTAMP]
	FROM EDAA_STG.TEMP_FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY A

    ---Delete more than 42 days data
    DELETE FROM EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY
    WHERE DT_VAL < GETDATE() - 43

    --UPDATE STATSTICS
    UPDATE STATISTICS EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC_DLY;

	UPDATE [EDAA_STG].[FCT_SL_WTRMARK]
			SET UPDATEDTIMESTAMP =  (SELECT MAX([UPDATEDTIMESTAMP])
										FROM  EDAA_PRES.FCT_DSTB_CTR_INV_QTY_TY_LY_FSC)
	WHERE TABLE_NME = 'FCT_DSTB_CTR_INV_QTY_TY_LY_FSC'

  END TRY

  BEGIN CATCH
    DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = 'EDAA_ETL.PROC_FCT_DLY_STR_ITMSKU_INV_TY_LY_FSC_DLY'
    DECLARE @ERROR_LINE AS int;
    DECLARE @ERROR_MSG AS nvarchar(max);

    SELECT
      @ERROR_LINE = ERROR_NUMBER(),
      @ERROR_MSG = ERROR_MESSAGE();
    --------- Log execution error ----------



    EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                  @ERROR_LINE = @ERROR_LINE,
                                  @ERROR_MSG = @ERROR_MSG;

    -- DETECT THE CHANGE

    THROW;


  END CATCH
END
