CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_DM_TO_PRES_LOAD]
AS
BEGIN
  BEGIN TRY

    /*DATAMART AUDITING VARIABLES*/
    DECLARE @NEW_AUD_SKY bigint
    DECLARE @NBR_OF_RW_ISRT int
    DECLARE @NBR_OF_RW_UDT int
    DECLARE @EXEC_LYR varchar(255)
    DECLARE @EXEC_JOB varchar(500)
    DECLARE @SRC_ENTY varchar(500)
    DECLARE @TGT_ENTY varchar(500)
    DECLARE @GETDATETIME datetime = GETDATE()

    /* -------- insert into TY subset table --------  */
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW',
                                            @EXEC_JOB = 'PROC_FCT_DLY_STR_ITMSKU_SLS_DM_TO_PRES_LOAD',
                                            @SRC_ENTY = 'FCT_DLY_STR_ITMSKU_SLS',
                                            @TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC',
                                            @NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT



    --TURNCATE PRES AND STAGE TABLES
    TRUNCATE TABLE [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC];
    TRUNCATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC];

    WITH TY_DATA_LOAD
	AS
	(
    SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      [SLS_AMT],
      [SLS_QTY],
      [SLS_WGT],
      [PRM_TO_SLS_AMT],
      [PRM_TO_SLS_QTY],
      [PRM_TO_SLS_WGT],
      [PRM_TO_SLS_MKDN_AMT],
      [CLRNC_SLS_AMT],
      [CLRNC_QTY],
      [CLRNC_WGT],
      [CLRNC_MKDN_AMT],
      [COGS_AMT],
      [COGS_FNC_CHRG_AMT],
      [COGS_FNC_CR_AMT],
      [COGS_STRGE_CHRG_AMT],
      [DRCT_MGN_AMT],
      [PRM_TO_SLS_DRCT_MGN_AMT],
      [CLRNC_DRCT_MGN_AMT],
      [COGS_FRT_AMT],
      [COGS_DIST_CNTR_HNDL_AMT]

    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
    INNER JOIN (SELECT
      DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal d
    WHERE FSC_YR = YEAR(GETDATE())
    AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')) b
      ON a.DT_SK = b.DT_SK
	)


    INSERT INTO [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] ([DT_SK]
    , [LY_DT_SK]
    , [LY_DT_SK_HLDY]
    , [LY_DT_SK_CAL]
    , [ITM_SKU]
    , [STR_ID]
    , [SLS_AMT_TY_FSC]
    , [SLS_AMT_LY_FSC]
    , [SLS_QTY_TY_FSC]
    , [SLS_QTY_LY_FSC]
    , [SLS_WGT_TY_FSC]
    , [SLS_WGT_LY_FSC]
    , [PRM_TO_SLS_AMT_TY_FSC]
    , [PRM_TO_SLS_AMT_LY_FSC]
    , [PRM_TO_SLS_QTY_TY_FSC]
    , [PRM_TO_SLS_QTY_LY_FSC]
    , [PRM_TO_SLS_WGT_TY_FSC]
    , [PRM_TO_SLS_WGT_LY_FSC]
    , [PRM_TO_SLS_MKDN_AMT_TY_FSC]
    , [PRM_TO_SLS_MKDN_AMT_LY_FSC]
    , [CLRNC_SLS_AMT_TY_FSC]
    , [CLRNC_SLS_AMT_LY_FSC]
    , [CLRNC_QTY_TY_FSC]
    , [CLRNC_QTY_LY_FSC]
    , [CLRNC_WGT_TY_FSC]
    , [CLRNC_WGT_LY_FSC]
    , [CLRNC_MKDN_AMT_TY_FSC]
    , [CLRNC_MKDN_AMT_LY_FSC]
    , [COGS_AMT_TY_FSC]
    , [COGS_AMT_LY_FSC]
    , [COGS_FNC_CHRG_AMT_TY_FSC]
    , [COGS_FNC_CHRG_AMT_LY_FSC]
    , [COGS_FNC_CR_AMT_TY_FSC]
    , [COGS_FNC_CR_AMT_LY_FSC]
    , [COGS_STRGE_CHRG_AMT_TY_FSC]
    , [COGS_STRGE_CHRG_AMT_LY_FSC]
    , [DRCT_MGN_AMT_TY_FSC]
    , [DRCT_MGN_AMT_LY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC]
    , [CLRNC_DRCT_MGN_AMT_TY_FSC]
    , [CLRNC_DRCT_MGN_AMT_LY_FSC]
    , [COGS_FRT_AMT_TY_FSC]
    , [COGS_FRT_AMT_LY_FSC]
    , [COGS_DIST_CNTR_HNDL_AMT_TY_FSC]
    , [COGS_DIST_CNTR_HNDL_AMT_LY_FSC]
    , [UPDATEDTIMESTAMP])
      SELECT
        DT_SK,
        LY_DT_SK,
        LY_DT_SK_HLDY,
        LY_DT_SK_CAL,
        ITM_SKU,
        STR_ID,
        SLS_AMT,
        0,
        SLS_QTY,
        0,
        SLS_WGT,
        0,
        PRM_TO_SLS_AMT,
        0,
        PRM_TO_SLS_QTY,
        0,
        PRM_TO_SLS_WGT,
        0,
        PRM_TO_SLS_MKDN_AMT,
        0,
        CLRNC_SLS_AMT,
        0,
        CLRNC_QTY,
        0,
        CLRNC_WGT,
        0,
        CLRNC_MKDN_AMT,
        0,
        COGS_AMT,
        0,
        COGS_FNC_CHRG_AMT,
        0,
        COGS_FNC_CR_AMT,
        0,
        COGS_STRGE_CHRG_AMT,
        0,
        DRCT_MGN_AMT,
        0,
        PRM_TO_SLS_DRCT_MGN_AMT,
        0,
        CLRNC_DRCT_MGN_AMT,
        0,
        COGS_FRT_AMT,
        0,
        COGS_DIST_CNTR_HNDL_AMT,
        0,
        @GETDATETIME
      FROM TY_DATA_LOAD
      WHERE SLS_AMT <> 0
      OR SLS_QTY <> 0
      OR SLS_WGT <> 0
      OR PRM_TO_SLS_AMT <> 0
      OR PRM_TO_SLS_QTY <> 0
      OR PRM_TO_SLS_WGT <> 0
      OR PRM_TO_SLS_MKDN_AMT <> 0
      OR CLRNC_SLS_AMT <> 0
      OR CLRNC_QTY <> 0
      OR CLRNC_WGT <> 0
      OR CLRNC_MKDN_AMT <> 0
      OR COGS_AMT <> 0
      OR COGS_FNC_CHRG_AMT <> 0
      OR COGS_FNC_CR_AMT <> 0
      OR COGS_STRGE_CHRG_AMT <> 0
      OR DRCT_MGN_AMT <> 0
      OR PRM_TO_SLS_DRCT_MGN_AMT <> 0
      OR CLRNC_DRCT_MGN_AMT <> 0
      OR COGS_FRT_AMT <> 0
      OR COGS_DIST_CNTR_HNDL_AMT <> 0;


    -- END OF TY DATA POPULATION--
    ;
    WITH LY_DATA_LOAD
    AS (
	SELECT
      CAST(b.DT_SK AS int) AS DT_SK,
      CAST(b.LY_DT_SK AS int) AS LY_DT_SK,
      CAST(b.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
      CAST(b.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
      A.[ITM_SKU] AS ITM_SKU,
      A.[STR_ID] AS STR_ID,
      [SLS_AMT],
      [SLS_QTY],
      [SLS_WGT],
      [PRM_TO_SLS_AMT],
      [PRM_TO_SLS_QTY],
      [PRM_TO_SLS_WGT],
      [PRM_TO_SLS_MKDN_AMT],
      [CLRNC_SLS_AMT],
      [CLRNC_QTY],
      [CLRNC_WGT],
      [CLRNC_MKDN_AMT],
      [COGS_AMT],
      [COGS_FNC_CHRG_AMT],
      [COGS_FNC_CR_AMT],
      [COGS_STRGE_CHRG_AMT],
      [DRCT_MGN_AMT],
      [PRM_TO_SLS_DRCT_MGN_AMT],
      [CLRNC_DRCT_MGN_AMT],
      [COGS_FRT_AMT],
      [COGS_DIST_CNTR_HNDL_AMT]

    FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] AS a
    INNER JOIN (SELECT
      DT_SK,
      FORMAT(Lst_Yr_Fsc_Dt, 'yyyyMMdd') AS LY_DT_SK,
      FORMAT(Lst_Yr_Hldy_Dt, 'yyyyMMdd') AS LY_DT_SK_HLDY,
      FORMAT(Lst_Yr_Cal_Dt, 'yyyyMMdd') AS LY_DT_SK_CAL
    FROM edaa_dw.dim_dly_cal d
    WHERE FSC_YR = YEAR(GETDATE())
    AND DT_SK < FORMAT(GETDATE(), 'yyyyMMdd')) b
      ON a.DT_SK = b.LY_DT_SK)

    INSERT INTO [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] ([DT_SK]
    , [LY_DT_SK]
    , [LY_DT_SK_HLDY]
    , [LY_DT_SK_CAL]
    , [ITM_SKU]
    , [STR_ID]
    , [SLS_AMT_TY_FSC]
    , [SLS_AMT_LY_FSC]
    , [SLS_QTY_TY_FSC]
    , [SLS_QTY_LY_FSC]
    , [SLS_WGT_TY_FSC]
    , [SLS_WGT_LY_FSC]
    , [PRM_TO_SLS_AMT_TY_FSC]
    , [PRM_TO_SLS_AMT_LY_FSC]
    , [PRM_TO_SLS_QTY_TY_FSC]
    , [PRM_TO_SLS_QTY_LY_FSC]
    , [PRM_TO_SLS_WGT_TY_FSC]
    , [PRM_TO_SLS_WGT_LY_FSC]
    , [PRM_TO_SLS_MKDN_AMT_TY_FSC]
    , [PRM_TO_SLS_MKDN_AMT_LY_FSC]
    , [CLRNC_SLS_AMT_TY_FSC]
    , [CLRNC_SLS_AMT_LY_FSC]
    , [CLRNC_QTY_TY_FSC]
    , [CLRNC_QTY_LY_FSC]
    , [CLRNC_WGT_TY_FSC]
    , [CLRNC_WGT_LY_FSC]
    , [CLRNC_MKDN_AMT_TY_FSC]
    , [CLRNC_MKDN_AMT_LY_FSC]
    , [COGS_AMT_TY_FSC]
    , [COGS_AMT_LY_FSC]
    , [COGS_FNC_CHRG_AMT_TY_FSC]
    , [COGS_FNC_CHRG_AMT_LY_FSC]
    , [COGS_FNC_CR_AMT_TY_FSC]
    , [COGS_FNC_CR_AMT_LY_FSC]
    , [COGS_STRGE_CHRG_AMT_TY_FSC]
    , [COGS_STRGE_CHRG_AMT_LY_FSC]
    , [DRCT_MGN_AMT_TY_FSC]
    , [DRCT_MGN_AMT_LY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC]
    , [PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC]
    , [CLRNC_DRCT_MGN_AMT_TY_FSC]
    , [CLRNC_DRCT_MGN_AMT_LY_FSC]
    , [COGS_FRT_AMT_TY_FSC]
    , [COGS_FRT_AMT_LY_FSC]
    , [COGS_DIST_CNTR_HNDL_AMT_TY_FSC]
    , [COGS_DIST_CNTR_HNDL_AMT_LY_FSC]
    , [UPDATEDTIMESTAMP])
      SELECT
        DT_SK,
        LY_DT_SK,
        LY_DT_SK_HLDY,
        LY_DT_SK_CAL,
        ITM_SKU,
        STR_ID,
        0,
        SLS_AMT,
        0,
        SLS_QTY,
        0,
        SLS_WGT,
        0,
        PRM_TO_SLS_AMT,
        0,
        PRM_TO_SLS_QTY,
        0,
        PRM_TO_SLS_WGT,
        0,
        PRM_TO_SLS_MKDN_AMT,
        0,
        CLRNC_SLS_AMT,
        0,
        CLRNC_QTY,
        0,
        CLRNC_WGT,
        0,
        CLRNC_MKDN_AMT,
        0,
        COGS_AMT,
        0,
        COGS_FNC_CHRG_AMT,
        0,
        COGS_FNC_CR_AMT,
        0,
        COGS_STRGE_CHRG_AMT,
        0,
        DRCT_MGN_AMT,
        0,
        PRM_TO_SLS_DRCT_MGN_AMT,
        0,
        CLRNC_DRCT_MGN_AMT,
        0,
        COGS_FRT_AMT,
        0,
        COGS_DIST_CNTR_HNDL_AMT,
        @GETDATETIME
      FROM LY_DATA_LOAD
      WHERE SLS_AMT <> 0
      OR SLS_QTY <> 0
      OR SLS_WGT <> 0
      OR PRM_TO_SLS_AMT <> 0
      OR PRM_TO_SLS_QTY <> 0
      OR PRM_TO_SLS_WGT <> 0
      OR PRM_TO_SLS_MKDN_AMT <> 0
      OR CLRNC_SLS_AMT <> 0
      OR CLRNC_QTY <> 0
      OR CLRNC_WGT <> 0
      OR CLRNC_MKDN_AMT <> 0
      OR COGS_AMT <> 0
      OR COGS_FNC_CHRG_AMT <> 0
      OR COGS_FNC_CR_AMT <> 0
      OR COGS_STRGE_CHRG_AMT <> 0
      OR DRCT_MGN_AMT <> 0
      OR PRM_TO_SLS_DRCT_MGN_AMT <> 0
      OR CLRNC_DRCT_MGN_AMT <> 0
      OR COGS_FRT_AMT <> 0
      OR COGS_DIST_CNTR_HNDL_AMT <> 0;

    -- SUM TY & LY in Single Row
    INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] (DT_SK,
    LY_DT_SK,
    LY_DT_SK_HLDY,
    LY_DT_SK_CAL,
    ITM_SKU,
    STR_ID,
    SLS_AMT_TY_FSC,
    SLS_AMT_LY_FSC,
    SLS_QTY_TY_FSC,
    SLS_QTY_LY_FSC,
    SLS_WGT_TY_FSC,
    SLS_WGT_LY_FSC,
    PRM_TO_SLS_AMT_TY_FSC,
    PRM_TO_SLS_AMT_LY_FSC,
    PRM_TO_SLS_QTY_TY_FSC,
    PRM_TO_SLS_QTY_LY_FSC,
    PRM_TO_SLS_WGT_TY_FSC,
    PRM_TO_SLS_WGT_LY_FSC,
    PRM_TO_SLS_MKDN_AMT_TY_FSC,
    PRM_TO_SLS_MKDN_AMT_LY_FSC,
    CLRNC_SLS_AMT_TY_FSC,
    CLRNC_SLS_AMT_LY_FSC,
    CLRNC_QTY_TY_FSC,
    CLRNC_QTY_LY_FSC,
    CLRNC_WGT_TY_FSC,
    CLRNC_WGT_LY_FSC,
    CLRNC_MKDN_AMT_TY_FSC,
    CLRNC_MKDN_AMT_LY_FSC,
    COGS_AMT_TY_FSC,
    COGS_AMT_LY_FSC,
    COGS_FNC_CHRG_AMT_TY_FSC,
    COGS_FNC_CHRG_AMT_LY_FSC,
    COGS_FNC_CR_AMT_TY_FSC,
    COGS_FNC_CR_AMT_LY_FSC,
    COGS_STRGE_CHRG_AMT_TY_FSC,
    COGS_STRGE_CHRG_AMT_LY_FSC,
    DRCT_MGN_AMT_TY_FSC,
    DRCT_MGN_AMT_LY_FSC,
    PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC,
    PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
    CLRNC_DRCT_MGN_AMT_TY_FSC,
    CLRNC_DRCT_MGN_AMT_LY_FSC,
    COGS_FRT_AMT_TY_FSC,
    COGS_FRT_AMT_LY_FSC,
    COGS_DIST_CNTR_HNDL_AMT_TY_FSC,
    COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
    LOADKEY,
    UPDATEDTIMESTAMP)
      SELECT
        CAST(x.DT_SK AS int) AS DT_SK,
        CAST(x.LY_DT_SK AS int) AS LY_DT_SK,
        CAST(x.LY_DT_SK_HLDY AS int) AS LY_DT_SK_HLDY,
        CAST(x.LY_DT_SK_CAL AS int) AS LY_DT_SK_CAL,
        x.ITM_SKU,
        x.STR_ID,
        SUM(x.SLS_AMT_TY_FSC) AS SLS_AMT_TY_FSC,
        SUM(x.SLS_AMT_LY_FSC) AS SLS_AMT_LY_FSC,
        SUM(x.SLS_QTY_TY_FSC) AS SLS_QTY_TY_FSC,
        SUM(x.SLS_QTY_LY_FSC) AS SLS_QTY_LY_FSC,
        SUM(x.SLS_WGT_TY_FSC) AS SLS_WGT_TY_FSC,
        SUM(x.SLS_WGT_LY_FSC) AS SLS_WGT_LY_FSC,
        SUM(x.PRM_TO_SLS_AMT_TY_FSC) AS PRM_TO_SLS_AMT_TY_FSC,
        SUM(x.PRM_TO_SLS_AMT_LY_FSC) AS PRM_TO_SLS_AMT_LY_FSC,
        SUM(x.PRM_TO_SLS_QTY_TY_FSC) AS PRM_TO_SLS_QTY_TY_FSC,
        SUM(x.PRM_TO_SLS_QTY_LY_FSC) AS PRM_TO_SLS_QTY_LY_FSC,
        SUM(x.PRM_TO_SLS_WGT_TY_FSC) AS PRM_TO_SLS_WGT_TY_FSC,
        SUM(x.PRM_TO_SLS_WGT_LY_FSC) AS PRM_TO_SLS_WGT_LY_FSC,
        SUM(x.PRM_TO_SLS_MKDN_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_AMT_TY_FSC,
        SUM(x.PRM_TO_SLS_MKDN_AMT_LY_FSC) AS PRM_TO_SLS_MKDN_AMT_LY_FSC,
        SUM(x.CLRNC_SLS_AMT_TY_FSC) AS CLRNC_SLS_AMT_TY_FSC,
        SUM(x.CLRNC_SLS_AMT_LY_FSC) AS CLRNC_SLS_AMT_LY_FSC,
        SUM(x.CLRNC_QTY_TY_FSC) AS CLRNC_QTY_TY_FSC,
        SUM(x.CLRNC_QTY_LY_FSC) AS CLRNC_QTY_LY_FSC,
        SUM(x.CLRNC_WGT_TY_FSC) AS CLRNC_WGT_TY_FSC,
        SUM(x.CLRNC_WGT_LY_FSC) AS CLRNC_WGT_LY_FSC,
        SUM(x.CLRNC_MKDN_AMT_TY_FSC) AS CLRNC_MKDN_AMT_TY_FSC,
        SUM(x.CLRNC_MKDN_AMT_LY_FSC) AS CLRNC_MKDN_AMT_LY_FSC,
        SUM(x.COGS_AMT_TY_FSC) AS COGS_AMT_TY_FSC,
        SUM(x.COGS_AMT_LY_FSC) AS COGS_AMT_LY_FSC,
        SUM(x.COGS_FNC_CHRG_AMT_TY_FSC) AS COGS_FNC_CHRG_AMT_TY_FSC,
        SUM(x.COGS_FNC_CHRG_AMT_LY_FSC) AS COGS_FNC_CHRG_AMT_LY_FSC,
        SUM(x.COGS_FNC_CR_AMT_TY_FSC) AS COGS_FNC_CR_AMT_TY_FSC,
        SUM(x.COGS_FNC_CR_AMT_LY_FSC) AS COGS_FNC_CR_AMT_LY_FSC,
        SUM(x.COGS_STRGE_CHRG_AMT_TY_FSC) AS COGS_STRGE_CHRG_AMT_TY_FSC,
        SUM(x.COGS_STRGE_CHRG_AMT_LY_FSC) AS COGS_STRGE_CHRG_AMT_LY_FSC,
        SUM(x.DRCT_MGN_AMT_TY_FSC) AS DRCT_MGN_AMT_TY_FSC,
        SUM(x.DRCT_MGN_AMT_LY_FSC) AS DRCT_MGN_AMT_LY_FSC,
        SUM(x.PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC,
        SUM(x.PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
        SUM(x.CLRNC_DRCT_MGN_AMT_TY_FSC) AS CLRNC_DRCT_MGN_AMT_TY_FSC,
        SUM(x.CLRNC_DRCT_MGN_AMT_LY_FSC) AS CLRNC_DRCT_MGN_AMT_LY_FSC,
        SUM(x.COGS_FRT_AMT_TY_FSC) AS COGS_FRT_AMT_TY_FSC,
        SUM(x.COGS_FRT_AMT_LY_FSC) AS COGS_FRT_AMT_LY_FSC,
        SUM(x.COGS_DIST_CNTR_HNDL_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_TY_FSC,
        SUM(x.COGS_DIST_CNTR_HNDL_AMT_LY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
        @NEW_AUD_SKY,
        @GETDATETIME
      FROM [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] x
      --WHERE x.STR_ID=19
      GROUP BY CAST(x.DT_SK AS int),
               CAST(x.LY_DT_SK AS int),
               CAST(x.LY_DT_SK_HLDY AS int),
               CAST(x.LY_DT_SK_CAL AS int),
               x.ITM_SKU,
               x.STR_ID

    UPDATE T
    SET T.SLS_AMT_LY_HLDY = T.SLS_AMT_LY_FSC,
        T.SLS_QTY_LY_HLDY = T.SLS_QTY_LY_FSC,
        T.SLS_WGT_LY_HLDY = T.SLS_WGT_LY_FSC,
        T.PRM_TO_SLS_AMT_LY_HLDY = T.PRM_TO_SLS_AMT_LY_FSC,
        T.PRM_TO_SLS_QTY_LY_HLDY = T.PRM_TO_SLS_QTY_LY_FSC,
        T.PRM_TO_SLS_WGT_LY_HLDY = T.PRM_TO_SLS_WGT_LY_FSC,
        T.PRM_TO_SLS_MKDN_AMT_LY_HLDY = T.PRM_TO_SLS_MKDN_AMT_LY_FSC,
        T.CLRNC_SLS_AMT_LY_HLDY = T.CLRNC_SLS_AMT_LY_FSC,
        T.CLRNC_QTY_LY_HLDY = T.CLRNC_QTY_LY_FSC,
        T.CLRNC_WGT_LY_HLDY = T.CLRNC_WGT_LY_FSC,
        T.CLRNC_MKDN_AMT_LY_HLDY = T.CLRNC_MKDN_AMT_LY_FSC,
        T.COGS_AMT_LY_HLDY = T.COGS_AMT_LY_FSC,
        T.COGS_FNC_CHRG_AMT_LY_HLDY = T.COGS_FNC_CHRG_AMT_LY_FSC,
        T.COGS_STRGE_CHRG_AMT_LY_HLDY = T.COGS_STRGE_CHRG_AMT_LY_FSC,
        T.DRCT_MGN_AMT_LY_HLDY = T.DRCT_MGN_AMT_LY_FSC,
        T.PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY = T.PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
        T.CLRNC_DRCT_MGN_AMT_LY_HLDY = T.CLRNC_DRCT_MGN_AMT_LY_FSC,
        T.COGS_FRT_AMT_LY_HLDY = T.COGS_FRT_AMT_LY_FSC,
        T.COGS_DIST_CNTR_HNDL_AMT_LY_HLDY = T.COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
        T.[COGS_FNC_CR_AMT_LY_HLDY] = T.[COGS_FNC_CR_AMT_LY_FSC]
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
    WHERE T.ITM_SKU = T.ITM_SKU
    AND T.STR_ID = T.STR_ID
    AND T.LY_DT_SK_HLDY = T.LY_DT_SK


    UPDATE T
    SET T.SLS_AMT_LY_CAL = T.SLS_AMT_LY_FSC,
        T.SLS_QTY_LY_CAL = T.SLS_QTY_LY_FSC,
        T.SLS_WGT_LY_CAL = T.SLS_WGT_LY_FSC,
        T.PRM_TO_SLS_AMT_LY_CAL = T.PRM_TO_SLS_AMT_LY_FSC,
        T.PRM_TO_SLS_QTY_LY_CAL = T.PRM_TO_SLS_QTY_LY_FSC,
        T.PRM_TO_SLS_WGT_LY_CAL = T.PRM_TO_SLS_WGT_LY_FSC,
        T.PRM_TO_SLS_MKDN_AMT_LY_CAL = T.PRM_TO_SLS_MKDN_AMT_LY_FSC,
        T.CLRNC_SLS_AMT_LY_CAL = T.CLRNC_SLS_AMT_LY_FSC,
        T.CLRNC_QTY_LY_CAL = T.CLRNC_QTY_LY_FSC,
        T.CLRNC_WGT_LY_CAL = T.CLRNC_WGT_LY_FSC,
        T.CLRNC_MKDN_AMT_LY_CAL = T.CLRNC_MKDN_AMT_LY_FSC,
        T.COGS_AMT_LY_CAL = T.COGS_AMT_LY_FSC,
        T.COGS_FNC_CHRG_AMT_LY_CAL = T.COGS_FNC_CHRG_AMT_LY_FSC,
        T.COGS_STRGE_CHRG_AMT_LY_CAL = T.COGS_STRGE_CHRG_AMT_LY_FSC,
        T.DRCT_MGN_AMT_LY_CAL = T.DRCT_MGN_AMT_LY_FSC,
        T.PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL = T.PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
        T.CLRNC_DRCT_MGN_AMT_LY_CAL = T.CLRNC_DRCT_MGN_AMT_LY_FSC,
        T.COGS_FRT_AMT_LY_CAL = T.COGS_FRT_AMT_LY_FSC,
        T.COGS_DIST_CNTR_HNDL_AMT_LY_CAL = T.COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
        T.[COGS_FNC_CR_AMT_LY_CAL] = T.[COGS_FNC_CR_AMT_LY_FSC]
    FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] T
    WHERE T.ITM_SKU = T.ITM_SKU
    AND T.STR_ID = T.STR_ID
    AND T.LY_DT_SK_CAL = T.LY_DT_SK


    --TRUNCATE STAGE TABLE
    TRUNCATE TABLE [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC];
    --UPDATE STATISTICS
    UPDATE STATISTICS [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC];
    --EXEC SP_AUDIT_DATA_LOAD_END
    EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
                                          @NBR_OF_RW_ISRT = 0,
                                          @NBR_OF_RW_UDT = 0


  END TRY

  BEGIN CATCH
    DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_SLS_DM_TO_PRES_LOAD]'
    DECLARE @ERROR_LINE AS int;
    DECLARE @ERROR_MSG AS nvarchar(max);

    SELECT
      @ERROR_LINE = ERROR_NUMBER(),
      @ERROR_MSG = ERROR_MESSAGE();

    --------- Log execution error ----------
    EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
                                  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
                                  @ERROR_LINE = @ERROR_LINE,
                                  @ERROR_MSG = @ERROR_MSG;

    -- Detect the change


    THROW;

  END CATCH
END
