CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_AGG_LOAD] AS
BEGIN
--exec [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_AGG_LOAD]
BEGIN TRY

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY bigint
DECLARE @NBR_OF_RW_ISRT bigint
DECLARE @NBR_OF_RW_UDT bigint
DECLARE @EXEC_LYR varchar(255)
DECLARE @EXEC_JOB varchar(500)
DECLARE @SRC_ENTY varchar(500)
DECLARE @TGT_ENTY varchar(500)
DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_AGG_LOAD'
DECLARE @ERROR_LINE AS int
DECLARE @ERROR_MSG AS nvarchar(max)

/*Audit Log Start*/

EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_PRES',
@EXEC_JOB = 'PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_LOAD',
@SRC_ENTY = 'FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC',
@TGT_ENTY = 'FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_AGG',
@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;

--TRUNCATE TABLE
TRUNCATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_AGG]

;WITH CTE
AS(SELECT
dtsel.ROW_ID_VAL,
dtsel.PRE_DEF_ID,
CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)) AS DT_VAL,
A.[ITM_SKU],
A.[STR_ID],
A.[INV_ADJ_SK],
SUM(A.[INV_ADJSTD_AMT_TY_FSC])  as [INV_ADJSTD_AMT_TY_FSC],
SUM(A.[INV_ADJSTD_QTY_TY_FSC])  as [INV_ADJSTD_QTY_TY_FSC],
SUM(A.[INV_ADJSTD_AMT_LY_FSC])  as [INV_ADJSTD_AMT_LY_FSC],
SUM(A.[INV_ADJSTD_QTY_LY_FSC])  as [INV_ADJSTD_QTY_LY_FSC],
SUM(A.[INV_ADJSTD_AMT_LY_HLDY]) as [INV_ADJSTD_AMT_LY_HLDY],
SUM(A.[INV_ADJSTD_QTY_LY_HLDY]) as [INV_ADJSTD_QTY_LY_HLDY],
SUM(A.[INV_ADJSTD_AMT_LY_CAL])  as [INV_ADJSTD_AMT_LY_CAL],
SUM(A.[INV_ADJSTD_QTY_LY_CAL])  as [INV_ADJSTD_QTY_LY_CAL]

FROM EDAA_PRES.FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC A,
(SELECT
*,
ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
WHERE AGG_TYP = 'AGG') dtsel
WHERE A.DT_SK >= dtsel.MIN_DT
AND A.DT_SK <= dtsel.MAX_DT
GROUP BY
dtsel.ROW_ID_VAL,
dtsel.PRE_DEF_ID,
CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)),
A.[ITM_SKU],
A.[STR_ID],
A.[INV_ADJ_SK]
)

INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_AGG]
([ROW_ID_VAL],
[PRE_DEF_ID],
[DT_VAL],
[ITM_SKU],
[STR_ID],
[INV_ADJ_SK],
[INV_ADJSTD_AMT_TY_FSC],
[INV_ADJSTD_QTY_TY_FSC],
[INV_ADJSTD_AMT_LY_FSC],
[INV_ADJSTD_QTY_LY_FSC],
[INV_ADJSTD_AMT_LY_HLDY],
[INV_ADJSTD_QTY_LY_HLDY],
[INV_ADJSTD_AMT_LY_CAL],
[INV_ADJSTD_QTY_LY_CAL],
[UPDATEDTIMESTAMP]
)
SELECT
[ROW_ID_VAL]
,[PRE_DEF_ID]
,[DT_VAL]
,[ITM_SKU]
,[STR_ID]
,[INV_ADJ_SK]
,[INV_ADJSTD_AMT_TY_FSC]
,[INV_ADJSTD_QTY_TY_FSC]
,[INV_ADJSTD_AMT_LY_FSC]
,[INV_ADJSTD_QTY_LY_FSC]
,[INV_ADJSTD_AMT_LY_HLDY]
,[INV_ADJSTD_QTY_LY_HLDY]
,[INV_ADJSTD_AMT_LY_CAL]
,[INV_ADJSTD_QTY_LY_CAL]
,GETDATE() as [UPDATEDTIMESTAMP]
FROM CTE

--UPDATE STATISTICS
UPDATE STATISTICS [EDAA_PRES].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_AGG];
END TRY
BEGIN CATCH
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
@NBR_OF_RW_ISRT = 0,
@NBR_OF_RW_UDT = 0
SET @ERROR_PROCEDURE_NAME = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_INV_ADJ_AGG_LOAD'

--SET @ERROR_LINE
--SET @ERROR_MSG
SELECT
@ERROR_LINE = ERROR_NUMBER(),
@ERROR_MSG = ERROR_MESSAGE();

--------- Log execution error ----------
EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;
THROW;
END CATCH
END
