CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD] @SRC_NAME [NVARCHAR](100) AS
  IF @SRC_NAME = 'UT_UPC_DLY_SL_ADJ_HST' OR @SRC_NAME = 'UT_UPC_DLY_SL_HST'
  BEGIN
      --exec [EDAA_ETL].[PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD]  'UT_UPC_DLY_SL_HST'
	  BEGIN TRY

		/*Datamart Auditing variables*/
		DECLARE @NEW_AUD_SKY bigint
		DECLARE @NBR_OF_RW_ISRT int
		DECLARE @NBR_OF_RW_UDT int
		DECLARE @EXEC_LYR varchar(255)
		DECLARE @EXEC_JOB varchar(500)
		DECLARE @SRC_ENTY varchar(500)
		DECLARE @TGT_ENTY varchar(500)
		DECLARE @ERROR_PROCEDURE_NAME AS varchar(60) = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD'
		DECLARE @ERROR_LINE AS int
		DECLARE @ERROR_MSG AS nvarchar(max)

		/*Audit Log Start*/
		EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_PRES',
												@EXEC_JOB = 'PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD',
												@SRC_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC',
												@TGT_ENTY = 'FCT_DLY_STR_ITMSKU_SLS_AGG',
												@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;

		--TRUNCATE TABLE
		TRUNCATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_AGG]

		;WITH COMBINED_TABLES
		AS (
		SELECT
		  dtsel.ROW_ID_VAL,
		  dtsel.PRE_DEF_ID,
		  CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)) AS DT_VAL,
		  ITM_SKU,
		  STR_ID,
		  SUM(SLS_AMT_TY_FSC) AS SLS_AMT_TY_FSC,
		  SUM(SLS_AMT_LY_FSC) AS SLS_AMT_LY_FSC,
		  SUM(SLS_AMT_LY_HLDY) AS SLS_AMT_LY_HLDY,
		  SUM(SLS_AMT_LY_CAL) AS SLS_AMT_LY_CAL,
		  SUM(SLS_QTY_TY_FSC) AS SLS_QTY_TY_FSC,
		  SUM(SLS_QTY_LY_FSC) AS SLS_QTY_LY_FSC,
		  SUM(SLS_QTY_LY_HLDY) AS SLS_QTY_LY_HLDY,
		  SUM(SLS_QTY_LY_CAL) AS SLS_QTY_LY_CAL,
		  SUM(SLS_WGT_TY_FSC) AS SLS_WGT_TY_FSC,
		  SUM(SLS_WGT_LY_FSC) AS SLS_WGT_LY_FSC,
		  SUM(SLS_WGT_LY_HLDY) AS SLS_WGT_LY_HLDY,
		  SUM(SLS_WGT_LY_CAL) AS SLS_WGT_LY_CAL,
		  SUM(PRM_TO_SLS_AMT_TY_FSC) AS PRM_TO_SLS_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_AMT_LY_FSC) AS PRM_TO_SLS_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_AMT_LY_HLDY) AS PRM_TO_SLS_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_AMT_LY_CAL) AS PRM_TO_SLS_AMT_LY_CAL,
		  SUM(PRM_TO_SLS_QTY_TY_FSC) AS PRM_TO_SLS_QTY_TY_FSC,
		  SUM(PRM_TO_SLS_QTY_LY_FSC) AS PRM_TO_SLS_QTY_LY_FSC,
		  SUM(PRM_TO_SLS_QTY_LY_HLDY) AS PRM_TO_SLS_QTY_LY_HLDY,
		  SUM(PRM_TO_SLS_QTY_LY_CAL) AS PRM_TO_SLS_QTY_LY_CAL,
		  SUM(PRM_TO_SLS_WGT_TY_FSC) AS PRM_TO_SLS_WGT_TY_FSC,
		  SUM(PRM_TO_SLS_WGT_LY_FSC) AS PRM_TO_SLS_WGT_LY_FSC,
		  SUM(PRM_TO_SLS_WGT_LY_HLDY) AS PRM_TO_SLS_WGT_LY_HLDY,
		  SUM(PRM_TO_SLS_WGT_LY_CAL) AS PRM_TO_SLS_WGT_LY_CAL,
		  SUM(PRM_TO_SLS_MKDN_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_MKDN_AMT_LY_FSC) AS PRM_TO_SLS_MKDN_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_MKDN_AMT_LY_HLDY) AS PRM_TO_SLS_MKDN_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_MKDN_AMT_LY_CAL) AS PRM_TO_SLS_MKDN_AMT_LY_CAL,
		  SUM(CLRNC_SLS_AMT_TY_FSC) AS CLRNC_SLS_AMT_TY_FSC,
		  SUM(CLRNC_SLS_AMT_LY_FSC) AS CLRNC_SLS_AMT_LY_FSC,
		  SUM(CLRNC_SLS_AMT_LY_HLDY) AS CLRNC_SLS_AMT_LY_HLDY,
		  SUM(CLRNC_SLS_AMT_LY_CAL) AS CLRNC_SLS_AMT_LY_CAL,
		  SUM(CLRNC_QTY_TY_FSC) AS CLRNC_QTY_TY_FSC,
		  SUM(CLRNC_QTY_LY_FSC) AS CLRNC_QTY_LY_FSC,
		  SUM(CLRNC_QTY_LY_HLDY) AS CLRNC_QTY_LY_HLDY,
		  SUM(CLRNC_QTY_LY_CAL) AS CLRNC_QTY_LY_CAL,
		  SUM(CLRNC_WGT_TY_FSC) AS CLRNC_WGT_TY_FSC,
		  SUM(CLRNC_WGT_LY_FSC) AS CLRNC_WGT_LY_FSC,
		  SUM(CLRNC_WGT_LY_HLDY) AS CLRNC_WGT_LY_HLDY,
		  SUM(CLRNC_WGT_LY_CAL) AS CLRNC_WGT_LY_CAL,
		  SUM(CLRNC_MKDN_AMT_TY_FSC) AS CLRNC_MKDN_AMT_TY_FSC,
		  SUM(CLRNC_MKDN_AMT_LY_FSC) AS CLRNC_MKDN_AMT_LY_FSC,
		  SUM(CLRNC_MKDN_AMT_LY_HLDY) AS CLRNC_MKDN_AMT_LY_HLDY,
		  SUM(CLRNC_MKDN_AMT_LY_CAL) AS CLRNC_MKDN_AMT_LY_CAL,
		  SUM(COGS_AMT_TY_FSC) AS COGS_AMT_TY_FSC,
		  SUM(COGS_AMT_LY_FSC) AS COGS_AMT_LY_FSC,
		  SUM(COGS_AMT_LY_HLDY) AS COGS_AMT_LY_HLDY,
		  SUM(COGS_AMT_LY_CAL) AS COGS_AMT_LY_CAL,
		  SUM(COGS_FNC_CHRG_AMT_TY_FSC) AS COGS_FNC_CHRG_AMT_TY_FSC,
		  SUM(COGS_FNC_CHRG_AMT_LY_FSC) AS COGS_FNC_CHRG_AMT_LY_FSC,
		  SUM(COGS_FNC_CHRG_AMT_LY_HLDY) AS COGS_FNC_CHRG_AMT_LY_HLDY,
		  SUM(COGS_FNC_CHRG_AMT_LY_CAL) AS COGS_FNC_CHRG_AMT_LY_CAL,
		  SUM(COGS_FNC_CR_AMT_TY_FSC) AS COGS_FNC_CR_AMT_TY_FSC,
		  SUM(COGS_FNC_CR_AMT_LY_FSC) AS COGS_FNC_CR_AMT_LY_FSC,
		  SUM(COGS_FNC_CR_AMT_LY_HLDY) AS COGS_FNC_CR_AMT_LY_HLDY,
		  SUM(COGS_FNC_CR_AMT_LY_CAL) AS COGS_FNC_CR_AMT_LY_CAL,
		  SUM(COGS_STRGE_CHRG_AMT_TY_FSC) AS COGS_STRGE_CHRG_AMT_TY_FSC,
		  SUM(COGS_STRGE_CHRG_AMT_LY_FSC) AS COGS_STRGE_CHRG_AMT_LY_FSC,
		  SUM(COGS_STRGE_CHRG_AMT_LY_HLDY) AS COGS_STRGE_CHRG_AMT_LY_HLDY,
		  SUM(COGS_STRGE_CHRG_AMT_LY_CAL) AS COGS_STRGE_CHRG_AMT_LY_CAL,
		  SUM(DRCT_MGN_AMT_TY_FSC) AS DRCT_MGN_AMT_TY_FSC,
		  SUM(DRCT_MGN_AMT_LY_FSC) AS DRCT_MGN_AMT_LY_FSC,
		  SUM(DRCT_MGN_AMT_LY_HLDY) AS DRCT_MGN_AMT_LY_HLDY,
		  SUM(DRCT_MGN_AMT_LY_CAL) AS DRCT_MGN_AMT_LY_CAL,
		  SUM(PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL,
		  SUM(CLRNC_DRCT_MGN_AMT_TY_FSC) AS CLRNC_DRCT_MGN_AMT_TY_FSC,
		  SUM(CLRNC_DRCT_MGN_AMT_LY_FSC) AS CLRNC_DRCT_MGN_AMT_LY_FSC,
		  SUM(CLRNC_DRCT_MGN_AMT_LY_HLDY) AS CLRNC_DRCT_MGN_AMT_LY_HLDY,
		  SUM(CLRNC_DRCT_MGN_AMT_LY_CAL) AS CLRNC_DRCT_MGN_AMT_LY_CAL,
		  SUM(COGS_FRT_AMT_TY_FSC) AS COGS_FRT_AMT_TY_FSC,
		  SUM(COGS_FRT_AMT_LY_FSC) AS COGS_FRT_AMT_LY_FSC,
		  SUM(COGS_FRT_AMT_LY_HLDY) AS COGS_FRT_AMT_LY_HLDY,
		  SUM(COGS_FRT_AMT_LY_CAL) AS COGS_FRT_AMT_LY_CAL,
		  SUM(COGS_DIST_CNTR_HNDL_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_TY_FSC,
		  SUM(COGS_DIST_CNTR_HNDL_AMT_LY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
		  SUM(COGS_DIST_CNTR_HNDL_AMT_LY_HLDY) AS COGS_DIST_CNTR_HNDL_AMT_LY_HLDY,
		  SUM(COGS_DIST_CNTR_HNDL_AMT_LY_CAL) AS COGS_DIST_CNTR_HNDL_AMT_LY_CAL

		FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC] a,
			 (SELECT
			   *,
			   ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
			 FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
			 WHERE AGG_TYP = 'AGG') dtsel
		WHERE a.DT_SK >= dtsel.MIN_DT
		AND a.DT_SK <= dtsel.MAX_DT
		GROUP BY dtsel.ROW_ID_VAL,
				 dtsel.PRE_DEF_ID,
				 CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)),
				 ITM_SKU,
				 STR_ID
		UNION

		SELECT
		  dtsel.ROW_ID_VAL,
		  dtsel.PRE_DEF_ID,
		  CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)) AS DT_VAL,
		  ITM_SKU,
		  STR_ID,
		  SUM(SLS_ADJ_AMT_TY_FSC) AS SLS_ADJ_AMT_TY_FSC,
		  SUM(SLS_ADJ_AMT_LY_FSC) AS SLS_ADJ_AMT_LY_FSC,
		  SUM(SLS_ADJ_AMT_LY_HLDY) AS SLS_ADJ_AMT_LY_HLDY,
		  SUM(SLS_ADJ_AMT_LY_CAL) AS SLS_ADJ_AMT_LY_CAL,
		  SUM(SLS_ADJ_QTY_TY_FSC) AS SLS_ADJ_QTY_TY_FSC,
		  SUM(SLS_ADJ_QTY_LY_FSC) AS SLS_ADJ_QTY_LY_FSC,
		  SUM(SLS_ADJ_QTY_LY_HLDY) AS SLS_ADJ_QTY_LY_HLDY,
		  SUM(SLS_ADJ_QTY_LY_CAL) AS SLS_ADJ_QTY_LY_CAL,
		  SUM(SLS_ADJ_WGT_TY_FSC) AS SLS_ADJ_WGT_TY_FSC,
		  SUM(SLS_ADJ_WGT_LY_FSC) AS SLS_ADJ_WGT_LY_FSC,
		  SUM(SLS_ADJ_WGT_LY_HLDY) AS SLS_ADJ_WGT_LY_HLDY,
		  SUM(SLS_ADJ_WGT_LY_CAL) AS SLS_ADJ_WGT_LY_CAL,
		  SUM(PRM_TO_SLS_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_ADJ_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_ADJ_AMT_LY_FSC) AS PRM_TO_SLS_ADJ_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_ADJ_AMT_LY_HLDY) AS PRM_TO_SLS_ADJ_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_ADJ_AMT_LY_CAL) AS PRM_TO_SLS_ADJ_AMT_LY_CAL,
		  SUM(PRM_TO_SLS_ADJ_QTY_TY_FSC) AS PRM_TO_SLS_ADJ_QTY_TY_FSC,
		  SUM(PRM_TO_SLS_ADJ_QTY_LY_FSC) AS PRM_TO_SLS_ADJ_QTY_LY_FSC,
		  SUM(PRM_TO_SLS_ADJ_QTY_LY_HLDY) AS PRM_TO_SLS_ADJ_QTY_LY_HLDY,
		  SUM(PRM_TO_SLS_ADJ_QTY_LY_CAL) AS PRM_TO_SLS_ADJ_QTY_LY_CAL,
		  SUM(PRM_TO_SLS_ADJ_WGT_TY_FSC) AS PRM_TO_SLS_ADJ_WGT_TY_FSC,
		  SUM(PRM_TO_SLS_ADJ_WGT_LY_FSC) AS PRM_TO_SLS_ADJ_WGT_LY_FSC,
		  SUM(PRM_TO_SLS_ADJ_WGT_LY_HLDY) AS PRM_TO_SLS_ADJ_WGT_LY_HLDY,
		  SUM(PRM_TO_SLS_ADJ_WGT_LY_CAL) AS PRM_TO_SLS_ADJ_WGT_LY_CAL,
		  SUM(PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_ADJ_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC) AS PRM_TO_SLS_MKDN_ADJ_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY) AS PRM_TO_SLS_MKDN_ADJ_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL) AS PRM_TO_SLS_MKDN_ADJ_AMT_LY_CAL,
		  SUM(CLRNC_SLS_ADJ_AMT_TY_FSC) AS CLRNC_SLS_ADJ_AMT_TY_FSC,
		  SUM(CLRNC_SLS_ADJ_AMT_LY_FSC) AS CLRNC_SLS_ADJ_AMT_LY_FSC,
		  SUM(CLRNC_SLS_ADJ_AMT_LY_HLDY) AS CLRNC_SLS_ADJ_AMT_LY_HLDY,
		  SUM(CLRNC_SLS_ADJ_AMT_LY_CAL) AS CLRNC_SLS_ADJ_AMT_LY_CAL,
		  SUM(CLRNC_ADJ_QTY_TY_FSC) AS CLRNC_ADJ_QTY_TY_FSC,
		  SUM(CLRNC_ADJ_QTY_LY_FSC) AS CLRNC_ADJ_QTY_LY_FSC,
		  SUM(CLRNC_ADJ_QTY_LY_HLDY) AS CLRNC_ADJ_QTY_LY_HLDY,
		  SUM(CLRNC_ADJ_QTY_LY_CAL) AS CLRNC_ADJ_QTY_LY_CAL,
		  SUM(CLRNC_ADJ_WGT_TY_FSC) AS CLRNC_ADJ_WGT_TY_FSC,
		  SUM(CLRNC_ADJ_WGT_LY_FSC) AS CLRNC_ADJ_WGT_LY_FSC,
		  SUM(CLRNC_ADJ_WGT_LY_HLDY) AS CLRNC_ADJ_WGT_LY_HLDY,
		  SUM(CLRNC_ADJ_WGT_LY_CAL) AS CLRNC_ADJ_WGT_LY_CAL,
		  SUM(CLRNC_MKDN_ADJ_AMT_TY_FSC) AS CLRNC_MKDN_ADJ_AMT_TY_FSC,
		  SUM(CLRNC_MKDN_ADJ_AMT_LY_FSC) AS CLRNC_MKDN_ADJ_AMT_LY_FSC,
		  SUM(CLRNC_MKDN_ADJ_AMT_LY_HLDY) AS CLRNC_MKDN_ADJ_AMT_LY_HLDY,
		  SUM(CLRNC_MKDN_ADJ_AMT_LY_CAL) AS CLRNC_MKDN_ADJ_AMT_LY_CAL,
		  SUM(COGS_ADJ_AMT_TY_FSC) AS COGS_ADJ_AMT_TY_FSC,
		  SUM(COGS_ADJ_AMT_LY_FSC) AS COGS_ADJ_AMT_LY_FSC,
		  SUM(COGS_ADJ_AMT_LY_HLDY) AS COGS_ADJ_AMT_LY_HLDY,
		  SUM(COGS_ADJ_AMT_LY_CAL) AS COGS_ADJ_AMT_LY_CAL,
		  SUM(COGS_FNC_CHRG_ADJ_AMT_TY_FSC) AS COGS_FNC_CHRG_ADJ_AMT_TY_FSC,
		  SUM(COGS_FNC_CHRG_ADJ_AMT_LY_FSC) AS COGS_FNC_CHRG_ADJ_AMT_LY_FSC,
		  SUM(COGS_FNC_CHRG_ADJ_AMT_LY_HLDY) AS COGS_FNC_CHRG_ADJ_AMT_LY_HLDY,
		  SUM(COGS_FNC_CHRG_ADJ_AMT_LY_CAL) AS COGS_FNC_CHRG_ADJ_AMT_LY_CAL,
		  SUM(COGS_FNC_CR_ADJ_AMT_TY_FSC) AS COGS_FNC_CR_ADJ_AMT_TY_FSC,
		  SUM(COGS_FNC_CR_ADJ_AMT_LY_FSC) AS COGS_FNC_CR_ADJ_AMT_LY_FSC,
		  SUM(COGS_FNC_CR_ADJ_AMT_LY_HLDY) AS COGS_FNC_CR_ADJ_AMT_LY_HLDY,
		  SUM(COGS_FNC_CR_ADJ_AMT_LY_CAL) AS COGS_FNC_CR_ADJ_AMT_LY_CAL,
		  SUM(COGS_STRGE_CHRG_ADJ_AMT_TY_FSC) AS COGS_STRGE_CHRG_ADJ_AMT_TY_FSC,
		  SUM(COGS_STRGE_CHRG_ADJ_AMT_LY_FSC) AS COGS_STRGE_CHRG_ADJ_AMT_LY_FSC,
		  SUM(COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY) AS COGS_STRGE_CHRG_ADJ_AMT_LY_HLDY,
		  SUM(COGS_STRGE_CHRG_ADJ_AMT_LY_CAL) AS COGS_STRGE_CHRG_ADJ_AMT_LY_CAL,
		  SUM(DRCT_MGN_ADJ_AMT_TY_FSC) AS DRCT_MGN_ADJ_AMT_TY_FSC,
		  SUM(DRCT_MGN_ADJ_AMT_LY_FSC) AS DRCT_MGN_ADJ_AMT_LY_FSC,
		  SUM(DRCT_MGN_ADJ_AMT_LY_HLDY) AS DRCT_MGN_ADJ_AMT_LY_HLDY,
		  SUM(DRCT_MGN_ADJ_AMT_LY_CAL) AS DRCT_MGN_ADJ_AMT_LY_CAL,
		  SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_TY_FSC,
		  SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_FSC,
		  SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_HLDY,
		  SUM(PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL) AS PRM_TO_SLS_DRCT_MGN_ADJ_AMT_LY_CAL,
		  SUM(CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC) AS CLRNC_DRCT_MGN_ADJ_AMT_TY_FSC,
		  SUM(CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC) AS CLRNC_DRCT_MGN_ADJ_AMT_LY_FSC,
		  SUM(CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY) AS CLRNC_DRCT_MGN_ADJ_AMT_LY_HLDY,
		  SUM(CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL) AS CLRNC_DRCT_MGN_ADJ_AMT_LY_CAL,
		  SUM(COGS_FRT_ADJ_AMT_TY_FSC) AS COGS_FRT_ADJ_AMT_TY_FSC,
		  SUM(COGS_FRT_ADJ_AMT_LY_FSC) AS COGS_FRT_ADJ_AMT_LY_FSC,
		  SUM(COGS_FRT_ADJ_AMT_LY_HLDY) AS COGS_FRT_ADJ_AMT_LY_HLDY,
		  SUM(COGS_FRT_ADJ_AMT_LY_CAL) AS COGS_FRT_ADJ_AMT_LY_CAL,
		  SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_TY_FSC,
		  SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_FSC,
		  SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_HLDY,
		  SUM(COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL) AS COGS_DIST_CNTR_HNDL_ADJ_AMT_LY_CAL
		FROM [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_ADJ_TY_LY_FSC] a,
			 (SELECT
			   *,
			   ROW_NUMBER() OVER (ORDER BY PRE_DEF_ID) AS ROW_ID_VAL
			 FROM EDAA_PRES.V_DIM_PRE_DEF_CAL_TYP
			 WHERE AGG_TYP = 'AGG') dtsel
		WHERE a.DT_SK >= dtsel.MIN_DT
		AND a.DT_SK <= dtsel.MAX_DT
		GROUP BY dtsel.ROW_ID_VAL,
				 dtsel.PRE_DEF_ID,
				 CONVERT(date, CONVERT(varchar(10), dtsel.MAX_DT, 120)),
				 ITM_SKU,
				 STR_ID)


		--INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_AGG]
		INSERT INTO [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_AGG]
		  SELECT
			ROW_ID_VAL,
			PRE_DEF_ID,
			DT_VAL,
			ITM_SKU,
			STR_ID,
			SUM(SLS_AMT_TY_FSC) AS SLS_AMT_TY_FSC,
			SUM(SLS_AMT_LY_FSC) AS SLS_AMT_LY_FSC,
			SUM(SLS_AMT_LY_HLDY) AS SLS_AMT_LY_HLDY,
			SUM(SLS_AMT_LY_CAL) AS SLS_AMT_LY_CAL,
			SUM(SLS_QTY_TY_FSC) AS SLS_QTY_TY_FSC,
			SUM(SLS_QTY_LY_FSC) AS SLS_QTY_LY_FSC,
			SUM(SLS_QTY_LY_HLDY) AS SLS_QTY_LY_HLDY,
			SUM(SLS_QTY_LY_CAL) AS SLS_QTY_LY_CAL,
			SUM(SLS_WGT_TY_FSC) AS SLS_WGT_TY_FSC,
			SUM(SLS_WGT_LY_FSC) AS SLS_WGT_LY_FSC,
			SUM(SLS_WGT_LY_HLDY) AS SLS_WGT_LY_HLDY,
			SUM(SLS_WGT_LY_CAL) AS SLS_WGT_LY_CAL,
			SUM(PRM_TO_SLS_AMT_TY_FSC) AS PRM_TO_SLS_AMT_TY_FSC,
			SUM(PRM_TO_SLS_AMT_LY_FSC) AS PRM_TO_SLS_AMT_LY_FSC,
			SUM(PRM_TO_SLS_AMT_LY_HLDY) AS PRM_TO_SLS_AMT_LY_HLDY,
			SUM(PRM_TO_SLS_AMT_LY_CAL) AS PRM_TO_SLS_AMT_LY_CAL,
			SUM(PRM_TO_SLS_QTY_TY_FSC) AS PRM_TO_SLS_QTY_TY_FSC,
			SUM(PRM_TO_SLS_QTY_LY_FSC) AS PRM_TO_SLS_QTY_LY_FSC,
			SUM(PRM_TO_SLS_QTY_LY_HLDY) AS PRM_TO_SLS_QTY_LY_HLDY,
			SUM(PRM_TO_SLS_QTY_LY_CAL) AS PRM_TO_SLS_QTY_LY_CAL,
			SUM(PRM_TO_SLS_WGT_TY_FSC) AS PRM_TO_SLS_WGT_TY_FSC,
			SUM(PRM_TO_SLS_WGT_LY_FSC) AS PRM_TO_SLS_WGT_LY_FSC,
			SUM(PRM_TO_SLS_WGT_LY_HLDY) AS PRM_TO_SLS_WGT_LY_HLDY,
			SUM(PRM_TO_SLS_WGT_LY_CAL) AS PRM_TO_SLS_WGT_LY_CAL,
			SUM(PRM_TO_SLS_MKDN_AMT_TY_FSC) AS PRM_TO_SLS_MKDN_AMT_TY_FSC,
			SUM(PRM_TO_SLS_MKDN_AMT_LY_FSC) AS PRM_TO_SLS_MKDN_AMT_LY_FSC,
			SUM(PRM_TO_SLS_MKDN_AMT_LY_HLDY) AS PRM_TO_SLS_MKDN_AMT_LY_HLDY,
			SUM(PRM_TO_SLS_MKDN_AMT_LY_CAL) AS PRM_TO_SLS_MKDN_AMT_LY_CAL,
			SUM(CLRNC_SLS_AMT_TY_FSC) AS CLRNC_SLS_AMT_TY_FSC,
			SUM(CLRNC_SLS_AMT_LY_FSC) AS CLRNC_SLS_AMT_LY_FSC,
			SUM(CLRNC_SLS_AMT_LY_HLDY) AS CLRNC_SLS_AMT_LY_HLDY,
			SUM(CLRNC_SLS_AMT_LY_CAL) AS CLRNC_SLS_AMT_LY_CAL,
			SUM(CLRNC_QTY_TY_FSC) AS CLRNC_QTY_TY_FSC,
			SUM(CLRNC_QTY_LY_FSC) AS CLRNC_QTY_LY_FSC,
			SUM(CLRNC_QTY_LY_HLDY) AS CLRNC_QTY_LY_HLDY,
			SUM(CLRNC_QTY_LY_CAL) AS CLRNC_QTY_LY_CAL,
			SUM(CLRNC_WGT_TY_FSC) AS CLRNC_WGT_TY_FSC,
			SUM(CLRNC_WGT_LY_FSC) AS CLRNC_WGT_LY_FSC,
			SUM(CLRNC_WGT_LY_HLDY) AS CLRNC_WGT_LY_HLDY,
			SUM(CLRNC_WGT_LY_CAL) AS CLRNC_WGT_LY_CAL,
			SUM(CLRNC_MKDN_AMT_TY_FSC) AS CLRNC_MKDN_AMT_TY_FSC,
			SUM(CLRNC_MKDN_AMT_LY_FSC) AS CLRNC_MKDN_AMT_LY_FSC,
			SUM(CLRNC_MKDN_AMT_LY_HLDY) AS CLRNC_MKDN_AMT_LY_HLDY,
			SUM(CLRNC_MKDN_AMT_LY_CAL) AS CLRNC_MKDN_AMT_LY_CAL,
			SUM(COGS_AMT_TY_FSC) AS COGS_AMT_TY_FSC,
			SUM(COGS_AMT_LY_FSC) AS COGS_AMT_LY_FSC,
			SUM(COGS_AMT_LY_HLDY) AS COGS_AMT_LY_HLDY,
			SUM(COGS_AMT_LY_CAL) AS COGS_AMT_LY_CAL,
			SUM(COGS_FNC_CHRG_AMT_TY_FSC) AS COGS_FNC_CHRG_AMT_TY_FSC,
			SUM(COGS_FNC_CHRG_AMT_LY_FSC) AS COGS_FNC_CHRG_AMT_LY_FSC,
			SUM(COGS_FNC_CHRG_AMT_LY_HLDY) AS COGS_FNC_CHRG_AMT_LY_HLDY,
			SUM(COGS_FNC_CHRG_AMT_LY_CAL) AS COGS_FNC_CHRG_AMT_LY_CAL,
			SUM(COGS_FNC_CR_AMT_TY_FSC) AS COGS_FNC_CR_AMT_TY_FSC,
			SUM(COGS_FNC_CR_AMT_LY_FSC) AS COGS_FNC_CR_AMT_LY_FSC,
			SUM(COGS_FNC_CR_AMT_LY_HLDY) AS COGS_FNC_CR_AMT_LY_HLDY,
			SUM(COGS_FNC_CR_AMT_LY_CAL) AS COGS_FNC_CR_AMT_LY_CAL,
			SUM(COGS_STRGE_CHRG_AMT_TY_FSC) AS COGS_STRGE_CHRG_AMT_TY_FSC,
			SUM(COGS_STRGE_CHRG_AMT_LY_FSC) AS COGS_STRGE_CHRG_AMT_LY_FSC,
			SUM(COGS_STRGE_CHRG_AMT_LY_HLDY) AS COGS_STRGE_CHRG_AMT_LY_HLDY,
			SUM(COGS_STRGE_CHRG_AMT_LY_CAL) AS COGS_STRGE_CHRG_AMT_LY_CAL,
			SUM(DRCT_MGN_AMT_TY_FSC) AS DRCT_MGN_AMT_TY_FSC,
			SUM(DRCT_MGN_AMT_LY_FSC) AS DRCT_MGN_AMT_LY_FSC,
			SUM(DRCT_MGN_AMT_LY_HLDY) AS DRCT_MGN_AMT_LY_HLDY,
			SUM(DRCT_MGN_AMT_LY_CAL) AS DRCT_MGN_AMT_LY_CAL,
			SUM(PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC,
			SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC,
			SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY,
			SUM(PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL) AS PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL,
			SUM(CLRNC_DRCT_MGN_AMT_TY_FSC) AS CLRNC_DRCT_MGN_AMT_TY_FSC,
			SUM(CLRNC_DRCT_MGN_AMT_LY_FSC) AS CLRNC_DRCT_MGN_AMT_LY_FSC,
			SUM(CLRNC_DRCT_MGN_AMT_LY_HLDY) AS CLRNC_DRCT_MGN_AMT_LY_HLDY,
			SUM(CLRNC_DRCT_MGN_AMT_LY_CAL) AS CLRNC_DRCT_MGN_AMT_LY_CAL,
			SUM(COGS_FRT_AMT_TY_FSC) AS COGS_FRT_AMT_TY_FSC,
			SUM(COGS_FRT_AMT_LY_FSC) AS COGS_FRT_AMT_LY_FSC,
			SUM(COGS_FRT_AMT_LY_HLDY) AS COGS_FRT_AMT_LY_HLDY,
			SUM(COGS_FRT_AMT_LY_CAL) AS COGS_FRT_AMT_LY_CAL,
			SUM(COGS_DIST_CNTR_HNDL_AMT_TY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_TY_FSC,
			SUM(COGS_DIST_CNTR_HNDL_AMT_LY_FSC) AS COGS_DIST_CNTR_HNDL_AMT_LY_FSC,
			SUM(COGS_DIST_CNTR_HNDL_AMT_LY_HLDY) AS COGS_DIST_CNTR_HNDL_AMT_LY_HLDY,
			SUM(COGS_DIST_CNTR_HNDL_AMT_LY_CAL) AS COGS_DIST_CNTR_HNDL_AMT_LY_CAL
		  FROM COMBINED_TABLES
		  GROUP BY ROW_ID_VAL,
				   PRE_DEF_ID,
				   DT_VAL,
				   ITM_SKU,
				   STR_ID;

		--UPDATE STATISTICS
		UPDATE STATISTICS [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_AGG];

	  END TRY

	  BEGIN CATCH
		EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY,
											  @NBR_OF_RW_ISRT = 0,
											  @NBR_OF_RW_UDT = 0
		SET @ERROR_PROCEDURE_NAME = 'EDAA_ETL.PROC_FCT_DLY_ITM_SKU_STR_SLS_AGG_LOAD'
		--SET @ERROR_LINE
		--SET @ERROR_MSG

		SELECT
		  @ERROR_LINE = ERROR_NUMBER(),
		  @ERROR_MSG = ERROR_MESSAGE();

		--------- Log execution error ----------
		EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY,
									  @ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
									  @ERROR_LINE = @ERROR_LINE,
									  @ERROR_MSG = @ERROR_MSG;

		THROW;

	  END CATCH

  END
