CREATE PROC [EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_POSTPROCESS] AS

BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_POSTPROCESS'
,@SRC_ENTY  = 'UT_UPC_DLY_INV_HST_INITIAL'
,@TGT_ENTY = 'FCT_DLY_STR_ITMSKU_INV'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

DECLARE @NBR_OF_RW_ISRT_TOTAL INT = 0,  @NBR_OF_RW_UDT_TOTAL INT =0

;with t2099 as
(select row_number() over(partition by itm_sku, str_id order by inv_row_start_dt desc) rn,
dateadd(d,-1,lag(inv_row_start_dt) OVER (PARTITION BY itm_sku, str_id ORDER BY inv_row_start_dt desc)) AS LastInvDt,
f.* from edaa_dw.fct_dly_str_itmsku_inv f )
update
edaa_dw.fct_dly_str_itmsku_inv  set
Inv_row_end_dt = tab.LastInvDt,
Aud_Upd_Sk = @NEW_AUD_SKY
from
edaa_dw.fct_dly_str_itmsku_inv f2, t2099 as tab
where
f2.itm_sku=tab.itm_sku and f2.inv_row_start_dt=tab.inv_row_start_dt and f2.str_id=tab.str_id and
f2.inv_row_end_dt='2099-01-01' and tab.LastInvDt is not null ;

PRINT('DATA LOAD DONE IN DW TABLE');

BEGIN

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM EDAA_DW.fct_dly_str_itmsku_inv WHERE AUD_INS_SK = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT(1)  FROM EDAA_DW.fct_dly_str_itmsku_inv WHERE AUD_UPD_SK = @NEW_AUD_SKY


/*AUDIT LOG END*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT =@NBR_OF_RW_ISRT, @NBR_OF_RW_UDT = @NBR_OF_RW_UDT ;

END



END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[PROC_FCT_DLY_STR_ITMSKU_INV_INITIAL_POSTPROCESS]'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


   THROW;




END CATCH
