CREATE PROC [EDAA_ETL].[PROC_FCT_HRLY_ITMSKU_STR_FUEL_SLS_TABLELOAD] AS
-- exec  [EDAA_ETL].[PROC_FCT_HRLY_ITMSKU_STR_FUEL_SLS_TABLELOAD]
BEGIN

	-- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON

	BEGIN TRY
		/*DATAMART AUDITING VARIABLES*/
		DECLARE @NEW_AUD_SKY BIGINT
		DECLARE @NBR_OF_RW_ISRT BIGINT
		DECLARE @NBR_OF_RW_UDT BIGINT
		DECLARE @EXEC_LYR VARCHAR(255)
		DECLARE @EXEC_JOB VARCHAR(500)
		DECLARE @SRC_ENTY VARCHAR(500)
		DECLARE @TGT_ENTY VARCHAR(500)


		/*AUDIT LOG START*/
		EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR = 'EDAA_DW'
			,@EXEC_JOB = '[EDAA_ETL].[PROC_FCT_HRLY_ITMSKU_STR_FUEL_SLS_TABLELOAD]'
			,@SRC_ENTY = '[EDAA_STG].[FCT_HRLY_ITMSKU_SLS] '
			,@TGT_ENTY = '[EDAA_DW].[FCT_HRLY_ITMSKU_SLS_TY_LY_FSC]'
			,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;

		INSERT INTO [EDAA_DW].[FCT_HRLY_STR_ITMSKU_TY_LY_FUEL_SLS]
		(

	        [DT_SK],
	        [ITM_SKU],
	        [STR_ID],
		    [SLS_AMT],
		    [SLS_QTY],
		    [PRM_TO_SLS_DRCT_MGN_AMT],
			[AUD_INS_SK],
			[AUD_UPD_SK]
		 )

		SELECT
		CAST(REPLACE(A.STO_POS_BUS_DT,'-','') AS INT) AS DT_SK,
		[UPC_ID],
		[UT_ID],
		[UPC_PTS_AM],
		[UPC_PTS_QT],
		[UPC_PTS_DMGN_AM],
        @NEW_AUD_SKY as AUD_INS_SK
	   ,NULL as AUD_UPD_SK
		FROM [EDAA_STG].[FCT_HRLY_ITMSKU_SLS]  AS A
		LEFT OUTER JOIN (
				SELECT GEO_HIST_SK
					,STR_ID
					,VLD_FRM
					,VLD_TO
				FROM EDAA_DW.DIM_GEO WHERE IS_CURR_IND = 1 ) AS GEO ON GEO.STR_ID = A.[UT_ID]

		LEFT OUTER JOIN (
				SELECT PROD_HIST_SK
					,ITM_SKU
					,PROD_SK
					,VLD_FRM
					,VLD_TO
				FROM EDAA_DW.DIM_PROD WHERE IS_CURR_IND = 1 )AS P ON P.ITM_SKU = A.[UT_ID]



		PRINT ('---DW load complete---');
	END TRY

	BEGIN CATCH
		DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL.PROC_FCT_HRLY_ITMSKU_STR_FUEL_SLS_TABLELOAD'
		DECLARE @ERROR_LINE AS INT;
		DECLARE @ERROR_MSG AS NVARCHAR(max);

		SELECT @ERROR_LINE = ERROR_NUMBER()
			,@ERROR_MSG = ERROR_MESSAGE();

		--------- Log execution error ----------
		EXEC EDAA_CNTL.SP_LOG_AUD_ERR @AUD_SKY = @NEW_AUD_SKY
			,@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME
			,@ERROR_LINE = @ERROR_LINE
			,@ERROR_MSG = @ERROR_MSG;


		-- Detect the change
		THROW;
	END CATCH
END
