CREATE PROC [EDAA_ETL].[SP_DW_FCT_HRLY_FUEL_PCHG_DTL_TABLELOAD] AS

/*
 =============================================
 Author:        Akanksha Kumari
 Create date:   4-March-2022
 Description:   Stored proc to load the Fuel price change data from
				EDAA_STG.FUEL_PCHG_DTL table to FCT_HRLY_FUEL_PCHG_DTL tble on EDAA_DW
 =============================================
 Change History
 4-march-2022   Akanksha Kumari      Initial version

*/

BEGIN TRY

SET NOCOUNT ON
SET XACT_ABORT ON

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'SP_DW_FCT_HRLY_FUEL_PCHG_DTL_TABLELOAD'
,@SRC_ENTY  = 'FUEL_PCHG_DTL'
,@TGT_ENTY = 'FCT_HRLY_FUEL_PCHG_DTL'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


--------- Append data into Datawarehouse table -----
INSERT INTO [EDAA_DW].[FCT_HRLY_FUEL_PCHG_DTL]
(
		 [FUEL_PCHG_SEQ_ID]
		,[STR_ID]
		,[GEO_HIST_SK]
		,[ITM_GRP_ID]
		,[CAL_DT]
		,[SRC_RW_GRTN_TMS]
		,[DT_SK]
		,[FUEL_PR_AMT]
		,[SRC_RW_PRCS_ID]
		,[PCHG_KLBRT_TN_ID]
		,[PCHG_KLBRT_STS_TX]
		,[RW_CRT_TMS]
		,[AUD_INS_SK]
        ,[AUD_UPD_SK]
)
SELECT [FUEL_PCHG_SEQ_ID]
      ,b.[STR_ID]
      ,[GEO_HIST_SK]
      ,[ITM_GRP_ID]
	  ,CONVERT (date, SRC_RW_GRTN_TMS) as CAL_DT
	  ,[SRC_RW_GRTN_TMS]
	  ,[DT_SK]
	  ,[FUEL_PR_AMT]
	  ,[SRC_RW_PRCS_ID]
	  ,[PCHG_KLBRT_TN_ID]
	  ,[PCHG_KLBRT_STS_TX]
	  ,GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Eastern Standard Time' as RW_CRT_TMS
	  ,@NEW_AUD_SKY [Aud_Ins_Sk]
      ,NULL AS [Aud_Upd_Sk]
 FROM [EDAA_STG].[FUEL_PCHG_DTL] as a
 INNER JOIN [EDAA_DW].[DIM_GEO] as b on a.[STR_ID] = b.[STR_ID]
 AND b.[vld_to]='2099-01-01'
 INNER JOIN [EDAA_DW].[DIM_DLY_CAL] c ON c.[CAL_DT]=CONVERT (date, SRC_RW_GRTN_TMS)


BEGIN
SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM [EDAA_DW].[FCT_HRLY_FUEL_PCHG_DTL] WHERE Aud_Ins_Sk = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT(1)  FROM [EDAA_DW].[FCT_HRLY_FUEL_PCHG_DTL] WHERE Aud_Upd_Sk = @NEW_AUD_SKY

END

/*Audit Log End*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'SP_DW_FCT_HRLY_FUEL_PCHG_DTL_TABLELOAD'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change
------- stored proc execution should fail. The processing of the presentation layer

   THROW;


END CATCH
