CREATE PROC EDAA_ETL.SP_REF_BYR_EMP_PKY_MPRS_CURRPREV_ARCHIVE AS
/*
 =============================================
 Author:        Arindam Pathak
 Create date:   15-Apr-2021
 Description:   This SP Archive the previous day data to Archive table before
				truncating the DW fact table for current day 1st load
 =============================================
 Change History
 15-Apr-2021	AP      Initial Version

*/

BEGIN TRY

SET NOCOUNT ON
SET XACT_ABORT ON

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_REF'
,@EXEC_JOB  = 'SP_REF_BYR_EMP_PKY_MPRS_CURRPREV_ARCHIVE'
,@SRC_ENTY  = 'BYR_EMP_PKY_MPRS_CURRPREV_INF'
,@TGT_ENTY = 'BYR_EMP_PKY_MPRS_CURRPREV_INF_HST'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT
;


INSERT INTO EDAA_REF.BYR_EMP_PKY_MPRS_CURRPREV_INF_HST(
	   MJR_P_SUB_CT_ID
      ,BYR_ID
      ,INDV_LST_NM
      ,MGR_EMP_ID
      ,MGR_ID
      ,PKY_ID
      ,MPRS_CT_ID
      ,INS_DT
      ,CURR_PKY_ID
      ,PKY_DSC
      ,CURR_MPRS_CT_ID
      ,MPRS_CT_DSC
      ,EMP_ID
      ,AUD_INS_SKY
  )

  SELECT
	   MJR_P_SUB_CT_ID
      ,BYR_ID
      ,INDV_LST_NM
      ,MGR_EMP_ID
      ,MGR_ID
      ,PKY_ID
      ,MPRS_CT_ID
      ,INS_DT
      ,CURR_PKY_ID
      ,PKY_DSC
      ,CURR_MPRS_CT_ID
      ,MPRS_CT_DSC
      ,EMP_ID
      ,@NEW_AUD_SKY
  FROM EDAA_REF.BYR_EMP_PKY_MPRS_CURRPREV_INF
  WHERE INS_DT NOT IN (SELECT MAX(INS_DT) FROM EDAA_REF.BYR_EMP_PKY_MPRS_CURRPREV_INF)




  DELETE FROM EDAA_REF.BYR_EMP_PKY_MPRS_CURRPREV_INF
  WHERE INS_DT NOT IN (SELECT MAX(INS_DT) FROM EDAA_REF.BYR_EMP_PKY_MPRS_CURRPREV_INF)
  ;






  /*Audit Log End*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = 0, @NBR_OF_RW_UDT  = 0

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL.SP_REF_BYR_EMP_PKY_MPRS_CURRPREV_ARCHIVE'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


   THROW;




END CATCH
GO
