CREATE PROC [EDAA_ETL].[SP_REF_GS_STA_FUEL_TYP_SETUP_HST_TABLELOAD] AS

/*
 =============================================
 Author:        Akanksha Kumari
 Create date:   6-Dec-2021
 Description:   Stored proc to load the Gas station fuel type data from SQL SERVER table
				to GS_STA_FUEL_TYP_SETUP_HST tble on EDAA_REF
 =============================================
 Change History
 6-Dec-2021   Akanksha Kumari      Initial version

*/

BEGIN TRY

SET NOCOUNT ON
SET XACT_ABORT ON

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_REF'
,@EXEC_JOB  = 'SP_REF_GS_STA_FUEL_TYP_SETUP_HST_TABLELOAD'
,@SRC_ENTY  = 'GS_STA_FUEL_TYP_SETUP'
,@TGT_ENTY = 'GS_STA_FUEL_TYP_SETUP_HST'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


---------update data in target table -----
UPDATE EDAA_REF.GS_STA_FUEL_TYP_SETUP_HST
  SET
		RW_UDT_TS = STG.RW_UDT_TS,
		PRD_STRT_DT = STG.PRD_STRT_DT,
		PRD_END_DT = STG.PRD_END_DT,
		AUD_UPD_SK = @NEW_AUD_SKY
FROM EDAA_STG.GS_STA_FUEL_TYP_SETUP STG
INNER JOIN EDAA_REF.GS_STA_FUEL_TYP_SETUP_HST TGT
on  STG.STR_ID = TGT.STR_ID
AND STG.FUEL_TYP_ID = TGT.FUEL_TYP_ID
AND STG.PRD_STRT_DT = TGT.PRD_STRT_DT

--------insert new data in target table---

INSERT INTO EDAA_REF.GS_STA_FUEL_TYP_SETUP_HST
SELECT
		STR_ID
		,FUEL_TYP_ID
		,RW_UDT_TS
		,PRD_STRT_DT
		,PRD_END_DT
		,@NEW_AUD_SKY AS AUD_INS_SK
		,NULL AS AUD_UPD_SK
FROM EDAA_STG.GS_STA_FUEL_TYP_SETUP
WHERE PRD_STRT_DT = cast(getdate() as date)



BEGIN
SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM [EDAA_REF].[GS_STA_FUEL_TYP_SETUP_HST] WHERE Aud_Ins_Sk = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT(1)  FROM [EDAA_REF].[GS_STA_FUEL_TYP_SETUP_HST] WHERE Aud_Upd_Sk = @NEW_AUD_SKY

END

/*Audit Log End*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'SP_REF_GS_STA_FUEL_TYP_SETUP_HST_TABLELOAD'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change
------- stored proc execution should fail. The processing of the presentation layer

   THROW;




END CATCH
