CREATE PROC [EDAA_ETL].[SP_STG_DW_FCT_WKND_PKY_MPRK_ADJ_TABLELOAD] AS

/*
 =============================================
 Author:        Krishna Kumar Shaw
 Create date:   20-Apr-2021
 Description:   Stored proc truncate and load Hourly Weekend PKY MPRK Adjustement table.
 =============================================
 Change History
 20-Apr-2021   KKS      Initial version

*/


BEGIN TRY

SET NOCOUNT ON
SET XACT_ABORT ON

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'SP_STG_DW_FACT_FCT_WKND_PKY_MPRK_ADJ_TABLELOAD'
,@SRC_ENTY  = 'EDAA_STG.FCT_WKND_PKY_MPRK_ADJ'
,@TGT_ENTY = 'FCT_WKND_PKY_MPRK_ADJ'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


INSERT INTO EDAA_DW.FCT_WKND_PKY_MPRK_ADJ
(
Fnc_Lvl3_Pky_Id
,Dt_Sk
,Mprk_Adj_Prcntg
,Aud_Ins_Sk
,Aud_Upd_Sk

)
SELECT
			 Fnc_Lvl3_Pky_Id
			,Dt_Sk
			,Mprk_Adj_Prcntg
			,@NEW_AUD_SKY 	AS Aud_Ins_Sk
			,NULL 			AS Aud_Upd_Sk

FROM 	EDAA_STG.FCT_WKND_PKY_MPRK_ADJ



BEGIN
SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM EDAA_DW.FCT_WKND_PKY_MPRK_ADJ WHERE Aud_Ins_Sk = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT(1)  FROM EDAA_DW.FCT_WKND_PKY_MPRK_ADJ WHERE Aud_Upd_Sk = @NEW_AUD_SKY

------------ UPDATE Statistics-------

UPDATE STATISTICS  EDAA_DW.FCT_WKND_PKY_MPRK_ADJ;

END

/*Audit Log End*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL.SP_STG_DW_FACT_FCT_WKND_PKY_MPRK_ADJ_TABLELOAD'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


   THROW;




END CATCH
