CREATE PROC [EDAA_ETL].[SP_STG_DW_FCT_POCAA_HST_SUMMARY] AS

/*
 =============================================
 Author:        Core Build Team
 Create date:   12-july-2022
 Description:   Stored proc load FCT_POCAA_HST_SUMMARY table.
 =============================================
*/

BEGIN TRY

SET NOCOUNT ON
SET XACT_ABORT ON

/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT BIGINT
DECLARE @NBR_OF_RW_UDT BIGINT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
 @EXEC_LYR  = 'EDAA_DW'
,@EXEC_JOB  = 'SP_STG_DW_FCT_POCAA_HST_SUMMARY'
,@SRC_ENTY  = 'EDAA_STG.FCT_POCAA_HST_SUMMARY'
,@TGT_ENTY = 'FCT_POCAA_HST_SUMMARY'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT

--UPDATE DW
--SET DW.IsCurr=0
--FROM
--[EDAA_DW].[FCT_MPRS_RCV_DTL] DW
--INNER JOIN [EDAA_STG].[FCT_MPRS_RCV_DTL] STG
--ON STG.PO_NBR_ID=DW.PO_NBR_ID
--AND STG.LD_ID=DW.LD_ID
--AND STG.VDR_SHP_ID=DW.VDR_SHP_ID
--AND STG.IN_PK_ID=DW.IN_PK_ID
--WHERE STG.IsCDC=1
--AND DW.IsCDC=0;

/* Validate Late arriving dimension: DIM_GEO */
PRINT('LATEARRIVINGDIMENSION: DIM_GEO')

IF OBJECT_ID('TEMPDB..#LATEARRIVINGDIMENSIONFACTRECORDS') IS NOT NULL
DROP TABLE #LATEARRIVINGDIMENSIONFACTRECORDS

CREATE TABLE #LATEARRIVINGDIMENSIONFACTRECORDS
WITH (
	DISTRIBUTION = ROUND_ROBIN
	)
AS
SELECT DISTINCT FACT_DATA_FEED.Str_Id,
CASE WHEN GEO.Str_Id IS NULL THEN 1 ELSE 0 END AS IS_GEO_MISSING
FROM
(
SELECT DISTINCT Str_Id
FROM  EDAA_STG.FCT_POCAA_HST_SUMMARY
) AS FACT_DATA_FEED

LEFT  JOIN	(SELECT DISTINCT Str_Id
				FROM EDAA_DW.DIM_GEO
				--WHERE IS_CURR_IND<>0
					) AS GEO
	ON GEO.Str_Id = FACT_DATA_FEED.Str_Id
WHERE  GEO.Str_Id IS NULL

DECLARE @NEXT_GEO_HIST_SK INT
SELECT @NEXT_GEO_HIST_SK =ISNULL(MAX(GEO_HIST_SK),0)   FROM EDAA_DW.DIM_GEO

PRINT('LATEARRIVINGDIMENSION: DIM_GEO LOAD')

IF(@NEXT_GEO_HIST_SK IS NOT NULL)
BEGIN


INSERT INTO EDAA_DW.DIM_GEO
SELECT
		(ROW_NUMBER() OVER (ORDER BY STR_ID)) + @NEXT_GEO_HIST_SK 		AS GEO_HIST_SK
		,(ROW_NUMBER() OVER (ORDER BY STR_ID)) + @NEXT_GEO_HIST_SK  		AS GEO_SK
		,CONVERT(INTEGER,STR_ID)   								 		AS STR_ID
		,CONVERT(VARCHAR(5),'n/a')		STR_NM
		,CONVERT(INTEGER,0)				GROSS_FLR_AREA
		,CONVERT(VARCHAR(5),'n/a')		RGN_NM
		,CONVERT(VARCHAR(5),'n/a')		MKT_NM
		,NULL                    AS		LOC_LNGTD
		,NULL                    AS		LOC_LTTD
		,CONVERT(INTEGER,-1)				STR_CLS_ID
		,CONVERT(VARCHAR(5),'n/a')		STR_CLS_NM
		,CONVERT(VARCHAR(5),'n/a')		LOC_ST_ID
		,CONVERT(VARCHAR(5),'n/a')		LOC_CNTY_ID
		,CONVERT(VARCHAR(5),'n/a')		LOC_CTY
		,CONVERT(VARCHAR(5),'n/a')		LOC_ZP_CODE
		,CONVERT(VARCHAR(5),'n/a')		DIV_ID
		,CONVERT(VARCHAR(5),'n/a')		DIV_NM
		,NULL                    AS		CURR_YR_NEW_STR_IND
		,NULL                    AS		LST_YR_NEW_STR_IND
		,NULL                    AS		TWO_YRS_AGO_NEW_STR_IND
		,NULL                    AS		RGN_ID
		,NULL                    AS		MKT_ID
		,NULL                    AS		STR_OPN_DT
		,NULL                    AS		STR_CLS_DT
		,CONVERT(VARCHAR(5),'n/a')		STR_CTGRY_NM
		,NULL                    AS		STR_ZN_ID
		,CONVERT(VARCHAR(5),'n/a')		STR_ZN_NM
		,NULL                    AS		STR_CMP_CTGRY_ID
		,CONVERT(VARCHAR(5),'n/a')		STR_CMP_CTGRY_DESC
		,CAST('2000-01-01' AS DATE)	    VLD_FROM
		,CAST('2099-01-01' AS DATE)		VLD_TO
		,CAST(1 AS BIT)					IS_CURR_IND
		,CAST(0 AS BIT)					IS_DMY_IND
		,CAST(1 AS BIT)					IS_EMB_IND
		,'New embryo'				    ETL_ACTN
		,@NEW_AUD_SKY					AUD_INS_SK
		,NULL							AUD_UPD_SK
FROM
	(
	SELECT
			DISTINCT STR_ID
	FROM #LATEARRIVINGDIMENSIONFACTRECORDS
	WHERE 	IS_GEO_MISSING = 1
	) AS MISSING_GEO
	WHERE 	NOT EXISTS
	(
	SELECT 1 FROM EDAA_DW.DIM_GEO DIM
	WHERE
	MISSING_GEO.STR_ID = DIM.STR_ID
	)

END

/* Validate Late arriving dimension: DIM_PROD */
PRINT('LATEARRIVINGDIMENSION: DIM_PROD')

IF OBJECT_ID('TEMPDB..#LATEARRIVINGPRODDIMENSIONFACTRECORDS') IS NOT NULL
DROP TABLE #LATEARRIVINGPRODDIMENSIONFACTRECORDS

CREATE TABLE #LATEARRIVINGPRODDIMENSIONFACTRECORDS
WITH (
	DISTRIBUTION = ROUND_ROBIN
	)
AS
SELECT DISTINCT FACT_DATA_FEED.Itm_Sku,
--'' as Fnc_Lvl2_Mprs_Ctgry_Id,
--'' as Fnc_Lvl3_Pky_Id,
CASE WHEN PROD.Itm_Sku IS NULL THEN 1 ELSE 0 END AS IS_PROD_MISSING
FROM
(
SELECT DISTINCT Itm_Sku
FROM  EDAA_STG.FCT_MPRS_PRODUCT_RCV_SUMMARY
) AS FACT_DATA_FEED

LEFT  JOIN	(SELECT DISTINCT Itm_Sku--, Fnc_Lvl2_Mprs_Ctgry_Id
				FROM EDAA_DW.DIM_PROD
			---	WHERE IS_CURR_IND<>0
					) AS PROD
	ON PROD.Itm_Sku = FACT_DATA_FEED.Itm_Sku
	WHERE  PROD.Itm_Sku IS NULL


DECLARE @NEXT_PROD_HIST_SK INT
SELECT @NEXT_PROD_HIST_SK =ISNULL(MAX(PROD_HIST_SK),0)   FROM EDAA_DW.DIM_PROD

PRINT('LATEARRIVINGDIMENSION: DIM_PROD LOAD')

IF(@NEXT_PROD_HIST_SK IS NOT NULL)
BEGIN


INSERT INTO EDAA_DW.DIM_PROD

SELECT
            (ROW_NUMBER() OVER (ORDER BY Itm_Sku)) + @NEXT_PROD_HIST_SK 	AS PROD_HIST_SK
            ,(ROW_NUMBER() OVER (ORDER BY Itm_Sku)) + @NEXT_PROD_HIST_SK  	AS PROD_SK
            ,CONVERT(VARCHAR(150),MISSING_PROD.Itm_Sku)   					AS Itm_Sku
            ,CONVERT(VARCHAR(255),'n/a')        Itm_Nm
            ,CONVERT(VARCHAR(10),'n/a')        Lvl1_Prod_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl1_Prod_Desc
            ,CONVERT(VARCHAR(20),'n/a')        Lvl2_Prod_Clsfctn_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl2_Prod_Clsfctn_Desc
            ,CONVERT(VARCHAR(10),'n/a')        Lvl3_Prod_Sub_Ctgry_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl3_Prod_Sub_Ctgry_Desc
            ,CONVERT(VARCHAR(10),'n/a')        Lvl4_Prod_Ctgry_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl4_Prod_Ctgry_Desc
            ,CONVERT(VARCHAR(10),'n/a')        Lvl5_Bsns_Sgmt_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl5_Bsns_Sgmt_Desc
            ,CONVERT(VARCHAR(10),'n/a')        Lvl6_MDS_Area_Id
            ,CONVERT(VARCHAR(80),'n/a')        Lvl6_MDS_Area_Desc
            ,CONVERT(VARCHAR(10),'n/a')        Fnc_Lvl1_Prod_Ctgry_Id
            ,CONVERT(VARCHAR(80),'n/a')        Fnc_Lvl1_Prod_Ctgry_Desc
            ,-1							       Fnc_Lvl2_Mprs_Ctgry_Id--not present in staging table
            ,CONVERT(VARCHAR(80),'n/a')        Fnc_Lvl2_Mprs_Ctgry_Desc
            ,-1								   Fnc_Lvl3_Pky_Id--not present in staging table
            ,CONVERT(VARCHAR(80),'n/a')        Fnc_Lvl3_Pky_Desc
            ,CONVERT(VARCHAR(15),'n/a')        Fnc_Lvl4_Area_Id
            ,CONVERT(VARCHAR(80),'n/a')        Fnc_Lvl4_Area_Desc
            ,NULL   					AS 	  Str_Area_Dtl_Id
            ,CONVERT(VARCHAR(50),'n/a')        Str_Area_Dtl_Desc
            ,NULL     					AS 	  Str_Area_Summ_Id
            ,CONVERT(VARCHAR(50),'n/a')        Str_Area_Summ_Desc
            ,NULL   					AS 	  Str_Dept_Dtl_Id
            ,CONVERT(VARCHAR(50),'n/a')        Str_Dept_Dtl_Desc
            ,NULL   					AS 	  Str_Dept_Summ_Id
            ,CONVERT(VARCHAR(50),'n/a')        Str_Dept_Summ_Desc
            ,CAST('2000-01-01' AS DATE) AS    Vld_Frm
            ,CAST('2099-01-01' AS DATE) AS    Vld_To
            ,CAST(1 AS BIT)					  Is_Curr_Ind
            ,CAST(0 AS BIT)					  Is_Dmy_Ind
            ,CAST(1 AS BIT)					  Is_Emb_Ind
            ,'New embryo'					  Etl_Actn
            ,@NEW_AUD_SKY					  Aud_Ins_sk
            ,NULL					          Aud_Upd_sk
			,CAST(1 AS BIT) 		  		  Itm_Prim_Ind
			,CONVERT(VARCHAR(500),'n/a') 		  Prod_Size_Desc
			,CONVERT(VARCHAR(250),'n/a') 		  Brnd_Nm
			,CONVERT(VARCHAR(250),'n/a') 		  Brnd_Desc
			,CONVERT(VARCHAR(250),'n/a') 		  Brnd_Ctgry
			,CONVERT(VARCHAR(500),'n/a') 		  Prod_Desc
			,CONVERT(VARCHAR(500),'n/a') 		  Prod_Desc_Note
			,CAST('2099-12-31' AS DATE) AS    Outdate
			,NULL						AS 	  Byr_Id
			,CONVERT(VARCHAR(100),'n/a') 		  Prod_Sts
			,CONVERT(VARCHAR(500),'n/a') 		  Prod_Sts_Note
			,NULL		 		 		AS 	  Vdr_Id
			,NULL AS Sku_Ct
FROM
	(
	SELECT
			DISTINCT Itm_Sku--, Fnc_Lvl2_Mprs_Ctgry_Id
	FROM #LATEARRIVINGPRODDIMENSIONFACTRECORDS
	WHERE 	IS_PROD_MISSING = 1
	) AS MISSING_PROD
	WHERE 	NOT EXISTS
	(
	SELECT 1 FROM EDAA_DW.DIM_PROD DIM_PROD
	WHERE
	MISSING_PROD.Itm_Sku = DIM_PROD.Itm_Sku
	)

END

INSERT INTO EDAA_DW.FCT_POCAA_HST_SUMMARY
(
		Dt_Sk,
		Geo_Hist_Sk,
		Prod_Hist_Sk,
		SwellAndDefectiveAlw,
		Bat_Prcs_Tms,
		Bat_Prcs_Id,
		Aud_Ins_Sk,
		Aud_Upd_Sk
)
SELECT
		ISNULL(CAL.Dt_Sk,-1) AS Dt_Sk,
		ISNULL(GEO.Geo_Hist_Sk,-1) AS Geo_Hist_Sk,
		ISNULL(PROD.Prod_Hist_Sk,-1) AS Prod_Hist_Sk,
		POHST.SwellAndDefectiveAlw,
		POHST.Bat_Prcs_Tms,
		POHST.Bat_Prcs_Id,
		@NEW_AUD_SKY AS Aud_Ins_Sk,
		NULL AS Aud_Upd_Sk

FROM  EDAA_STG.FCT_POCAA_HST_SUMMARY POHST
LEFT JOIN  EDAA_DW.DIM_GEO GEO ON GEO.Str_Id = POHST.Str_Id AND GEO.IS_Curr_Ind=1
LEFT JOIN  EDAA_DW.DIM_PROD PROD ON PROD.Itm_Sku=POHST.Itm_Sku AND PROD.IS_Curr_Ind=1
LEFT JOIN  EDAA_DW.Dim_Dly_Cal CAL ON POHST.Dt_Sk=CAL.Dt_Sk

BEGIN
SELECT @NBR_OF_RW_ISRT = COUNT_BIG(1)  FROM EDAA_DW.FCT_MPRS_GDSD_RCV_DTL WHERE Aud_Ins_Sk = @NEW_AUD_SKY
SELECT @NBR_OF_RW_UDT  = COUNT_BIG(1)  FROM EDAA_DW.FCT_MPRS_GDSD_RCV_DTL WHERE Aud_Upd_Sk = @NEW_AUD_SKY

------------ UPDATE Statistics-------

UPDATE STATISTICS  EDAA_DW.FCT_POCAA_HST_SUMMARY;

END

/*Audit Log End*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_CNTL.SP_STG_DW_FCT_MPRS_RCV_DTL'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------



EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change


   THROW;
END CATCH


GO
