/****** Object:  StoredProcedure [EDAA_ETL].[SP_STG_DW_REF_VISITR_TYP_TABLELOAD]    Script Date: 3/3/2023 3:18:44 PM ******/
CREATE PROC [EDAA_ETL].[SP_STG_DW_REF_VISITR_TYP_TABLELOAD] AS


BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT BIGINT
DECLARE @NBR_OF_RW_UDT BIGINT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR  = 'EDAA_DW',
										@EXEC_JOB  = 'SP_STG_DW_REF_VISITR_TYP_TABLELOAD',
										@SRC_ENTY  = '[EDAA_STG].[REF_VISITR_TYP]',
										@TGT_ENTY  = '[EDAA_DW].[REF_VISITR_TYP]',
										@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT


;WITH update_data
  AS (SELECT
        A.VISITR_TYP_ID					    AS VISITR_TYP_ID,
		A.VISITR_TYP_NM					    AS VISITR_TYP_NM,
		A.VISITR_TYP_DESC					AS VISITR_TYP_DESC,
		A.UPD_TMS 							AS UPD_TMS,
		A.UPD_BY 							AS UPD_BY

  FROM [EDAA_STG].[REF_VISITR_TYP] AS A)

  --UPDATE [EDAA_DW].[REF_VISITR_TYP]
  UPDATE [EDAA_DW].[REF_VISITR_TYP]
  SET VISITR_TYP_NM = src.VISITR_TYP_NM,
      VISITR_TYP_DESC = src.VISITR_TYP_DESC,
      UPD_TMS = src.UPD_TMS,
      UPD_BY = src.UPD_BY,
      AUD_UPD_SK = @NEW_AUD_SKY
  FROM [EDAA_DW].[REF_VISITR_TYP] tgt, update_data src
  WHERE tgt.VISITR_TYP_ID = src.VISITR_TYP_ID;

  PRINT ('-- Update records complete for VISITR_TYP_ID --')

  ;WITH insert_data
  AS (SELECT
        A.VISITR_TYP_ID					    AS VISITR_TYP_ID,
		A.VISITR_TYP_NM					    AS VISITR_TYP_NM,
		A.VISITR_TYP_DESC					AS VISITR_TYP_DESC,
		A.UPD_TMS 							AS UPD_TMS,
		A.UPD_BY 							AS UPD_BY,
		@NEW_AUD_SKY AS AUD_INS_SK,
        NULL AS AUD_UPD_SK

  FROM [EDAA_STG].[REF_VISITR_TYP] AS A)

  -- INSERT DATA into [EDAA_DW].[REF_VISITR_TYP]
  INSERT INTO [EDAA_DW].[REF_VISITR_TYP]
  (
	VISITR_TYP_ID,
    VISITR_TYP_NM,
    VISITR_TYP_DESC,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
)
    SELECT
      *
    FROM insert_data A
    WHERE A.VISITR_TYP_ID NOT IN (SELECT
      distinct B.VISITR_TYP_ID
    FROM [EDAA_DW].[REF_VISITR_TYP] B)
  ;

  PRINT ('---DW load complete---');

  UPDATE STATISTICS [EDAA_DW].[REF_VISITR_TYP]

BEGIN

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM [EDAA_DW].[REF_VISITR_TYP] WHERE AUD_INS_SK = @NEW_AUD_SKY
print(@NBR_OF_RW_ISRT)

SELECT @NBR_OF_RW_UDT = COUNT(1)  FROM [EDAA_DW].[REF_VISITR_TYP] WHERE AUD_UPD_SK = @NEW_AUD_SKY
print(@NBR_OF_RW_UDT)

END


/*AUDIT LOG END*/

EXEC [EDAA_CNTL].[SP_AUDIT_DATA_LOAD_END] @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[SP_STG_DW_REF_VISITR_TYP_TABLELOAD]'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------

EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change
 THROW;

END CATCH
GO
