/****** Object:  StoredProcedure [EDAA_ETL].[SP_STG_DW_REF_RF_LNK_TYP_TABLELOAD]    Script Date: 3/9/2023 6:25:57 PM ******/
CREATE PROC [EDAA_ETL].[SP_STG_DW_REF_RF_LNK_TYP_TABLELOAD] AS


BEGIN TRY

/*DATAMART AUDITING VARIABLES*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT BIGINT
DECLARE @NBR_OF_RW_UDT BIGINT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)

/*AUDIT LOG START*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START @EXEC_LYR  = 'EDAA_DW',
										@EXEC_JOB  = 'SP_STG_DW_REF_RF_LNK_TYP_TABLELOAD',
										@SRC_ENTY  = '[EDAA_STG].[REF_RF_LNK_TYP]',
										@TGT_ENTY  = '[EDAA_DW].[REF_RF_LNK_TYP]',
										@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT



print('---Finding update records---');

	;WITH update_data
  AS (SELECT
    A.RF_LNK_TYP_ID AS RF_LNK_TYP_ID,
    A.RF_LNK_TYP_NM AS RF_LNK_TYP_NM,
    A.RF_LNK_TYP_DESC AS RF_LNK_TYP_DESC,
    A.UPD_TMS AS UPD_TMS,
	A.UPD_BY AS UPD_BY
	FROM [EDAA_STG].[REF_RF_LNK_TYP] AS A)

	UPDATE [EDAA_DW].[REF_RF_LNK_TYP]
  SET
      RF_LNK_TYP_NM = src.RF_LNK_TYP_NM,
      RF_LNK_TYP_DESC = src.RF_LNK_TYP_DESC,
      UPD_TMS = src.UPD_TMS,
      UPD_BY = src.UPD_BY,
      AUD_UPD_SK = @NEW_AUD_SKY
  FROM [EDAA_DW].[REF_RF_LNK_TYP] tgt, update_data src
  WHERE tgt.RF_LNK_TYP_ID = src.RF_LNK_TYP_ID;

print('---Finding insert records---');
;WITH insert_data
  AS (SELECT
    A.RF_LNK_TYP_ID AS RF_LNK_TYP_ID,
    A.RF_LNK_TYP_NM AS RF_LNK_TYP_NM,
    A.RF_LNK_TYP_DESC AS RF_LNK_TYP_DESC,
    A.UPD_TMS AS UPD_TMS,
	A.UPD_BY AS UPD_BY,
	@NEW_AUD_SKY AS AUD_INS_SK,
	NULL AS AUD_UPD_SK
	FROM [EDAA_STG].[REF_RF_LNK_TYP] AS A)

INSERT INTO [EDAA_DW].[REF_RF_LNK_TYP]
(
	RF_LNK_TYP_ID,
	RF_LNK_TYP_NM,
	RF_LNK_TYP_DESC,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
)
SELECT
*
from insert_data A where A.RF_LNK_TYP_ID not in (select distinct B.RF_LNK_TYP_ID from [EDAA_DW].[REF_RF_LNK_TYP] B);


  print('---DW load completed---');

  UPDATE STATISTICS [EDAA_DW].[REF_RF_LNK_TYP]


BEGIN

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM [EDAA_DW].[REF_RF_LNK_TYP] WHERE AUD_INS_SK = @NEW_AUD_SKY
print(@NBR_OF_RW_ISRT)

SELECT @NBR_OF_RW_UDT = COUNT(1)  FROM [EDAA_DW].[REF_RF_LNK_TYP] WHERE AUD_UPD_SK = @NEW_AUD_SKY
print(@NBR_OF_RW_UDT)

END


/*AUDIT LOG END*/
EXEC [EDAA_CNTL].[SP_AUDIT_DATA_LOAD_END] @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT, @NBR_OF_RW_UDT = @NBR_OF_RW_UDT

END TRY

BEGIN CATCH
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = '[EDAA_ETL].[SP_STG_DW_REF_RF_LNK_TYP_TABLELOAD]'
DECLARE @ERROR_LINE AS INT;
DECLARE @ERROR_MSG AS NVARCHAR(max);

 SELECT
      @ERROR_LINE =  ERROR_NUMBER()
      ,@ERROR_MSG = ERROR_MESSAGE();
--------- Log execution error ----------

EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;

-- Detect the change
 THROW;

END CATCH
