CREATE TABLE [EDAA_DW].[ANLT_SVC_EMP_UT_ROLE_INF]
(
	[MJR_EMP_ID] [nvarchar](4000) NULL,
	[UT_ID] [int] NULL,
	[ROLE_TYP_NM] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
