CREATE TABLE [EDAA_DW].[DIM_DLY_CAL] (
    [Dt_Sk]                     INT           NOT NULL,
    [Cal_Dt]                    DATE          NOT NULL,
    [Cal_Dt_Nm]                 VARCHAR (12)  NULL,
    [Lst_Yr_Fsc_Dt]             DATE          NULL,
    [Lst_Yr_Hldy_Dt]            DATE          NULL,
    [Hldy_Nm]                   VARCHAR (255) NULL,
    [Lst_Yr_Cal_Dt]             DATE          NULL,
    [Wknd_Dt]                   DATE          NULL,
    [Lst_Yr_Wknd_Dt]            DATE          NULL,
    [Lst_Yr_Fsc_Wknd_Dt]        DATE          NULL,
    [Cal_Yr]                    SMALLINT      NULL,
    [Dy_Of_Wk_Nm]               VARCHAR (10)  NULL,
    [Fsc_Yr]                    SMALLINT      NULL,
    [Fsc_Yr_Bgn_Dt]             DATE          NULL,
    [Fsc_Yr_End_Dt]             DATE          NULL,
    [Fsc_Qtr_Nm]                VARCHAR (5)   NULL,
    [Fsc_Qtr_Bgn_Dt]            DATE          NULL,
    [Fsc_Qtr_End_Dt]            DATE          NULL,
    [Fsc_Prd_Nm]                VARCHAR (6)   NULL,
    [Fsc_Prd_Seq_Id]            INT           NULL,
    [Fsc_Qtr_Seq_Id]            INT           NULL,
    [Cal_Typ_Ordr_Id]           SMALLINT      NULL,
    [Cal_Dy_Of_Wk_Id]           SMALLINT      NULL,
    [Cal_Dy_Of_Wk_Nm]           VARCHAR (10)  NULL,
    [Cal_Mon_Of_Yr_Nm]          VARCHAR (10)  NULL,
    [Cal_Mon_Of_The_Yr_Shrt_Nm] VARCHAR (3)   NULL,
    [Lst_Yr_Fsc_Dt_Sk]          INT           NULL,
    [Lst_Yr_Cal_Dt_Sk]          INT           NULL,
    [Lst_Yr_Hldy_Dt_Sk]         INT           NULL,
    [Etl_Actn]                  VARCHAR (20)  NULL,
    [Aud_Ins_Sk]                BIGINT        NULL,
    [Aud_Upd_Sk]                BIGINT        NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);
