CREATE TABLE [EDAA_DW].[DIM_LB_MARK]
(
	[LB_SK] [int] IDENTITY(1,1) NOT NULL,
	[LB_MARK_ID] [int] NOT NULL,
	[LB_MARK_NM] [varchar](50) NULL,
	[LB_MARK_DSC] [varchar](2000) NULL,
	[LB_MARK_IMG] [varchar](2000) NULL,
	[AUD_INS_SK] [int] NULL,
	[AUD_UPD_SK] [int] NULL,
 CONSTRAINT [PK_DIM_LB_MARK] PRIMARY KEY NONCLUSTERED
	(
		[LB_MARK_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
