/****** Object:  Table [EDAA_DW].[DIM_PROD]    Script Date: 8/25/2021 2:26:00 AM ******/
CREATE TABLE [EDAA_DW].[DIM_PROD]
(
	[Prod_Hist_Sk] [bigint] NOT NULL,
	[Prod_Sk] [int] NOT NULL,
	[Itm_Sku] [decimal](18, 0) NOT NULL,
	[Itm_Nm] [varchar](255) NULL,
	[Lvl1_Prod_Id] [varchar](10) NULL,
	[Lvl1_Prod_Desc] [varchar](80) NULL,
	[Lvl2_Prod_Clsfctn_Id] [varchar](20) NULL,
	[Lvl2_Prod_Clsfctn_Desc] [varchar](80) NULL,
	[Lvl3_Prod_Sub_Ctgry_Id] [varchar](10) NULL,
	[Lvl3_Prod_Sub_Ctgry_Desc] [varchar](80) NULL,
	[Lvl4_Prod_Ctgry_Id] [varchar](10) NULL,
	[Lvl4_Prod_Ctgry_Desc] [varchar](80) NULL,
	[Lvl5_Bsns_Sgmt_Id] [varchar](10) NULL,
	[Lvl5_Bsns_Sgmt_Desc] [varchar](80) NULL,
	[Lvl6_Mds_Area_Id] [varchar](10) NULL,
	[Lvl6_Mds_Area_Desc] [varchar](80) NULL,
	[Fnc_Lvl1_Prod_Ctgry_Id] [varchar](10) NULL,
	[Fnc_Lvl1_Prod_Ctgry_Desc] [varchar](80) NULL,
	[Fnc_Lvl2_Mprs_Ctgry_Id] [smallint] NULL,
	[Fnc_Lvl2_Mprs_Ctgry_Desc] [varchar](80) NULL,
	[Fnc_Lvl3_Pky_Id] [smallint] NULL,
	[Fnc_Lvl3_Pky_Desc] [varchar](80) NULL,
	[Fnc_Lvl4_Area_Id] [varchar](15) NULL,
	[Fnc_Lvl4_Area_Desc] [varchar](80) NULL,
	[Str_Area_Dtl_Id] [int] NULL,
	[Str_Area_Dtl_Desc] [varchar](50) NULL,
	[Str_Area_Summ_Id] [int] NULL,
	[Str_Area_Summ_Desc] [varchar](50) NULL,
	[Str_Dept_Dtl_Id] [int] NULL,
	[Str_Dept_Dtl_Desc] [varchar](50) NULL,
	[Str_Dept_Summ_Id] [int] NULL,
	[Str_Dept_Summ_Desc] [varchar](50) NULL,
	[Vld_Frm] [date] NULL,
	[Vld_To] [date] NULL,
	[Is_Curr_Ind] [bit] NULL,
	[Is_Dmy_Ind] [bit] NULL,
	[Is_Emb_Ind] [bit] NULL,
	[Etl_Actn] [varchar](20) NULL,
	[Aud_Ins_Sk] [bigint] NULL,
	[Aud_Upd_Sk] [bigint] NULL,
	[Itm_Prim_Ind] [char](1) NULL,
	[Prod_Size_Desc] [varchar](500) NULL,
	[Brnd_Nm] [varchar](250) NULL,
	[Brnd_Desc] [varchar](250) NULL,
	[Brnd_Ctgry] [varchar](250) NULL,
	[Prod_Desc] [varchar](500) NULL,
	[Prod_Desc_Note] [varchar](500) NULL,
	[Outdate] [date] NULL,
	[Byr_Id] [int] NULL,
	[Prod_Sts] [varchar](100) NULL,
	[Prod_Sts_Note] [varchar](500) NULL,
	[Vdr_Id] [int] NULL,
	[Sku_Ct] [char](3) NULL

)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
);
