CREATE TABLE [EDAA_DW].[DIM_GEO] (
    [Geo_Hist_Sk]             INT            NOT NULL,
    [Geo_Sk]                  INT            NOT NULL,
    [Str_Id]                  INT            NOT NULL,
    [Str_Nm]                  VARCHAR (150)  NULL,
    [Gross_Flr_Area]          VARCHAR (150)  NULL,
    [Rgn_Nm]                  VARCHAR (100)  NULL,
    [Mkt_Nm]                  VARCHAR (35)   NULL,
    [Loc_Lngtd]               DECIMAL (9, 6) NULL,
    [Loc_Lttd]                DECIMAL (9, 6) NULL,
    [Str_Cls_Id]              SMALLINT       NULL,
    [Str_Cls_Nm]              VARCHAR (15)   NULL,
    [Loc_St_Id]               VARCHAR (3)    NULL,
    [Loc_Cnty_Id]             VARCHAR (20)   NULL,
    [Loc_Cty]                 VARCHAR (50)   NULL,
    [Loc_Zp_Code]             VARCHAR (9)    NULL,
    [Div_Id]                  VARCHAR (3)    NULL,
    [Div_Nm]                  VARCHAR (40)   NULL,
    [Curr_Yr_New_Str_Ind]     SMALLINT       NULL,
    [Lst_Yr_New_Str_Ind]      SMALLINT       NULL,
    [Two_Yrs_Ago_New_Str_Ind] SMALLINT       NULL,
    [Rgn_Id]                  SMALLINT       NULL,
    [Mkt_Id]                  SMALLINT       NULL,
    [Str_Opn_Dt]              DATE           NULL,
    [Str_Cls_Dt]              DATE           NULL,
    [Str_Ctgry_Nm]            VARCHAR (50)   NULL,
    [Str_Zn_Id]               SMALLINT       NULL,
    [Str_Zn_Nm]               VARCHAR (15)   NULL,
    [Str_Cmp_Ctgry_Id]        INT            NULL,
    [Str_Cmp_Ctgry_Desc]      VARCHAR (15)   NULL,
    [Vld_Frm]                 DATE           NULL,
    [Vld_To]                  DATE           NULL,
    [Is_Curr_Ind]             BIT            NULL,
    [Is_Dmy_Ind]              BIT            NULL,
    [Is_Emb_Ind]              BIT            NULL,
    [Etl_Actn]                VARCHAR (20)   NULL,
    [Aud_Ins_Sk]              BIGINT         NULL,
    [Aud_Upd_Sk]              BIGINT         NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);
