CREATE TABLE [EDAA_DW].[DIM_INGR]
(
	[INGR_SK] [int] IDENTITY(1,1) NOT NULL,
	[INGR_ID] [varchar](64) NOT NULL,
	[INGR_NM] [varchar](4000) NOT NULL,
	[INGR_DSC] [varchar](4000) NOT NULL,
	[AUD_INS_SK] [int] NULL,
	[AUD_UPD_SK] [int] NULL,
 CONSTRAINT [PK_DIM_INGR_ID] PRIMARY KEY NONCLUSTERED
	(
		[INGR_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
