CREATE TABLE [EDAA_DW].[DIM_ITM_LB_MARK]
(
	[ITM_LB_SK] [int] IDENTITY(1,1) NOT NULL,
	[LB_MARK_ID] [int] NOT NULL,
	[PROD_SK] [int] NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[UPC_TYP_NM] [varchar](10) NULL,
	[P_LB_VRS_ID] [varchar](2000) NULL,
	[LB_MARK_NT] [varchar](2000) NULL,
	[AUD_INS_SK] [int] NULL,
	[AUD_UPD_SK] [int] NULL,
 CONSTRAINT [PK_DIM_ITM_LB_MARK] PRIMARY KEY NONCLUSTERED
	(
		[LB_MARK_ID] ASC,
		[ITM_SKU] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX
	(
		[LB_MARK_ID] ASC
	)
)
