CREATE TABLE [EDAA_DW].[DIM_LB_MARK_GRP]
(
	[LB_GRP_SK] [int] IDENTITY(1,1) NOT NULL,
	[LB_MARK_GRP_ID] [int] NOT NULL,
	[LB_MARK_ID] [int] NOT NULL,
	[LB_MARK_GRP_NM] [varchar](2000) NULL,
	[AUD_INS_SK] [int] NULL,
	[AUD_UPD_SK] [int] NULL,
 CONSTRAINT [PK_DIM_LB_MARK_GRP] PRIMARY KEY NONCLUSTERED
	(
		[LB_MARK_GRP_ID] ASC,
		[LB_MARK_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
