CREATE TABLE [EDAA_DW].[DIM_ITM_INGR]
(
	[ITM_SK] [int] IDENTITY(1,1) NOT NULL,
	[INGR_SK] [int] NULL,
	[PROD_SK] [int] NULL,
	[INGR_ID] [varchar](64) NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[UPC_TYP_NM] [varchar](10) NULL,
	[P_INGR_PER_STRT_DT] [date] NULL,
	[P_INGR_PER_END_DT] [date] NULL,
	[AUD_INS_SK] [int] NULL,
	[AUD_UPD_SK] [int] NULL,
 CONSTRAINT [PK_DIM_ITEM_INGR] PRIMARY KEY NONCLUSTERED
	(
		[INGR_ID] ASC,
		[ITM_SKU] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = HASH ( [ITM_SKU] ),
	CLUSTERED COLUMNSTORE INDEX
)
