CREATE TABLE [EDAA_DW].[FCT_ITM_FBRC]
(
	[Prod_Hist_Sk] [bigint] NOT NULL,
	[ITM_SKU_ID] [varchar](20) NOT NULL,
	[FBRC_ID] [int] NOT NULL,
	[PROD_ID] [varchar](10) NOT NULL,
	[GOLD_RCD_ID] [varchar](128) NOT NULL,
	[UDT_TMS] [datetime] NOT NULL,
	[UDT_BY] [varchar](256) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_FCT_ITM_FBRC] PRIMARY KEY NONCLUSTERED
	(
		[FBRC_ID] ASC,
		[Prod_Hist_Sk] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = HASH ( [PROD_ID] ),
	CLUSTERED COLUMNSTORE INDEX
)
