CREATE TABLE [EDAA_DW].[FCT_WPG_VISIT]
(
	[WPG_VISIT_STRT_TMS] [datetime] NULL,
	[EXCL_HIT_ID] [smallint] NULL,
	[DSG_MKT_AREA_ID] [int] NULL,
	[WPG_CHL_NM] [varchar](400) NULL,
	[CLCK_MAP_LNK] [varchar](500) NULL,
	[CLCK_MAP_PG] [varchar](500) NULL,
	[CLCK_MAP_RGN] [varchar](255) NULL,
	[WPG_NM] [varchar](400) NULL,
	[WPG_FN_NM] [varchar](400) NULL,
	[DSG_STR_ID] [smallint] NULL,
	[DSG_STR_TXT] [varchar](4000) NULL,
	[CUST_ACCT_ID] [bigint] NULL,
	[CKI_ID] [varchar](200) NULL,
	[INTRL_ADV_CMPN_TAG] [varchar](400) NULL,
	[DGTL_CPN_ID] [bigint] NULL,
	[DGTL_ORDR_ID] [bigint] NULL,
	[DGTL_SRC_ID] [smallint] NULL,
	[SRCH_STRNG_TXT] [varchar](4000) NULL,
	[SRCH_RSUL_SORT_TXT] [varchar](4000) NULL,
	[SRCH_RSUL_FLTR_TXT] [varchar](4000) NULL,
	[VISITR_TYP_ID] [smallint] NULL,
	[ADD_TO_CAT_LOC] [varchar](250) NULL,
	[CLCTN_NM] [varchar](400) NULL,
	[EXTRL_ADV_CMPN_TAG] [varchar](400) NULL,
	[ITM_SKU] [varchar](50) NULL,
	[SRCH_RSUL_RNK_VAL] [smallint] NULL,
	[FLYR_TYP_NM] [varchar](400) NULL,
	[FLYR_INTRL_RUN_ID] [int] NULL,
	[PROMO_OFR_ID] [bigint] NULL,
	[PROMO_OFR_TXT] [varchar](4000) NULL,
	[WKLY_ADV_DGTL_CPN_ID] [bigint] NULL,
	[CAT_ID] [bigint] NULL,
	[CAT_TXT] [varchar](4000) NULL,
	[SRCH_MTHD_NM] [varchar](400) NULL,
	[PLN_PKP_TM_SLT] [varchar](400) NULL,
	[FST_AVL_TM_SLT] [varchar](400) NULL,
	[PLN_PKP_DT] [date] NULL,
	[SRCH_RSUL_CNT] [int] NULL,
	[CLN_SRCH_STRNG_TXT] [varchar](4000) NULL,
	[FST_AVL_TM_SLT_DT] [date] NULL,
	[CLLT_LVL] [varchar](400) NULL,
	[ADD_TO_CAT_PG_NM] [varchar](400) NULL,
	[HM_STR_ID] [smallint] NULL,
	[HM_STR_TXT] [varchar](4000) NULL,
	[CRSL_PROD_IMPSN] [varchar](500) NULL,
	[MOB_APL_HM_SC_TYP] [varchar](30) NULL,
	[LND_PG_CMPN_TAG] [varchar](500) NULL,
	[MKT_CMPN_TAG] [varchar](500) NULL,
	[CPN_LOC] [varchar](100) NULL,
	[ADD_TO_CAT_CPN_INF] [varchar](400) NULL,
	[MOB_APL_VSN_ID] [varchar](255) NULL,
	[DY_SNCE_LST_USE] [smallint] NULL,
	[MOB_DVC_NM] [varchar](400) NULL,
	[MOB_OPR_SYS_VRSN] [varchar](100) NULL,
	[EVNT_RSP_CD] [smallint] NULL,
	[EVNT_NM] [varchar](400) NULL,
	[WPG_URL] [varchar](500) NULL,
	[APL_TYP_NM] [varchar](400) NULL,
	[WEB__NM] [varchar](400) NULL,
	[RF_PG_URL] [varchar](500) NULL,
	[SRCH_ENG_ID] [int] NOT NULL,
	[RF_DMN_NM] [varchar](400) NULL,
	[RF_LNK_TYP_ID] [smallint] NOT NULL,
	[SRCH_ENG_PG_NUM] [smallint] NULL,
	[USR_AGNT_DESC] [varchar](4000) NULL,
	[VISITR_LST_TCH_ATTR] [varchar](400) NULL,
	[VISITR_LST_TCH_ID] [smallint] NULL,
	[VISITR_FST_TCH_ATTR] [varchar](400) NULL,
	[VISITR_FST_TCH_ID] [smallint] NULL,
	[VISITR_INST_EVNT_IND] [bit] NULL,
	[NW_VISITR_IND] [bit] NULL,
	[VISITR_NUM] [int] NULL,
	[VISIT_PG_NUM] [int] NOT NULL,
	[SESN_ID] [varchar](255) NOT NULL,
	[MSTR_CMPN_ID] [varchar](255) NULL,
	[UPD_TMS] [datetime] NOT NULL,
	[UPD_BY] [varchar](64) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_FCT_WPG_VISIT] PRIMARY KEY NONCLUSTERED
	(
		[VISIT_PG_NUM] ASC,
		[SESN_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = HASH ( [SESN_ID] ),
	CLUSTERED COLUMNSTORE INDEX
)
