CREATE TABLE [EDAA_DW].[FCT_WSTE_VISIT]
(
	[WEB_SESN_STRT_TMS] [datetime] NULL,
	[VISIT_NUM] [int] NULL,
	[SESN_ID] [varchar](255) NOT NULL,
	[UPD_TMS] [datetime] NOT NULL,
	[UPD_BY] [varchar](64) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_FCT_WSTE_VISIT] PRIMARY KEY NONCLUSTERED
	(
		[SESN_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = HASH ( [SESN_ID] ),
	CLUSTERED COLUMNSTORE INDEX
)
