CREATE TABLE [EDAA_DW].[FCT_HRLY_PROD_CURR_YR_SLS] (
    [Dt_Tm_Hr]                     DATETIME        NOT NULL,
    [Geo_Hist_Sk]                  INT             NOT NULL,
    [Prod_Hist_Sk]                 BIGINT          NOT NULL,
    [Dt_Sk]                        INT             NOT NULL,
    [Str_Id]                       INT             NOT NULL,
    [Sls_Amt]                      DECIMAL (11, 2) NULL,
    [Prm_To_Prm_Drct_Mgn_Amt]      DECIMAL (11, 4) NULL,
    [Sls_Qty]                      DECIMAL (9)     NULL,
    [Prm_To_Sls_Amt]               DECIMAL (11, 2) NULL,
    [Prm_To_Sls_Drct_Mgn_Amt]      DECIMAL (11, 4) NULL,
    [Prm_To_Clrnc_Drct_Mgn_Amt]    DECIMAL (11, 4) NULL,
    [Scn_Bsd_Trdng_Ind]            CHAR (1)        NULL,
    [Mprs_Src_Ctgry]               CHAR (1)        NULL,
    [Mprs_Prcs_Id]                 CHAR (1)        NULL,
    [Mprs_Ctgry_Id]                SMALLINT        NULL,
    [Fnc_Lvl3_Pky_Id]              SMALLINT        NULL,
    [Str_Sls_Key_Ind]              SMALLINT        NULL,
    [Prod_Drct_Mgn_Ind]            CHAR (1)        NULL,
    [Wgtd_Qty]                     DECIMAL (8, 2)  NULL,
    [Prm_To_Sls_Qty]               DECIMAL (9)     NULL,
    [Prm_To_Sls_Wgtd_Qty]          DECIMAL (8, 2)  NULL,
    [Prm_To_Sls_Mkdn_Amt]          DECIMAL (9, 2)  NULL,
    [Prm_To_Clrnc_Amt]             DECIMAL (11, 2) NULL,
    [Prm_To_Clrnc_Qty]             DECIMAL (9)     NULL,
    [Prm_To_Clrnc_Wgtd_Qty]        DECIMAL (8, 2)  NULL,
    [Prm_To_Clrnc_Mkdn_Amt]        DECIMAL (9, 2)  NULL,
    [Cogs_Fnc_Chrg_Amt]            DECIMAL (11, 4) NULL,
    [Cogs_Fnc_Cr_Amt]              DECIMAL (11, 4) NULL,
    [Cogs_Strge_Chrg_Amt]          DECIMAL (11, 4) NULL,
    [Cogs_Frt_Amt]                 DECIMAL (11, 4) NULL,
    [Cogs_Dist_Fclt_Hdl_Amt]       DECIMAL (11, 4) NULL,
    [Str_Hdl_Mrkng_Amt]            DECIMAL (11, 4) NULL,
    [Str_Hdl_Rcvng_Amt]            DECIMAL (11, 4) NULL,
    [Str_Hdl_Chckng_Amt]           DECIMAL (11, 4) NULL,
    [Str_Hdl_Stckng_Amt]           DECIMAL (11, 4) NULL,
    [Edi_Prm_To_Prm_Appld_Qty]     DECIMAL (9)     NULL,
    [Edi_Prm_To_Prm_Appld_Wgt_Qty] DECIMAL (8, 2)  NULL,
    [Dgtl_Cst_Ctgry]               VARCHAR (3)     NULL,
    [Aud_Ins_Sk]                   BIGINT          NULL,
    [Aud_Upd_Sk]                   BIGINT          NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Str_Id]));
