CREATE TABLE [EDAA_DW].[REF_SRCH_ENGN]
(
	[SRCH_ENG_ID] [int] NOT NULL,
	[SRCH_ENG_NM] [varchar](128) NULL,
	[SRCH_ENG_DESC] [varchar](512) NULL,
	[SRCH_ENG_URL] [varchar](2083) NULL,
	[UPD_TMS] [datetime] NOT NULL,
	[UPD_BY] [varchar](64) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_SRCH_ENGN] PRIMARY KEY NONCLUSTERED
	(
		[SRCH_ENG_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
