CREATE TABLE [EDAA_DW].[REF_RF_LNK_TYP]
(
	[RF_LNK_TYP_ID] [smallint] NOT NULL,
	[RF_LNK_TYP_NM] [varchar](128) NULL,
	[RF_LNK_TYP_DESC] [varchar](512) NULL,
	[UPD_TMS] [datetime] NOT NULL,
	[UPD_BY] [varchar](64) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_RF_LNK_TYP] PRIMARY KEY NONCLUSTERED
	(
		[RF_LNK_TYP_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
