CREATE TABLE [EDAA_DW].[REF_VISITR_TYP]
(
	[VISITR_TYP_ID] [smallint] NOT NULL,
	[VISITR_TYP_NM] [varchar](10) NOT NULL,
	[VISITR_TYP_DESC] [varchar](50) NOT NULL,
	[UPD_TMS] [datetime] NOT NULL,
	[UPD_BY] [varchar](64) NOT NULL,
	[AUD_INS_SK] [bigint] NULL,
	[AUD_UPD_SK] [bigint] NULL,
 CONSTRAINT [PK_REF_VISITR_TYP] PRIMARY KEY NONCLUSTERED
	(
		[VISITR_TYP_ID] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
