CREATE TABLE [EDAA_DW].[STR_UPC_SL_STS]
(
	[STR_ID] [int] NULL,
	[PHM_FLG] [nvarchar](1024) NULL,
	[TM_SKY_SL] [int] NULL,
	[FLG_LOADED] [nvarchar](1024) NULL,
	[LAST_REFRESHED] [datetime2](7) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
