CREATE TABLE [DM].[DIM_STO_DLY_SL_STS] (
    [INDX_ID]     SMALLINT     NOT NULL,
    [INDX_DSC]    VARCHAR (80) NOT NULL,
    [DAY_DT]      DATE         NOT NULL,
    [AUD_INS_SKY] BIGINT       NULL
)
WITH (HEAP, DISTRIBUTION = REPLICATE);
