CREATE TABLE [DM].[DIM_AUD_ETL] (
    [AUD_SKY]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [EXEC_STRT_TS]      DATETIME      NOT NULL,
    [EXEC_END_TS]       DATETIME      NULL,
    [EXEC_USID]         VARCHAR (255) NOT NULL,
    [EXEC_LYR]          VARCHAR (255) NOT NULL,
    [EXEC_JOB]          VARCHAR (500) NOT NULL,
    [SRC_ENTY]          VARCHAR (500) NOT NULL,
    [TGT_ENTY]          VARCHAR (500) NOT NULL,
    [CHLD_ETL_AUD_SKY]  BIGINT        NULL,
    [PRSNT_LYR_PRC_STS] SMALLINT      NULL,
    [SEM_LYR_PRC_STS]   SMALLINT      NULL,
    [NBR_OF_RW_ISRT]    INT           NULL,
    [NBR_OF_RW_UDT]     INT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);


GO
CREATE NONCLUSTERED INDEX [EXEC_LYR_NCIDX]
    ON [DM].[DIM_AUD_ETL]([EXEC_LYR] ASC);


GO
CREATE NONCLUSTERED INDEX [TGT_ENTY_NCIDX]
    ON [DM].[DIM_AUD_ETL]([TGT_ENTY] ASC);
