CREATE TABLE [EDAA_STG].[DIM_DLY_CAL]
(
	[Dt_Sk] [int] NULL,
	[LY_DT_SK] [int] NULL,
	[LY_DT_SK_HLDY] [int] NULL,
	[LY_DT_SK_CAL] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
