CREATE TABLE [EDAA_STG].[DIM_INV_ADJ_TYP_CT_TMP]
(
	[INV_TN_TYP_CT_ID] [smallint] NULL,
	[INV_TN_TYP_CT_NM] [varchar](50) NULL,
	[INV_TN_TYP_CT_DSC] [varchar](100) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
