CREATE TABLE [EDAA_STG].[DLY_UT_P_UPC_HST_LOSTSALES]
(
	[P_UPC_ID] [decimal](18, 0) NULL,
	[UT_ID] [smallint] NULL,
	[DAY_DT] [char](8) NULL,
	[TG_RGL_LOST_SL_QT] [decimal](11, 2) NULL,
	[TG_PROMO_LOST_SL_QT] [decimal](11, 2) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
