CREATE TABLE [EDAA_STG].[EMP_LOC]
(
	[EMP_ID] [int] NOT NULL,
	[LOC_ID] [int] NOT NULL,
	[PRD_STRT_TMS] [datetime2](7) NOT NULL,
	[PRD_END_TMS] [datetime2](7) NULL,
	[EMP_LOC_NTE_DESC] [nvarchar](256) NULL,
	[LOC_TYP_ID] [int] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
