CREATE TABLE [EDAA_STG].[EMP_NM_COMP]
(
	[EMP_ID] [int] NOT NULL,
	[EMP_NM_ID] [int] NOT NULL,
	[NM_COMP_ORDR_NUM] [int] NOT NULL,
	[EMP_NM] [nvarchar](256) NULL,
	[NM_COMP_TYP_ID] [int] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
