CREATE TABLE [EDAA_STG].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_FSC_TEMP]
(
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[DT_SK] [int] NULL,
	[LY_DT_SK] [int] NULL,
	[LY_DT_SK_HLDY] [int] NULL,
	[LY_DT_SK_CAL] [int] NULL,
	[INV_ADJ_SK] [int] NULL,
	[STR_ID] [smallint] NOT NULL,
	[INV_ADJSTD_TY_AMT] [decimal](13, 4) NULL,
	[INV_ADJSTD_TY_QTY] [decimal](11, 2) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
