CREATE TABLE [EDAA_STG].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_TEMP]
(
	[DT_SK] [int] NULL,
	[LY_DT_SK] [int] NULL,
	[LY_DT_SK_HLDY] [int] NULL,
	[LY_DT_SK_CAL] [int] NULL,
	[ITM_SKU] [decimal](18, 0) NULL,
	[STR_ID] [smallint] NULL,
	[INV_ADJ_SK] [int] NULL,
	[INV_ADJSTD_AMT_TY_FSC] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_TY_FSC] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_FSC] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_FSC] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_HLDY] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_HLDY] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_CAL] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_CAL] [decimal](11, 2) NULL,
	[UPDATEDTIMESTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
