CREATE TABLE [EDAA_STG].[FCT_DLY_STR_ITMSKU_INV_LY_FSC_TEMP]
(
	[STR_ID] [smallint] NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[DT_SK] [int] NULL,
	[LY_DT_SK] [int] NULL,
	[LY_DT_SK_HLDY] [int] NULL,
	[LY_DT_SK_CAL] [int] NULL,
	[INV_AMT_TY] [int] NOT NULL,
	[INV_QTY_TY] [int] NOT NULL,
	[INV_AMT_LY] [decimal](13, 4) NULL,
	[INV_QTY_LY] [decimal](11, 2) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
