CREATE TABLE [EDAA_STG].[FCT_WSTE_VISIT]
(
	[WEB_SESN_STRT_TMS] [datetime2](7) NULL,
	[VISIT_NUM] [int] NULL,
	[SESN_ID] [nvarchar](4000) NULL,
	[UPD_TMS] [datetime2](7) NULL,
	[UPD_BY] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
