CREATE TABLE [EDAA_STG].[FUEL_PCHG_DTL]
(
[FUEL_PCHG_SEQ_ID] [INTEGER]  NOT NULL ,
[STR_ID] [SMALLINT]  NOT NULL ,
[ITM_GRP_ID] [SMALLINT]  NOT NULL ,
[FUEL_PR_AMT] [DECIMAL] (6,3)  NOT NULL ,
[SRC_RW_GRTN_TMS] [DATETIME]  NOT NULL ,
[SRC_RW_PRCS_ID] [VARCHAR](30)  NOT NULL ,
[PCHG_KLBRT_TN_ID] [VARCHAR](100)  NULL ,
[PCHG_KLBRT_STS_TX] [CHAR] (3) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
