CREATE TABLE [EDAA_STG].[ITM_GRP_ITM]
(
	[ITM_GRP_ID] [int] NOT NULL,
	[ITM_SKU_ID] [varchar](100) NOT NULL,
	[PRD_STRT_DT] [date] NOT NULL,
	[PRD_END_DT] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
