CREATE TABLE [EDAA_STG].[ITM_GRP]
(
	[ITM_GRP_ID] [int] NOT NULL,
	[ITM_GRP_NM] [varchar](128) NOT NULL,
	[ITM_GRP_DESC] [varchar](512) NULL,
	[ITM_STAT_ATV_IND] [char](1) NOT NULL,
	[PRD_STRT_DT] [date] NOT NULL,
	[PRD_END_DT] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
