CREATE TABLE [EDAA_STG].[REF_SRCH_ENGN]
(
	[SRCH_ENG_ID] [int] NULL,
	[SRCH_ENG_NM] [nvarchar](4000) NULL,
	[SRCH_ENG_DESC] [nvarchar](4000) NULL,
	[SRCH_ENG_URL] [nvarchar](4000) NULL,
	[UPD_TMS] [datetime2](7) NULL,
	[UPD_BY] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
