CREATE TABLE [EDAA_STG].[REF_VISITR_TYP]
(
	[VISITR_TYP_ID] [int] NULL,
	[VISITR_TYP_NM] [nvarchar](4000) NULL,
	[VISITR_TYP_DESC] [nvarchar](4000) NULL,
	[UPD_TMS] [datetime2](7) NULL,
	[UPD_BY] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
