CREATE TABLE [EDAA_STG].[STG_FCT_DLY_STR_ITMSKU_SLS_TY_LY_FSC]
(
	[DT_SK] [int] NOT NULL,
	[LY_DT_SK] [int] NOT NULL,
	[LY_DT_SK_HLDY] [int] NULL,
	[LY_DT_SK_CAL] [int] NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[STR_ID] [smallint] NOT NULL,
	[SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[SLS_QTY_TY_FSC] [decimal](38, 0) NULL,
	[SLS_QTY_LY_FSC] [decimal](38, 0) NULL,
	[SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_QTY_TY_FSC] [decimal](38, 0) NULL,
	[PRM_TO_SLS_QTY_LY_FSC] [decimal](38, 0) NULL,
	[PRM_TO_SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_QTY_TY_FSC] [decimal](38, 0) NULL,
	[CLRNC_QTY_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_LY_FSC] [decimal](38, 4) NULL,
	[UPDATEDTIMESTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
