CREATE TABLE [EDAA_STG].[TEMP_FCT_DLY_STR_ITMSKU_INV_TY_LY_FSC]
(
	[STR_ID] [smallint] NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[DT_SK] [int] NOT NULL,
	[LY_DT_SK] [nvarchar](4000) NULL,
	[LY_DT_SK_HLDY] [nvarchar](4000) NULL,
	[LY_DT_SK_CAL] [nvarchar](4000) NULL,
	[INV_AMT_TY_FSC] [decimal](38, 4) NULL,
	[INV_QTY_TY_FSC] [decimal](38, 2) NULL,
	[INV_AMT_LY_FSC] [decimal](38, 4) NULL,
	[INV_QTY_LY_FSC] [decimal](38, 2) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
