CREATE TABLE [EDAA_STG].[UT_UPC_DLY_INV_HST_INCL]
(
	[STR_ID] [int] NULL,
	[UPC_ID] [decimal](18, 0) NULL,
	[INV_ROW_START_DT] [date] NULL,
	[INV_ROW_END_DT] [date] NULL,
	[INV_EACH_AMT] [decimal](14, 4) NULL,
	[INV_FNC_CHRG_AMT] [decimal](14, 4) NULL,
	[INV_FNC_CR_AMT] [decimal](14, 4) NULL,
	[INV_STRGE_CHRG_AMT] [decimal](14, 4) NULL,
	[INV_FRT_AMT] [decimal](14, 4) NULL,
	[INV_DIST_CNTR_HNDL_AMT] [decimal](14, 4) NULL,
	[INV_AMT] [decimal](14, 4) NULL,
	[INV_QTY] [decimal](14, 4) NULL,
	[INV_CLRNC_IND] [char](1) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
