/****** Object:  Table [EDAA_STG].[UT_UPC_DLY_INV_HST]    Script Date: 10/29/2021 7:33:00 AM ******/
CREATE TABLE [EDAA_STG].[UT_UPC_DLY_INV_HST]
(
	[SU_UNIT_ID] [nvarchar](256) NULL,
	[SU_UPC_ID] [nvarchar](256) NULL,
	[SU_PRMKY_ID] [nvarchar](256) NULL,
	[SU_MPRS_CATG_ID] [nvarchar](256) NULL,
	[SU_UPC_CBC_SQ_FTG_QTY] [nvarchar](256) NULL,
	[SU_PROD_MJR_PFRM_COST_AMT] [nvarchar](256) NULL,
	[SU_STOR_BOH_QTY] [nvarchar](256) NULL,
	[SU_STOR_BOH_QTY_CLRN] [nvarchar](256) NULL,
	[SU_STOR_TOT_UPC_INV_AMT] [nvarchar](256) NULL,
	[SU_STOR_TOT_UPC_INV_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_TOT_FNC_CHRG_AMT] [nvarchar](256) NULL,
	[SU_UPC_TOT_FNC_CHRG_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_TOT_FNC_CRED_AMT] [nvarchar](256) NULL,
	[SU_UPC_TOT_FNC_CRED_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_TOT_STOR_CHRG_AMT] [nvarchar](256) NULL,
	[SU_UPC_TOT_STOR_CHRG_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_TOT_STOR_HNDL_AMT] [nvarchar](256) NULL,
	[SU_STOR_BOH_DCML_QTY] [nvarchar](256) NULL,
	[SU_UPC_TOT_FRGHT_AMT] [nvarchar](256) NULL,
	[SU_UPC_TOT_FRGHT_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_TOT_DC_HNDL_AMT] [nvarchar](256) NULL,
	[SU_UPC_TOT_DC_HNDL_AMT_CLRN] [nvarchar](256) NULL,
	[SU_UPC_RANDM_CNT_DT] [nvarchar](256) NULL,
	[SU_CLRNCE_FLAG] [nvarchar](256) NULL,
	[SU_CREATE_DT] [nvarchar](256) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
