CREATE TABLE [EDAA_STG].[UT_UPC_DLY_INV_HST_DER_INITIAL]
(
	[STR_ID] [int] NULL,
	[UPC_ID] [float] NULL,
	[INV_ROW_START_DT] [date] NULL,
	[INV_ROW_END_DT] [date] NULL,
	[INV_EACH_AMT] [float] NULL,
	[INV_FNC_CHRG_AMT] [float] NULL,
	[INV_FNC_CR_AMT] [float] NULL,
	[INV_STRGE_CHRG_AMT] [float] NULL,
	[INV_FRT_AMT] [float] NULL,
	[INV_DIST_CNTR_HNDL_AMT] [float] NULL,
	[INV_AMT] [float] NULL,
	[INV_QTY] [float] NULL,
	[INV_CLRNC_IND] [nvarchar](256) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
);
