CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_P_SUB_CT_INCR_LY_FSC] AS select
FCT_DLY.TM_SKY as TM_SKY_LY_FSC,
TM.FCL_DAY_DT_LY, TM.DAY_DT, TM.TM_SKY as TM_SKY,
ISNULL(G.GEO_SKY, -1) AS GEO_SKY,
ISNULL(B.BYR_SKY, -1) AS BYR_SKY,
ISNULL(C.CHNL_SKY, -1) AS CHNL_SKY,
FCT_DLY.UT_ID,
FCT_DLY.P_SUB_CT_ID,
SUM(FCT_DLY.SLS_MKT_BSKT_AM) as SLS_MKT_BSKT_AM_LY_FSC,
SUM(FCT_DLY.DMGN_MKT_BSKT_AM) as DMGN_MKT_BSKT_AM_LY_FSC,
SUM(FCT_DLY.COGS_MKT_BSKT) as COGS_MKT_BSKT_LY_FSC,
SUM(FCT_DLY.DGTL_UT_SLS_AM) as DGTL_UT_SLS_AM_LY_FSC,
SUM(FCT_DLY.DGTL_SHOP_SLS_AM) as DGTL_SHOP_SLS_AM_LY_FSC,
SUM(FCT_DLY.SHOP_AND_SCN_STO_SLS_AM) as SHOP_AND_SCN_STO_SLS_AM_LY_FSC,
SUM(FCT_DLY.SHOP_AND_SCN_SLS_AM)  as SHOP_AND_SCN_SLS_AM_LY_FSC,
SUM(FCT_DLY.SLS_MKT_BSKT_QTY) as SLS_MKT_BSKT_QTY_LY_FSC,
SUM(FCT_DLY.SLS_MKT_BSKT_AM_COMP) as SLS_MKT_BSKT_AM_COMP_LY_FSC,
SUM(FCT_DLY.CALC_CIRC_AM) as CALC_CIRC_AM_LY_FSC,
SUM(FCT_DLY.CALC_CLRN_AM) as CALC_CLRN_AM_LY_FSC,
SUM(FCT_DLY.CALC_DGTL_CIRC_AM) as CALC_DGTL_CIRC_AM_LY_FSC,
SUM(FCT_DLY.CALC_HOOK_AM) as CALC_HOOK_AM_LY_FSC,
SUM(FCT_DLY.CALC_DUM_AM) as CALC_DUM_AM_LY_FSC,
SUM(FCT_DLY.CALC_MDWK_AM) as CALC_MDWK_AM_LY_FSC,
SUM(FCT_DLY.CALC_MPRKS_AM) as CALC_MPRKS_AM_LY_FSC,
SUM(FCT_DLY.CALC_OTH_AM) as CALC_OTH_AM_LY_FSC,
SUM(FCT_DLY.CALC_PERS_RWRD_AM) as CALC_PERS_RWRD_AM_LY_FSC,
SUM(FCT_DLY.CALC_SHLF_EDG_AM) as CALC_SHLF_EDG_AM_LY_FSC,
SUM(FCT_DLY.CALC_SP_EVNT_AM) as CALC_SP_EVNT_AM_LY_FSC,
SUM(FCT_DLY.CALC_TEAM_MMB_AM) as CALC_TEAM_MMB_AM_LY_FSC,
SUM(FCT_DLY.SLS_MKT_BSKT_AM_NCOMP) as SLS_MKT_BSKT_AM_NCOMP_LY_FSC

FROM DM.FCT_DLY_SL_MB_P_SUB_CT AS FCT_DLY
----- inner join to get last year fiscal data
INNER JOIN
DM.DIM_TM as TM ON  FCT_DLY.TM_SKY = TM.TM_SKY_LY_FSC
----- join to get dimension skys
LEFT JOIN DM.DIM_GEO AS G ON G.GEO_HST_SKY = FCT_DLY.GEO_HST_SKY
LEFT JOIN DM.DIM_CHNL AS C ON C.CHNL_HST_SKY = FCT_DLY.CHNL_HST_SKY
LEFT JOIN DM.DIM_BYR_P_SUB_CT AS B ON B.BYR_HST_SKY = FCT_DLY.BYR_HST_SKY

----  Inner join to get changed and updated skys

/******* CHANGE 11/9 = comment below section ***/

/*LEFT JOIN ETL.FCT_DLY_SL_MB_P_SUB_CT_INCR_KEYS AS INCR
ON INCR.UT_ID = FCT_DLY.UT_ID AND INCR.CHNL_SKY = C.CHNL_SKY AND INCR.P_SUB_CT_ID = FCT_DLY.P_SUB_CT_ID
AND INCR.TM_SKY = TM.TM_SKY
where TM.TM_SKY is not null*/

/******* CHANGE 11/9 = introduce below condition to check only those last year dates corresponding to current incremental***/
where TM.TM_SKY In (

--select distinct tm_sky from ETL.FCT_DLY_SL_P_SUB_CT_INCR_KEYS

--/*fix last year records for future dates*/

select distinct tm_sky from (
 select tm_sky from (
  select   tm_sky, count(1) as Records from [ETL].[FCT_DLY_SL_MB_P_SUB_CT_INCR_KEYS]
  GROUP BY tm_sky
  ) as x
UNION

select tm_sky from dm.dim_tm where tm_sky between
(

SELECT  min([TM_SKY])
  FROM [PRES].[DIM_TM_CALC]
  where [PRE_DEF_DT_FLTR] = 'Current Wk'

)
AND
(
SELECT  max([TM_SKY])
  FROM [PRES].[DIM_TM_CALC]
  where [PRE_DEF_DT_FLTR] = 'Current Wk'

)

) as x



)

GROUP BY
FCT_DLY.TM_SKY,
TM.FCL_DAY_DT_LY, TM.DAY_DT, TM.TM_SKY,
ISNULL(G.GEO_SKY, -1),
ISNULL(B.BYR_SKY, -1),
ISNULL(C.CHNL_SKY, -1),
FCT_DLY.UT_ID,
FCT_DLY.P_SUB_CT_ID;
