CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_CURR]
AS SELECT
FCT_DLY.TM_SKY as TM_SKY,
T.DAY_DT,
G.GEO_HST_SKY,
G.GEO_SKY,
C.CHNL_HST_SKY,
C.CHNL_SKY,
FCT_DLY.UT_ID,
FCT_DLY.P_CT_BUS_KEY,
FNC_TN_CNT as FNC_TN_CNT
from DM.FCT_DLY_SL_MB_TXN_P_SUB_CT FCT_DLY WITH(NOLOCK)
----- join to get dimension skys
LEFT JOIN DM.DIM_GEO G WITH(NOLOCK)  ON G.GEO_HST_SKY = FCT_DLY.GEO_HST_SKY
LEFT JOIN DM.DIM_CHNL C WITH(NOLOCK) ON C.CHNL_HST_SKY = FCT_DLY.CHNL_HST_SKY
--INNER JOIN DM.DIM_TM T WITH(NOLOCK) ON T.TM_SKY = FCT_DLY.TM_SKY; /*commented this for MB Incremental*/
----  Inner join to get changed and updated skys
INNER JOIN ETL.FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_KEYS INCR WITH(NOLOCK)
ON INCR.UT_ID = FCT_DLY.UT_ID AND INCR.CHNL_HST_SKY = FCT_DLY.CHNL_HST_SKY
AND INCR.P_CT_BUS_KEY = FCT_DLY.P_CT_BUS_KEY AND FCT_DLY.GEO_HST_SKY = INCR.GEO_HST_SKY
AND INCR.TM_SKY = FCT_DLY.TM_SKY
INNER JOIN DM.DIM_TM T WITH(NOLOCK) ON T.TM_SKY = INCR.TM_SKY;
