CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC] AS SELECT  [GEO_HST_SKY]
      ,[GEO_SKY]
      ,[TM_SKY]
      ,[CHNL_SKY]
      ,[CHNL_HST_SKY]
      ,[UT_ID]
      ,[P_CT_BUS_KEY]
      ,[FNC_TN_CNT]
      ,[FNC_TN_CNT_LY_CLDR]
      ,[FNC_TN_CNT_LY_FSC]
      ,[FNC_TN_CNT_LY_HLDY]
      ,[FNC_TN_CNT_DIFF_TY_VS_LY_CLDR]
      ,[FNC_TN_CNT_DIFF_TY_VS_LY_FSC]
      ,[FNC_TN_CNT_DIFF_TY_VS_LY_HLDY]


  FROM [ETL].[FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC_STG];
