CREATE VIEW [ETL].[V_SRC_FCT_WK_STRT_INV_P_SUB_CT_CALC_STG]
AS SELECT
S.[GEO_HST_SKY]
,S.GEO_SKY
      ,S.[TM_SKY]
      ,ISNULL(S.[BYR_HST_SKY], -1) AS [BYR_HST_SKY]
	  ,ISNULL(S.BYR_SKY, -1) AS BYR_SKY
      ,ISNULL(P.P_HST_SKY, -1) AS P_HST_SKY
	  ,ISNULL(P.P_SKY, -1) AS P_SKY
      ,S.[UT_ID]
      ,SUM([TG_INV_CST_AM]) AS [TG_INV_CST_AM]
      ,SUM([TG_CLRN_INV_CST_AM]) AS [TG_CLRN_INV_CST_AM]
      ,SUM([INV_CLRN_QTY]) AS [INV_CLRN_QTY]
      ,SUM([TG_INV_QTY])  AS [TG_INV_QTY]



	  ,SUM([TG_INV_CST_AM_LY_CLDR]) AS [TG_INV_CST_AM_LY_CLDR]
      ,SUM([TG_CLRN_INV_CST_AM_LY_CLDR]) AS [TG_CLRN_INV_CST_AM_LY_CLDR]
      ,SUM([INV_CLRN_QTY_LY_CLDR]) AS [INV_CLRN_QTY_LY_CLDR]
      ,SUM([TG_INV_QTY_LY_CLDR]) AS [TG_INV_QTY_LY_CLDR]

	   ,SUM([TG_INV_CST_AM_LY_FSC]) AS [TG_INV_CST_AM_LY_FSC]
      ,SUM([TG_CLRN_INV_CST_AM_LY_FSC]) AS [TG_CLRN_INV_CST_AM_LY_FSC]
      ,SUM([INV_CLRN_QTY_LY_FSC]) AS [INV_CLRN_QTY_LY_FSC]
      ,SUM([TG_INV_QTY_LY_FSC]) AS [TG_INV_QTY_LY_FSC]

      ,SUM( ISNULL([TG_INV_CST_AM_LY_HLDY], 0)) as [TG_INV_CST_AM_LY_HLDY]
      ,SUM( ISNULL([TG_CLRN_INV_CST_AM_LY_HLDY], 0)) as [TG_CLRN_INV_CST_AM_LY_HLDY]
      ,SUM(ISNULL([INV_CLRN_QTY_LY_HLDY], 0)) as [INV_CLRN_QTY_LY_HLDY]
      ,SUM(ISNULL([TG_INV_QTY_LY_HLDY], 0)) as [TG_INV_QTY_LY_HLDY]


,SUM(ISNULL(TG_INV_CST_AM, 0) - ISNULL(TG_INV_CST_AM_LY_CLDR, 0)) AS TG_INV_CST_AM_DIFF_TY_VS_LY_CLDR

,SUM(ISNULL(TG_CLRN_INV_CST_AM, 0) - ISNULL(TG_CLRN_INV_CST_AM_LY_CLDR, 0)) AS TG_CLRN_INV_CST_AM_DIFF_TY_VS_LY_CLDR

,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_CLDR, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_CLDR

,SUM(ISNULL(TG_INV_QTY, 0) - ISNULL(TG_INV_QTY_LY_CLDR, 0)) AS TG_INV_QTY_DIFF_TY_VS_LY_CLDR

,SUM(ISNULL(TG_INV_CST_AM, 0) - ISNULL(TG_INV_CST_AM_LY_FSC, 0)) AS TG_INV_CST_AM_DIFF_TY_VS_LY_FSC

,SUM(ISNULL(TG_CLRN_INV_CST_AM, 0) - ISNULL(TG_CLRN_INV_CST_AM_LY_FSC, 0)) AS TG_CLRN_INV_CST_AM_DIFF_TY_VS_LY_FSC

,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_FSC, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_FSC

,SUM(ISNULL(TG_INV_QTY, 0) - ISNULL(TG_INV_QTY_LY_FSC, 0)) AS TG_INV_QTY_DIFF_TY_VS_LY_FSC

	,SUM(ISNULL(TG_INV_CST_AM, 0) - ISNULL(TG_INV_CST_AM_LY_HLDY, 0)) AS TG_INV_CST_AM_DIFF_TY_VS_LY_HLDY

	,SUM(ISNULL(TG_CLRN_INV_CST_AM, 0) - ISNULL(TG_CLRN_INV_CST_AM_LY_HLDY, 0) ) AS TG_CLRN_INV_CST_AM_DIFF_TY_VS_LY_HLDY

	,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_HLDY, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_HLDY

	,SUM(ISNULL(TG_INV_QTY, 0) - ISNULL(TG_INV_QTY_LY_HLDY, 0)) AS TG_INV_QTY_DIFF_TY_VS_LY_HLDY

  FROM  [ETL].[FCT_WK_STRT_INV_P_SUB_CT_INCR_CURR] AS S
  INNER JOIN DM.DIM_TM AS T ON T.TM_SKY = S.TM_SKY
  LEFT JOIN (
SELECT [P_HST_SKY]
      ,[P_SKY]
      ,[P_SUB_CT_ID]
      ,FNC_PKY_ID
      ,FNC_MPRS_CT_ID
      ,[VLD_FROM]
      ,[VLD_TO]
  FROM [PRES].[DIM_P_L3]) AS P
  ON P.[P_SUB_CT_ID] = S.[P_SUB_CT_ID] AND
  S.FNC_MPRS_CT_ID = P.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = P.FNC_PKY_ID
 AND T.DAY_DT BETWEEN CAST(VLD_FROM as date) AND ISNULL(CAST(VLD_TO as date), CAST('2099-01-01' as date))


 LEFT JOIN [ETL].[FCT_WK_STRT_INV_P_SUB_CT_INCR_LY_CLDR] AS CLDR
 ON CLDR.GEO_SKY = S.GEO_SKY AND CLDR.UT_ID = S.UT_ID AND CLDR.TM_SKY = S.TM_SKY
 AND CLDR.BYR_SKY = S.BYR_SKY  AND
 S.FNC_MPRS_CT_ID = CLDR.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = CLDR.FNC_PKY_ID

  LEFT JOIN [ETL].[FCT_WK_STRT_INV_P_SUB_CT_INCR_LY_FSC] AS FSC
 ON FSC.GEO_SKY = S.GEO_SKY AND FSC.UT_ID = S.UT_ID AND FSC.TM_SKY = S.TM_SKY
 AND FSC.BYR_SKY = S.BYR_SKY  AND
 S.FNC_MPRS_CT_ID = FSC.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = FSC.FNC_PKY_ID

 LEFT JOIN [ETL].[FCT_WK_STRT_INV_P_SUB_CT_INCR_LY_HLDY] AS HLDY
 ON HLDY.GEO_SKY = S.GEO_SKY AND HLDY.UT_ID = S.UT_ID AND HLDY.TM_SKY = S.TM_SKY
 AND HLDY.BYR_SKY = S.BYR_SKY  AND
 S.FNC_MPRS_CT_ID = HLDY.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = HLDY.FNC_PKY_ID
 GROUP BY
 S.[GEO_HST_SKY]
,S.GEO_SKY
      ,S.[TM_SKY]
      ,S.[BYR_HST_SKY]
	  ,S.BYR_SKY
      ,ISNULL(P.P_HST_SKY, -1)
	  ,ISNULL(P.P_SKY, -1)
      ,S.[UT_ID];
