CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC_STG] AS SELECT
S.[GEO_HST_SKY]
,S.GEO_SKY
      ,S.[TM_SKY]
      ,S.CHNL_SKY
	  ,S.CHNL_HST_SKY
      ,S.[UT_ID]
	  ,S.P_CT_BUS_KEY
	  ,S.FNC_TN_CNT
	  ,CLDR.FNC_TN_CNT_LY_CLDR
	    ,FSC.FNC_TN_CNT_LY_FSC
		   ,HLDY.FNC_TN_CNT_LY_HLDY
 ,ISNULL(S.FNC_TN_CNT, 0) - ISNULL(CLDR.FNC_TN_CNT_LY_CLDR, 0) as FNC_TN_CNT_DIFF_TY_VS_LY_CLDR
  ,ISNULL(S.FNC_TN_CNT, 0) - ISNULL(FSC.FNC_TN_CNT_LY_FSC, 0) as FNC_TN_CNT_DIFF_TY_VS_LY_FSC

   ,
	ISNULL(S.FNC_TN_CNT, 0) - ISNULL(HLDY.FNC_TN_CNT_LY_HLDY, 0) as FNC_TN_CNT_DIFF_TY_VS_LY_HLDY

  FROM [ETL].[FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_CURR] AS S

 LEFT JOIN [ETL].[FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_LY_CLDR] AS CLDR
 ON CLDR.GEO_SKY = S.GEO_SKY AND CLDR.UT_ID = S.UT_ID AND CLDR.TM_SKY = S.TM_SKY
 AND CLDR.CHNL_SKY = S.CHNL_SKY AND S.P_CT_BUS_KEY = CLDR.P_CT_BUS_KEY

  LEFT JOIN [ETL].[FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_LY_FSC] AS FSC
 ON FSC.GEO_SKY = S.GEO_SKY AND FSC.UT_ID = S.UT_ID AND FSC.TM_SKY = S.TM_SKY
 AND FSC.CHNL_SKY = S.CHNL_SKY AND S.P_CT_BUS_KEY = FSC.P_CT_BUS_KEY


  LEFT JOIN [ETL].[FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_LY_HLDY] AS HLDY
 ON HLDY.GEO_SKY = S.GEO_SKY AND HLDY.UT_ID = S.UT_ID AND HLDY.TM_SKY = S.TM_SKY
 AND HLDY.CHNL_SKY = S.CHNL_SKY AND S.P_CT_BUS_KEY = HLDY.P_CT_BUS_KEY;
