CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_P_SUB_CT_INCR_CURR] AS SELECT
	S.[GEO_HST_SKY],
	G.[GEO_SKY],
	S.[TM_SKY],
	S.[BYR_HST_SKY],
	B.[BYR_SKY],
	S.[CHNL_HST_SKY],
	C.[CHNL_SKY],
	S.[UT_ID],
	S.[P_SUB_CT_ID],
	CAST(SUM([SLS_MKT_BSKT_AM]) as decimal(11, 3)) AS [SLS_MKT_BSKT_AM],
	CAST(SUM([DMGN_MKT_BSKT_AM]) as decimal(11, 3)) AS [DMGN_MKT_BSKT_AM],
	CAST(SUM([COGS_MKT_BSKT]) as decimal(11, 3)) AS [COGS_MKT_BSKT],
	CAST(SUM([DGTL_UT_SLS_AM]) as decimal(11, 3)) AS [DGTL_UT_SLS_AM],
	CAST(SUM([DGTL_SHOP_SLS_AM]) as decimal(11, 3))  AS [DGTL_SHOP_SLS_AM],
	CAST(SUM([SHOP_AND_SCN_STO_SLS_AM]) as decimal(11, 3)) AS [SHOP_AND_SCN_STO_SLS_AM],
	CAST(SUM([SHOP_AND_SCN_SLS_AM]) as decimal(11, 3)) AS [SHOP_AND_SCN_SLS_AM],
	CAST(SUM([SLS_MKT_BSKT_QTY]) as decimal(11, 3)) AS [SLS_MKT_BSKT_QTY],
	CAST(SUM([SLS_MKT_BSKT_AM_COMP]) as decimal(11, 3)) AS [SLS_MKT_BSKT_AM_COMP],
	CAST(SUM([CALC_CIRC_AM]) as decimal(11, 3)) AS [CALC_CIRC_AM],
	CAST(SUM([CALC_CLRN_AM]) as decimal(11, 3)) AS [CALC_CLRN_AM],
	CAST(SUM([CALC_DGTL_CIRC_AM]) as decimal(11, 3)) AS [CALC_DGTL_CIRC_AM],
	CAST(SUM([CALC_HOOK_AM]) as decimal(11, 3)) AS [CALC_HOOK_AM],
	CAST(SUM([CALC_DUM_AM]) as decimal(11, 3)) AS [CALC_DUM_AM],
	CAST(SUM([CALC_MDWK_AM]) as decimal(11, 3)) AS [CALC_MDWK_AM],
	CAST(SUM([CALC_MPRKS_AM]) as decimal(11, 3)) AS [CALC_MPRKS_AM],
	CAST(SUM([CALC_OTH_AM]) as decimal(11, 3)) AS [CALC_OTH_AM],
	CAST(SUM([CALC_PERS_RWRD_AM]) as decimal(11, 3)) AS [CALC_PERS_RWRD_AM],
	CAST(SUM([CALC_SHLF_EDG_AM]) as decimal(11, 3)) AS [CALC_SHLF_EDG_AM],
	CAST(SUM([CALC_SP_EVNT_AM]) as decimal(11, 3)) AS [CALC_SP_EVNT_AM],
	CAST(SUM([CALC_TEAM_MMB_AM]) as decimal(11, 3)) AS [CALC_TEAM_MMB_AM],
	CAST(SUM([SLS_MKT_BSKT_AM_NCOMP]) as decimal(11, 3)) AS [SLS_MKT_BSKT_AM_NCOMP]
	FROM
	[ETL].[FCT_DLY_SL_MB_P_SUB_CT_INCR_KEYS] AS INCR
   INNER JOIN [DM].[FCT_DLY_SL_MB_P_SUB_CT] AS S /******* CHANGE 11/9 == replace left join with inner join ***/
   ON INCR.UT_ID = S.UT_ID AND INCR.CHNL_HST_SKY = S.CHNL_HST_SKY AND INCR.TM_SKY = S.TM_SKY
   AND INCR.P_SUB_CT_ID = S.P_SUB_CT_ID AND INCR.BYR_HST_SKY = S.BYR_HST_SKY
   LEFT JOIN DM.DIM_GEO AS G ON G.GEO_HST_SKY = S.GEO_HST_SKY
LEFT JOIN DM.DIM_CHNL AS C ON C.CHNL_HST_SKY = S.CHNL_HST_SKY
LEFT JOIN DM.DIM_BYR_P_SUB_CT AS B ON B.BYR_HST_SKY = S.BYR_HST_SKY
--where S.[TM_SKY] is not null /******* CHANGE 11/9 == removed condition as already handled by inner join ***/
GROUP BY
S.[GEO_HST_SKY],
	G.[GEO_SKY],
	S.[TM_SKY],
	S.[BYR_HST_SKY],
	B.[BYR_SKY],
	S.[CHNL_HST_SKY],
	C.[CHNL_SKY],
	S.[UT_ID],
	S.[P_SUB_CT_ID];
