CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_P_SUB_CT_INCR_LY_CLDR] AS select
FCT_CLDR.TM_SKY as TM_SKY_LY_CLDR,
TM.DAY_DT_LY, TM.DAY_DT, TM.TM_SKY as TM_SKY,
ISNULL(G.GEO_SKY, -1) AS GEO_SKY,
ISNULL(B.BYR_SKY, -1) AS BYR_SKY,
FCT_CLDR.UT_ID,
---FCT_CLDR.P_SUB_CT_ID,
BYR.mjr_p_sub_ct_id as P_SUB_CT_ID,
CURR_MPRS_CT_ID AS FNC_MPRS_CT_ID,
CURR_PKY_ID AS FNC_PKY_ID,
SUM(FCT_CLDR.SLS_FNC_AM) AS SLS_FNC_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_QTY) AS SLS_FNC_QTY_LY_CLDR,
SUM(FCT_CLDR.DM_FNC_AM) AS DM_FNC_AM_LY_CLDR,
SUM(FCT_CLDR.DM_FNC_CLRN_AM) AS DM_FNC_CLRN_AM_LY_CLDR,
SUM(FCT_CLDR.DM_FNC_PROMO_AM) AS DM_FNC_PROMO_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_CLRN_AM) AS SLS_FNC_CLRN_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_CLRN_MKDN_AM) AS SLS_FNC_CLRN_MKDN_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_PROMO_AM) AS SLS_FNC_PROMO_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_PROMO_MKDN_AM) AS SLS_FNC_PROMO_MKDN_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_CLRN_QTY) AS SLS_FNC_CLRN_QTY_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_SCN_QTY) AS SLS_FNC_SCN_QTY_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_AM_COMP) AS SLS_FNC_AM_COMP_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_AM_NCOMP) AS SLS_FNC_AM_NCOMP_LY_CLDR,
SUM(FCT_CLDR.INV_SHRK_AM) AS INV_SHRK_AM_LY_CLDR,
SUM(FCT_CLDR.INV_CLRN_QTY) AS INV_CLRN_QTY_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_AM) - SUM(FCT_CLDR.DM_FNC_AM) as COGS_FNC_LY_CLDR,
(SUM(FCT_CLDR.DM_FNC_AM) - SUM(FCT_CLDR.DM_FNC_PROMO_AM) ) - SUM(FCT_CLDR.DM_FNC_CLRN_AM) as DM_FNC_RRTL_AM_LY_CLDR,
SUM(FCT_CLDR.SLS_FNC_PROMO_MKDN_AM) + SUM(FCT_CLDR.SLS_FNC_CLRN_MKDN_AM) as SLS_FNC_MKDN_AM_LY_CLDR,
(SUM(FCT_CLDR.SLS_FNC_AM) - sum(FCT_CLDR.SLS_FNC_PROMO_AM)) - SUM(FCT_CLDR.SLS_FNC_CLRN_AM) as SLS_FNC_RRTL_MKDN_AM_LY_CLDR,
(SUM(FCT_CLDR.SLS_FNC_AM) - SUM(FCT_CLDR.SLS_FNC_CLRN_AM)) AS SLS_FNC_NCLRN_AM_LY_CLDR,
(SUM(FCT_CLDR.DM_FNC_AM) - SUM(FCT_CLDR.DM_FNC_CLRN_AM)) AS DM_FNC_NCLRN_AM_LY_CLDR
from DM.FCT_DLY_SL_P_SUB_CT AS FCT_CLDR
----- LEFT join to get last year calendar data
LEFT JOIN
DM.DIM_TM as TM ON  FCT_CLDR.TM_SKY = TM.TM_SKY_LY_CLDR

 -------- get current FNC_MPRS_CT_ID and FNC_PKY_ID from buyer employee bridge table -----
 INNER JOIN
 (

    SELECT pky_id, mprs_ct_id, LTRIM(RTRIM(mjr_p_sub_ct_id)) AS mjr_p_sub_ct_id, CURR_MPRS_CT_ID, CURR_PKY_ID
	FROM  dm_edw.byr_emp_pky_mprs_currprev_inf
    WHERE CAST(INS_DT as datetime) =
    (SELECT CAST(MAX(INS_DT) as datetime) AS INS_DT FROM dm_edw.byr_emp_pky_mprs_currprev_inf)
    AND mjr_p_sub_ct_id != ''
 ) AS BYR
 ON BYR.mprs_ct_id = FCT_CLDR.FNC_MPRS_CT_ID AND BYR.pky_id = FCT_CLDR.FNC_PKY_ID
--- AND BYR.mjr_p_sub_ct_id = FCT_CLDR.p_sub_ct_id

 ----  Inner join to get changed and updated skys
--INNER JOIN (SELECT GEO_SKY, UT_ID, TM_SKY, P_SUB_CT_ID,
--[FNC_MPRS_CT_ID], [FNC_PKY_ID]
--FROM ETL.FCT_DLY_SL_P_SUB_CT_INCR_KEYS
--GROUP BY GEO_SKY, UT_ID, TM_SKY, P_SUB_CT_ID, [FNC_MPRS_CT_ID], [FNC_PKY_ID]
--) AS INCR
--ON INCR.UT_ID = FCT_CLDR.UT_ID  AND INCR.P_SUB_CT_ID = FCT_CLDR.P_SUB_CT_ID
--AND INCR.TM_SKY = TM.TM_SKY AND INCR.FNC_MPRS_CT_ID = BYR.curr_mprs_ct_id
--AND INCR.[FNC_PKY_ID] = BYR.curr_pky_id

----- join to get dimension skys
LEFT JOIN DM.DIM_GEO AS G ON G.GEO_HST_SKY = FCT_CLDR.GEO_HST_SKY
LEFT JOIN DM.DIM_BYR_P_SUB_CT AS B ON B.BYR_HST_SKY = FCT_CLDR.BYR_HST_SKY
where tm.tm_sky IN (

----select distinct tm_sky from ETL.FCT_DLY_SL_P_SUB_CT_INCR_KEYS

/*fix last year records for future dates*/

select distinct tm_sky from (
 select tm_sky from (
  select   tm_sky, count(1) as Records from [ETL].[FCT_DLY_SL_P_SUB_CT_INCR_KEYS]
  GROUP BY tm_sky
  ) as x
UNION

select tm_sky from dm.dim_tm where tm_sky between
(

SELECT  min([TM_SKY])
  FROM [PRES].[DIM_TM_CALC]
  where [PRE_DEF_DT_FLTR] = 'Current Wk'

)
AND
(
SELECT  max([TM_SKY])
  FROM [PRES].[DIM_TM_CALC]
  where [PRE_DEF_DT_FLTR] = 'Current Wk'

)

) as x


)
GROUP BY
FCT_CLDR.TM_SKY,
TM.DAY_DT_LY, TM.DAY_DT, TM.TM_SKY,
G.GEO_SKY,
B.BYR_SKY,
FCT_CLDR.UT_ID,
BYR.mjr_p_sub_ct_id,
CURR_MPRS_CT_ID,
CURR_PKY_ID;
