CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_P_SUB_CT_INCR_CURR_PLN]

/*


This view returns current increment sales and plan data together with the current
MPRS_CT_ID and
PKY_ID


*/

AS select



FCT_DLY.GEO_HST_SKY,
G.GEO_SKY,
FCT_DLY.TM_SKY,
FCT_DLY.BYR_HST_SKY,
B.BYR_SKY,
BYR.mjr_p_sub_ct_id AS P_SUB_CT_ID,
FCT_DLY.UT_ID,
CURR_MPRS_CT_ID as FNC_MPRS_CT_ID,
CURR_PKY_ID as FNC_PKY_ID,
SUM(FCT_DLY.DM_FNC_AM) AS DM_FNC_AM,
SUM(FCT_DLY.DM_FNC_CLRN_AM) AS DM_FNC_CLRN_AM,
SUM(FCT_DLY.DM_FNC_PROMO_AM) AS DM_FNC_PROMO_AM,
SUM(FCT_DLY.SLS_FNC_AM) AS SLS_FNC_AM,
SUM(FCT_DLY.SLS_FNC_QTY) AS SLS_FNC_QTY,
SUM(FCT_DLY.SLS_FNC_PROMO_AM) AS SLS_FNC_PROMO_AM,
SUM(FCT_DLY.SLS_FNC_PROMO_MKDN_AM) AS SLS_FNC_PROMO_MKDN_AM,
SUM(FCT_DLY.SLS_FNC_CLRN_QTY) AS SLS_FNC_CLRN_QTY,
SUM(FCT_DLY.SLS_FNC_CLRN_AM) AS SLS_FNC_CLRN_AM,
SUM(FCT_DLY.SLS_FNC_CLRN_MKDN_AM) AS SLS_FNC_CLRN_MKDN_AM,
SUM(FCT_DLY.SLS_FNC_SCN_QTY) AS SLS_FNC_SCN_QTY,
SUM(FCT_DLY.SLS_FNC_AM_COMP) AS SLS_FNC_AM_COMP,
SUM(FCT_DLY.SLS_FNC_AM_NCOMP) AS SLS_FNC_AM_NCOMP,
SUM(FCT_DLY.INV_SHRK_AM) AS INV_SHRK_AM,
SUM(FCT_DLY.INV_CLRN_QTY) AS INV_CLRN_QTY,
SUM(FCT_DLY.SLS_FNC_AN_PLN_AM) AS SLS_FNC_AN_PLN_AM,
SUM(FCT_DLY.DM_FNC_AN_PLN_AM) AS DM_FNC_AN_PLN_AM,
SUM(FCT_DLY.INV_SHRK_AN_PLN_AM) AS INV_SHRK_AN_PLN_AM,
SUM(ISNULL(FCT_DLY.SLS_FNC_AM, 0) - ISNULL(FCT_DLY.DM_FNC_AM, 0)) as COGS_FNC,
SUM((ISNULL(FCT_DLY.DM_FNC_AM, 0) - ISNULL(FCT_DLY.DM_FNC_PROMO_AM, 0) ) - ISNULL(FCT_DLY.DM_FNC_CLRN_AM, 0)) as DM_FNC_RRTL_AM,
SUM(ISNULL(FCT_DLY.SLS_FNC_PROMO_MKDN_AM, 0) + ISNULL(FCT_DLY.SLS_FNC_CLRN_MKDN_AM, 0)) as SLS_FNC_MKDN_AM,
SUM((ISNULL(FCT_DLY.SLS_FNC_AM, 0) - ISNULL(FCT_DLY.SLS_FNC_PROMO_AM, 0)) - ISNULL(FCT_DLY.SLS_FNC_CLRN_AM, 0)) as SLS_FNC_RRTL_MKDN_AM,
SUM((ISNULL(FCT_DLY.SLS_FNC_AM, 0) - ISNULL(FCT_DLY.SLS_FNC_CLRN_AM, 0))) AS SLS_FNC_NCLRN_AM,
SUM((ISNULL(FCT_DLY.DM_FNC_AM, 0) - ISNULL(FCT_DLY.DM_FNC_CLRN_AM, 0))) AS DM_FNC_NCLRN_AM,
SUM(FCT_DLY.SLS_PLN_QT) AS SLS_PLN_QT
 from [ETL].[FCT_DLY_SL_P_SUB_CT_CALC_SALES_PLAN] FCT_DLY
 -------- get current FNC_MPRS_CT_ID and FNC_PKY_ID from buyer employee bridge table -----
 inner JOIN
 (

    SELECT pky_id, mprs_ct_id, LTRIM(RTRIM(mjr_p_sub_ct_id)) AS mjr_p_sub_ct_id, CURR_MPRS_CT_ID, CURR_PKY_ID
	FROM  dm_edw.byr_emp_pky_mprs_currprev_inf
    WHERE CAST(INS_DT as datetime) =
    (SELECT CAST(MAX(INS_DT) as datetime) AS INS_DT FROM dm_edw.byr_emp_pky_mprs_currprev_inf)
    AND mjr_p_sub_ct_id != ''
 ) AS BYR
 ON BYR.mprs_ct_id = FCT_DLY.FNC_MPRS_CT_ID AND BYR.pky_id = FCT_DLY.FNC_PKY_ID AND FCT_DLY.p_sub_ct_id = BYR.mjr_p_sub_ct_id
LEFT JOIN DM.DIM_GEO AS G ON G.GEO_HST_SKY = FCT_DLY.GEO_HST_SKY
LEFT JOIN DM.DIM_BYR_P_SUB_CT AS B ON B.BYR_HST_SKY = FCT_DLY.BYR_HST_SKY

GROUP BY
FCT_DLY.GEO_HST_SKY,
G.GEO_SKY,
FCT_DLY.TM_SKY,
FCT_DLY.BYR_HST_SKY,
B.BYR_SKY,
BYR.mjr_p_sub_ct_id,
FCT_DLY.UT_ID,
CURR_MPRS_CT_ID,
CURR_PKY_ID;
GO
