CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_P_SUB_CT_CALC_STG] AS SELECT
S.[GEO_HST_SKY]
,S.GEO_SKY
      ,S.[TM_SKY]
      ,S.[BYR_HST_SKY]
	  ,S.BYR_SKY
      ,ISNULL(P.P_HST_SKY, -1) AS P_HST_SKY
	  ,ISNULL(P.P_SKY, -1) AS P_SKY
      ,S.[UT_ID]
      ,SUM([DM_FNC_AM]) AS [DM_FNC_AM]
      ,SUM([DM_FNC_CLRN_AM]) AS [DM_FNC_CLRN_AM]
      ,SUM([DM_FNC_PROMO_AM]) AS [DM_FNC_PROMO_AM]
      ,SUM([SLS_FNC_AM])  AS [SLS_FNC_AM]
      ,SUM([SLS_FNC_QTY]) AS [SLS_FNC_QTY]
      ,SUM([SLS_FNC_PROMO_AM]) AS [SLS_FNC_PROMO_AM]
      ,SUM([SLS_FNC_PROMO_MKDN_AM]) AS [SLS_FNC_PROMO_MKDN_AM]
      ,SUM([SLS_FNC_CLRN_QTY]) AS [SLS_FNC_CLRN_QTY]
      ,SUM([SLS_FNC_CLRN_AM]) AS [SLS_FNC_CLRN_AM]
      ,SUM([SLS_FNC_CLRN_MKDN_AM]) AS [SLS_FNC_CLRN_MKDN_AM]
      ,SUM([SLS_FNC_SCN_QTY]) AS [SLS_FNC_SCN_QTY]
      ,SUM([SLS_FNC_AM_COMP]) AS [SLS_FNC_AM_COMP]
      ,SUM([SLS_FNC_AM_NCOMP]) AS [SLS_FNC_AM_NCOMP]
      ,SUM([INV_SHRK_AM]) AS [INV_SHRK_AM]
      ,SUM([INV_CLRN_QTY]) AS [INV_CLRN_QTY]
      ,SUM([SLS_FNC_AN_PLN_AM]) AS [SLS_FNC_AN_PLN_AM]
      ,SUM([DM_FNC_AN_PLN_AM]) AS [DM_FNC_AN_PLN_AM]
      ,SUM([INV_SHRK_AN_PLN_AM]) AS [INV_SHRK_AN_PLN_AM]
      ,SUM([COGS_FNC]) AS [COGS_FNC]
      ,SUM([DM_FNC_RRTL_AM]) AS [DM_FNC_RRTL_AM]
      ,SUM([SLS_FNC_MKDN_AM]) AS [SLS_FNC_MKDN_AM]
      ,SUM([SLS_FNC_RRTL_MKDN_AM]) AS [SLS_FNC_RRTL_MKDN_AM]
      ,SUM([SLS_FNC_NCLRN_AM]) AS [SLS_FNC_NCLRN_AM]
      ,SUM([DM_FNC_NCLRN_AM]) AS [DM_FNC_NCLRN_AM]
      ,SUM(SLS_PLN_QT) AS SLS_PLN_QT
	  ,SUM(ISNULL(S.DM_FNC_AM, 0) - ISNULL(S.DM_FNC_AN_PLN_AM, 0)) as DM_FNC_DIFF_TY_VS_AP
      ,SUM(ISNULL(S.SLS_FNC_AM, 0) - ISNULL(S.SLS_FNC_AN_PLN_AM, 0)) as SLS_FNC_DIFF_TY_VS_AP
       ,SUM(ISNULL(S.INV_SHRK_AM, 0) - ISNULL(S.INV_SHRK_AN_PLN_AM, 0)) as INV_SHRK_DIFF_TY_VS_AP
       ,SUM(ISNULL([SLS_FNC_QTY], 0) - ISNULL(SLS_PLN_QT, 0)) AS SLS_PLN_QT_DIFF_TY_VS_AP
	  ,SUM([SLS_FNC_AM_LY_CLDR]) AS [SLS_FNC_AM_LY_CLDR]
      ,SUM([SLS_FNC_QTY_LY_CLDR]) AS [SLS_FNC_QTY_LY_CLDR]
      ,SUM([DM_FNC_AM_LY_CLDR]) AS [DM_FNC_AM_LY_CLDR]
      ,SUM([DM_FNC_CLRN_AM_LY_CLDR]) AS [DM_FNC_CLRN_AM_LY_CLDR]
      ,SUM([DM_FNC_PROMO_AM_LY_CLDR]) AS [DM_FNC_PROMO_AM_LY_CLDR]
      ,SUM([SLS_FNC_CLRN_AM_LY_CLDR]) AS [SLS_FNC_CLRN_AM_LY_CLDR]
      ,SUM([SLS_FNC_CLRN_MKDN_AM_LY_CLDR]) AS [SLS_FNC_CLRN_MKDN_AM_LY_CLDR]
      ,SUM([SLS_FNC_PROMO_AM_LY_CLDR]) AS [SLS_FNC_PROMO_AM_LY_CLDR]
      ,SUM([SLS_FNC_PROMO_MKDN_AM_LY_CLDR]) AS [SLS_FNC_PROMO_MKDN_AM_LY_CLDR]
      ,SUM([SLS_FNC_CLRN_QTY_LY_CLDR]) AS [SLS_FNC_CLRN_QTY_LY_CLDR]
      ,SUM([SLS_FNC_SCN_QTY_LY_CLDR]) AS [SLS_FNC_SCN_QTY_LY_CLDR]
      ,SUM([SLS_FNC_AM_COMP_LY_CLDR]) AS [SLS_FNC_AM_COMP_LY_CLDR]
      ,SUM([SLS_FNC_AM_NCOMP_LY_CLDR]) AS [SLS_FNC_AM_NCOMP_LY_CLDR]
      ,SUM([INV_SHRK_AM_LY_CLDR]) AS [INV_SHRK_AM_LY_CLDR]
      ,SUM([INV_CLRN_QTY_LY_CLDR]) AS [INV_CLRN_QTY_LY_CLDR]
      ,SUM([COGS_FNC_LY_CLDR]) AS [COGS_FNC_LY_CLDR]
      ,SUM([DM_FNC_RRTL_AM_LY_CLDR]) AS [DM_FNC_RRTL_AM_LY_CLDR]
      ,SUM([SLS_FNC_MKDN_AM_LY_CLDR]) AS [SLS_FNC_MKDN_AM_LY_CLDR]
      ,SUM([SLS_FNC_RRTL_MKDN_AM_LY_CLDR]) AS [SLS_FNC_RRTL_MKDN_AM_LY_CLDR]
      ,SUM([SLS_FNC_NCLRN_AM_LY_CLDR]) AS [SLS_FNC_NCLRN_AM_LY_CLDR]
      ,SUM([DM_FNC_NCLRN_AM_LY_CLDR]) AS [DM_FNC_NCLRN_AM_LY_CLDR]

	   ,SUM([SLS_FNC_AM_LY_FSC]) AS [SLS_FNC_AM_LY_FSC]
      ,SUM([SLS_FNC_QTY_LY_FSC]) AS [SLS_FNC_QTY_LY_FSC]
      ,SUM([DM_FNC_AM_LY_FSC]) AS [DM_FNC_AM_LY_FSC]
      ,SUM([DM_FNC_CLRN_AM_LY_FSC]) AS [DM_FNC_CLRN_AM_LY_FSC]
      ,SUM([DM_FNC_PROMO_AM_LY_FSC]) AS [DM_FNC_PROMO_AM_LY_FSC]
      ,SUM([SLS_FNC_CLRN_AM_LY_FSC]) AS [SLS_FNC_CLRN_AM_LY_FSC]
      ,SUM([SLS_FNC_CLRN_MKDN_AM_LY_FSC]) AS [SLS_FNC_CLRN_MKDN_AM_LY_FSC]
      ,SUM([SLS_FNC_PROMO_AM_LY_FSC]) AS [SLS_FNC_PROMO_AM_LY_FSC]
      ,SUM([SLS_FNC_PROMO_MKDN_AM_LY_FSC]) AS [SLS_FNC_PROMO_MKDN_AM_LY_FSC]
      ,SUM([SLS_FNC_CLRN_QTY_LY_FSC]) AS [SLS_FNC_CLRN_QTY_LY_FSC]
      ,SUM([SLS_FNC_SCN_QTY_LY_FSC]) AS [SLS_FNC_SCN_QTY_LY_FSC]
      ,SUM([SLS_FNC_AM_COMP_LY_FSC]) AS [SLS_FNC_AM_COMP_LY_FSC]
      ,SUM([SLS_FNC_AM_NCOMP_LY_FSC]) AS [SLS_FNC_AM_NCOMP_LY_FSC]
      ,SUM([INV_SHRK_AM_LY_FSC]) AS [INV_SHRK_AM_LY_FSC]
      ,SUM([INV_CLRN_QTY_LY_FSC]) AS [INV_CLRN_QTY_LY_FSC]
      ,SUM([COGS_FNC_LY_FSC]) AS [COGS_FNC_LY_FSC]
      ,SUM([DM_FNC_RRTL_AM_LY_FSC]) AS [DM_FNC_RRTL_AM_LY_FSC]
      ,SUM([SLS_FNC_MKDN_AM_LY_FSC]) AS [SLS_FNC_MKDN_AM_LY_FSC]
      ,SUM([SLS_FNC_RRTL_MKDN_AM_LY_FSC]) AS [SLS_FNC_RRTL_MKDN_AM_LY_FSC]
      ,SUM([SLS_FNC_NCLRN_AM_LY_FSC]) AS [SLS_FNC_NCLRN_AM_LY_FSC]
      ,SUM([DM_FNC_NCLRN_AM_LY_FSC]) AS [DM_FNC_NCLRN_AM_LY_FSC]

	  ,SUM([SLS_FNC_AM_LY_HLDY]) AS [SLS_FNC_AM_LY_HLDY]

      ,SUM([SLS_FNC_QTY_LY_HLDY]) AS [SLS_FNC_QTY_LY_HLDY]
      ,SUM( [DM_FNC_AM_LY_HLDY]) AS [DM_FNC_AM_LY_HLDY]
      ,SUM( [DM_FNC_CLRN_AM_LY_HLDY]) AS [DM_FNC_CLRN_AM_LY_HLDY]
      ,SUM( [DM_FNC_PROMO_AM_LY_HLDY]) AS [DM_FNC_PROMO_AM_LY_HLDY]

      ,SUM([SLS_FNC_CLRN_AM_LY_HLDY]) AS [SLS_FNC_CLRN_AM_LY_HLDY]
      ,SUM([SLS_FNC_CLRN_MKDN_AM_LY_HLDY]) AS [SLS_FNC_CLRN_MKDN_AM_LY_HLDY]

      ,SUM([SLS_FNC_PROMO_AM_LY_HLDY]) AS [SLS_FNC_PROMO_AM_LY_HLDY]

      ,SUM([SLS_FNC_PROMO_MKDN_AM_LY_HLDY]) AS [SLS_FNC_PROMO_MKDN_AM_LY_HLDY]

      ,SUM([SLS_FNC_CLRN_QTY_LY_HLDY]) AS [SLS_FNC_CLRN_QTY_LY_HLDY]
      ,SUM([SLS_FNC_SCN_QTY_LY_HLDY]) AS [SLS_FNC_SCN_QTY_LY_HLDY]
      ,SUM([SLS_FNC_AM_COMP_LY_HLDY]) AS [SLS_FNC_AM_COMP_LY_HLDY]

      ,SUM([SLS_FNC_AM_NCOMP_LY_HLDY]) AS  [SLS_FNC_AM_NCOMP_LY_HLDY]
      ,SUM([INV_SHRK_AM_LY_HLDY]) AS [INV_SHRK_AM_LY_HLDY]
      ,SUM([INV_CLRN_QTY_LY_HLDY]) AS [INV_CLRN_QTY_LY_HLDY]
      ,SUM([COGS_FNC_LY_HLDY]) AS [COGS_FNC_LY_HLDY]
      ,SUM([DM_FNC_RRTL_AM_LY_HLDY]) AS [DM_FNC_RRTL_AM_LY_HLDY]
      ,SUM([SLS_FNC_MKDN_AM_LY_HLDY]) AS [SLS_FNC_MKDN_AM_LY_HLDY]
      ,SUM([SLS_FNC_RRTL_MKDN_AM_LY_HLDY]) AS [SLS_FNC_RRTL_MKDN_AM_LY_HLDY]
      ,SUM([SLS_FNC_NCLRN_AM_LY_HLDY]) AS [SLS_FNC_NCLRN_AM_LY_HLDY]
      ,SUM([DM_FNC_NCLRN_AM_LY_HLDY]) AS [DM_FNC_NCLRN_AM_LY_HLDY]

,SUM(ISNULL(SLS_FNC_AM, 0) - ISNULL(SLS_FNC_AM_LY_CLDR, 0)) AS SLS_FNC_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(DM_FNC_AM, 0) - ISNULL(DM_FNC_AM_LY_CLDR, 0)) AS DM_FNC_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(DM_FNC_CLRN_AM, 0) - ISNULL(DM_FNC_CLRN_AM_LY_CLDR, 0)) AS DM_FNC_CLRN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(DM_FNC_PROMO_AM, 0) - ISNULL(DM_FNC_PROMO_AM_LY_CLDR, 0)) AS DM_FNC_PROMO_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_CLRN_AM, 0) - ISNULL(SLS_FNC_CLRN_AM_LY_CLDR, 0)) AS SLS_FNC_CLRN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_CLRN_MKDN_AM, 0) - ISNULL(SLS_FNC_CLRN_MKDN_AM_LY_CLDR, 0)) AS SLS_FNC_CLRN_MKDN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_PROMO_AM, 0) - ISNULL(SLS_FNC_PROMO_AM_LY_CLDR, 0)) AS SLS_FNC_PROMO_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_PROMO_MKDN_AM, 0) - ISNULL(SLS_FNC_PROMO_MKDN_AM_LY_CLDR, 0)) AS SLS_FNC_PROMO_MKDN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_CLRN_QTY, 0) - ISNULL(SLS_FNC_CLRN_QTY_LY_CLDR, 0)) AS SLS_FNC_CLRN_QTY_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_QTY, 0) - ISNULL(SLS_FNC_QTY_LY_CLDR, 0)) AS SLS_FNC_QTY_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_SCN_QTY, 0) - ISNULL(SLS_FNC_SCN_QTY_LY_CLDR, 0)) AS SLS_FNC_SCN_QTY_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_AM_COMP, 0) - ISNULL(SLS_FNC_AM_COMP_LY_CLDR, 0)) AS SLS_FNC_AM_COMP_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_AM_NCOMP, 0) - ISNULL(SLS_FNC_AM_NCOMP_LY_CLDR, 0)) AS SLS_FNC_AM_NCOMP_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(INV_SHRK_AM, 0) - ISNULL(INV_SHRK_AM_LY_CLDR, 0)) AS INV_SHRK_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_CLDR, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(COGS_FNC, 0) - ISNULL(COGS_FNC_LY_CLDR, 0)) AS COGS_FNC_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(DM_FNC_RRTL_AM, 0) - ISNULL(DM_FNC_RRTL_AM_LY_CLDR, 0)) AS DM_FNC_RRTL_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_MKDN_AM, 0) - ISNULL(SLS_FNC_MKDN_AM_LY_CLDR, 0)) AS SLS_FNC_MKDN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_RRTL_MKDN_AM, 0) - ISNULL(SLS_FNC_RRTL_MKDN_AM_LY_CLDR, 0)) AS SLS_FNC_RRTL_MKDN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(SLS_FNC_NCLRN_AM, 0) - ISNULL([SLS_FNC_NCLRN_AM_LY_CLDR], 0)) as SLS_FNC_NCLRN_AM_DIFF_TY_VS_LY_CLDR
,SUM(ISNULL(DM_FNC_NCLRN_AM, 0) - ISNULL([DM_FNC_NCLRN_AM_LY_CLDR], 0)) as DM_FNC_NCLRN_AM_DIFF_TY_VS_LY_CLDR

,SUM(ISNULL(SLS_FNC_AM, 0) - ISNULL(SLS_FNC_AM_LY_FSC, 0)) AS SLS_FNC_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(DM_FNC_AM, 0) - ISNULL(DM_FNC_AM_LY_FSC, 0)) AS DM_FNC_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(DM_FNC_CLRN_AM, 0) - ISNULL(DM_FNC_CLRN_AM_LY_FSC, 0)) AS DM_FNC_CLRN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(DM_FNC_PROMO_AM, 0) - ISNULL(DM_FNC_PROMO_AM_LY_FSC, 0)) AS DM_FNC_PROMO_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_CLRN_AM, 0) - ISNULL(SLS_FNC_CLRN_AM_LY_FSC, 0)) AS SLS_FNC_CLRN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_CLRN_MKDN_AM, 0) - ISNULL(SLS_FNC_CLRN_MKDN_AM_LY_FSC, 0)) AS SLS_FNC_CLRN_MKDN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_PROMO_AM, 0) - ISNULL(SLS_FNC_PROMO_AM_LY_FSC, 0)) AS SLS_FNC_PROMO_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_PROMO_MKDN_AM, 0) - ISNULL(SLS_FNC_PROMO_MKDN_AM_LY_FSC, 0)) AS SLS_FNC_PROMO_MKDN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_CLRN_QTY, 0) - ISNULL(SLS_FNC_CLRN_QTY_LY_FSC, 0)) AS SLS_FNC_CLRN_QTY_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_QTY, 0) - ISNULL(SLS_FNC_QTY_LY_FSC, 0)) AS SLS_FNC_QTY_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_SCN_QTY, 0) - ISNULL(SLS_FNC_SCN_QTY_LY_FSC, 0)) AS SLS_FNC_SCN_QTY_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_AM_COMP, 0) - ISNULL(SLS_FNC_AM_COMP_LY_FSC, 0)) AS SLS_FNC_AM_COMP_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_AM_NCOMP, 0) - ISNULL(SLS_FNC_AM_NCOMP_LY_FSC, 0)) AS SLS_FNC_AM_NCOMP_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(INV_SHRK_AM, 0) - ISNULL(INV_SHRK_AM_LY_FSC, 0)) AS INV_SHRK_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_FSC, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(COGS_FNC, 0) - ISNULL(COGS_FNC_LY_FSC, 0)) AS COGS_FNC_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(DM_FNC_RRTL_AM, 0) - ISNULL(DM_FNC_RRTL_AM_LY_FSC, 0)) AS DM_FNC_RRTL_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_MKDN_AM, 0) - ISNULL(SLS_FNC_MKDN_AM_LY_FSC, 0)) AS SLS_FNC_MKDN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_RRTL_MKDN_AM, 0) - ISNULL(SLS_FNC_RRTL_MKDN_AM_LY_FSC, 0)) AS SLS_FNC_RRTL_MKDN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(SLS_FNC_NCLRN_AM, 0) - ISNULL([SLS_FNC_NCLRN_AM_LY_FSC], 0)) as SLS_FNC_NCLRN_AM_DIFF_TY_VS_LY_FSC
,SUM(ISNULL(DM_FNC_NCLRN_AM, 0) - ISNULL([DM_FNC_NCLRN_AM_LY_FSC], 0)) as DM_FNC_NCLRN_AM_DIFF_TY_VS_LY_FSC

,SUM(ISNULL(SLS_FNC_AM, 0) - ISNULL(SLS_FNC_AM_LY_HLDY, 0)) AS SLS_FNC_AM_DIFF_TY_VS_LY_HLDY
,SUM(
ISNULL(DM_FNC_AM, 0) - ISNULL(DM_FNC_AM_LY_HLDY, 0)) AS DM_FNC_AM_DIFF_TY_VS_LY_HLDY

,SUM(
ISNULL(DM_FNC_CLRN_AM, 0) - ISNULL(DM_FNC_CLRN_AM_LY_HLDY, 0)) AS DM_FNC_CLRN_AM_DIFF_TY_VS_LY_HLDY

,SUM(
ISNULL(DM_FNC_PROMO_AM, 0) - ISNULL(DM_FNC_PROMO_AM_LY_HLDY, 0)) AS DM_FNC_PROMO_AM_DIFF_TY_VS_LY_HLDY

,SUM(
ISNULL(SLS_FNC_CLRN_AM, 0) - ISNULL(SLS_FNC_CLRN_AM_LY_HLDY, 0)) AS SLS_FNC_CLRN_AM_DIFF_TY_VS_LY_HLDY

,SUM(
ISNULL(SLS_FNC_CLRN_MKDN_AM, 0) - ISNULL(SLS_FNC_CLRN_MKDN_AM_LY_HLDY, 0)) AS SLS_FNC_CLRN_MKDN_AM_DIFF_TY_VS_LY_HLDY

,SUM(
ISNULL(SLS_FNC_PROMO_AM, 0) - ISNULL(SLS_FNC_PROMO_AM_LY_HLDY, 0)) AS SLS_FNC_PROMO_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_PROMO_MKDN_AM, 0) - ISNULL(SLS_FNC_PROMO_MKDN_AM_LY_HLDY, 0)) AS SLS_FNC_PROMO_MKDN_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_CLRN_QTY, 0) - ISNULL(SLS_FNC_CLRN_QTY_LY_HLDY, 0)) AS SLS_FNC_CLRN_QTY_DIFF_TY_VS_LY_HLDY
,SUM(ISNULL(SLS_FNC_QTY, 0) - ISNULL(SLS_FNC_QTY_LY_HLDY, 0)) AS SLS_FNC_QTY_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_SCN_QTY, 0) - ISNULL(SLS_FNC_SCN_QTY_LY_HLDY, 0)) AS SLS_FNC_SCN_QTY_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_AM_COMP, 0) - ISNULL(SLS_FNC_AM_COMP_LY_HLDY, 0)) AS SLS_FNC_AM_COMP_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_AM_NCOMP, 0) - ISNULL(SLS_FNC_AM_NCOMP_LY_HLDY, 0)) AS SLS_FNC_AM_NCOMP_DIFF_TY_VS_LY_HLDY

,SUM( ISNULL(INV_SHRK_AM, 0) - ISNULL(INV_SHRK_AM_LY_HLDY, 0)) AS INV_SHRK_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(INV_CLRN_QTY, 0) - ISNULL(INV_CLRN_QTY_LY_HLDY, 0)) AS INV_CLRN_QTY_DIFF_TY_VS_LY_HLDY

,SUM( ISNULL(COGS_FNC, 0) - ISNULL(COGS_FNC_LY_HLDY, 0)) AS COGS_FNC_DIFF_TY_VS_LY_HLDY

,SUM( ISNULL(DM_FNC_RRTL_AM, 0) - ISNULL(DM_FNC_RRTL_AM_LY_HLDY, 0) ) AS DM_FNC_RRTL_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_MKDN_AM, 0) - ISNULL(SLS_FNC_MKDN_AM_LY_HLDY, 0)) AS SLS_FNC_MKDN_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_RRTL_MKDN_AM, 0) - ISNULL(SLS_FNC_RRTL_MKDN_AM_LY_HLDY, 0)) AS SLS_FNC_RRTL_MKDN_AM_DIFF_TY_VS_LY_HLDY

,SUM(ISNULL(SLS_FNC_NCLRN_AM, 0) - ISNULL([SLS_FNC_NCLRN_AM_LY_HLDY], 0)) as SLS_FNC_NCLRN_AM_DIFF_TY_VS_LY_HLDY
,SUM(ISNULL(DM_FNC_NCLRN_AM, 0) - ISNULL([DM_FNC_NCLRN_AM_LY_HLDY], 0)) as DM_FNC_NCLRN_AM_DIFF_TY_VS_LY_HLDY

  FROM [ETL].[FCT_DLY_SL_P_SUB_CT_INCR_CURR_PLN] AS S
  INNER JOIN DM.DIM_TM AS T ON T.TM_SKY = S.TM_SKY
  LEFT JOIN (
SELECT [P_HST_SKY]
      ,[P_SKY]
      ,[P_SUB_CT_ID]
      ,FNC_PKY_ID
      ,FNC_MPRS_CT_ID
      ,[VLD_FROM]
      ,[VLD_TO]
  FROM [PRES].[DIM_P_L3]) AS P
  ON P.[P_SUB_CT_ID] = S.[P_SUB_CT_ID] AND
  S.FNC_MPRS_CT_ID = P.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = P.FNC_PKY_ID
 AND T.DAY_DT BETWEEN CAST(VLD_FROM as date) AND ISNULL(CAST(VLD_TO as date), CAST('2099-01-01' as date))
 LEFT JOIN [ETL].[FCT_DLY_SL_P_SUB_CT_INCR_LY_CLDR] AS CLDR
 ON CLDR.GEO_SKY = S.GEO_SKY AND CLDR.UT_ID = S.UT_ID AND CLDR.TM_SKY = S.TM_SKY
 AND CLDR.BYR_SKY = S.BYR_SKY
 AND
 S.FNC_MPRS_CT_ID = CLDR.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = CLDR.FNC_PKY_ID

  LEFT JOIN [ETL].[FCT_DLY_SL_P_SUB_CT_INCR_LY_FSC] AS FSC
 ON FSC.GEO_SKY = S.GEO_SKY AND FSC.UT_ID = S.UT_ID AND FSC.TM_SKY = S.TM_SKY
 AND FSC.BYR_SKY = S.BYR_SKY
 AND
 S.FNC_MPRS_CT_ID = FSC.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = FSC.FNC_PKY_ID

 LEFT JOIN [ETL].[FCT_DLY_SL_P_SUB_CT_INCR_LY_HLDY] AS HLDY
 ON HLDY.GEO_SKY = S.GEO_SKY AND HLDY.UT_ID = S.UT_ID AND HLDY.TM_SKY = S.TM_SKY
 AND HLDY.BYR_SKY = S.BYR_SKY
 AND
 S.FNC_MPRS_CT_ID = HLDY.FNC_MPRS_CT_ID AND S.FNC_PKY_ID = HLDY.FNC_PKY_ID

 GROUP BY
 S.[GEO_HST_SKY]
,S.GEO_SKY
      ,S.[TM_SKY]
      ,S.[BYR_HST_SKY]
	  ,S.BYR_SKY
      ,ISNULL(P.P_HST_SKY, -1)
	  ,ISNULL(P.P_SKY, -1)
      ,S.[UT_ID];
