CREATE VIEW [ETL].[V_SRC_FCT_DLY_SL_MB_P_SUB_CT_CALC_STG] AS SELECT
       S.[GEO_HST_SKY]
	  ,S.GEO_SKY
      ,S.[TM_SKY]
      ,S.[CHNL_HST_SKY]
	  ,S.CHNL_SKY
      ,ISNULL(S.[BYR_HST_SKY], -1) AS [BYR_HST_SKY]
	  ,ISNULL(S.BYR_SKY, -1) AS BYR_SKY
	  ,S.[P_SUB_CT_ID]
      ,S.[UT_ID]
      ,ISNULL(S.[SLS_MKT_BSKT_AM], 0) AS [SLS_MKT_BSKT_AM]
      ,ISNULL(S.[SLS_MKT_BSKT_QTY], 0) AS [SLS_MKT_BSKT_QTY]
      ,ISNULL(S.[DMGN_MKT_BSKT_AM], 0) AS [DMGN_MKT_BSKT_AM]
      ,ISNULL(S.[COGS_MKT_BSKT], 0) AS [COGS_MKT_BSKT]
      ,ISNULL(S.[DGTL_UT_SLS_AM], 0) AS [DGTL_UT_SLS_AM]
      ,ISNULL(S.[CALC_CIRC_AM], 0) AS [CALC_CIRC_AM]
      ,ISNULL(S.[CALC_CLRN_AM], 0) AS [CALC_CLRN_AM]
      ,ISNULL(S.[CALC_DGTL_CIRC_AM], 0) AS [CALC_DGTL_CIRC_AM]
      ,ISNULL(S.[CALC_HOOK_AM], 0) AS [CALC_HOOK_AM]
      ,ISNULL(S.[CALC_DUM_AM], 0) AS [CALC_DUM_AM]
      ,ISNULL(S.[CALC_MDWK_AM], 0) AS [CALC_MDWK_AM]
      ,ISNULL(S.[CALC_MPRKS_AM], 0) AS [CALC_MPRKS_AM]
      ,ISNULL(S.[CALC_OTH_AM], 0) AS [CALC_OTH_AM]
      ,ISNULL(S.[CALC_PERS_RWRD_AM], 0) AS [CALC_PERS_RWRD_AM]
      ,ISNULL(S.[CALC_SHLF_EDG_AM], 0) AS [CALC_SHLF_EDG_AM]
      ,ISNULL(S.[CALC_SP_EVNT_AM], 0) AS [CALC_SP_EVNT_AM]
      ,ISNULL(S.[CALC_TEAM_MMB_AM], 0) AS [CALC_TEAM_MMB_AM]
      ,ISNULL(S.[DGTL_SHOP_SLS_AM], 0) AS [DGTL_SHOP_SLS_AM]
      ,ISNULL(S.[SHOP_AND_SCN_STO_SLS_AM], 0) AS [SHOP_AND_SCN_STO_SLS_AM]
      ,ISNULL(S.[SHOP_AND_SCN_SLS_AM], 0) AS [SHOP_AND_SCN_SLS_AM]
      ,ISNULL(S.[SLS_MKT_BSKT_AM_COMP], 0) AS [SLS_MKT_BSKT_AM_COMP]
      ,ISNULL(S.[SLS_MKT_BSKT_AM_NCOMP], 0) AS [SLS_MKT_BSKT_AM_NCOMP]
	  ,FLD.[SLS_MKT_BSKT_AM_LY_FSC]
      ,FLD.[DMGN_MKT_BSKT_AM_LY_FSC]
      ,FLD.[COGS_MKT_BSKT_LY_FSC]
      ,FLD.[DGTL_UT_SLS_AM_LY_FSC]
      ,FLD.[DGTL_SHOP_SLS_AM_LY_FSC]
      ,FLD.[SHOP_AND_SCN_STO_SLS_AM_LY_FSC]
      ,FLD.[SHOP_AND_SCN_SLS_AM_LY_FSC]
      ,FLD.[SLS_MKT_BSKT_QTY_LY_FSC]
      ,FLD.[SLS_MKT_BSKT_AM_COMP_LY_FSC]
      ,FLD.[CALC_CIRC_AM_LY_FSC]
      ,FLD.[CALC_CLRN_AM_LY_FSC]
      ,FLD.[CALC_DGTL_CIRC_AM_LY_FSC]
      ,FLD.[CALC_HOOK_AM_LY_FSC]
      ,FLD.[CALC_DUM_AM_LY_FSC]
      ,FLD.[CALC_MDWK_AM_LY_FSC]
      ,FLD.[CALC_MPRKS_AM_LY_FSC]
      ,FLD.[CALC_OTH_AM_LY_FSC]
      ,FLD.[CALC_PERS_RWRD_AM_LY_FSC]
      ,FLD.[CALC_SHLF_EDG_AM_LY_FSC]
      ,FLD.[CALC_SP_EVNT_AM_LY_FSC]
      ,FLD.[CALC_TEAM_MMB_AM_LY_FSC]
      ,FLD.[SLS_MKT_BSKT_AM_NCOMP_LY_FSC]

	   ,CLDR.[SLS_MKT_BSKT_AM_LY_CLDR]
      ,CLDR.[DMGN_MKT_BSKT_AM_LY_CLDR]
      ,CLDR.[COGS_MKT_BSKT_LY_CLDR]
      ,CLDR.[DGTL_UT_SLS_AM_LY_CLDR]
      ,CLDR.[DGTL_SHOP_SLS_AM_LY_CLDR]
      ,CLDR.[SHOP_AND_SCN_STO_SLS_AM_LY_CLDR]
      ,CLDR.[SHOP_AND_SCN_SLS_AM_LY_CLDR]
      ,CLDR.[SLS_MKT_BSKT_QTY_LY_CLDR]
      ,CLDR.[SLS_MKT_BSKT_AM_COMP_LY_CLDR]
      ,CLDR.[CALC_CIRC_AM_LY_CLDR]
      ,CLDR.[CALC_CLRN_AM_LY_CLDR]
      ,CLDR.[CALC_DGTL_CIRC_AM_LY_CLDR]
      ,CLDR.[CALC_HOOK_AM_LY_CLDR]
      ,CLDR.[CALC_DUM_AM_LY_CLDR]
      ,CLDR.[CALC_MDWK_AM_LY_CLDR]
      ,CLDR.[CALC_MPRKS_AM_LY_CLDR]
      ,CLDR.[CALC_OTH_AM_LY_CLDR]
      ,CLDR.[CALC_PERS_RWRD_AM_LY_CLDR]
      ,CLDR.[CALC_SHLF_EDG_AM_LY_CLDR]
      ,CLDR.[CALC_SP_EVNT_AM_LY_CLDR]
      ,CLDR.[CALC_TEAM_MMB_AM_LY_CLDR]
      ,CLDR.[SLS_MKT_BSKT_AM_NCOMP_LY_CLDR]

	  , HLDY_LY.SLS_MKT_BSKT_AM_LY_HLDY
,HLDY_LY.SLS_MKT_BSKT_QTY_LY_HLDY
,HLDY_LY.DMGN_MKT_BSKT_AM_LY_HLDY
,HLDY_LY.COGS_MKT_BSKT_LY_HLDY
,HLDY_LY.DGTL_UT_SLS_AM_LY_HLDY
,HLDY_LY.CALC_CIRC_AM_LY_HLDY
,HLDY_LY.CALC_CLRN_AM_LY_HLDY
,HLDY_LY.CALC_DGTL_CIRC_AM_LY_HLDY
, HLDY_LY.CALC_HOOK_AM_LY_HLDY
,HLDY_LY.CALC_DUM_AM_LY_HLDY
,HLDY_LY.CALC_MDWK_AM_LY_HLDY
, HLDY_LY.CALC_MPRKS_AM_LY_HLDY
, HLDY_LY.CALC_OTH_AM_LY_HLDY
, HLDY_LY.CALC_PERS_RWRD_AM_LY_HLDY
, HLDY_LY.CALC_SHLF_EDG_AM_LY_HLDY
,HLDY_LY.CALC_SP_EVNT_AM_LY_HLDY
,HLDY_LY.CALC_TEAM_MMB_AM_LY_HLDY
, HLDY_LY.DGTL_SHOP_SLS_AM_LY_HLDY
, HLDY_LY.SHOP_AND_SCN_STO_SLS_AM_LY_HLDY
, HLDY_LY.SHOP_AND_SCN_SLS_AM_LY_HLDY
, HLDY_LY.SLS_MKT_BSKT_AM_COMP_LY_HLDY
,HLDY_LY.SLS_MKT_BSKT_AM_NCOMP_LY_HLDY


,ISNULL(s.SLS_MKT_BSKT_AM, 0) - ISNULL(FLD.SLS_MKT_BSKT_AM_LY_FSC, 0) AS SLS_MKT_BSKT_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.DGTL_UT_SLS_AM, 0) - ISNULL(FLD.DGTL_UT_SLS_AM_LY_FSC, 0) AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.DMGN_MKT_BSKT_AM, 0) - ISNULL(FLD.DMGN_MKT_BSKT_AM_LY_FSC, 0) AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.COGS_MKT_BSKT, 0) - ISNULL(FLD.COGS_MKT_BSKT_LY_FSC, 0) AS COGS_MKT_BSKT_DIFF_TY_VS_LY_FSC

,ISNULL(s.DGTL_SHOP_SLS_AM, 0) - ISNULL(FLD.DGTL_SHOP_SLS_AM_LY_FSC, 0) AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.SHOP_AND_SCN_STO_SLS_AM, 0) - ISNULL(FLD.SHOP_AND_SCN_STO_SLS_AM_LY_FSC, 0) AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.SHOP_AND_SCN_SLS_AM, 0) - ISNULL(FLD.SHOP_AND_SCN_SLS_AM_LY_FSC, 0) AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.SLS_MKT_BSKT_QTY, 0) - ISNULL(FLD.SLS_MKT_BSKT_QTY_LY_FSC, 0) AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_FSC

,ISNULL(s.SLS_MKT_BSKT_AM_COMP, 0) - ISNULL(FLD.SLS_MKT_BSKT_AM_COMP_LY_FSC, 0) AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_CIRC_AM, 0) - ISNULL(FLD.CALC_CIRC_AM_LY_FSC, 0) AS CALC_CIRC_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_CLRN_AM, 0) - ISNULL(FLD.CALC_CLRN_AM_LY_FSC, 0) AS CALC_CLRN_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_DGTL_CIRC_AM, 0) - ISNULL(FLD.CALC_DGTL_CIRC_AM_LY_FSC, 0) AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_HOOK_AM, 0) - ISNULL(FLD.CALC_HOOK_AM_LY_FSC, 0) AS CALC_HOOK_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_DUM_AM, 0) - ISNULL(FLD.CALC_DUM_AM_LY_FSC, 0) AS CALC_DUM_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_MDWK_AM, 0) - ISNULL(FLD.CALC_MDWK_AM_LY_FSC, 0) AS CALC_MDWK_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_MPRKS_AM, 0) - ISNULL(FLD.CALC_MPRKS_AM_LY_FSC, 0) AS CALC_MPRKS_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_OTH_AM, 0) - ISNULL(FLD.CALC_OTH_AM_LY_FSC, 0) AS CALC_OTH_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_PERS_RWRD_AM, 0) - ISNULL(FLD.CALC_PERS_RWRD_AM_LY_FSC, 0) AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_SHLF_EDG_AM, 0) - ISNULL(FLD.CALC_SHLF_EDG_AM_LY_FSC, 0) AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_SP_EVNT_AM, 0) - ISNULL(FLD.CALC_SP_EVNT_AM_LY_FSC, 0) AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.CALC_TEAM_MMB_AM, 0) - ISNULL(FLD.CALC_TEAM_MMB_AM_LY_FSC, 0) AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_FSC

,ISNULL(s.SLS_MKT_BSKT_AM_NCOMP, 0) - ISNULL(FLD.SLS_MKT_BSKT_AM_NCOMP_LY_FSC, 0) AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_FSC



--,s.DGTL_UT_SLS_AM - FLD.DGTL_UT_SLS_AM_LY_FSC AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_FSC
--,s.DMGN_MKT_BSKT_AM - FLD.DMGN_MKT_BSKT_AM_LY_FSC AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_FSC
--,s.COGS_MKT_BSKT - FLD.COGS_MKT_BSKT_LY_FSC AS COGS_MKT_BSKT_DIFF_TY_VS_LY_FSC
--,s.DGTL_SHOP_SLS_AM - FLD.DGTL_SHOP_SLS_AM_LY_FSC AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_FSC
--,s.SHOP_AND_SCN_STO_SLS_AM - FLD.SHOP_AND_SCN_STO_SLS_AM_LY_FSC AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_FSC
--,s.SHOP_AND_SCN_SLS_AM - FLD.SHOP_AND_SCN_SLS_AM_LY_FSC AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_FSC
--,s.SLS_MKT_BSKT_QTY - FLD.SLS_MKT_BSKT_QTY_LY_FSC AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_FSC
--,s.SLS_MKT_BSKT_AM_COMP - FLD.SLS_MKT_BSKT_AM_COMP_LY_FSC AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_FSC
--,s.CALC_CIRC_AM - FLD.CALC_CIRC_AM_LY_FSC AS CALC_CIRC_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_CLRN_AM - FLD.CALC_CLRN_AM_LY_FSC AS CALC_CLRN_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_DGTL_CIRC_AM - FLD.CALC_DGTL_CIRC_AM_LY_FSC AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_HOOK_AM - FLD.CALC_HOOK_AM_LY_FSC AS CALC_HOOK_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_DUM_AM - FLD.CALC_DUM_AM_LY_FSC AS CALC_DUM_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_MDWK_AM - FLD.CALC_MDWK_AM_LY_FSC AS CALC_MDWK_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_MPRKS_AM - FLD.CALC_MPRKS_AM_LY_FSC AS CALC_MPRKS_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_OTH_AM - FLD.CALC_OTH_AM_LY_FSC AS CALC_OTH_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_PERS_RWRD_AM - FLD.CALC_PERS_RWRD_AM_LY_FSC AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_SHLF_EDG_AM - FLD.CALC_SHLF_EDG_AM_LY_FSC AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_SP_EVNT_AM - FLD.CALC_SP_EVNT_AM_LY_FSC AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_FSC
--,s.CALC_TEAM_MMB_AM - FLD.CALC_TEAM_MMB_AM_LY_FSC AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_FSC
--,s.SLS_MKT_BSKT_AM_NCOMP - FLD.SLS_MKT_BSKT_AM_NCOMP_LY_FSC AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_FSC

,ISNULL(s.SLS_MKT_BSKT_AM, 0) - ISNULL(HLDY_LY.SLS_MKT_BSKT_AM_LY_HLDY, 0) AS SLS_MKT_BSKT_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.DMGN_MKT_BSKT_AM, 0) - ISNULL(HLDY_LY.DMGN_MKT_BSKT_AM_LY_HLDY, 0) AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_HLDY

,ISNULL(s.COGS_MKT_BSKT, 0) - ISNULL(HLDY_LY.COGS_MKT_BSKT_LY_HLDY, 0) AS COGS_MKT_BSKT_DIFF_TY_VS_LY_HLDY
,ISNULL(s.DGTL_UT_SLS_AM, 0) - ISNULL(HLDY_LY.DGTL_UT_SLS_AM_LY_HLDY, 0) AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.DGTL_SHOP_SLS_AM, 0) - ISNULL(HLDY_LY.DGTL_SHOP_SLS_AM_LY_HLDY, 0) AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.SHOP_AND_SCN_STO_SLS_AM, 0) - ISNULL(HLDY_LY.SHOP_AND_SCN_STO_SLS_AM_LY_HLDY, 0) AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_HLDY

,ISNULL(s.SHOP_AND_SCN_SLS_AM, 0) - ISNULL(HLDY_LY.SHOP_AND_SCN_SLS_AM_LY_HLDY, 0) AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.SLS_MKT_BSKT_QTY, 0) - ISNULL(HLDY_LY.SLS_MKT_BSKT_QTY_LY_HLDY, 0) AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_HLDY
,ISNULL(s.SLS_MKT_BSKT_AM_COMP, 0) - ISNULL(HLDY_LY.SLS_MKT_BSKT_AM_COMP_LY_HLDY, 0) AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_CIRC_AM, 0) - ISNULL(HLDY_LY.CALC_CIRC_AM_LY_HLDY, 0) AS CALC_CIRC_AM_DIFF_TY_VS_LY_HLDY

,ISNULL(s.CALC_CLRN_AM, 0) - ISNULL(HLDY_LY.CALC_CLRN_AM_LY_HLDY, 0) AS CALC_CLRN_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_DGTL_CIRC_AM, 0) - ISNULL(HLDY_LY.CALC_DGTL_CIRC_AM_LY_HLDY, 0) AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_HOOK_AM, 0) - ISNULL(HLDY_LY.CALC_HOOK_AM_LY_HLDY, 0) AS CALC_HOOK_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_DUM_AM, 0) - ISNULL(HLDY_LY.CALC_DUM_AM_LY_HLDY, 0) AS CALC_DUM_AM_DIFF_TY_VS_LY_HLDY

,ISNULL(s.CALC_MDWK_AM, 0) - ISNULL(HLDY_LY.CALC_MDWK_AM_LY_HLDY, 0) AS CALC_MDWK_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_MPRKS_AM, 0) - ISNULL(HLDY_LY.CALC_MPRKS_AM_LY_HLDY, 0) AS CALC_MPRKS_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_OTH_AM, 0) - ISNULL(HLDY_LY.CALC_OTH_AM_LY_HLDY, 0) AS CALC_OTH_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_PERS_RWRD_AM, 0) - ISNULL(HLDY_LY.CALC_PERS_RWRD_AM_LY_HLDY, 0) AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_HLDY

,ISNULL(s.CALC_SHLF_EDG_AM, 0) - ISNULL(HLDY_LY.CALC_SHLF_EDG_AM_LY_HLDY, 0) AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_SP_EVNT_AM, 0) - ISNULL(HLDY_LY.CALC_SP_EVNT_AM_LY_HLDY, 0) AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.CALC_TEAM_MMB_AM, 0) - ISNULL(HLDY_LY.CALC_TEAM_MMB_AM_LY_HLDY, 0) AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_HLDY
,ISNULL(s.SLS_MKT_BSKT_AM_NCOMP, 0) - ISNULL(HLDY_LY.SLS_MKT_BSKT_AM_NCOMP_LY_HLDY, 0) AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_HLDY





--,CASE WHEN SLS_MKT_BSKT_AM_LY_HLDY IS NULL THEN ISNULL(SLS_MKT_BSKT_AM, 0) - ISNULL(SLS_MKT_BSKT_AM_LY_FSC, 0) ELSE ISNULL(SLS_MKT_BSKT_AM, 0) - ISNULL(SLS_MKT_BSKT_AM_LY_HLDY, 0) END  AS SLS_MKT_BSKT_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN DMGN_MKT_BSKT_AM_LY_HLDY IS NULL THEN ISNULL(DMGN_MKT_BSKT_AM, 0) - ISNULL(DMGN_MKT_BSKT_AM_LY_FSC, 0) ELSE ISNULL(DMGN_MKT_BSKT_AM, 0) - ISNULL(DMGN_MKT_BSKT_AM_LY_HLDY, 0) END  AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN COGS_MKT_BSKT_LY_HLDY IS NULL THEN ISNULL(COGS_MKT_BSKT, 0) - ISNULL(COGS_MKT_BSKT_LY_FSC, 0) ELSE ISNULL(COGS_MKT_BSKT, 0)- ISNULL(COGS_MKT_BSKT_LY_HLDY, 0) END  AS COGS_MKT_BSKT_DIFF_TY_VS_LY_HLDY
--,CASE WHEN DGTL_UT_SLS_AM_LY_HLDY IS NULL THEN ISNULL(DGTL_UT_SLS_AM, 0) - ISNULL(DGTL_UT_SLS_AM_LY_FSC, 0) ELSE ISNULL(DGTL_UT_SLS_AM, 0) - ISNULL(DGTL_UT_SLS_AM_LY_HLDY, 0) END  AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN DGTL_SHOP_SLS_AM_LY_HLDY IS NULL THEN ISNULL(DGTL_SHOP_SLS_AM, 0) - ISNULL(DGTL_SHOP_SLS_AM_LY_FSC, 0) ELSE ISNULL(DGTL_SHOP_SLS_AM, 0) - ISNULL(DGTL_SHOP_SLS_AM_LY_HLDY, 0) END  AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN SHOP_AND_SCN_STO_SLS_AM_LY_HLDY IS NULL THEN ISNULL(SHOP_AND_SCN_STO_SLS_AM, 0) - ISNULL(SHOP_AND_SCN_STO_SLS_AM_LY_FSC, 0) ELSE ISNULL(SHOP_AND_SCN_STO_SLS_AM, 0) - ISNULL(SHOP_AND_SCN_STO_SLS_AM_LY_HLDY, 0) END  AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN SHOP_AND_SCN_SLS_AM_LY_HLDY IS NULL THEN ISNULL(SHOP_AND_SCN_SLS_AM, 0) - ISNULL(SHOP_AND_SCN_SLS_AM_LY_FSC, 0) ELSE ISNULL(SHOP_AND_SCN_SLS_AM, 0) - ISNULL(SHOP_AND_SCN_SLS_AM_LY_HLDY, 0) END  AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN SLS_MKT_BSKT_QTY_LY_HLDY IS NULL THEN ISNULL(SLS_MKT_BSKT_QTY, 0) - ISNULL(SLS_MKT_BSKT_QTY_LY_FSC, 0) ELSE ISNULL(SLS_MKT_BSKT_QTY, 0) - ISNULL(SLS_MKT_BSKT_QTY_LY_HLDY, 0) END  AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_HLDY
--,CASE WHEN SLS_MKT_BSKT_AM_COMP_LY_HLDY IS NULL THEN ISNULL(SLS_MKT_BSKT_AM_COMP, 0) - ISNULL(SLS_MKT_BSKT_AM_COMP_LY_FSC, 0) ELSE ISNULL(SLS_MKT_BSKT_AM_COMP, 0) - ISNULL(SLS_MKT_BSKT_AM_COMP_LY_HLDY, 0) END  AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_CIRC_AM_LY_HLDY IS NULL THEN ISNULL(CALC_CIRC_AM, 0) - ISNULL(CALC_CIRC_AM_LY_FSC, 0) ELSE ISNULL(CALC_CIRC_AM, 0)- ISNULL(CALC_CIRC_AM_LY_HLDY, 0) END  AS CALC_CIRC_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_CLRN_AM_LY_HLDY IS NULL THEN ISNULL(CALC_CLRN_AM, 0) - ISNULL(CALC_CLRN_AM_LY_FSC, 0) ELSE ISNULL(CALC_CLRN_AM, 0) - ISNULL(CALC_CLRN_AM_LY_HLDY, 0) END  AS CALC_CLRN_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_DGTL_CIRC_AM_LY_HLDY IS NULL THEN ISNULL(CALC_DGTL_CIRC_AM, 0) - ISNULL(CALC_DGTL_CIRC_AM_LY_FSC, 0) ELSE ISNULL(CALC_DGTL_CIRC_AM, 0) - ISNULL(CALC_DGTL_CIRC_AM_LY_HLDY, 0) END  AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_HOOK_AM_LY_HLDY IS NULL THEN ISNULL(CALC_HOOK_AM, 0) - ISNULL(CALC_HOOK_AM_LY_FSC, 0) ELSE ISNULL(CALC_HOOK_AM, 0) - ISNULL(CALC_HOOK_AM_LY_HLDY, 0) END  AS CALC_HOOK_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_DUM_AM_LY_HLDY IS NULL THEN ISNULL(CALC_DUM_AM, 0) - ISNULL(CALC_DUM_AM_LY_FSC, 0) ELSE ISNULL(CALC_DUM_AM, 0) - ISNULL(CALC_DUM_AM_LY_HLDY, 0) END  AS CALC_DUM_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_MDWK_AM_LY_HLDY IS NULL THEN ISNULL(CALC_MDWK_AM, 0) - ISNULL(CALC_MDWK_AM_LY_FSC, 0) ELSE ISNULL(CALC_MDWK_AM, 0) - ISNULL(CALC_MDWK_AM_LY_HLDY, 0) END  AS CALC_MDWK_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_MPRKS_AM_LY_HLDY IS NULL THEN ISNULL(CALC_MPRKS_AM, 0) - ISNULL(CALC_MPRKS_AM_LY_FSC, 0) ELSE ISNULL(CALC_MPRKS_AM, 0) - ISNULL(CALC_MPRKS_AM_LY_HLDY, 0) END  AS CALC_MPRKS_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_OTH_AM_LY_HLDY IS NULL THEN ISNULL(CALC_OTH_AM, 0) - ISNULL(CALC_OTH_AM_LY_FSC, 0) ELSE ISNULL(CALC_OTH_AM, 0) - ISNULL(CALC_OTH_AM_LY_HLDY, 0) END  AS CALC_OTH_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_PERS_RWRD_AM_LY_HLDY IS NULL THEN ISNULL(CALC_PERS_RWRD_AM, 0) - ISNULL(CALC_PERS_RWRD_AM_LY_FSC, 0) ELSE ISNULL(CALC_PERS_RWRD_AM, 0) - ISNULL(CALC_PERS_RWRD_AM_LY_HLDY, 0) END  AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_SHLF_EDG_AM_LY_HLDY IS NULL THEN ISNULL(CALC_SHLF_EDG_AM, 0) - ISNULL(CALC_SHLF_EDG_AM_LY_FSC, 0) ELSE ISNULL(CALC_SHLF_EDG_AM, 0) - ISNULL(CALC_SHLF_EDG_AM_LY_HLDY, 0) END  AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_SP_EVNT_AM_LY_HLDY IS NULL THEN ISNULL(CALC_SP_EVNT_AM, 0) - ISNULL(CALC_SP_EVNT_AM_LY_FSC, 0) ELSE ISNULL(CALC_SP_EVNT_AM, 0) - ISNULL(CALC_SP_EVNT_AM_LY_HLDY, 0) END  AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN CALC_TEAM_MMB_AM_LY_HLDY IS NULL THEN ISNULL(CALC_TEAM_MMB_AM, 0) - ISNULL(CALC_TEAM_MMB_AM_LY_FSC, 0) ELSE ISNULL(CALC_TEAM_MMB_AM, 0) - ISNULL(CALC_TEAM_MMB_AM_LY_HLDY, 0) END  AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_HLDY
--,CASE WHEN SLS_MKT_BSKT_AM_NCOMP_LY_HLDY IS NULL THEN ISNULL(SLS_MKT_BSKT_AM_NCOMP, 0) - ISNULL(SLS_MKT_BSKT_AM_NCOMP_LY_FSC, 0) ELSE ISNULL(SLS_MKT_BSKT_AM_NCOMP, 0) - ISNULL(SLS_MKT_BSKT_AM_NCOMP_LY_HLDY, 0) END  AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_HLDY



-- ,s.SLS_MKT_BSKT_AM - CLDR.SLS_MKT_BSKT_AM_LY_CLDR AS SLS_MKT_BSKT_AM_DIFF_TY_VS_LY_CLDR

--,s.DMGN_MKT_BSKT_AM - CLDR.DMGN_MKT_BSKT_AM_LY_CLDR AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_CLDR
--,s.COGS_MKT_BSKT - CLDR.COGS_MKT_BSKT_LY_CLDR AS COGS_MKT_BSKT_DIFF_TY_VS_LY_CLDR
--,s.DGTL_UT_SLS_AM - CLDR.DGTL_UT_SLS_AM_LY_CLDR AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_CLDR
--,s.DGTL_SHOP_SLS_AM - CLDR.DGTL_SHOP_SLS_AM_LY_CLDR AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_CLDR
--,s.SHOP_AND_SCN_STO_SLS_AM - CLDR.SHOP_AND_SCN_STO_SLS_AM_LY_CLDR AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_CLDR
--,s.SHOP_AND_SCN_SLS_AM - CLDR.SHOP_AND_SCN_SLS_AM_LY_CLDR AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_CLDR
--,s.SLS_MKT_BSKT_QTY - CLDR.SLS_MKT_BSKT_QTY_LY_CLDR AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_CLDR
--,s.SLS_MKT_BSKT_AM_COMP - CLDR.SLS_MKT_BSKT_AM_COMP_LY_CLDR AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_CLDR
--,s.CALC_CIRC_AM - CLDR.CALC_CIRC_AM_LY_CLDR AS CALC_CIRC_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_CLRN_AM - CLDR.CALC_CLRN_AM_LY_CLDR AS CALC_CLRN_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_DGTL_CIRC_AM - CLDR.CALC_DGTL_CIRC_AM_LY_CLDR AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_HOOK_AM - CLDR.CALC_HOOK_AM_LY_CLDR AS CALC_HOOK_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_DUM_AM - CLDR.CALC_DUM_AM_LY_CLDR AS CALC_DUM_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_MDWK_AM - CLDR.CALC_MDWK_AM_LY_CLDR AS CALC_MDWK_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_MPRKS_AM - CLDR.CALC_MPRKS_AM_LY_CLDR AS CALC_MPRKS_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_OTH_AM - CLDR.CALC_OTH_AM_LY_CLDR AS CALC_OTH_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_PERS_RWRD_AM - CLDR.CALC_PERS_RWRD_AM_LY_CLDR AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_SHLF_EDG_AM - CLDR.CALC_SHLF_EDG_AM_LY_CLDR AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_SP_EVNT_AM - CLDR.CALC_SP_EVNT_AM_LY_CLDR AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_CLDR
--,s.CALC_TEAM_MMB_AM - CLDR.CALC_TEAM_MMB_AM_LY_CLDR AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_CLDR
--,s.SLS_MKT_BSKT_AM_NCOMP - CLDR.SLS_MKT_BSKT_AM_NCOMP_LY_CLDR AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_CLDR


,ISNULL(s.SLS_MKT_BSKT_AM,0) - ISNULL(CLDR.SLS_MKT_BSKT_AM_LY_CLDR ,0) AS SLS_MKT_BSKT_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.DMGN_MKT_BSKT_AM ,0)- ISNULL(CLDR.DMGN_MKT_BSKT_AM_LY_CLDR ,0) AS DMGN_MKT_BSKT_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.COGS_MKT_BSKT ,0) - ISNULL(CLDR.COGS_MKT_BSKT_LY_CLDR ,0) AS COGS_MKT_BSKT_DIFF_TY_VS_LY_CLDR
,ISNULL(s.DGTL_UT_SLS_AM ,0) - ISNULL(CLDR.DGTL_UT_SLS_AM_LY_CLDR ,0) AS DGTL_UT_SLS_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.DGTL_SHOP_SLS_AM ,0) - ISNULL(CLDR.DGTL_SHOP_SLS_AM_LY_CLDR ,0) AS DGTL_SHOP_SLS_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.SHOP_AND_SCN_STO_SLS_AM ,0) - ISNULL(CLDR.SHOP_AND_SCN_STO_SLS_AM_LY_CLDR ,0) AS SHOP_AND_SCN_STO_SLS_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.SHOP_AND_SCN_SLS_AM ,0) - ISNULL(CLDR.SHOP_AND_SCN_SLS_AM_LY_CLDR ,0) AS SHOP_AND_SCN_SLS_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.SLS_MKT_BSKT_QTY ,0) - ISNULL(CLDR.SLS_MKT_BSKT_QTY_LY_CLDR ,0) AS SLS_MKT_BSKT_QTY_DIFF_TY_VS_LY_CLDR
,ISNULL(s.SLS_MKT_BSKT_AM_COMP ,0) - ISNULL(CLDR.SLS_MKT_BSKT_AM_COMP_LY_CLDR ,0) AS SLS_MKT_BSKT_AM_COMP_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_CIRC_AM ,0) - ISNULL(CLDR.CALC_CIRC_AM_LY_CLDR ,0) AS CALC_CIRC_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_CLRN_AM ,0) - ISNULL(CLDR.CALC_CLRN_AM_LY_CLDR ,0) AS CALC_CLRN_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_DGTL_CIRC_AM ,0) - ISNULL(CLDR.CALC_DGTL_CIRC_AM_LY_CLDR ,0)AS CALC_DGTL_CIRC_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_HOOK_AM ,0) - ISNULL(CLDR.CALC_HOOK_AM_LY_CLDR ,0) AS CALC_HOOK_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_DUM_AM ,0) - ISNULL(CLDR.CALC_DUM_AM_LY_CLDR ,0) AS CALC_DUM_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_MDWK_AM ,0) - ISNULL(CLDR.CALC_MDWK_AM_LY_CLDR ,0) AS CALC_MDWK_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_MPRKS_AM ,0) - ISNULL(CLDR.CALC_MPRKS_AM_LY_CLDR ,0) AS CALC_MPRKS_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_OTH_AM ,0) - ISNULL(CLDR.CALC_OTH_AM_LY_CLDR ,0) AS CALC_OTH_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_PERS_RWRD_AM ,0) - ISNULL(CLDR.CALC_PERS_RWRD_AM_LY_CLDR ,0) AS CALC_PERS_RWRD_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_SHLF_EDG_AM ,0) - ISNULL(CLDR.CALC_SHLF_EDG_AM_LY_CLDR ,0) AS CALC_SHLF_EDG_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_SP_EVNT_AM ,0) - ISNULL(CLDR.CALC_SP_EVNT_AM_LY_CLDR ,0) AS CALC_SP_EVNT_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.CALC_TEAM_MMB_AM ,0) - ISNULL(CLDR.CALC_TEAM_MMB_AM_LY_CLDR ,0) AS CALC_TEAM_MMB_AM_DIFF_TY_VS_LY_CLDR
,ISNULL(s.SLS_MKT_BSKT_AM_NCOMP ,0) - ISNULL(CLDR.SLS_MKT_BSKT_AM_NCOMP_LY_CLDR ,0) AS SLS_MKT_BSKT_AM_NCOMP_DIFF_TY_VS_LY_CLDR




,CAST(1 AS bit) AS IS_ATV
,GETDATE() AS [FST_ISRT_DT]
,CAST(NULL as datetime) AS [LST_UDT_DT]
      ,CAST(NULL as datetime) AS [DEL_DT]
FROM ETL.FCT_DLY_SL_MB_P_SUB_CT_INCR_CURR AS S

INNER JOIN DM.DIM_TM AS T ON T.TM_SKY = S.TM_SKY
 LEFT JOIN [ETL].[FCT_DLY_SL_MB_P_SUB_CT_INCR_LY_FSC] AS FLD
 ON FLD.[P_SUB_CT_ID] = S.[P_SUB_CT_ID] AND FLD.UT_ID = S.UT_ID
 AND FLD.CHNL_SKY = S.CHNL_SKY AND FLD.BYR_SKY = S.BYR_SKY
 AND FLD.TM_SKY = S.TM_SKY

  LEFT JOIN [ETL].[FCT_DLY_SL_MB_P_SUB_CT_INCR_LY_CLDR] AS CLDR
 ON CLDR.[P_SUB_CT_ID] = S.[P_SUB_CT_ID] AND CLDR.UT_ID = S.UT_ID
 AND CLDR.CHNL_SKY = S.CHNL_SKY AND CLDR.BYR_SKY = S.BYR_SKY
 AND CLDR.TM_SKY = S.TM_SKY

 LEFT JOIN [ETL].[FCT_DLY_SL_MB_P_SUB_CT_INCR_LY_HLDY] AS HLDY_LY
 ON HLDY_LY.[P_SUB_CT_ID] = S.[P_SUB_CT_ID] AND HLDY_LY.UT_ID = S.UT_ID
 AND HLDY_LY.CHNL_SKY = S.CHNL_SKY AND HLDY_LY.BYR_SKY = S.BYR_SKY
 AND HLDY_LY.TM_SKY = S.TM_SKY;
