CREATE TABLE [EDAA_PRES].[DIM_PROD_L3] (
    [Prod_L3_Hist_Sk]          BIGINT       NOT NULL,
    [Prod_L3_Sk]               INT          NOT NULL,
    [Lvl3_Prod_Sub_Ctgry_Id]   VARCHAR (10) NULL,
    [Lvl3_Prod_Sub_Ctgry_Desc] VARCHAR (80) NULL,
    [Lvl4_Prod_Ctgry_Id]       VARCHAR (10) NULL,
    [Lvl4_Prod_Ctgry_Desc]     VARCHAR (80) NULL,
    [Lvl5_Bsns_Sgmt_Id]        VARCHAR (10) NULL,
    [Lvl5_Bsns_Sgmt_Desc]      VARCHAR (80) NULL,
    [Lvl6_MDSArea_Id]          VARCHAR (10) NULL,
    [Lvl6_MDSArea_Desc]        VARCHAR (80) NULL,
    [Fnc_Lvl2_Mprs_Ctgry_Id]   SMALLINT     NULL,
    [Fnc_Lvl2_Mprs_Ctgry_Desc] VARCHAR (80) NULL,
    [Fnc_Lvl3_Pky_Id]          SMALLINT     NULL,
    [Fnc_Lvl3_Pky_Desc]        VARCHAR (80) NULL,
    [Fnc_Lvl4_Area_Id]         VARCHAR (15) NULL,
    [Fnc_Lvl4_Area_Desc]       VARCHAR (80) NULL,
    [Str_Area_Dtl_Id]          INT          NULL,
    [Str_Area_Dtl_Desc]        VARCHAR (50) NULL,
    [Str_Area_Summ_Id]         INT          NULL,
    [Str_Area_Summ_Desc]       VARCHAR (50) NULL,
    [Str_Dept_Dtl_Id]          INT          NULL,
    [Str_Dept_Dtl_Desc]        VARCHAR (50) NULL,
    [Str_Dept_Summ_Id]         INT          NULL,
    [Str_Dept_Summ_Desc]       VARCHAR (50) NULL,
    [Vld_Frm]                  DATE         NULL,
    [Vld_To]                   DATE         NULL,
    [Is_Curr_Ind]              BIT          NULL,
    [Is_Dmy_Ind]               BIT          NULL,
    [Is_Emb_Ind]               BIT          NULL,
    [Etl_Actn]                 VARCHAR (20) NULL,
    [Aud_Ins_Sk]               BIGINT       NULL,
    [Aud_Upd_Sk]               BIGINT       NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = REPLICATE);
