CREATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_SLS_DLY]
(
	[ROW_ID_VAL] [int] NOT NULL,
	[PRE_DEF_ID] [int] NOT NULL,
	[DT_VAL] [date] NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[STR_ID] [smallint] NOT NULL,
	[SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[SLS_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[SLS_AMT_LY_CAL] [decimal](38, 4) NULL,
	[SLS_QTY_TY_FSC] [decimal](38, 0) NULL,
	[SLS_QTY_LY_FSC] [decimal](38, 0) NULL,
	[SLS_QTY_LY_HLDY] [decimal](38, 0) NULL,
	[SLS_QTY_LY_CAL] [decimal](38, 0) NULL,
	[SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[SLS_WGT_LY_HLDY] [decimal](38, 4) NULL,
	[SLS_WGT_LY_CAL] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_LY_CAL] [decimal](38, 4) NULL,
	[PRM_TO_SLS_QTY_TY_FSC] [decimal](38, 0) NULL,
	[PRM_TO_SLS_QTY_LY_FSC] [decimal](38, 0) NULL,
	[PRM_TO_SLS_QTY_LY_HLDY] [decimal](38, 0) NULL,
	[PRM_TO_SLS_QTY_LY_CAL] [decimal](38, 0) NULL,
	[PRM_TO_SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_LY_HLDY] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_LY_CAL] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_LY_CAL] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_LY_CAL] [decimal](38, 4) NULL,
	[CLRNC_QTY_TY_FSC] [decimal](38, 0) NULL,
	[CLRNC_QTY_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_QTY_LY_HLDY] [decimal](38, 0) NULL,
	[CLRNC_QTY_LY_CAL] [decimal](38, 0) NULL,
	[CLRNC_WGT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_LY_HLDY] [decimal](38, 4) NULL,
	[CLRNC_WGT_LY_CAL] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_LY_CAL] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_LY_CAL] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_LY_CAL] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_LY_CAL] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_LY_HLDY] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_LY_CAL] [decimal](38, 4) NULL,
	[UPDATEDTIMESTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [ITM_SKU] ),
	CLUSTERED COLUMNSTORE INDEX
)
