CREATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_INV_ADJ_TY_LY_FSC_DLY]
(
	[ROW_ID_VAL] [int] NOT NULL,
	[PRE_DEF_ID] [int] NOT NULL,
	[DT_VAL] [date] NOT NULL,
	[ITM_SKU] [decimal](18, 0) NOT NULL,
	[STR_ID] [smallint] NULL,
	[INV_ADJ_SK] [int] NOT NULL,
	[INV_ADJSTD_AMT_TY_FSC] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_TY_FSC] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_FSC] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_FSC] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_HLDY] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_HLDY] [decimal](11, 2) NULL,
	[INV_ADJSTD_AMT_LY_CAL] [decimal](17, 4) NULL,
	[INV_ADJSTD_QTY_LY_CAL] [decimal](11, 2) NULL,
	[UPDATEDTIMESTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [ITM_SKU] ),
	CLUSTERED COLUMNSTORE INDEX
)
