/****** Object:  Table [EDAA_PRES].[FCT_PRODUCT_MPRS_COSTRCV_SLS_AGG]    Script Date: 8/19/2022 8:58:56 AM ******/

CREATE TABLE [EDAA_PRES].[FCT_PRODUCT_MPRS_COSTRCV_SLS_AGG]
(
	[ROW_ID_VAL] [int] NOT NULL,
	[CLN_TYP_ID] [smallint] NOT NULL,
	[PRE_DEF_ID] [int] NOT NULL,
	[DT_VAL] [date] NOT NULL,
	[GEO_HIST_SK] [int] NOT NULL,
	[PROD_HIST_SK] [int] NOT NULL,
	[ITM_SKU] [bigint] NOT NULL,
	[STR_ID] [bigint] NOT NULL,
	[Mjr_Pkg_Ut_Qty_TY_FSC] [bigint] NULL,
	[Mjr_Pkg_Ut_Qty_LY_FSC] [bigint] NULL,
	[Itm_Grss_Cst_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Itm_Grss_Cst_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Itm_Net_Cst_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Itm_Net_Cst_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Itm_Chrg_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Itm_Chrg_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Itm_Alw_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Itm_Alw_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Po_Chrg_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Po_Chrg_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Po_Alw_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Po_Alw_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Csh_Dct_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Csh_Dct_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Frt_Chrg_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Frt_Chrg_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Frt_Alw_Ea_Amt_TY_FSC] [decimal](24, 5) NULL,
	[Frt_Alw_Ea_Amt_LY_FSC] [decimal](24, 5) NULL,
	[Frt_Unld_Chrg_Amt_TY_FSC] [decimal](20, 6) NULL,
	[Frt_Unld_Chrg_Amt_LY_FSC] [decimal](20, 6) NULL,
	[Ipt_Ld_Chrg_Amt_TY_FSC] [decimal](20, 4) NULL,
	[Ipt_Ld_Chrg_Amt_LY_FSC] [decimal](20, 4) NULL,
	[Bkh_Frt_Chrg_Amt_TY_FSC] [decimal](20, 6) NULL,
	[Bkh_Frt_Chrg_Amt_LY_FSC] [decimal](20, 6) NULL,
	[Extd_Bkh_Frt_Chrg_Amt_TY_FSC] [decimal](20, 4) NULL,
	[Extd_Bkh_Frt_Chrg_Amt_LY_FSC] [decimal](20, 4) NULL,
	[SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[SLS_QTY_TY_FSC] [decimal](38, 4) NULL,
	[SLS_QTY_LY_FSC] [decimal](38, 4) NULL,
	[SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_QTY_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_QTY_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_WGT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_SLS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_QTY_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_QTY_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_WGT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_MKDN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FNC_CR_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_STRGE_CHRG_AMT_LY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[PRM_TO_SLS_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_TY_FSC] [decimal](38, 4) NULL,
	[CLRNC_DRCT_MGN_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_FRT_AMT_LY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_TY_FSC] [decimal](38, 4) NULL,
	[COGS_DIST_CNTR_HNDL_AMT_LY_FSC] [decimal](38, 4) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [ITM_SKU] ),
	CLUSTERED COLUMNSTORE INDEX,
	PARTITION
	(
		[ROW_ID_VAL] RANGE RIGHT FOR VALUES (1, 2, 3, 4, 5, 6)
	)
)
GO
