/****** Object:  Table [EDAA_PRES].[FCT_DLY_STR_ITMSKU_MPRS_COSTRCV_SLS_AGG]    Script Date: 9/28/2022 2:32:56 AM ******/

CREATE TABLE [EDAA_PRES].[FCT_DLY_STR_ITMSKU_MPRS_COSTRCV_SLS_AGG]
(
	[Row_Id_Val] [int] NOT NULL,
	[Cln_Typ_Id] [smallint] NOT NULL,
	[Pre_Def_Id] [int] NOT NULL,
	[Dt_Val] [date] NOT NULL,
	[Geo_Hist_Sk] [int] NOT NULL,
	[Prod_Hist_Sk] [int] NOT NULL,
	[Itm_Sku] [bigint] NOT NULL,
	[Str_Id] [bigint] NOT NULL,
	[Mjr_Pkg_Ut_Qty_Ty_Fsc] [decimal](24, 4) NULL,
	[Mjr_Pkg_Ut_Qty_Ly_Fsc] [decimal](24, 4) NULL,
	[Itm_Grss_Cst_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Itm_Grss_Cst_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Itm_Net_Cst_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Itm_Net_Cst_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Itm_Chrg_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Itm_Chrg_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Itm_Alw_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Itm_Alw_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Po_Chrg_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Po_Chrg_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Po_Alw_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Po_Alw_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Csh_Dct_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Csh_Dct_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Frt_Chrg_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Frt_Chrg_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Frt_Alw_Ea_Amt_Ty_Fsc] [decimal](24, 5) NULL,
	[Frt_Alw_Ea_Amt_Ly_Fsc] [decimal](24, 5) NULL,
	[Frt_Unld_Chrg_Amt_Ty_Fsc] [decimal](20, 6) NULL,
	[Frt_Unld_Chrg_Amt_Ly_Fsc] [decimal](20, 6) NULL,
	[Ipt_Ld_Chrg_Amt_Ty_Fsc] [decimal](20, 4) NULL,
	[Ipt_Ld_Chrg_Amt_Ly_Fsc] [decimal](20, 4) NULL,
	[Bkh_Frt_Chrg_Amt_Ty_Fsc] [decimal](20, 6) NULL,
	[Bkh_Frt_Chrg_Amt_Ly_Fsc] [decimal](20, 6) NULL,
	[Extd_Bkh_Frt_Chrg_Amt_Ty_Fsc] [decimal](20, 4) NULL,
	[Extd_Bkh_Frt_Chrg_Amt_Ly_Fsc] [decimal](20, 4) NULL,
	[Cst_Gds_Rdc_Amt_Ty_Fsc] [decimal](15, 4) NULL,
	[Cst_Gds_Rdc_Amt_Ly_Fsc] [decimal](15, 4) NULL,
	[Swl_Dft_Alw_Ty_Fsc] [decimal](22, 5) NULL,
	[Swl_Dft_Alw_Ly_Fsc] [decimal](22, 5) NULL,
	[Sls_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Sls_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Sls_Qty_Ty_Fsc] [int] NULL,
	[Sls_Qty_Ly_Fsc] [int] NULL,
	[Sls_Wgt_Ty_Fsc] [int] NULL,
	[Sls_Wgt_Ly_Fsc] [int] NULL,
	[SLS_UOM_QTY_TY] [int] NULL,
	[SLS_UOM_QTY_LY] [int] NULL,
	[Prm_To_Sls_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Prm_To_Sls_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Prm_To_Sls_Qty_Ty_Fsc] [int] NULL,
	[Prm_To_Sls_Qty_Ly_Fsc] [int] NULL,
	[Prm_To_Sls_Wgt_Ty_Fsc] [int] NULL,
	[Prm_To_Sls_Wgt_Ly_Fsc] [int] NULL,
	[Prm_To_Sls_Mkdn_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Prm_To_Sls_Mkdn_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Sls_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Sls_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Qty_Ty_Fsc] [int] NULL,
	[Clrnc_Qty_Ly_Fsc] [int] NULL,
	[Clrnc_Wgt_Ty_Fsc] [int] NULL,
	[Clrnc_Wgt_Ly_Fsc] [int] NULL,
	[Clrnc_Mkdn_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Mkdn_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_Fnc_Chrg_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_Fnc_Chrg_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_Fnc_Cr_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_Fnc_Cr_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_StrGe_Chrg_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_StrGe_Chrg_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Drct_Mgn_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Drct_Mgn_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Prm_To_Sls_Drct_Mgn_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Prm_To_Sls_Drct_Mgn_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Drct_Mgn_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Clrnc_Drct_Mgn_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_Frt_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_Frt_Amt_Ly_Fsc] [decimal](38, 4) NULL,
	[Cogs_Dist_Cntr_Hndl_Amt_Ty_Fsc] [decimal](38, 4) NULL,
	[Cogs_Dist_Cntr_Hndl_Amt_Ly_Fsc] [decimal](38, 4) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Itm_Sku] ),
	CLUSTERED COLUMNSTORE INDEX,
	PARTITION
	(
		[Row_Id_Val] RANGE RIGHT FOR VALUES (1, 2, 3, 4, 5, 6)
	)
)
