CREATE VIEW [V_EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_HST]
AS SELECT DT_SK,  STR_ID , ITM_SKU , CAST(SUM(SLS_AMT) AS DECIMAL(18,2)) AS SLS_AMT  ,
SUM(SLS_UT_QTY) AS SLS_UT_QTY  , SUM(SLS_WGT_QTY) AS SLS_WGT_QTY ,
SUM(SLS_QTY) AS SLS_QTY, CAST(SUM(PRM_TO_SLS_AMT) AS DECIMAL(18,2))  AS PRM_TO_SLS_AMT ,
SUM(PRM_TO_SLS_QTY) AS PRM_TO_SLS_QTY ,
SUM(PRM_TO_SLS_WGT) AS PRM_TO_SLS_WGT ,
CAST(SUM(PRM_TO_SLS_MKDN_AMT) AS DECIMAL(18,2))  AS  PRM_TO_SLS_MKDN_AMT,
CAST(SUM(CLRNC_SLS_AMT) AS DECIMAL(18,2))  AS  CLRNC_SLS_AMT, SUM(CLRNC_QTY) AS CLRNC_QTY ,
SUM(CLRNC_WGT) AS  CLRNC_WGT,
CAST(SUM(CLRNC_MKDN_AMT) AS DECIMAL(18,2))  AS CLRNC_MKDN_AMT ,
CAST(SUM(COGS_AMT) AS DECIMAL(18,2))  AS COGS_AMT ,
CAST(SUM(COGS_FNC_CHRG_AMT) AS DECIMAL(18,2))  AS COGS_FNC_CHRG_AMT ,
CAST(SUM(COGS_FNC_CR_AMT) AS DECIMAL(18,2))  AS COGS_FNC_CR_AMT,
CAST(SUM(COGS_STRGE_CHRG_AMT) AS DECIMAL(18,2))  AS COGS_STRGE_CHRG_AMT ,
CAST(SUM(DRCT_MGN_AMT) AS DECIMAL(18,2))  AS DRCT_MGN_AMT ,
CAST(SUM(PRM_TO_SLS_DRCT_MGN_AMT) AS DECIMAL(18,2))  AS PRM_TO_SLS_DRCT_MGN_AMT ,
CAST(SUM(CLRNC_DRCT_MGN_AMT) AS DECIMAL(18,2))  AS CLRNC_DRCT_MGN_AMT,
CAST(SUM(COGS_FRT_AMT) AS DECIMAL(18,2))  AS  COGS_FRT_AMT,
CAST(SUM(COGS_DIST_CNTR_HNDL_AMT) AS DECIMAL(18,2)) AS COGS_DIST_CNTR_HNDL_AMT
FROM
(
	SELECT [DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU]
      ,[SLS_AMT]
      ,[SLS_UT_QTY]
      ,[SLS_WGT_QTY]
	  ,CASE WHEN SLS_WGT_QTY <> 0 THEN SLS_WGT_QTY else SLS_UT_QTY END AS SLS_QTY
      ,[PRM_TO_SLS_AMT]
      ,[PRM_TO_SLS_QTY]
      ,[PRM_TO_SLS_WGT]
      ,[PRM_TO_SLS_MKDN_AMT]
      ,[CLRNC_SLS_AMT]
      ,[CLRNC_QTY]
      ,[CLRNC_WGT]
      ,[CLRNC_MKDN_AMT]
      ,[COGS_AMT]
      ,[COGS_FNC_CHRG_AMT]
      ,[COGS_FNC_CR_AMT]
      ,[COGS_STRGE_CHRG_AMT]
      ,[DRCT_MGN_AMT]
      ,[PRM_TO_SLS_DRCT_MGN_AMT]
      ,[CLRNC_DRCT_MGN_AMT]
      ,[COGS_FRT_AMT]
      ,[COGS_DIST_CNTR_HNDL_AMT]
FROM(
SELECT [DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU]
      ,[SLS_AMT]
      ,[SLS_QTY] AS SLS_UT_QTY
      ,[SLS_WGT] AS SLS_WGT_QTY
      ,[PRM_TO_SLS_AMT]
      ,[PRM_TO_SLS_QTY]
      ,[PRM_TO_SLS_WGT]
      ,[PRM_TO_SLS_MKDN_AMT]
      ,[CLRNC_SLS_AMT]
      ,[CLRNC_QTY]
      ,[CLRNC_WGT]
      ,[CLRNC_MKDN_AMT]
      ,[COGS_AMT]
      ,[COGS_FNC_CHRG_AMT]
      ,[COGS_FNC_CR_AMT]
      ,[COGS_STRGE_CHRG_AMT]
      ,[DRCT_MGN_AMT]
      ,[PRM_TO_SLS_DRCT_MGN_AMT]
      ,[CLRNC_DRCT_MGN_AMT]
      ,[COGS_FRT_AMT]
      ,[COGS_DIST_CNTR_HNDL_AMT]
  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] WITH(NOLOCK)
)SLS

UNION ALL

SELECT [DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU]
      ,[SLS_ADJ_AMT] AS SLS_AMT
      ,[SLS_ADJ_UT_QTY] AS SLS_UT_QTY
      ,[SLS_ADJ_WGT_QTY] AS SLS_WGT_QTY
	    ,CASE WHEN SLS_ADJ_WGT_QTY <> 0 THEN SLS_ADJ_WGT_QTY else SLS_ADJ_UT_QTY END AS SLS_QTY
      ,[PRM_TO_SLS_ADJ_AMT] AS PRM_TO_SLS_AMT
      ,[PRM_TO_SLS_ADJ_QTY] AS PRM_TO_SLS_QTY
      ,[PRM_TO_SLS_ADJ_WGT] AS PRM_TO_SLS_WGT
      ,[PRM_TO_SLS_MKDN_ADJ_AMT] AS PRM_TO_SLS_MKDN_AMT
      ,[CLRNC_SLS_ADJ_AMT] AS CLRNC_SLS_AMT
      ,[CLRNC_ADJ_QTY] AS CLRNC_QTY
      ,[CLRNC_ADJ_WGT] AS CLRNC_WGT
      ,[CLRNC_MKDN_ADJ_AMT] AS CLRNC_MKDN_AMT
      ,[COGS_ADJ_AMT] AS COGS_AMT
      ,[COGS_FNC_CHRG_ADJ_AMT] AS COGS_FNC_CHRG_AMT
      ,[COGS_FNC_CR_ADJ_AMT] AS COGS_FNC_CR_AMT
      ,[COGS_STRGE_CHRG_ADJ_AMT] AS COGS_STRGE_CHRG_AMT
      ,[DRCT_MGN_ADJ_AMT] AS DRCT_MGN_AMT
      ,[PRM_TO_SLS_DRCT_MGN_ADJ_AMT] AS PRM_TO_SLS_DRCT_MGN_AMT
      ,[CLRNC_DRCT_MGN_ADJ_AMT] AS CLRNC_DRCT_MGN_AMT
	    ,[COGS_FRT_ADJ_AMT] AS COGS_FRT_AMT
      ,[COGS_DIST_CNTR_HNDL_ADJ_AMT] AS COGS_DIST_CNTR_HNDL_AMT
FROM
(SELECT
      [DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU]
      ,[SLS_ADJ_AMT]
      ,[SLS_ADJ_QTY] AS SLS_ADJ_UT_QTY
      ,[SLS_ADJ_WGT] AS SLS_ADJ_WGT_QTY
      ,[PRM_TO_SLS_ADJ_AMT]
      ,[PRM_TO_SLS_ADJ_QTY]
      ,[PRM_TO_SLS_ADJ_WGT]
      ,[PRM_TO_SLS_MKDN_ADJ_AMT]
      ,[CLRNC_SLS_ADJ_AMT]
      ,[CLRNC_ADJ_QTY]
      ,[CLRNC_ADJ_WGT]
      ,[CLRNC_MKDN_ADJ_AMT]
      ,[COGS_ADJ_AMT]
      ,[COGS_FNC_CHRG_ADJ_AMT]
      ,[COGS_FNC_CR_ADJ_AMT]
      ,[COGS_STRGE_CHRG_ADJ_AMT]
      ,[DRCT_MGN_ADJ_AMT]
      ,[PRM_TO_SLS_DRCT_MGN_ADJ_AMT]
      ,[CLRNC_DRCT_MGN_ADJ_AMT]
	    ,[COGS_FRT_ADJ_AMT]
      ,[COGS_DIST_CNTR_HNDL_ADJ_AMT]
  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS_ADJ] WITH(NOLOCK)
  )SLS_ADJ
  ) t
GROUP BY DT_SK, ITM_SKU , STR_ID;
