CREATE VIEW [V_EDAA_DW].[FCT_DLY_TL_FUEL_PKP]
AS
SELECT [ENTY_NM]
      ,[TL_NM]
      ,[VNDR_PROD_NM]
      ,[FUEL_CST_TYP_NM]
      ,[FUEL_CST_AMT]
      ,[SRC_RW_GRTN_TMS]
      ,[RW_PRCS_ID]
      ,[CAL_DT]
      ,[DT_SK]
      ,[AUD_INS_SK]
      ,[AUD_UPD_SK]
  FROM [EDAA_DW].[FCT_DLY_TL_FUEL_PKP]WITH(NOLOCK)	;
