CREATE VIEW [V_EDAA_DW].[FCT_DLY_STR_ITMSKU_LOST_SLS]
AS
SELECT [PROD_HIST_SK]
      ,[GEO_HIST_SK]
      ,[DT_SK]
      ,[ITM_SKU]
      ,[STR_ID]
      ,[REG_LOST_SLS_QTY]
      ,[PROMO_LOST_SLS_QTY]
      ,[AUD_INS_SK]
      ,[AUD_UPD_SK]
  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_LOST_SLS] WITH(NOLOCK)
