CREATE VIEW [V_EDAA_DW].[FCT_DLY_STR_ITMSKU_LOST_SLS_DTL]
AS SELECT [PROD_HIST_SK]
      ,[GEO_HIST_SK]
      ,[DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU]
      ,SUM([REG_LOST_SLS_QTY]) AS REG_LOST_SLS_QTY
      ,SUM([PROMO_LOST_SLS_QTY]) AS PROMO_LOST_SLS_QTY
FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_LOST_SLS] WITH(NOLOCK)
GROUP BY [PROD_HIST_SK]
      ,[GEO_HIST_SK]
      ,[DT_SK]
	  ,[STR_ID]
	  ,[ITM_SKU];
