CREATE VIEW [V_EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS]
AS
SELECT [DT_SK]
      ,[GEO_HIST_SK]
      ,[PROD_HIST_SK]
      ,[MPRS_PRCS_ID]
      ,[ITM_SKU]
      ,[FNC_LVL3_PKY_ID]
      ,[STR_ID]
      ,[FNC_LVL2_MPRS_CTGRY_ID]
      ,[SBT_FLAG]
      ,[SLS_AMT]
      ,[SLS_QTY]
      ,[SLS_WGT]
      ,[PRM_TO_SLS_AMT]
      ,[PRM_TO_SLS_QTY]
      ,[PRM_TO_SLS_WGT]
      ,[PRM_TO_SLS_MKDN_AMT]
      ,[CLRNC_SLS_AMT]
      ,[CLRNC_QTY]
      ,[CLRNC_WGT]
      ,[CLRNC_MKDN_AMT]
      ,[COGS_AMT]
      ,[COGS_FNC_CHRG_AMT]
      ,[COGS_FNC_CR_AMT]
      ,[COGS_STRGE_CHRG_AMT]
      ,[DRCT_MGN_AMT]
      ,[PRM_TO_SLS_DRCT_MGN_AMT]
      ,[CLRNC_DRCT_MGN_AMT]
      ,[COGS_FRT_AMT]
      ,[COGS_DIST_CNTR_HNDL_AMT]
      ,[AUD_INS_SK]
      ,[AUD_UPD_SK]
  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_SLS] WITH(NOLOCK)
