CREATE VIEW [V_EDAA_DW].[FCT_HRLY_FUEL_PCHG_DTL]
AS
SELECT
[FUEL_PCHG_SEQ_ID],
[STR_ID],
[GEO_HIST_SK],
[ITM_GRP_ID],
[CAL_DT],
[SRC_RW_GRTN_TMS],
[DT_SK],
[FUEL_PR_AMT],
[SRC_RW_PRCS_ID],
[PCHG_KLBRT_TN_ID],
[PCHG_KLBRT_STS_TX],
[RW_CRT_TMS],
[AUD_INS_SK],
[AUD_UPD_SK]
  FROM [EDAA_DW].[FCT_HRLY_FUEL_PCHG_DTL] WITH(NOLOCK);
