CREATE VIEW [V_EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_ADJ]
AS
SELECT [PROD_HIST_SK]
      ,[GEO_HIST_SK]
      ,[ITM_SKU]
      ,[DT_SK]
      ,[INV_ADJ_SK]
      ,[STR_ID]
      ,[INV_ADJSTD_QTY]
      ,[INV_ADJSTD_AMT]
      ,[AUD_INS_SK]
      ,[AUD_UPD_SK]
  FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV_ADJ] WITH(NOLOCK)
