/****** Object:  Table [dm_edw].[DT_INF]    Script Date: 9/9/2020 1:50:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dm_edw].[DT_INF]
(
	[DAY_DT] [date] NOT NULL,
	[DAY_DT_LY] [date] NOT NULL,
	[FCL_DAY_DT_LY] [date] NOT NULL,
	[WK_END_DT] [date] NOT NULL,
	[WK_END_DT_LY] [date] NOT NULL,
	[FCL_WK_END_DT_LY] [date] NOT NULL,
	[CLDR_DAY_OF_WK_ID] [int] NOT NULL,
	[CLDR_DAY_OF_WK_NM] [char](9) NOT NULL,
	[CLDR_DAY_OF_WK_SHRT_NM] [char](3) NOT NULL,
	[CLDR_DAY_OF_MTH_ID] [smallint] NOT NULL,
	[CLDR_DAY_OF_YR_ID] [smallint] NOT NULL,
	[CLDR_WK_OF_YR_ID] [smallint] NOT NULL,
	[CLDR_MTH_OF_YR_ID] [int] NOT NULL,
	[CLDR_MTH_OF_YR_NM] [char](9) NOT NULL,
	[CLDR_MTH_OF_YR_SHRT_NM] [char](3) NOT NULL,
	[CLDR_YR_ID] [smallint] NOT NULL,
	[FCL_DAY_OF_WK_ID] [int] NOT NULL,
	[FCL_DAY_OF_PER_ID] [smallint] NOT NULL,
	[FCL_DAY_OF_QTR_ID] [smallint] NOT NULL,
	[FCL_DAY_OF_YR_ID] [smallint] NOT NULL,
	[FCL_WK_OF_PER_ID] [int] NOT NULL,
	[FCL_WK_OF_QTR_ID] [int] NOT NULL,
	[FCL_WK_OF_YR_ID] [smallint] NOT NULL,
	[FCL_PER_OF_QTR_ID] [int] NOT NULL,
	[FCL_PER_OF_YR_ID] [int] NOT NULL,
	[FCL_PER_OF_YR_LY_ID] [int] NOT NULL,
	[FCL_PER_BEGN_DT] [date] NOT NULL,
	[FCL_PER_END_DT] [date] NOT NULL,
	[FCL_PER_BEGN_DT_LY] [date] NOT NULL,
	[FCL_PER_END_DT_LY] [date] NOT NULL,
	[FCL_PER_SEQ_ID] [int] NOT NULL,
	[FCL_QTR_OF_YR_ID] [int] NOT NULL,
	[FCL_QTR_BEGN_DT] [date] NOT NULL,
	[FCL_QTR_END_DT] [date] NOT NULL,
	[FCL_QTR_SEQ_ID] [int] NOT NULL,
	[FCL_YR_ID] [smallint] NOT NULL,
	[FCL_YR_LY_ID] [smallint] NOT NULL,
	[FCL_YR_BEGN_DT] [date] NOT NULL,
	[FCL_YR_END_DT] [date] NOT NULL,
	[TERADATA_DAY_OF_CLDR] [int] NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
