/****** Object:  Table [dm_edw].[HLDY_DT_XRF_INF]    Script Date: 9/9/2020 1:51:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dm_edw].[HLDY_DT_XRF_INF]
(
	[DAY_DT] [date] NULL,
	[LY_DAY_DT] [date] NULL,
	[LY_FCL_DAY_DT] [date] NULL,
	[LY_HLDY_DAY_DT] [date] NULL,
	[HLDY_DT_DSC] [varchar](400) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
