CREATE TABLE [dm_edw].[BYR_EMP_PKY_MPRS_CURRPREV_HST] (
    [INS_DT]               DATETIME2 (7)  NULL,
    [CURR_PKY_ID]          INT            NULL,
    [PKY_DSC]              NVARCHAR (256) NULL,
    [CURR_MPRS_CT_ID]      INT            NULL,
    [MPRS_CT_DSC]          NVARCHAR (256) NULL,
    [PKY_ID]               INT            NULL,
    [MPRS_CT_ID]           INT            NULL,
    [BYR_ID]               INT            NULL,
    [MJR_P_SUB_CT_ID]      NVARCHAR (256) NULL,
    [EMP_ID]               INT            NULL,
    [MGR_EMP_ID]           INT            NULL,
    [RPLNR_EMP_ID]         INT            NULL,
    [RPLNR_SPVR_EMP_ID]    INT            NULL,
    [MGR_ID]               INT            NULL,
    [MPRS_CT_PLN_FLG]      NVARCHAR (256) NULL,
    [PA_EMP_ID]            INT            NULL,
    [PA_TLDR_EMP_ID]       INT            NULL,
    [PR_SPCLT_EMP_ID]      INT            NULL,
    [PR_TLDR_EMP_ID]       INT            NULL,
    [PROMO_EMP_ID]         INT            NULL,
    [PROMO_TLDR_EMP_ID]    INT            NULL,
    [FNCPL_EMP_ID]         INT            NULL,
    [FNCPL_MGR_EMP_ID]     INT            NULL,
    [VFA_EMP_ID]           INT            NULL,
    [VFA_TLDR_EMP_ID]      INT            NULL,
    [LYOUT_SPCLT_EMP_ID]   INT            NULL,
    [LYOUT_TLDR_EMP_ID]    INT            NULL,
    [MDS_DSTB_EMP_ID]      INT            NULL,
    [EDI_ADMN_EMP_ID]      INT            NULL,
    [EDI_ANLY_EMP_ID]      INT            NULL,
    [VMS_SPCLT_EMP_ID]     INT            NULL,
    [VMS_TLDR_EMP_ID]      INT            NULL,
    [MDS_AS_EMP_ID]        INT            NULL,
    [MDSPL_EMP_ID]         INT            NULL,
    [MDSPL_MGR_EMP_ID]     INT            NULL,
    [MDS_ANLY_EMP_ID]      INT            NULL,
    [SPCPL_EMP_ID]         INT            NULL,
    [SPCPL_MGR_EMP_ID]     INT            NULL,
    [PROMO_CRDNT_EMP_ID]   INT            NULL,
    [PROMO_CRDNT_MGR_ID]   INT            NULL,
    [PR_CRDNT_EMP_ID]      INT            NULL,
    [PR_CRDNT_MGR_ID]      INT            NULL,
    [MDS_RORG_FLG]         NVARCHAR (256) NULL,
    [ECOM_BYR_ID]          INT            NULL,
    [ECOM_BYR_EMP_ID]      INT            NULL,
    [ECOM_MGR_ID]          INT            NULL,
    [ECOM_MGR_EMP_ID]      INT            NULL,
    [ECOM_WVS_EMP_ID]      INT            NULL,
    [ECOM_WVS_MGR_EMP_ID]  INT            NULL,
    [ECOM_MDS_AS_EMP_ID]   INT            NULL,
    [ECOM_MDSPL_EMP_ID]    INT            NULL,
    [ECOM_MDSPL_MGR_ID]    INT            NULL,
    [ECOM_MDS_ANLY_ID]     INT            NULL,
    [MDS_AS_TRNE_EMP_ID]   INT            NULL,
    [INDV_FST_NM]          NVARCHAR (256) NULL,
    [INDV_MID_NM]          NVARCHAR (256) NULL,
    [INDV_LST_NM]          NVARCHAR (256) NULL,
    [BYR_NM]               NVARCHAR (256) NULL,
    [EDI_ADMN_TLDR_EMP_ID] INT            NULL,
    [EDI_ANLY_TLDR_EMP_ID] INT            NULL,
    [MJR_ALT_PHN_NBR]      NVARCHAR (256) NULL,
    [BYR_DID_PHN_NBR]      NVARCHAR (256) NULL,
    [AUD_INS_SKY]          BIGINT         NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
