CREATE TABLE [dm_edw].[DIM_P_TMP] (
    [P_HST_SKY]       BIGINT        NOT NULL,
    [P_SKY]           BIGINT        NOT NULL,
    [UPC_ID]          VARCHAR (100) NOT NULL,
    [UPC_DSC]         VARCHAR (500) NOT NULL,
    [P_ID]            VARCHAR (10)  NOT NULL,
    [P_DSC]           VARCHAR (80)  NOT NULL,
    [P_CLS_ID]        VARCHAR (10)  NOT NULL,
    [P_CLS_DSC]       VARCHAR (80)  NOT NULL,
    [P_SUB_CT_ID]     VARCHAR (10)  NOT NULL,
    [P_SUB_CT_DSC]    VARCHAR (80)  NOT NULL,
    [P_CT_ID]         VARCHAR (10)  NOT NULL,
    [P_CT_DSC]        VARCHAR (80)  NOT NULL,
    [BUS_SEG_ID]      VARCHAR (10)  NOT NULL,
    [BUS_SEG_DSC]     VARCHAR (80)  NOT NULL,
    [MDS_ARE_ID]      VARCHAR (10)  NOT NULL,
    [MDS_ARE_DSC]     VARCHAR (80)  NOT NULL,
    [FNC_P_CAT_ID]    VARCHAR (10)  NOT NULL,
    [FNC_P_CAT_DSC]   VARCHAR (80)  NOT NULL,
    [FNC_MPRS_CT_ID]  SMALLINT      NOT NULL,
    [FNC_MPRS_CT_DSC] VARCHAR (80)  NOT NULL,
    [FNC_PKY_ID]      SMALLINT      NOT NULL,
    [FNC_PKY_DSC]     VARCHAR (80)  NOT NULL,
    [FNC_ARE_ID]      VARCHAR (15)  NOT NULL,
    [FNC_ARE_DSC]     VARCHAR (80)  NOT NULL,
    [VLD_FROM]        DATETIME      NOT NULL,
    [VLD_TO]          DATETIME      NULL,
    [IS_CURR]         BIT           NULL,
    [IS_DMY]          BIT           NULL,
    [IS_EMBR]         BIT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
