CREATE TABLE [dm_edw].[DT_INF] (
    [DAY_DT]                 DATE     NOT NULL,
    [DAY_DT_LY]              DATE     NOT NULL,
    [FCL_DAY_DT_LY]          DATE     NOT NULL,
    [WK_END_DT]              DATE     NOT NULL,
    [WK_END_DT_LY]           DATE     NOT NULL,
    [FCL_WK_END_DT_LY]       DATE     NOT NULL,
    [CLDR_DAY_OF_WK_ID]      INT      NOT NULL,
    [CLDR_DAY_OF_WK_NM]      CHAR (9) NOT NULL,
    [CLDR_DAY_OF_WK_SHRT_NM] CHAR (3) NOT NULL,
    [CLDR_DAY_OF_MTH_ID]     SMALLINT NOT NULL,
    [CLDR_DAY_OF_YR_ID]      SMALLINT NOT NULL,
    [CLDR_WK_OF_YR_ID]       SMALLINT NOT NULL,
    [CLDR_MTH_OF_YR_ID]      INT      NOT NULL,
    [CLDR_MTH_OF_YR_NM]      CHAR (9) NOT NULL,
    [CLDR_MTH_OF_YR_SHRT_NM] CHAR (3) NOT NULL,
    [CLDR_YR_ID]             SMALLINT NOT NULL,
    [FCL_DAY_OF_WK_ID]       INT      NOT NULL,
    [FCL_DAY_OF_PER_ID]      SMALLINT NOT NULL,
    [FCL_DAY_OF_QTR_ID]      SMALLINT NOT NULL,
    [FCL_DAY_OF_YR_ID]       SMALLINT NOT NULL,
    [FCL_WK_OF_PER_ID]       INT      NOT NULL,
    [FCL_WK_OF_QTR_ID]       INT      NOT NULL,
    [FCL_WK_OF_YR_ID]        SMALLINT NOT NULL,
    [FCL_PER_OF_QTR_ID]      INT      NOT NULL,
    [FCL_PER_OF_YR_ID]       INT      NOT NULL,
    [FCL_PER_OF_YR_LY_ID]    INT      NOT NULL,
    [FCL_PER_BEGN_DT]        DATE     NOT NULL,
    [FCL_PER_END_DT]         DATE     NOT NULL,
    [FCL_PER_BEGN_DT_LY]     DATE     NOT NULL,
    [FCL_PER_END_DT_LY]      DATE     NOT NULL,
    [FCL_PER_SEQ_ID]         INT      NOT NULL,
    [FCL_QTR_OF_YR_ID]       INT      NOT NULL,
    [FCL_QTR_BEGN_DT]        DATE     NOT NULL,
    [FCL_QTR_END_DT]         DATE     NOT NULL,
    [FCL_QTR_SEQ_ID]         INT      NOT NULL,
    [FCL_YR_ID]              SMALLINT NOT NULL,
    [FCL_YR_LY_ID]           SMALLINT NOT NULL,
    [FCL_YR_BEGN_DT]         DATE     NOT NULL,
    [FCL_YR_END_DT]          DATE     NOT NULL,
    [TERADATA_DAY_OF_CLDR]   INT      NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
