/****** Object:  Database [edaa-stme]    Script Date: 6/29/2022 11:02:24 AM ******/
CREATE DATABASE [edaa-stme]
GO

ALTER DATABASE [edaa-stme] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [edaa-stme] SET ANSI_NULLS OFF
GO

ALTER DATABASE [edaa-stme] SET ANSI_PADDING OFF
GO

ALTER DATABASE [edaa-stme] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [edaa-stme] SET ARITHABORT OFF
GO

ALTER DATABASE [edaa-stme] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [edaa-stme] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [edaa-stme] SET QUOTED_IDENTIFIER OFF
GO
