CREATE PROCEDURE [EDAA_ETL_CUST].[PROC_DROP_MEDALLIA_OBJECT] @OBJECT_TYPE [VARCHAR](255) , @OBJECT_NAME [VARCHAR](255)
AS
BEGIN
DECLARE @drop_stmt NVARCHAR(200) = N'DROP ' + @OBJECT_TYPE + N' ' + @OBJECT_NAME;
EXEC sp_executesql @tsql = @drop_stmt;
END
GO
