CREATE PROC [EDAA_ETL_CUST].[PROC_FCT_DLY_STR_SRVY_IN_STR_LOAD] AS



BEGIN TRY



/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL_CUST.PROC_FCT_DLY_STR_SRVY_IN_STR_LOAD'
DECLARE @ERROR_LINE AS int
DECLARE @ERROR_MSG AS NVARCHAR(max)

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM EDAA_STG_CUST.SRVY WHERE UDT_BY like '%InStore%' and SRVY_ID not in( select SRVY_ID from [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_IN_STR])
SELECT @NBR_OF_RW_UDT = COUNT(1)  FROM [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_IN_STR] WHERE SRVY_ID in( select SRVY_ID from EDAA_STG_CUST.SRVY )

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
@EXEC_LYR  = 'EDAA_DW_CUST'
,@EXEC_JOB  = 'EDAA_ETL_CUST.PROC_FCT_DLY_STR_SRVY_IN_STR_LOAD'
,@SRC_ENTY  = 'EDAA_STG_CUST.SRVY,EDAA_STG_CUST.QN_RSP_VAL'
,@TGT_ENTY = 'FCT_DLY_STR_SRVY_IN_STR'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;



With initial_data as
(
select
SRVY_ID,
SRVY_CRT_SK,
SRVY_SBMT_SK,
SRVY_TYP_ID,
LLTY_ACCT_ID,
TXN_ID,
STR_SK ,
STR_ID,
TXN_DT_SK,
TXN_DT,
TXN_TM,
LN_ID,
TXN_NUM,
SHOP_CHL_CTGRY_ID,
"1" as "LKHD_RECM_RAT_VAL",
"2" as "OVALL_SATF_RAT_VAL",
"3" as "LKHD_RECM_RAT_RSN_TXT",
"4" as "FLEX_SRVY_TXT",
"5" as "ADL_CMNT_TXT",
"6" as "CHKOT_XPER_RAT_VAL",
"7" as "CHKOT_DSATF_RSN_TXT",
"8" as "CHKOT_OTH_DSATF_RSN_TXT",
"9" as "CSHR_FRND_RAT_VAL",
"10" as "SLF_CHKOT_ATTDNT_FRND_RAT_VAL",
case when upper("11") = 'YES' then cast(1 as bit) when upper("11") = 'NO' then cast(0 as bit) end as "TEAM_MBR_IACT_IND",
"12" as "TEAM_MBR_IACT_FRND_RAT_VAL ",
"13" as "RSN_SVC_RAT_TXT",
"14" as "CNTER_AST_TXT",
"15" as "DLI_CNTER_SVC_SATF_RAT_VAL",
"16" as "BKRY_CNTER_SVC_SATF_RAT_VAL",
"17" as "P_AVL_SATF_RAT_VAL",
"18" as "P_AVL_DSATF_RSN_TXT",
"19" as "P_AVL_OTH_DSATF_RSN_TXT",
"20" as "FRSH_QLTY_PDC_RAT_VAL",
"21" as "UNSATF_FRSH_QLTY_ARE_TXT",
"22" as "OTH_UNSATF_FRSH_QLTY_ARE_TXT",
"23" as "P_DSATF_TXT",
"24" as "SUG_TXT",
"25" as "STR_CLNS_RAT_VAL ",
"26" as "CNTC_MTHD_TXT",
"27" as "CLNS_ISU_ARE_TXT",
"28" as "OTH_CLNS_ISU_ARE_TXT",
"29" as "EXCPL_EMP_SVC_TXT",
Getdate() as "RW_CRT_TMS"
from
(
SELECT SRVY.SRVY_ID as SRVY_ID,
c1.[DT_SK] as  SRVY_SBMT_SK,
c2.[DT_SK]  as SRVY_CRT_SK,
SRVY.TXN_DT as TXN_DT,
c3.[DT_SK] as  TXN_DT_SK,
SRVY.TXN_TM as TXN_TM,
SRVY.STR_ID as STR_ID,
b.Geo_Hist_Sk  as STR_SK ,
SRVY.TXN_LN_ID as LN_ID,
SRVY.TXN_NUM as TXN_NUM,
SRVY.SRVY_TYP_ID as SRVY_TYP_ID,
SRVY.TXN_ID as TXN_ID,
SRVY.LLTY_ACCT_ID as LLTY_ACCT_ID,
SRVY.SHOP_CHL_CTGRY_ID as SHOP_CHL_CTGRY_ID,
SQR.QN_ID,
SQR.QN_RSP_VAL
FROM EDAA_STG_CUST.SRVY as SRVY
JOIN [EDAA_DW].[DIM_DLY_CAL] c1 ON c1.[CAL_DT]=CONVERT (date,SRVY_END_DT)
JOIN [EDAA_DW].[DIM_DLY_CAL] c2 ON c2.[CAL_DT]=CONVERT (date,SRVY_STRT_DT)
JOIN [EDAA_DW].[DIM_DLY_CAL] c3 ON c3.[CAL_DT]=CONVERT (date,TXN_DT)
JOIN  [EDAA_DW].[DIM_GEO] as b on SRVY.[STR_ID] = b.[STR_ID] and Is_Curr_Ind = 'True'
JOIN  EDAA_STG_CUST.SRVY_QN_RSP SQR on SQR.SRVY_ID = SRVY.SRVY_ID
WHERE SRVY.SRVY_TYP_ID in (1,2,3,4,7)
) as a
PIVOT
(
  max(a.QN_RSP_VAL)
  FOR a.QN_ID IN ("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29")
) as b
)


Merge [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_IN_STR] t1
using initial_data as sty
on(sty.SRVY_ID = t1.SRVY_ID
   and sty.SRVY_CRT_SK = t1.SRVY_CRT_SK
   and sty.SRVY_SBMT_SK = t1.SRVY_SBMT_SK)
WHEN MATCHED THEN
UPDATE SET
t1.SRVY_TYP_ID = sty.SRVY_TYP_ID,
t1.LLTY_ACCT_ID = sty.LLTY_ACCT_ID,
t1.TXN_ID = sty.TXN_ID,
t1.STR_SK  = sty.STR_SK ,
t1.STR_ID = sty.STR_ID,
t1.TXN_DT_SK = sty.TXN_DT_SK,
t1.TXN_DT = sty.TXN_DT,
t1.TXN_TM = sty.TXN_TM,
t1.LN_ID = sty.LN_ID,
t1.TXN_NUM = sty.TXN_NUM,
t1.SHOP_CHL_CTGRY_ID = sty.SHOP_CHL_CTGRY_ID,
t1.LKHD_RECM_RAT_VAL = sty.LKHD_RECM_RAT_VAL,
t1.OVALL_SATF_RAT_VAL = sty.OVALL_SATF_RAT_VAL,
t1.LKHD_RECM_RAT_RSN_TXT = sty.LKHD_RECM_RAT_RSN_TXT,
t1.FLEX_SRVY_TXT = sty.FLEX_SRVY_TXT,
t1.ADL_CMNT_TXT = sty.ADL_CMNT_TXT,
t1.CHKOT_XPER_RAT_VAL = sty.CHKOT_XPER_RAT_VAL,
t1.CHKOT_DSATF_RSN_TXT = sty.CHKOT_DSATF_RSN_TXT,
t1.CHKOT_OTH_DSATF_RSN_TXT = sty.CHKOT_OTH_DSATF_RSN_TXT,
t1.CSHR_FRND_RAT_VAL = sty.CSHR_FRND_RAT_VAL,
t1.SLF_CHKOT_ATTDNT_FRND_RAT_VAL = sty.SLF_CHKOT_ATTDNT_FRND_RAT_VAL,
t1.TEAM_MBR_IACT_IND = sty.TEAM_MBR_IACT_IND,
t1.TEAM_MBR_IACT_FRND_RAT_VAL  = sty.TEAM_MBR_IACT_FRND_RAT_VAL ,
t1.RSN_SVC_RAT_TXT = sty.RSN_SVC_RAT_TXT,
t1.CNTER_AST_TXT = sty.CNTER_AST_TXT,
t1.DLI_CNTER_SVC_SATF_RAT_VAL = sty.DLI_CNTER_SVC_SATF_RAT_VAL,
t1.BKRY_CNTER_SVC_SATF_RAT_VAL = sty.BKRY_CNTER_SVC_SATF_RAT_VAL,
t1.P_AVL_SATF_RAT_VAL = sty.P_AVL_SATF_RAT_VAL,
t1.P_AVL_DSATF_RSN_TXT = sty.P_AVL_DSATF_RSN_TXT,
t1.P_AVL_OTH_DSATF_RSN_TXT = sty.P_AVL_OTH_DSATF_RSN_TXT,
t1.FRSH_QLTY_PDC_RAT_VAL = sty.FRSH_QLTY_PDC_RAT_VAL,
t1.UNSATF_FRSH_QLTY_ARE_TXT = sty.UNSATF_FRSH_QLTY_ARE_TXT,
t1.OTH_UNSATF_FRSH_QLTY_ARE_TXT = sty.OTH_UNSATF_FRSH_QLTY_ARE_TXT,
t1.P_DSATF_TXT = sty.P_DSATF_TXT,
t1.SUG_TXT = sty.SUG_TXT,
t1.STR_CLNS_RAT_VAL  = sty.STR_CLNS_RAT_VAL ,
t1.CNTC_MTHD_TXT = sty.CNTC_MTHD_TXT,
t1.CLNS_ISU_ARE_TXT = sty.CLNS_ISU_ARE_TXT,
t1.OTH_CLNS_ISU_ARE_TXT = sty.OTH_CLNS_ISU_ARE_TXT,
t1.EXCPL_EMP_SVC_TXT = sty.EXCPL_EMP_SVC_TXT,
t1.RW_CRT_TMS = Getdate()
WHEN NOT MATCHED THEN
Insert (SRVY_ID,SRVY_CRT_SK,SRVY_SBMT_SK,SRVY_TYP_ID,LLTY_ACCT_ID,TXN_ID,STR_SK ,STR_ID,TXN_DT_SK,TXN_DT,TXN_TM,LN_ID,TXN_NUM,SHOP_CHL_CTGRY_ID,LKHD_RECM_RAT_VAL,OVALL_SATF_RAT_VAL,LKHD_RECM_RAT_RSN_TXT,FLEX_SRVY_TXT,ADL_CMNT_TXT,CHKOT_XPER_RAT_VAL,CHKOT_DSATF_RSN_TXT,CHKOT_OTH_DSATF_RSN_TXT,CSHR_FRND_RAT_VAL,SLF_CHKOT_ATTDNT_FRND_RAT_VAL,TEAM_MBR_IACT_IND,TEAM_MBR_IACT_FRND_RAT_VAL ,RSN_SVC_RAT_TXT,CNTER_AST_TXT,DLI_CNTER_SVC_SATF_RAT_VAL,BKRY_CNTER_SVC_SATF_RAT_VAL,P_AVL_SATF_RAT_VAL,P_AVL_DSATF_RSN_TXT,P_AVL_OTH_DSATF_RSN_TXT,FRSH_QLTY_PDC_RAT_VAL,UNSATF_FRSH_QLTY_ARE_TXT,OTH_UNSATF_FRSH_QLTY_ARE_TXT,P_DSATF_TXT,SUG_TXT,STR_CLNS_RAT_VAL ,CNTC_MTHD_TXT,CLNS_ISU_ARE_TXT,OTH_CLNS_ISU_ARE_TXT,EXCPL_EMP_SVC_TXT,RW_CRT_TMS)
Values(sty.SRVY_ID,sty.SRVY_CRT_SK,sty.SRVY_SBMT_SK,sty.SRVY_TYP_ID,sty.LLTY_ACCT_ID,sty.TXN_ID,sty.STR_SK ,sty.STR_ID,sty.TXN_DT_SK,sty.TXN_DT,sty.TXN_TM,sty.LN_ID,sty.TXN_NUM,sty.SHOP_CHL_CTGRY_ID,sty.LKHD_RECM_RAT_VAL,sty.OVALL_SATF_RAT_VAL,sty.LKHD_RECM_RAT_RSN_TXT,sty.FLEX_SRVY_TXT,sty.ADL_CMNT_TXT,sty.CHKOT_XPER_RAT_VAL,sty.CHKOT_DSATF_RSN_TXT,sty.CHKOT_OTH_DSATF_RSN_TXT,sty.CSHR_FRND_RAT_VAL,sty.SLF_CHKOT_ATTDNT_FRND_RAT_VAL,sty.TEAM_MBR_IACT_IND,sty.TEAM_MBR_IACT_FRND_RAT_VAL ,sty.RSN_SVC_RAT_TXT,sty.CNTER_AST_TXT,sty.DLI_CNTER_SVC_SATF_RAT_VAL,sty.BKRY_CNTER_SVC_SATF_RAT_VAL,sty.P_AVL_SATF_RAT_VAL,sty.P_AVL_DSATF_RSN_TXT,sty.P_AVL_OTH_DSATF_RSN_TXT,sty.FRSH_QLTY_PDC_RAT_VAL,sty.UNSATF_FRSH_QLTY_ARE_TXT,sty.OTH_UNSATF_FRSH_QLTY_ARE_TXT,sty.P_DSATF_TXT,sty.SUG_TXT,sty.STR_CLNS_RAT_VAL ,sty.CNTC_MTHD_TXT,sty.CLNS_ISU_ARE_TXT,sty.OTH_CLNS_ISU_ARE_TXT,sty.EXCPL_EMP_SVC_TXT,Getdate());
print('data updated');

--UPDATE STATISTICS
UPDATE STATISTICS [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_IN_STR];


END TRY


BEGIN CATCH



EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT=@NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT
--SET @ERROR_LINE
--SET @ERROR_MSG
print('Audit entry made');



SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();



--------- Log execution error ----------
EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;



THROW;



END CATCH
