CREATE PROC [EDAA_ETL_CUST].[PROC_FCT_DLY_STR_SRVY_PKP_DLVY_LOAD] AS



BEGIN TRY



/*Datamart Auditing variables*/
DECLARE @NEW_AUD_SKY BIGINT
DECLARE @NBR_OF_RW_ISRT INT
DECLARE @NBR_OF_RW_UDT INT
DECLARE @EXEC_LYR VARCHAR(255)
DECLARE @EXEC_JOB VARCHAR(500)
DECLARE @SRC_ENTY VARCHAR(500)
DECLARE @TGT_ENTY VARCHAR(500)
DECLARE @ERROR_PROCEDURE_NAME AS VARCHAR(60) = 'EDAA_ETL_CUST.PROC_FCT_DLY_STR_SRVY_PKP_DLVY_LOAD'
DECLARE @ERROR_LINE AS int
DECLARE @ERROR_MSG AS NVARCHAR(max)

SELECT @NBR_OF_RW_ISRT = COUNT(1)  FROM EDAA_STG_CUST.SRVY WHERE UDT_BY like '%Pickup%' and SRVY_ID not in( select SRVY_ID from [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_PKP_DLVY])
SELECT @NBR_OF_RW_UDT = COUNT(1)  FROM [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_PKP_DLVY] WHERE SRVY_ID in( select SRVY_ID from EDAA_STG_CUST.SRVY)

/*Audit Log Start*/
EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_START
@EXEC_LYR  = 'EDAA_DW_CUST'
,@EXEC_JOB  = 'FCT_DLY_STR_SRVY_PKP_DLVY_LOAD'
,@SRC_ENTY  = 'EDAA_STG_CUST.SRVY,EDAA_STG_CUST.QN_RSP_VAL'
,@TGT_ENTY = 'FCT_DLY_STR_SRVY_PKP_DLVY'
,@NEW_AUD_SKY = @NEW_AUD_SKY OUTPUT;



With initial_data as
(
select
SRVY_ID,
SRVY_CRT_SK,
SRVY_SBMT_SK,
SRVY_TYP_ID,
LLTY_ACCT_ID,
TXN_ID,
STR_SK,
STR_ID,
DGTL_ORDR_ID,
TXN_DT_SK,
TXN_DT,
TXN_TM,
LN_ID,
TXN_NUM,
SHOP_CHL_CTGRY_ID,
"1" as "LKHD_RECM_RAT_VAL",
"2" as "OVALL_SATF_RAT_VAL",
"3" as "LKHD_RECM_RAT_RSN_TXT",
"4" as "FLEX_SRVY_TXT",
"5" as "ADL_CMNT_TXT",
"31" as "ONLN_ORDR_XPER_RAT_VAL",
"39" as "ORDR_TRK_STAT_RAT_VAL",
"30" as "EMP_FRND_RAT_VAL",
"32" as "ORDR_CPT_RAT_VAL",
"33" as "QLTY_SBS_RAT_VAL",
case when upper("34") = 'YES' then cast(1 as bit) when upper("34") = 'NO' then cast(0 as bit) end as "XPER_PRB_IND",
case when upper("35") = 'YES' then cast(1 as bit) when upper("35") = 'NO' then cast(0 as bit) end as "PRB_RSLV_IND",
"36" as "IMPR_XPER_CMNT_TXT",
"37" as "EMP_TMLNS_RAT_VAL",
"38" as "FRSH_QLTY_PDC_RAT_VAL",
Getdate() as "RW_CRT_TMS"
from
(
SELECT SRVY.SRVY_ID as SRVY_ID,
c1.[DT_SK] as  SRVY_SBMT_SK,
c2.[DT_SK]  as SRVY_CRT_SK,
SRVY.DGTL_ORDR_ID,
SRVY.TXN_DT,
c3.[DT_SK] as  TXN_DT_SK,
SRVY.TXN_TM,
SRVY.STR_ID as STR_ID,
b.Geo_Hist_Sk  as STR_SK,
SRVY.TXN_LN_ID as LN_ID,
SRVY.TXN_NUM as TXN_NUM,
SRVY.SRVY_TYP_ID as SRVY_TYP_ID,
SRVY.TXN_ID as TXN_ID,
SRVY.LLTY_ACCT_ID as LLTY_ACCT_ID,
SRVY.SHOP_CHL_CTGRY_ID as SHOP_CHL_CTGRY_ID,
SQR.QN_ID,
SQR.QN_RSP_VAL
FROM EDAA_STG_CUST.SRVY as SRVY
JOIN [EDAA_DW].[DIM_DLY_CAL] c1 ON c1.[CAL_DT]=CONVERT (date,SRVY_END_DT)
JOIN [EDAA_DW].[DIM_DLY_CAL] c2 ON c2.[CAL_DT]=CONVERT (date,SRVY_STRT_DT)
JOIN [EDAA_DW].[DIM_DLY_CAL] c3 ON c3.[CAL_DT]=CONVERT (date,TXN_DT)
JOIN  [EDAA_DW].[DIM_GEO] as b on SRVY.[STR_ID] = b.[STR_ID] and Is_Curr_Ind = 'True'
JOIN  EDAA_STG_CUST.SRVY_QN_RSP SQR on SQR.SRVY_ID = SRVY.SRVY_ID
WHERE SRVY.SRVY_TYP_ID in (5,6)
) as a
PIVOT
(
  max(a.QN_RSP_VAL)
  FOR a.QN_ID IN ("1","2","3","4","5","31","39","30","32","33","34","35","36","37","38")
) as b
)


Merge [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_PKP_DLVY] t1
using initial_data as sty
on(sty.SRVY_ID = t1.SRVY_ID
   and sty.SRVY_CRT_SK = t1.SRVY_CRT_SK
   and sty.SRVY_SBMT_SK = t1.SRVY_SBMT_SK)
WHEN MATCHED THEN
UPDATE SET
t1.SRVY_TYP_ID = sty.SRVY_TYP_ID,
t1.LLTY_ACCT_ID = sty.LLTY_ACCT_ID,
t1.TXN_ID = sty.TXN_ID,
t1.STR_SK = sty.STR_SK,
t1.STR_ID = sty.STR_ID,
t1.DGTL_ORDR_ID = sty.DGTL_ORDR_ID,
t1.TXN_DT_SK = sty.TXN_DT_SK,
t1.TXN_DT = sty.TXN_DT,
t1.TXN_TM = sty.TXN_TM,
t1.LN_ID = sty.LN_ID,
t1.TXN_NUM = sty.TXN_NUM,
t1.SHOP_CHL_CTGRY_ID = sty.SHOP_CHL_CTGRY_ID,
t1.LKHD_RECM_RAT_VAL = sty.LKHD_RECM_RAT_VAL,
t1.OVALL_SATF_RAT_VAL = sty.OVALL_SATF_RAT_VAL,
t1.LKHD_RECM_RAT_RSN_TXT = sty.LKHD_RECM_RAT_RSN_TXT,
t1.FLEX_SRVY_TXT = sty.FLEX_SRVY_TXT,
t1.ADL_CMNT_TXT = sty.ADL_CMNT_TXT,
t1.ONLN_ORDR_XPER_RAT_VAL = sty.ONLN_ORDR_XPER_RAT_VAL,
t1.ORDR_TRK_STAT_RAT_VAL = sty.ORDR_TRK_STAT_RAT_VAL,
t1.EMP_FRND_RAT_VAL = sty.EMP_FRND_RAT_VAL,
t1.ORDR_CPT_RAT_VAL = sty.ORDR_CPT_RAT_VAL,
t1.QLTY_SBS_RAT_VAL = sty.QLTY_SBS_RAT_VAL,
t1.XPER_PRB_IND = sty.XPER_PRB_IND,
t1.PRB_RSLV_IND = sty.PRB_RSLV_IND,
t1.IMPR_XPER_CMNT_TXT = sty.IMPR_XPER_CMNT_TXT,
t1.EMP_TMLNS_RAT_VAL = sty.EMP_TMLNS_RAT_VAL,
t1.FRSH_QLTY_PDC_RAT_VAL = sty.FRSH_QLTY_PDC_RAT_VAL,
t1.RW_CRT_TMS = Getdate()
WHEN NOT MATCHED THEN
Insert (SRVY_ID,SRVY_CRT_SK,SRVY_SBMT_SK,SRVY_TYP_ID,LLTY_ACCT_ID,TXN_ID,STR_SK,STR_ID,DGTL_ORDR_ID,TXN_DT_SK,TXN_DT,TXN_TM,LN_ID,TXN_NUM,SHOP_CHL_CTGRY_ID,LKHD_RECM_RAT_VAL,OVALL_SATF_RAT_VAL,LKHD_RECM_RAT_RSN_TXT,FLEX_SRVY_TXT,ADL_CMNT_TXT,ONLN_ORDR_XPER_RAT_VAL,ORDR_TRK_STAT_RAT_VAL,EMP_FRND_RAT_VAL,ORDR_CPT_RAT_VAL,QLTY_SBS_RAT_VAL,XPER_PRB_IND,PRB_RSLV_IND,IMPR_XPER_CMNT_TXT,EMP_TMLNS_RAT_VAL,FRSH_QLTY_PDC_RAT_VAL,RW_CRT_TMS)
Values(sty.SRVY_ID,sty.SRVY_CRT_SK,sty.SRVY_SBMT_SK,sty.SRVY_TYP_ID,sty.LLTY_ACCT_ID,sty.TXN_ID,sty.STR_SK,sty.STR_ID,sty.DGTL_ORDR_ID,sty.TXN_DT_SK,sty.TXN_DT,sty.TXN_TM,sty.LN_ID,sty.TXN_NUM,sty.SHOP_CHL_CTGRY_ID,sty.LKHD_RECM_RAT_VAL,sty.OVALL_SATF_RAT_VAL,sty.LKHD_RECM_RAT_RSN_TXT,sty.FLEX_SRVY_TXT,sty.ADL_CMNT_TXT,sty.ONLN_ORDR_XPER_RAT_VAL,sty.ORDR_TRK_STAT_RAT_VAL,sty.EMP_FRND_RAT_VAL,sty.ORDR_CPT_RAT_VAL,sty.QLTY_SBS_RAT_VAL,sty.XPER_PRB_IND,sty.PRB_RSLV_IND,sty.IMPR_XPER_CMNT_TXT,sty.EMP_TMLNS_RAT_VAL,sty.FRSH_QLTY_PDC_RAT_VAL,Getdate());




--UPDATE STATISTICS
UPDATE STATISTICS [EDAA_DW_CUST].[FCT_DLY_STR_SRVY_PKP_DLVY];
END TRY


BEGIN CATCH


EXEC EDAA_CNTL.SP_AUDIT_DATA_LOAD_END @AUD_SKY = @NEW_AUD_SKY, @NBR_OF_RW_ISRT=@NBR_OF_RW_ISRT, @NBR_OF_RW_UDT  = @NBR_OF_RW_UDT
SET @ERROR_PROCEDURE_NAME = 'EDAA_ETL_CUST.PROC_FCT_DLY_STR_SRVY_PKP_DLVY_LOAD'
--SET @ERROR_LINE
--SET @ERROR_MSG



SELECT
      @ERROR_LINE =  ERROR_NUMBER()
       ,@ERROR_MSG = ERROR_MESSAGE();


--------- Log execution error ----------
EXEC EDAA_CNTL.SP_LOG_AUD_ERR
@AUD_SKY = @NEW_AUD_SKY,
@ERROR_PROCEDURE_NAME = @ERROR_PROCEDURE_NAME,
@ERROR_LINE = @ERROR_LINE,
@ERROR_MSG = @ERROR_MSG;



   THROW;



END CATCH
