CREATE VIEW [EDAA_PRES].[V_DIM_PRE_DEF_CAL_TYP]
AS
WITH dtsel
AS (SELECT DISTINCT
  DT_SK AS MIN_DT_SK,
  DT_SK AS MAX_DT_SK,
  DT_SK AS MIN_CAL_DT,
  DT_SK AS MAX_CAL_DT,
  'Yesterday' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  6 AS PRE_DEF_ID
FROM [EDAA_DW].[DIM_DLY_CAL] A WITH (NOLOCK)
WHERE A.Cal_DT = DATEADD(DAY, -1, CAST(GETDATE() AS date))

UNION

SELECT DISTINCT
  format(DATEADD(DAY, 1 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MIN_DT_SK,
  format(DATEADD(DAY, 7 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MAX_DT_SK,
  format(DATEADD(DAY, 1 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MIN_CAL_DT,
  format(DATEADD(DAY, 7 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MAX_CAL_DT,
  'WktoDT' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  5 AS PRE_DEF_ID
FROM [EDAA_DW].[DIM_DLY_CAL] WITH (NOLOCK)
WHERE CAL_DT = DATEADD(DAY, -1, CAST(GETDATE() AS date))

UNION

SELECT DISTINCT
  format(DATEADD(DAY, 1 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MIN_DT_SK,
  format(DATEADD(DAY, 7 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MAX_DT_SK,
  format(DATEADD(DAY, 1 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MIN_CAL_DT,
  format(DATEADD(DAY, 7 - DATEPART(WEEKDAY, WKND_DT), CAST(WKND_DT AS date)), 'yyyyMMdd') AS MAX_CAL_DT,
  'Last Week' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  4 AS SORT_ORDER
FROM [EDAA_DW].[DIM_DLY_CAL] WITH (NOLOCK)
WHERE CAL_DT = DATEADD(WEEK, -1, CAST(GETDATE() AS date))

UNION

SELECT DISTINCT
  MIN(G.Dt_Sk) AS MIN_DT_SK,
  MAX(G.Dt_Sk) AS MAX_DT_SK,
  MIN(CAST(CONVERT(char(8), G.Cal_DT, 112) AS int)) AS MIN_CAL_DT,
  MAX(CAST(CONVERT(char(8), G.Cal_DT, 112) AS int)) AS MAX_CAL_DT,
  'PTD' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  3 AS PRE_DEF_ID
FROM [EDAA_DW].[DIM_DLY_CAL] G WITH (NOLOCK)
WHERE G.FSC_PRD_NM = (SELECT
  FSC_PRD_NM
FROM [EDAA_DW].[DIM_DLY_CAL] B WITH (NOLOCK)
WHERE B.CAL_DT = DATEADD(DAY, -1, CAST(GETDATE() AS date)))

UNION

SELECT DISTINCT
  format(Fsc_Qtr_Bgn_Dt, 'yyyyMMdd') MIN_DT_SK,
  format(Fsc_Qtr_End_Dt, 'yyyyMMdd') MAX_DT_SK,
  format(Fsc_Qtr_Bgn_Dt, 'yyyyMMdd') MIN_CAL_DT,
  format(Fsc_Qtr_End_Dt, 'yyyyMMdd') MAX_CAL_DT,
  'QTD' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  2 AS PRE_DEF_ID
FROM [EDAA_DW].[DIM_DLY_CAL] A WITH (NOLOCK)
WHERE A.CAL_DT = DATEADD(DAY, -1, CAST(GETDATE() AS date))

UNION

SELECT DISTINCT

  format(Fsc_Yr_Bgn_Dt, 'yyyyMMdd') MIN_DT_SK,
  format(Fsc_Yr_End_Dt, 'yyyyMMdd') MAX_DT_SK,
  format(Fsc_Yr_Bgn_Dt, 'yyyyMMdd') MIN_CAL_DT,
  format(Fsc_Yr_End_Dt, 'yyyyMMdd') MAX_CAL_DT,
  'FYTD' AS PRE_DEF_NM,
  1 AS CAL_TYP_ID,
  1 AS PRE_DEF_ID
FROM [EDAA_DW].[DIM_DLY_CAL] A WITH (NOLOCK)
WHERE A.Fsc_Yr = YEAR(DATEADD(DAY, -1, CAST(GETDATE() AS date))))


SELECT DISTINCT
  CAST(a.PRE_DEF_ID AS int) AS PRE_DEF_ID,
  a.PRE_DEF_NM,
  'AGG' AS AGG_TYP,
  b.CLN_TYP_ID,
  b.CLN_TYP_NM,
  ' ' AS WKND_DT,
  dtsel.MIN_DT_SK AS MIN_DT,
  dtsel.MAX_DT_SK AS MAX_DT
FROM [EDAA_PRES].[DIM_PRE_DEF_CAL_LKP] a,
     [EDAA_PRES].[DIM_CAL_TYP_LKP] b,
     dtsel
WHERE a.PRE_DEF_ID = dtsel.PRE_DEF_ID
AND b.CLN_TYP_ID = dtsel.CAL_TYP_ID

UNION

SELECT DISTINCT
  CAST(E.DT_SK AS int) AS PRE_DEF_ID,
  CONVERT(char(10), E.Cal_DT, 101) AS PRE_DEF_NM,
  'DLY' AS AGG_TYP,
  b.CLN_TYP_ID,
  b.CLN_TYP_NM,
  CONVERT(char(10), E.WKND_DT, 101) AS WKND_DT,
  E.DT_SK AS MIN_DT,
  E.DT_SK AS MAX_DT
FROM [EDAA_DW].[DIM_DLY_CAL] E,
     [EDAA_PRES].[DIM_CAL_TYP_LKP] b,
     dtsel
WHERE b.CLN_TYP_ID = dtsel.CAL_TYP_ID
AND E.CAL_DT BETWEEN DATEADD(DAY, -42, CAST(GETDATE() AS date)) AND DATEADD(DAY, -1, CAST(GETDATE() AS date))
