/****** Object:  View [EDAA_PRES].[V_FCT_DLY_PYMT_TNR]    Script Date: 4/11/2023 5:59:15 AM ******/


CREATE VIEW [EDAA_PRES].[V_FCT_DLY_PYMT_TNR]
AS SELECT
GEO_HST_SK,
DT_SK,
STR_ID,
STR_BRND_NM,
FSC_YR_ID,
FSC_QTR_NM,
FSC_QTR_SEQ_ID,
FSC_PRD_NM,
FSC_PRD_SEQ_ID,
TXN_TYP_NM,
WLT_TYP_DESC,
TXN_STS_DESC,
TEND_TYP_NM,
CRD_TYP_DESC,
CRD_SUB_TYP_DESC,
RSP_MSG_TXT,
TXN_CNT,
APPR_AMT,
PIN_RCVD_TXT,
ISUR_BNK_NM,
POS_REG_NBR_ID,
OMNI_CHL_IND,
VOD_RVS_DESC,
STR_TYP_NM,
TXN_TY_CNT,
TXN_LY_CNT,
TXN_TY_AMT,
TXN_LY_AMT
FROM
EDAA_DW.FCT_DLY_PYMT_TNR;
