/****** Object:  View [EDAA_PRES].[V_FCT_WSTE_VISIT]    Script Date: 3/10/2023 1:09:26 PM ******/

CREATE VIEW [EDAA_PRES].[V_FCT_WSTE_VISIT]
AS (SELECT
	WEB_SESN_STRT_TMS,
	VISIT_NUM,
	SESN_ID,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
FROM [EDAA_DW].[FCT_WSTE_VISIT]);
GO
