/****** Object:  View [EDAA_PRES].[V_FCT_DLY_PYMT_TNR_TXN_AGG_AMT]    Script Date: 4/13/2023 2:21:09 AM ******/

CREATE VIEW [EDAA_PRES].[V_FCT_DLY_PYMT_TNR_TXN_AGG_AMT]
AS SELECT
DT_SK,
FSC_YR_ID,
TXN_TYP_NM,
SUM(TXN_TY_AMT) AS TXN_TY_AMT,
SUM(TXN_LY_AMT) AS TXN_LY_AMT
FROM EDAA_DW.FCT_DLY_PYMT_TNR
GROUP BY
DT_SK,
FSC_YR_ID,
TXN_TYP_NM;
