CREATE VIEW [EDAA_PRES].[V_FCT_DLY_STR_ITMSKU_INV_L1_PROD] AS SELECT
INV.PROD_HIST_SK,
  INV.GEO_HIST_SK,
  INV.ITM_SKU,
  PROD.Lvl1_Prod_Id,
  INV.STR_ID,
  SUM(INV_QTY) AS INV_QTY
FROM EDAA_DW.FCT_DLY_STR_ITMSKU_INV INV
JOIN EDAA_DW.DIM_PROD PROD
  ON INV.PROD_HIST_SK = PROD.PROD_HIST_SK
WHERE CAST(GETDATE()-1 AS date) BETWEEN inv_row_start_dt AND inv_row_end_dt and PROD.Is_Curr_Ind=1
GROUP BY INV.PROD_HIST_SK,
		INV.ITM_SKU,
        INV.GEO_HIST_SK,
		PROD.Lvl1_Prod_Id,
		INV.STR_ID;
