CREATE VIEW [EDAA_PRES].[V_GS_STA_FUEL_TYP]
AS SELECT
A.STR_ID
,B.ITM_GRP_ID
,B.ITM_GRP_NM
,B.ITM_GRP_DESC
,C.ITM_SKU_ID
FROM
[EDAA_REF].[GS_STA_FUEL_TYP_SETUP_HST] A WITH(NOLOCK)
INNER JOIN [EDAA_REF].[ITM_GRP_HST] B WITH(NOLOCK)
	ON A.FUEL_TYP_ID = B.ITM_GRP_ID
INNER JOIN [EDAA_REF].[ITM_GRP_ITM_HST] C WITH(NOLOCK)
	ON C.ITM_GRP_ID = B.ITM_GRP_ID
	AND B.ITM_STAT_ATV_IND = 1
	AND B.PRD_END_DT = '2099-01-01';
