CREATE VIEW [EDAA_PRES].[V_PERF_BRF_DIM_RFSH_TM]
AS SELECT
CONVERT(DATETIME2(0),SYSDATETIMEOFFSET() AT TIME ZONE 'EASTERN STANDARD TIME') AS REFRESHTIME
,(SELECT  MAX(CONVERT(DATETIME2(0),DT_TM_HR))
   FROM [EDAA_DW].[FCT_HRLY_PROD_CURR_YR_SLS]
   WHERE CONVERT(DATETIME2(0),DT_TM_HR)< CONVERT(DATETIME2(0),SYSDATETIMEOFFSET() AT TIME ZONE 'EASTERN STANDARD TIME')) AS RECENT_DATA;
GO
