CREATE VIEW [EDAA_PRES].[V_PERF_BRF_DIM_GEO_CURR]
AS SELECT
       [Geo_Sk]
      ,[Str_Id]
      ,[Str_Nm]
      ,[Gross_Flr_Area]
      ,[Rgn_Nm]
      ,[Mkt_Nm]
      ,[Loc_Lngtd]
      ,[Loc_Lttd]
      ,[Str_Cls_Id]
      ,[Str_Cls_Nm]
      ,[Loc_St_Id]
      ,[Loc_Cnty_Id]
      ,[Loc_Cty]
      ,[Loc_Zp_Code]
      ,[Div_Id]
      ,[Div_Nm]
      ,[Curr_Yr_New_Str_Ind]
      ,[Lst_Yr_New_Str_Ind]
      ,[Two_Yrs_Ago_New_Str_Ind]
      ,[Rgn_Id]
      ,[Mkt_Id]
      ,[Str_Opn_Dt]
	  ,Datepart(year, [Str_Opn_Dt]) as Opn_yr
      ,[Str_Cls_Dt]
	  ,Datepart(year, [Str_cls_Dt]) as Cls_yr
      ,[Str_Ctgry_Nm]
      ,[Str_Zn_Id]
      ,[Str_Zn_Nm]
      ,[Str_Cmp_Ctgry_Id]
      ,[Str_Cmp_Ctgry_Desc]
  FROM [EDAA_DW].[Dim_Geo]
  WHERE [Is_Curr_Ind] = 1;
