CREATE VIEW [EDAA_PRES].[V_PRES_FCT_DLY_STR_ITMSKU_INV]
AS
SELECT
  CAST(GETDATE() - 1 AS date) AS [DT_SK],
  I.[PROD_HIST_SK],
  I.[GEO_HIST_SK],
  I.[STR_ID],
  I.[ITM_SKU],
  I.[INV_AMT],
  I.[INV_QTY]
FROM [EDAA_DW].[FCT_DLY_STR_ITMSKU_INV] I
INNER JOIN [EDAA_DW].DIM_PROD PROD
  ON PROD.[PROD_HIST_SK] = I.[PROD_HIST_SK]
INNER JOIN [EDAA_DW].DIM_GEO GEO
  ON I.[GEO_HIST_SK] = GEO.[GEO_HIST_SK]
WHERE PROD.Is_Curr_Ind = 1
AND GEO.Is_Curr_Ind = 1
AND CAST(GETDATE() - 1 AS date) BETWEEN inv_row_start_dt AND inv_row_end_dt
--AND inv_row_end_dt >= inv_row_start_dt AND INV_ROW_END_DT = '2099-01-01'
