/****** Object:  View [EDAA_PRES].[V_REF_VISITR_TYP]    Script Date: 3/10/2023 1:08:19 PM ******/

CREATE VIEW [EDAA_PRES].[V_REF_VISITR_TYP]
AS (SELECT
VISITR_TYP_ID,
    VISITR_TYP_NM,
    VISITR_TYP_DESC,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
FROM [EDAA_DW].[REF_VISITR_TYP]);
GO
