/****** Object:  View [EDAA_PRES].[V_REF_SRCH_ENGN]    Script Date: 3/10/2023 1:07:47 PM ******/

CREATE VIEW [EDAA_PRES].[V_REF_SRCH_ENGN]
AS (SELECT
	SRCH_ENG_ID,
	SRCH_ENG_NM,
	SRCH_ENG_DESC,
	SRCH_ENG_URL,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
	FROM [EDAA_DW].[REF_SRCH_ENGN]);
GO
