/****** Object:  View [EDAA_PRES].[V_REF_RF_LNK_TYP]    Script Date: 3/10/2023 1:06:36 PM ******/

CREATE VIEW [EDAA_PRES].[V_REF_RF_LNK_TYP]
AS (SELECT
RF_LNK_TYP_ID,
	RF_LNK_TYP_NM,
	RF_LNK_TYP_DESC,
	UPD_TMS,
	UPD_BY,
	AUD_INS_SK,
	AUD_UPD_SK
FROM [EDAA_DW].[REF_RF_LNK_TYP]);
GO
