CREATE VIEW [EDAA_PRES].[V_WK_GRID]
AS
with maxdt as
(
	select MAX(PRE_DEF_ID) as MAX_PREDEF_ID from [EDAA_PRES].[DIM_PRE_DEF_CAL_LKP]
)
select maxdt.MAX_PREDEF_ID+ROW_NUMBER() OVER (ORDER BY E.DT_SK) as PRE_DEF_ID,CONVERT(CHAR(10), E.Cal_DT, 101) AS PRE_DEF_NM,'DLY' as AGG_TYP,1 as CLN_TYP_ID,'Fiscal' as CLN_TYP_NM,E.WKND_DT ,
  E.Dt_Sk as MIN_DT,E.Dt_Sk as MAX_DT
			FROM [EDAA_DW].[DIM_DLY_CAL] E,[EDAA_DW].[DIM_DLY_CAL] L4,maxdt where E.LST_YR_FSC_DT_SK = L4.DT_SK
			AND E.CAL_DT BETWEEN DATEADD(DAY, -42, CAST(GETDATE() as date)) AND
			DATEADD(DAY, -1, CAST(GETDATE() as date))
