IF EXISTS(SELECT TOP  1 * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('ETL.DM_PRSNT_BRDG_TBL'))
DROP TABLE ETL.DM_PRSNT_BRDG_TBL;
GO

CREATE TABLE ETL.DM_PRSNT_BRDG_TBL
(
TABLENAME 		VARCHAR(255) NOT NULL,
SRC_ENTY		VARCHAR(255) NOT NULL,
TGT_ENTY		VARCHAR(255) NOT NULL,

 CONSTRAINT [PK_DM_PRSNT_BRDG_TBL] PRIMARY KEY NONCLUSTERED
	(
		[TABLENAME] ASC,
		[SRC_ENTY] ASC,
		[TGT_ENTY] ASC
	) NOT ENFORCED
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN
)
GO



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_UT_MPRS_CT_INV_ADJ_HST_ADJ','FCT_DLY_SL_P_SUB_CT','FCT_DLY_SL_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_UT_MPRS_CT_HST_ADJ','FCT_DLY_SL_P_SUB_CT','FCT_DLY_SL_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_UT_P_UPC_HST_INV','FCT_DLY_SL_P_SUB_CT','FCT_DLY_SL_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_UT_MPRS_CT_HST_Sales','FCT_DLY_SL_P_SUB_CT','FCT_DLY_SL_P_SUB_CT_CALC');

INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('WK_DC_MPRS_CT_HST_INV','FCT_WK_STRT_INV_P_SUB_CT','FCT_WK_STRT_INV_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('WK_DC_MPRS_CT_HST_ADJ','FCT_WK_STRT_INV_P_SUB_CT','FCT_WK_STRT_INV_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('WK_UT_MPRS_CT_HST_ADJ','FCT_WK_STRT_INV_P_SUB_CT','FCT_WK_STRT_INV_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('WK_UT_MPRS_CT_HST_Sales','FCT_WK_STRT_INV_P_SUB_CT','FCT_WK_STRT_INV_P_SUB_CT_CALC');



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_MJR_P_SUB_CT_SL_HST','FCT_DLY_SL_MB_P_SUB_CT','FCT_DLY_SL_MB_P_SUB_CT_CALC');
INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('DLY_P_MDS_HCY_LVL_TN_HST','FCT_DLY_SL_MB_TXN_P_SUB_CT','FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC');



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('FCT_DLY_SL_MB_P_SUB_CT_CALC_INITIAL','FCT_DLY_SL_MB_P_SUB_CT','FCT_DLY_SL_MB_P_SUB_CT_CALC');



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC_INITIAL','FCT_DLY_SL_MB_TXN_P_SUB_CT','FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC');



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('FCT_DLY_SL_P_SUB_CT_CALC_INITIAL','FCT_DLY_SL_P_SUB_CT','FCT_DLY_SL_P_SUB_CT_CALC');



INSERT INTO ETL.DM_PRSNT_BRDG_TBL VALUES ('FCT_WK_STRT_INV_P_SUB_CT_CALC_INITIAL','FCT_WK_STRT_INV_P_SUB_CT','FCT_WK_STRT_INV_P_SUB_CT_CALC');
