CREATE TABLE [stg_edw].[DLY_UT_P_UPC_PR_HST] (
    [UT_ID]       SMALLINT        NOT NULL,
    [P_UPC_ID]    DECIMAL (18)    NOT NULL,
    [DAY_DT]      DATE            NOT NULL,
    [RGL_PR_AM]   DECIMAL (11, 2) NULL,
    [PROMO_PR_AM] DECIMAL (11, 2) NULL,
    [CLRN_PR_AM]  DECIMAL (11, 2) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
