CREATE TABLE [stg_edw].[FNC_SLSPN_MPRS_UT_DAY_INF] (
    [MPRS_CT_ID]        SMALLINT        NOT NULL,
    [PKY_ID]            SMALLINT        NOT NULL,
    [UT_ID]             SMALLINT        NOT NULL,
    [DAY_DT]            DATE            NOT NULL,
    [TG_SLSPN_AM]       DECIMAL (13, 4) NULL,
    [TG_DMGN_PLN_AM]    DECIMAL (13, 4) NULL,
    [TG_STL_PLN_AM]     DECIMAL (16, 4) NULL,
    [TG_TWAW_PLN_AM]    DECIMAL (16, 4) NULL,
    [TG_EXPD_LOSS_AM]   DECIMAL (15, 4) NULL,
    [TG_UNEXPD_LOSS_AM] DECIMAL (15, 4) NULL,
    [TG_SLSPN_QT]       DECIMAL (12, 2) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
