CREATE TABLE [stg_edw].[WK_UT_MPRS_CT_HST] (
    [PKY_ID]             SMALLINT        NOT NULL,
    [MPRS_CT_ID]         SMALLINT        NOT NULL,
    [UT_ID]              SMALLINT        NOT NULL,
    [WK_END_DT]          DATE            NOT NULL,
    [TG_INV_CST_AM]      DECIMAL (11, 2) NOT NULL,
    [TG_INV_QT]          INT             NOT NULL,
    [TG_SQF_QT]          DECIMAL (9, 2)  NOT NULL,
    [TG_SL_AM]           DECIMAL (9, 2)  NOT NULL,
    [TG_SL_QT]           INT             NOT NULL,
    [TG_DMGN_AM]         DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_FNC_CR_AM]   DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_FNC_CHR_AM]  DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_WRHG_AM]     DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_TDC_HDL_AM]  DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_STO_HDL_AM]  DECIMAL (9, 2)  NOT NULL,
    [TG_CGS_P_CST_AM]    DECIMAL (9, 2)  NOT NULL,
    [TG_PTS_AM]          DECIMAL (9, 2)  NOT NULL,
    [TG_PTS_QT]          INT             NOT NULL,
    [TG_PTS_DMGN_AM]     DECIMAL (9, 2)  NOT NULL,
    [TG_PTS_MKDN_AM]     DECIMAL (11, 2) NOT NULL,
    [TG_CLRN_AM]         DECIMAL (9, 2)  NOT NULL,
    [TG_CLRN_QT]         INT             NOT NULL,
    [TG_CLRN_DMGN_AM]    DECIMAL (9, 2)  NOT NULL,
    [TG_CLRN_MKDN_AM]    DECIMAL (9, 2)  NOT NULL,
    [TG_CLRN_INV_CST_AM] DECIMAL (9, 2)  NOT NULL,
    [TG_CLRN_INV_QT]     INT             NOT NULL,
    [TG_T_MKDN_AM]       DECIMAL (11, 2) NOT NULL,
    [TG_SCN_QT]          INT             NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
