
CREATE VIEW [EDAA_ETL].[V_DIM_HRLY_CAL_CALC]
AS WITH CTE_CLDR_TYPE AS
(
SELECT
'Calendar'              AS CLDR_TYP_CT ,
10                      AS CLDR_TYP_ORDR_ID
UNION
SELECT
'Fiscal'                AS CLDR_TYP_CT ,
20                      AS CLDR_TYP_ORDR_ID
UNION
SELECT
'Holiday'               AS CLDR_TYP_CT ,
30                      AS CLDR_TYP_ORDR_ID
),

CTE_HRLY_CAL
AS
(
SELECT A.*, B.* FROM
[EDAA_ETL].[V_STG_DW_DAY_DT_HR_INF] AS A
CROSS JOIN CTE_CLDR_TYPE AS B
)

SELECT
a.*
,CAST('All Days' AS VARCHAR(100)) AS [PRE_DEF_FLTR]
,CAST(30 as INT) AS [PRE_DEF_FLTR_ID]
FROM
CTE_HRLY_CAL As a


UNION


SELECT
a.*
,'Last Hour'  AS [PRE_DEF_FLTR]
,10 AS [PRE_DEF_FLTR_ID]
FROM
CTE_HRLY_CAL As a
WHERE
--Check the MAX Hour in Current Week Datamart Sales Fact table
a.DT_TM_HR=(SELECT MAX(CONVERT(DATETIME2(0),DT_TM_HR)) from [EDAA_DW].[FCT_HRLY_PROD_CURR_YR_SLS])
			AND  a.CAL_DT=CONVERT(DATE,SYSDATETIMEOFFSET() AT TIME ZONE 'Eastern Standard Time')


UNION


SELECT
a.*
,'DTD'  AS [PRE_DEF_FLTR]
,15 AS [PRE_DEF_FLTR_ID]
FROM
CTE_HRLY_CAL As a
WHERE
a.DT_TM_HR <= (SELECT MAX(CONVERT(DATETIME2(0),DT_TM_HR)) from [EDAA_DW].[FCT_HRLY_PROD_CURR_YR_SLS])
			AND  a.CAL_DT=CONVERT(DATE,SYSDATETIMEOFFSET() AT TIME ZONE 'Eastern Standard Time')


Union

SELECT
a.*
,'Curr Day' AS [PRE_DEF_FLTR]
,CAST(20 as INT) AS [PRE_DEF_FLTR_ID]
FROM
CTE_HRLY_CAL As a
Where a.CAL_DT=CONVERT(DATE,SYSDATETIMEOFFSET() AT TIME ZONE 'Eastern Standard Time');
GO
