CREATE TABLE [EDAA_STG_CUST].[QN_SBJ]
(
    [QN_SBJ_ID] [int] NOT NULL,
    [QN_SBJ_NM] [varchar](128) NULL,
    [QN_SBJ_DESC] [varchar](512) NULL
)
WITH
(
    DISTRIBUTION = ROUND_ROBIN,
    CLUSTERED COLUMNSTORE INDEX
)
