CREATE TABLE [EDAA_STG_CUST].[SRVY_TYP]
(
    [SRVY_TYP_ID] [int] NOT NULL,
    [SRVY_TYP_NM] [varchar](128) NULL,
    [SRVY_TYP_DESC] [varchar](512) NULL
)
WITH
(
    DISTRIBUTION = ROUND_ROBIN,
    CLUSTERED COLUMNSTORE INDEX
)
