CREATE VIEW [V_EDAA_PRES].[DIM_P] AS SELECT
  P_HST_SKY         	 AS 	Prod_Hist_Sk
 ,P_SKY					 AS		Prod_Sk
 ,UPC_ID 				 AS		Itm_Sku
 ,UPC_DSC 				 AS		Itm_Nm
 ,P_ID 					 AS		Lvl1_Prod_Id
 ,P_DSC 				 AS		Lvl1_Prod_Desc
 ,P_CLS_ID				 AS		Lvl2_Prod_Clsfctn_Id
 ,P_CLS_DSC				 AS		Lvl2_Prod_Clsfctn_Desc
 ,P_SUB_CT_ID			 AS		Lvl3_Prod_Sub_Ctgry_Id
 ,P_SUB_CT_DSC			 AS		Lvl3_Prod_Sub_Ctgry_Desc
 ,P_CT_ID				 AS		Lvl4_Prod_Ctgry_Id
 ,P_CT_DSC				 AS		Lvl4_Prod_Ctgry_Desc
 ,BUS_SEG_ID			 AS		Lvl5_Bsns_Sgmt_Id
 ,BUS_SEG_DSC			 AS		Lvl5_Bsns_Sgmt_Desc
 ,MDS_ARE_ID			 AS		Lvl6_Mds_Area_Id
 ,MDS_ARE_DSC			 AS		Lvl6_Mds_Area_Desc
 ,FNC_P_CAT_ID			 AS		Fnc_Lvl1_Prod_Ctgry_Id
 ,FNC_P_CAT_DSC			 AS		Fnc_Lvl1_Prod_Ctgry_Desc
 ,FNC_MPRS_CT_ID		 AS		Fnc_Lvl2_Mprs_Ctgry_Id
 ,FNC_MPRS_CT_DSC		 AS		Fnc_Lvl2_Mprs_Ctgry_Desc
 ,FNC_PKY_ID			 AS		Fnc_Lvl3_Pky_Id
 ,FNC_PKY_DSC			 AS		Fnc_Lvl3_Pky_Desc
 ,FNC_ARE_ID			 AS		Fnc_Lvl4_Area_Id
 ,FNC_ARE_DSC			 AS		Fnc_Lvl4_Area_Desc
 ,VLD_FROM				 AS		Vld_Frm
 ,VLD_TO				 AS		Vld_To
 ,IS_CURR				 AS		Is_Curr_Ind
 ,IS_DMY				 AS		Is_Dmy_Ind
 ,IS_EMBR				 AS		Is_Emb_Ind
 ,ETL_ACT				 AS		Etl_Actn
 ,AUD_INS_SKY			 AS		Aud_Ins_Sk
 ,AUD_UPD_SKY			 AS		Aud_Upd_Sk
 FROM DM.DIM_P WHERE IS_CURR=1;
