CREATE VIEW [V_EDAA_PRES].[FCT_DLY_STR_ITMSKU_TY_LY_FUEL_SLS_AGG]
AS
SELECT
    dtsel.ROW_ID_VAL
	,dtsel.PRE_DEF_ID
	,CONVERT(DATE, CONVERT(VARCHAR(10), dtsel.MAX_DT_SK, 120)) AS DT_VAL
	,[ITM_SKU]
	,[STR_ID]
	,SUM([TY_SLS_AMT]) AS [TY_SLS_AMT]
	,SUM([LY_SLS_AMT]) AS [LY_SLS_AMT]
	,SUM([TY_SLS_QTY]) AS [TY_SLS_QTY]
	,SUM([LY_SLS_QTY]) AS [LY_SLS_QTY]
	,SUM([TY_DRCT_MGN_AMT]) AS [TY_DRCT_MGN_AMT]
	,SUM([LY_DRCT_MGN_AMT]) AS [LY_DRCT_MGN_AMT]
FROM [V_EDAA_PRES].[FCT_DLY_STR_ITMSKU_TY_LY_FUEL_SLS] a
INNER JOIN (
	SELECT *
		,ROW_NUMBER() OVER (
			ORDER BY PRE_DEF_ID
			) AS ROW_ID_VAL
	FROM [V_EDAA_PRES].[DIM_PRE_DEF_DATE_FUEL]
	WHERE AGG_TYPE = 'AGG'
	) dtsel ON a.DT_SK >= dtsel.MIN_DT_SK
	AND a.DT_SK <= dtsel.MAX_DT_SK
GROUP BY dtsel.ROW_ID_VAL
	,dtsel.PRE_DEF_ID
	,CONVERT(DATE, CONVERT(VARCHAR(10), dtsel.MAX_DT_SK, 120))
	,ITM_SKU
	,STR_ID
