CREATE VIEW [V_EDAA_PRES].[FCT_DLY_STR_ITMSKU_TY_LY_FUEL_SLS_DLY]
AS
SELECT dtsel.ROW_ID_VAL
	,dtsel.PRE_DEF_ID
	,CONVERT(DATE, CONVERT(VARCHAR(10), dtsel.MAX_DT_SK, 120)) AS DT_VAL
	,[ITM_SKU]
	,[STR_ID]
	,[TY_SLS_AMT]
	,[LY_SLS_AMT]
	,[TY_SLS_QTY]
	,[LY_SLS_QTY]
	,[TY_DRCT_MGN_AMT]
	,[LY_DRCT_MGN_AMT]
FROM [V_EDAA_PRES].[FCT_DLY_STR_ITMSKU_TY_LY_FUEL_SLS] a
INNER JOIN (
	SELECT *
		,ROW_NUMBER() OVER (
			ORDER BY PRE_DEF_ID
			) AS ROW_ID_VAL
	FROM [V_EDAA_PRES].[DIM_PRE_DEF_DATE_FUEL]
	WHERE AGG_TYPE = 'DLY'
	) dtsel ON a.DT_SK >= dtsel.MIN_DT_SK
	AND a.DT_SK <= dtsel.MAX_DT_SK
