CREATE TABLE [stg].[DLY_UT_P_UPC_HST_ADJ] (
    [P_UPC_ID]          VARCHAR (18)   NULL,
    [UT_ID]             INT            NULL,
    [MPRS_CT_ID]        VARCHAR (20)   NULL,
    [PKY_ID]            VARCHAR (20)   NULL,
    [DAY_DT]            VARCHAR (8)    NULL,
    [TG_SL_AM]          DECIMAL (9, 2) NOT NULL,
    [TG_SL_QT]          INT            NOT NULL,
    [TG_DMGN_AM]        DECIMAL (9, 2) NULL,
    [TG_CGS_FNC_CR_AM]  DECIMAL (9, 2) NULL,
    [TG_CGS_FNC_CHR_AM] DECIMAL (9, 2) NULL,
    [TG_CGS_WRHG_AM]    DECIMAL (9, 2) NULL,
    [TG_CGS_TDC_HDL_AM] DECIMAL (9, 2) NULL,
    [TG_CGS_STO_HDL_AM] DECIMAL (9, 2) NULL,
    [TG_CGS_P_CST_AM]   DECIMAL (9, 2) NULL,
    [TG_PTS_AM]         DECIMAL (9, 2) NULL,
    [TG_PTS_QT]         INT            NOT NULL,
    [TG_PTS_DMGN_AM]    DECIMAL (9, 2) NOT NULL,
    [TG_PTS_MKDN_AM]    DECIMAL (9, 2) NOT NULL,
    [TG_CLRN_AM]        DECIMAL (9, 2) NOT NULL,
    [TG_CLRN_QT]        INT            NOT NULL,
    [TG_CLRN_DMGN_AM]   DECIMAL (9, 2) NULL,
    [TG_CLRN_MKDN_AM]   DECIMAL (9, 2) NOT NULL,
    [TG_T_MKDN_AM]      DECIMAL (9, 2) NOT NULL,
    [TG_SCN_QT]         INT            NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);
