CREATE TABLE [stg].[DLY_UT_P_UPC_PR_HST] (
    [UT_ID]       SMALLINT     NOT NULL,
    [P_UPC_ID]    DECIMAL (18) NOT NULL,
    [DAY_DT]      VARCHAR (30) NOT NULL,
    [RGL_PR_AM]   VARCHAR (30) NULL,
    [PROMO_PR_AM] VARCHAR (30) NULL,
    [CLRN_PR_AM]  VARCHAR (30) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
