CREATE TABLE [stg].[WK_DC_MPRS_CT_HST_INV] (
    [PKY_ID]              NVARCHAR (4000) NULL,
    [UT_ID]               NVARCHAR (4000) NULL,
    [FILLER]              NVARCHAR (4000) NULL,
    [MPRS_CT_ID]          NVARCHAR (4000) NULL,
    [WK_END_DT]           NVARCHAR (4000) NULL,
    [TG_INV_CS_QT]        NVARCHAR (4000) NULL,
    [TG_CLRN_INV_CS_QT]   NVARCHAR (4000) NULL,
    [TG_INV_CST_AM]       NVARCHAR (4000) NULL,
    [TG_CLRN_INV_CST_AM]  NVARCHAR (4000) NULL,
    [TG_FNC_CHRG_AM]      NVARCHAR (4000) NULL,
    [TG_CLRN_FNC_CHRG_AM] NVARCHAR (4000) NULL,
    [TG_FNC_CR_AM]        NVARCHAR (4000) NULL,
    [TG_CLRN_FNC_CR_AM]   NVARCHAR (4000) NULL,
    [TG_STG_CHRG_AM]      NVARCHAR (4000) NULL,
    [TG_CLRN_STG_CHRG_AM] NVARCHAR (4000) NULL,
    [TG_INV_QT]           NVARCHAR (4000) NULL,
    [TG_CLRN_INV_QT]      NVARCHAR (4000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
