CREATE PROC [EDAA_CNTL].[SP_AUDIT_DATA_LOAD_END] @AUD_SKY [BIGINT],@NBR_OF_RW_ISRT [BIGINT],@NBR_OF_RW_UDT [BIGINT] AS
BEGIN

DECLARE @EXECUTIONENDTIME DATETIME = GETUTCDATE()

UPDATE EDAA_CNTL.DIM_AUD_ETL
SET
EXEC_END_TS = @EXECUTIONENDTIME
,NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT
,NBR_OF_RW_UDT = @NBR_OF_RW_UDT
FROM EDAA_CNTL.DIM_AUD_ETL
WHERE
AUD_SKY = @AUD_SKY


END
