CREATE PROC [EDAA_CNTL].[SP_LOG_AUD_ERR] @AUD_SKY [bigint],@ERROR_PROCEDURE_NAME [varchar](500),@ERROR_LINE [int],@ERROR_MSG [varchar](max) AS

/*

 Stored procedure logs etl audit record errors

*/
DECLARE @EXECUTIONSTARTTIME DATETIME = GETUTCDATE();
INSERT INTO [EDAA_CNTL].[DIM_AUD_ERR_LOG]
(

    [AUD_SKY],
	[ERR_DT],
	[ERR_PROC_NM],
	[ERR_LN],
	[ERR_MSG]

)

SELECT
@AUD_SKY,
@EXECUTIONSTARTTIME,
@ERROR_PROCEDURE_NAME,
@ERROR_LINE,
@ERROR_MSG
