CREATE TABLE [EDAA_STG_EMP].[EMP_STAT]
(
	[EMP_ID] [int] NOT NULL,
	[PRD_STRT_TMS] [datetime2](7) NOT NULL,
	[PRD_END_TMS] [datetime2](7) NULL,
	[EMP_STAT_TYP_ID] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
