CREATE TABLE [PRES].[DIM_TM_CALC] (
    [TM_SKY]            INT          NOT NULL,
    [DAY_DT]            DATE         NULL,
    [DAY_DT_LY]         DATE         NULL,
    [FCL_DAY_DT_LY]     DATE         NOT NULL,
    [LY_HLDY_DAY_DT]    DATE         NULL,
    [WK_END_DT]         DATE         NULL,
    [WK_STRT_DT]        DATE         NULL,
    [WK_END_DT_LY]      DATE         NOT NULL,
    [WK_STRT_DT_LY]     DATE         NULL,
    [FCL_WK_END_DT_LY]  DATE         NOT NULL,
    [FCL_WK_STRT_DT_LY] DATE         NULL,
    [CLDR_TYP]          VARCHAR (10) NULL,
    [CLDR_TYP_ORDR_ID]  INT          NULL,
    [CLDR_DAY_OF_WK_NM] VARCHAR (15) NULL,
    [DAY_OF_WK]         VARCHAR (3)  NULL,
    [DATE_NM]           VARCHAR (11) NULL,
    [CLDR_DAY_OF_WK_ID] INT          NULL,
    [FCL_WK_ID]         INT          NULL,
    [CLDR_MTH_OF_YR_NM] VARCHAR (20) NULL,
    [FCL_PER_SEQ_ID]    INT          NULL,
    [FCL_QTR_SEQ_ID]    INT          NULL,
    [FCL_YR_ID]         SMALLINT     NOT NULL,
    [CLDR_YR_ID]        INT          NULL,
    [FCL_QTR_NM]        VARCHAR (10) NULL,
    [FCL_PER_NM]        VARCHAR (10) NULL,
    [PRE_DEF_DT_FLTR]   VARCHAR (25) NULL,
    [SORT_ORD_ID]       INT          NULL,
    [AUD_INS_SKY]       BIGINT       NOT NULL,
    [AUD_UPD_SKY]       BIGINT       NULL
)
WITH (HEAP, DISTRIBUTION = REPLICATE);
