CREATE VIEW [PRES].[V_DATA_STS]
AS SELECT CASE WHEN MIN(DAY_DT) = DATEADD(day, -1, CAST(GETDATE() AS date)) THEN
'Sales Loaded' ELSE 'Yest not Loaded' END
AS DATA_STS
FROM (
SELECT  MAX(T.DAY_DT) AS DAY_DT
FROM [PRES].[FCT_DLY_SL_MB_P_SUB_CT_CALC] AS S
INNER JOIN DM.DIM_TM AS T
ON T.TM_SKY = S.TM_SKY
UNION ALL
SELECT  MAX(T.DAY_DT) AS DAY_DT
FROM [PRES].[FCT_DLY_SL_MB_TXN_P_SUB_CT_CALC] AS S
INNER JOIN DM.DIM_TM AS T
ON T.TM_SKY = S.TM_SKY

) X;
