CREATE VIEW [PRES].[V_DIM_CHNL_CURR]
AS SELECT
        [CHNL_SKY]
      ,[CHNL_BUS_KEY]
      ,[SHOP_CHNL_CT]
      ,[SHOP_CHNL_GRP_CT]
      ,[SHOP_CHNL_CLS_CT]
      ,[SHOP_CHNL_CLS_CT_NM]
      ,[MBL_SLF_CHKOT_CT]
      ,[MBL_SLF_CHKOT_DSC]
      ,[MPRKS]
      ,[MPRKS_TN_CT]
      ,[MPERKS_TN_DSC]
      ,[CHNL_DTL]
      ,[SHOP_CHNL]
      ,[SHOP_AND_SCN]
      ,[DGTL_UT_FLG]
      ,SHOP_AND_SCN_FLG
  FROM [DM].[DIM_CHNL] AS C
  WHERE IS_CURR = 1;
