CREATE VIEW [PRES].[V_DIM_TM_CALC]
AS SELECT  [TM_SKY]
      ,[DAY_DT]
      ,[DAY_DT_LY]
      ,[FCL_DAY_DT_LY]
      ,[LY_HLDY_DAY_DT]
      ,[WK_END_DT]
      ,[WK_STRT_DT]
      ,[WK_END_DT_LY]
      ,[WK_STRT_DT_LY]
      ,[FCL_WK_END_DT_LY]
      ,[FCL_WK_STRT_DT_LY]
      ,[CLDR_TYP]
      ,[CLDR_TYP_ORDR_ID]
      ,[CLDR_DAY_OF_WK_NM]
      ,[DAY_OF_WK]
      ,[DATE_NM]
      ,[CLDR_DAY_OF_WK_ID]
      ,[FCL_WK_ID]
      ,[CLDR_MTH_OF_YR_NM]
      ,[FCL_PER_SEQ_ID]
      ,[FCL_QTR_SEQ_ID]
      ,[FCL_YR_ID]
      ,[CLDR_YR_ID]
      ,[FCL_QTR_NM]
      ,[FCL_PER_NM]
      ,[PRE_DEF_DT_FLTR]
      ,[SORT_ORD_ID]

  FROM [PRES].[DIM_TM_CALC] AS T;
