/****** Object:  View [PRES].[V_GET_FCT_DLY_SL_P_SUB_CT_CALC_LLY]    Script Date: 5/21/2021 12:13:10 PM ******/
CREATE VIEW [PRES].[V_GET_FCT_DLY_SL_P_SUB_CT_CALC_LLY] AS Select

	   LLY.[TM_SKY] AS [TM_SKY]
	  ,SLL.[GEO_HST_SKY] AS [GEO_HST_SKY]
      ,SLL.[GEO_SKY] AS [GEO_SKY]
      ,SLL.[BYR_HST_SKY] AS [BYR_HST_SKY]
	  ,empLL.[MJR_P_SUB_CT_ID] AS [P_SUB_CT_ID]
      ,SLL.[BYR_SKY] AS [BYR_SKY]
      ,SLL.[UT_ID] AS [UT_ID]
	  ,CAST(SUM(SLL.[SLS_FNC_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_QTY_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_QTY_LLY_FSC]
      ,CAST(SUM(SLL.[DM_FNC_AM_LY_FSC]) as decimal(11, 2)) AS [DM_FNC_AM_LLY_FSC]
      ,CAST(SUM(SLL.[DM_FNC_CLRN_AM_LY_FSC]) as decimal(11, 2)) AS [DM_FNC_CLRN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[DM_FNC_PROMO_AM_LY_FSC]) as decimal(11, 2)) AS [DM_FNC_PROMO_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_CLRN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_CLRN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_CLRN_MKDN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_CLRN_MKDN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_PROMO_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_PROMO_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_PROMO_MKDN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_PROMO_MKDN_AM_LLY_FSC]
      ,SUM(SLL.[SLS_FNC_CLRN_QTY_LY_FSC]) AS [SLS_FNC_CLRN_QTY_LLY_FSC]
      ,SUM(SLL.[SLS_FNC_SCN_QTY_LY_FSC]) AS [SLS_FNC_SCN_QTY_LLY_FSC]
      ,CAST(SUM(SLL.[INV_SHRK_AM_LY_FSC]) as decimal(11, 2)) AS [INV_SHRK_AM_LLY_FSC]
      ,CAST(SUM(SLL.[INV_CLRN_QTY_LY_FSC]) as decimal(11, 2)) AS [INV_CLRN_QTY_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_AM_COMP_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_AM_COMP_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_AM_NCOMP_LY_FSC]) as decimal(11, 2)) As [SLS_FNC_AM_NCOMP_LLY_FSC]
      ,CAST(SUM(SLL.[COGS_FNC_LY_FSC]) as decimal(11, 2)) AS [COGS_FNC_LLY_FSC]
      ,CAST(SUM(SLL.[DM_FNC_RRTL_AM_LY_FSC]) as decimal(11, 2)) AS [DM_FNC_RRTL_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_MKDN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_MKDN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_RRTL_MKDN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_RRTL_MKDN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[SLS_FNC_NCLRN_AM_LY_FSC]) as decimal(11, 2)) AS [SLS_FNC_NCLRN_AM_LLY_FSC]
      ,CAST(SUM(SLL.[DM_FNC_NCLRN_AM_LY_FSC]) as decimal(11, 2)) AS [DM_FNC_NCLRN_AM_LLY_FSC]
  FROM
  [PRES].[FCT_DLY_SL_P_SUB_CT_CALC_ARCHIVE] SLL WITH(NOLOCK)
  INNER JOIN
  (
	      Select DISTINCT A.[TM_SKY],
		  B.[TM_SKY] AS 'TM_SKY_LY',
		  Replace(B.[FCL_DAY_DT_LY],'-','') AS 'TM_SKY_LLY'
		  FROM [PRES].[DIM_TM_CALC] as A with(nolock)
		  INNER JOIN [PRES].[DIM_TM_CALC] as B with(nolock) ON
		  Replace(A.[FCL_DAY_DT_LY],'-','') = B.[DAY_DT] AND B.CLDR_TYP='Fiscal'
		  where A.FCL_YR_ID = (Select Distinct FCL_YR_ID from PRES.DIM_TM_CALC WITH(NOLOCK) WHERE DAY_DT = CONVERT(VARCHAR,DATEADD(D,-1,GETDATE()),112))

  )
  LLY
  ON SLL.TM_SKY = LLY.TM_SKY_LY
  INNER JOIN [PRES].[DIM_P_L3] PLL WITH(NOLOCK) ON PLL.[P_HST_SKY] = SLL.[P_HST_SKY]
  INNER JOIN [dm_edw].[BYR_EMP_PKY_MPRS_CURRPREV_INF] empLL WITH(NOLOCK)
  ON PLL.FNC_PKY_ID = empLL.PKY_ID and PLL.FNC_MPRS_CT_ID = empLL.MPRS_CT_ID
  GROUP BY
	   SLL.[GEO_HST_SKY]
      ,SLL.[GEO_SKY]
      ,LLY.[TM_SKY]
	  ,empLL.[MJR_P_SUB_CT_ID]
      ,SLL.[BYR_HST_SKY]
      ,SLL.[BYR_SKY]
      ,SLL.[UT_ID];
GO
