CREATE VIEW [PRES].[V_MTRC_SWTH]
AS SELECT 'Sales Diff LY' AS TYP,  1 AS INDX_ID
UNION
SELECT 'Sales Diff AP' AS TYP,  2 AS INDX_ID
UNION
SELECT 'DM Diff LY' AS TYP,  3 AS INDX_ID
UNION
SELECT 'DM Diff AP' AS TYP,  4 AS INDX_ID
UNION
SELECT 'Txn Comp Diff LY' AS TYP,  5 AS INDX_ID
/*Added for LLY*/
UNION
SELECT 'Sales Diff LLY' AS TYP,  6 AS INDX_ID
UNION
SELECT 'DM Diff LLY' AS TYP,  7 AS INDX_ID
UNION
SELECT 'Txn Comp Diff LLY' AS TYP,  8 AS INDX_ID;
