CREATE TABLE [EDAA_CNTL].[DIM_AUD_ETL] (
    [AUD_SKY]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [EXEC_STRT_TS]      DATETIME      NOT NULL,
    [EXEC_END_TS]       DATETIME      NULL,
    [EXEC_USID]         VARCHAR (255) NOT NULL,
    [EXEC_LYR]          VARCHAR (255) NOT NULL,
    [EXEC_JOB]          VARCHAR (500) NOT NULL,
    [SRC_ENTY]          VARCHAR (500) NOT NULL,
    [TGT_ENTY]          VARCHAR (500) NOT NULL,
    [CHLD_ETL_AUD_SKY]  BIGINT        NULL,
    [PRSNT_LYR_PRC_STS] SMALLINT      NULL,
    [SEM_LYR_PRC_STS]   SMALLINT      NULL,
    [NBR_OF_RW_ISRT]    BIGINT           NULL,
    [NBR_OF_RW_UDT]     BIGINT           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
