CREATE TABLE [EDAA_CNTL].[ETL_KEY_VAL_PAIRS] (
    [Cntrlkey]   INT            IDENTITY (1, 1) NOT NULL,
    [CntrlCode]  VARCHAR (250)  NULL,
    [CntrlDesc]  VARCHAR (500)  NULL,
    [CntrlValue] VARCHAR (1000) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
