/****** Object:  StoredProcedure [ETL].[AUDIT_DATA_LOAD_END]    Script Date: 9/9/2020 7:19:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [ETL].[AUDIT_DATA_LOAD_END] @AUD_SKY [BIGINT],@NBR_OF_RW_ISRT [INT],@NBR_OF_RW_UDT [INT] AS
BEGIN

DECLARE @EXECUTIONENDTIME DATETIME = GETUTCDATE()

UPDATE DM.DIM_AUD_ETL
SET
EXEC_END_TS = @EXECUTIONENDTIME
,NBR_OF_RW_ISRT = @NBR_OF_RW_ISRT
,NBR_OF_RW_UDT = @NBR_OF_RW_UDT
FROM DM.DIM_AUD_ETL
WHERE
AUD_SKY = @AUD_SKY


END
GO
