/****** Object:  StoredProcedure [ETL].[AUDIT_DATA_LOAD_START]    Script Date: 9/9/2020 6:48:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [ETL].[AUDIT_DATA_LOAD_START] @EXEC_LYR [VARCHAR](255),@EXEC_JOB [VARCHAR](500),@SRC_ENTY [VARCHAR](500),@TGT_ENTY [VARCHAR](500),@NEW_AUD_SKY [BIGINT] OUT AS
BEGIN

DECLARE @EXECUTIONSTARTTIME DATETIME = GETUTCDATE()

INSERT INTO DM.DIM_AUD_ETL
           (
		    EXEC_STRT_TS
           ,EXEC_END_TS
           ,EXEC_USID
           ,EXEC_LYR
           ,EXEC_JOB
           ,SRC_ENTY
           ,TGT_ENTY
           ,NBR_OF_RW_ISRT
           ,NBR_OF_RW_UDT)
     SELECT
            @EXECUTIONSTARTTIME
           ,NULL
           ,USER_NAME()
		   ,@EXEC_LYR
           ,@EXEC_JOB
           ,@SRC_ENTY
           ,@TGT_ENTY
           ,NULL
           ,NULL

SELECT @NEW_AUD_SKY = AUD_SKY FROM DM.DIM_AUD_ETL
WHERE
EXEC_LYR = @EXEC_LYR
AND EXEC_JOB = @EXEC_JOB
AND TGT_ENTY = @TGT_ENTY
AND EXEC_STRT_TS = @EXECUTIONSTARTTIME

SELECT @NEW_AUD_SKY

END
GO
