/****** Object:  StoredProcedure [ETL].[PROC_DM_FACTS_MB_INCREMENTAL]    Script Date: 9/9/2020 7:24:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [ETL].[PROC_DM_FACTS_MB_INCREMENTAL] @SRC_ENTY [VARCHAR](500) AS
BEGIN
IF @SRC_ENTY ='DLY_MJR_P_SUB_CT_SL_HST'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_MB_P_SUB_CT_INCR_TABLELOAD;
	END
IF @SRC_ENTY ='DLY_P_MDS_HCY_LVL_TN_HST'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_MB_TXN_P_SUB_CT_INCR_TABLELOAD;
	END
ELSE
	BEGIN
		PRINT('TABLES LOADED SUCCESSFULLY!!!!');
	END

END
GO
