/****** Object:  StoredProcedure [ETL].[PROC_DM_FACTS_MF_INCREMENTAL]    Script Date: 9/9/2020 7:24:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [ETL].[PROC_DM_FACTS_MF_INCREMENTAL] @SRC_ENTY [VARCHAR](500) AS
BEGIN
IF @SRC_ENTY ='DLY_UT_MPRS_CT_INV_ADJ_HST_ADJ'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_P_SUB_CT_SHRINKAGELOAD;
	END
IF @SRC_ENTY ='DLY_UT_MPRS_CT_HST_ADJ'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_P_SUB_CT_ADJLOAD;
	END
IF @SRC_ENTY ='DLY_UT_P_UPC_HST_INV'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_P_SUB_CT_INVLOAD;
	END
IF @SRC_ENTY ='DLY_UT_MPRS_CT_HST_SALES'
	BEGIN
		EXEC ETL.PROC_FCT_DLY_SL_P_SUB_CT_SALESLOAD;
	END
IF @SRC_ENTY ='WK_UT_MPRS_CT_HST_SALES'
	BEGIN
		EXEC ETL.PROC_FCT_WK_STRT_INV_P_SUB_CT_SALESLOAD;
	END
IF @SRC_ENTY ='WK_UT_MPRS_CT_HST_ADJ'
	BEGIN
		EXEC ETL.PROC_FCT_WK_STRT_INV_P_SUB_CT_ADJLOAD;
	END
IF @SRC_ENTY ='WK_DC_MPRS_CT_HST_ADJ'
	BEGIN
		EXEC ETL.PROC_FCT_WK_STRT_INV_P_SUB_CT_WK_DC_ADJLOAD;
	END
IF @SRC_ENTY ='WK_DC_MPRS_CT_HST_INV'
	BEGIN
		EXEC   ETL.PROC_FCT_WK_STRT_INV_P_SUB_CT_INVLOAD ;
	END


ELSE
	BEGIN
		PRINT('TABLES LOADED SUCCESSFULLY!!!!');
	END

END
GO
