CREATE VIEW [EDAA_DW].[V_Base_CUST_FLYBUY] AS SELECT
      [CRBSD_PCK_ID],
	[ORDR_ID] ,
	[CRBSD_PCK_PARTY_ID],
	[STR_ID] ,
	[APL_PLTFRM_ID],
	[LOC_ATH_ID],
	[CRBSD_PCK_PARTY_NM],
	[PKP_CMT_TMS],
	[PKP_CMT_TM_ZN_TMS],
	[CUST_RDM_TMS],
	[CUST_RDM_TM_ZN_TMS],
	[PKP_STRT_TMS],
	[PKP_STRT_TM_ZN_TMS],
	[PKP_FFL_TMS],
	[PKP_FFL_TM_ZN_TMS],
	[CUST_TRP_DIST_METR],
	[CUST_WT_TM],
	[UPD_DT] ,
	[UPD_BY_FLG]

from [EDAA_STG].[CUST_FLYBUY] WITH (nolock);
