CREATE VIEW [EDAA_DW].[V_HOURLY_CAL]
AS SELECT
		CAST(DT.DAY_DT as VARCHAR) +' '+ CAST(TM.HR AS VARCHAR) AS DT_TM_HR,
		DT.DAY_DT AS CAL_DT,
		TM.DAY_TM_INTVL_ID AS DY_TM_INTRVL_ID
	FROM [DM_EDW].[DT_INF] AS DT
	CROSS JOIN EDAA_REF.DAY_TM_INTVL_INF  AS TM;
