CREATE TABLE [EDAA_DW_CUST].[DIM_DLY_SRVY_TYP_LKU]
(
[SRVY_TYP_SK] [smallint] NOT NULL,
[SRVY_TYP_NM] [varchar](128) NULL,
[SRVY_TYP_DESC] [varchar](512) NULL,
CONSTRAINT [PK_DIM_DLY_SRVY_TYP_LKU] PRIMARY KEY NONCLUSTERED
       (
              [SRVY_TYP_SK] ASC
       ) NOT ENFORCED
)
WITH
(
DISTRIBUTION=ROUND_ROBIN,
CLUSTERED COLUMNSTORE INDEX
)
GO
