/****** Object:  Table [stg].[DLY_UT_P_UPC_HST_LOSTSALES]    Script Date: 9/9/2020 3:27:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [stg].[DLY_UT_P_UPC_HST_LOSTSALES]
(
	[UT_ID] [int] NOT NULL,
	[P_UPC_ID] [varchar](18) NOT NULL,
	[DAY_DT] [varchar](8) NOT NULL,
	[TG_RGL_LOST_SL_QT] [decimal](9, 2) NOT NULL,
	[TG_PROMO_LOST_SL_QT] [decimal](9, 2) NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
